NervJS/taro

packages/taro-components/src/components/label/index.js
=> fix(components): label事件、样式等修复

docs/GETTING-STARTED.md, docs/event.md
=> docs: 文档更新

packages/taro-cli/templates/default/index.js, packages/taro-cli/templates/default/npmrc
=> feat(cli): 添加 npmrc 用于读取 taobao 镜像资源

README.md
文档增加npx使用说明，对于不喜欢全局安装的人可以使用 npx。
=> docs: add npx support

docs/component.md
=> docs: fix words error.

docs/composition.md, packages/taro-cli/templates/default/index.js
=> fix: 修复css预处理器提示语句错误

README.md
=> docs: 美化文档格式

packages/eslint-plugin-taro/__tests__/jsx-handler-names.js, packages/eslint-plugin-taro/rules/jsx-handler-names.js
=> fix(eslint-plugin-taro): 组件属性无法使用 this.state.* 形式赋值

packages/taro-components/types/Button.d.ts, packages/taro-components/types/Camera.d.ts, packages/taro-components/types/Canvas.d.ts, packages/taro-components/types/Checkbox.d.ts, packages/taro-components/types/CoverView.d.ts, packages/taro-components/types/Form.d.ts, packages/taro-components/types/Icon.d.ts, packages/taro-components/types/Image.d.ts, packages/taro-components/types/Input.d.ts, packages/taro-components/types/Label.d.ts, packages/taro-components/types/MovableView.d.ts, packages/taro-components/types/Navigator.d.ts, packages/taro-components/types/OpenData.d.ts, packages/taro-components/types/PickView.d.ts, packages/taro-components/types/Progress.d.ts, packages/taro-components/types/Radio.d.ts, packages/taro-components/types/RichText.d.ts, packages/taro-components/types/ScrollView.d.ts, packages/taro-components/types/Slider.d.ts, packages/taro-components/types/Swiper.d.ts, packages/taro-components/types/Switch.d.ts, packages/taro-components/types/Textarea.d.ts, packages/taro-components/types/Video.d.ts
修正类型定义中的可选属性，解决使用tsx时组件无限报错的问题
camera组件新api类型定义添加
=> typings update

packages/taro/types/index.d.ts
给request和socket增加返回类型，可以实现自动提示，如果后台接口有改变可以通过报错来判断出错位置。
暂时先修正部分字段类型，以后发现再继续修改。
=> 增加泛型参数及修正部分字段类型

packages/taro-cli/src/h5.js
调试了`class xxx {}`声明方式和因为使用了装饰器时ts代码产生的`let xxx = class xxx {}` 两种声明方式，都可以能运行起来。
=> 按照weapp思路修复 BUG #392

packages/taro-transformer-wx/src/constant.ts
=> fix(taro-transformer-wx): 集合中添加缺失的默认组件

packages/taro/types/index.d.ts
1. 文档说的支持 this.$scope
2. 补充 SelectorQuery 相关的 TS 定义
=> Taro 补充部分 typing

docs/native-api.md, packages/taro/types/index.d.ts
Fix: https://github.com/NervJS/taro/issues/486
@yuche Plz review, thx~
=> Update types for getCurrentPages && getApp

docs/components/media/audio.md, docs/components/media/video.md, packages/taro-components/src/components/audio/__test__/audio.test.js, packages/taro-components/src/components/audio/index.js, packages/taro-components/src/components/video/index.js
see https://github.com/NervJS/taro/pull/520#issuecomment-416093051
=> refact(taro-components): 音视频组件的onTimeupdate改为onTimeUpdate

package.json
[support for defaultProps in JSX](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#support-for-defaultprops-in-jsx)
=> typescript 升级到 3.0.1 更好的支持 React / Redux 项目

docs/props.md, packages/taro/types/index.d.ts
=> docs(taro): 增加全局样式引用说明

README.md
=> 添加 Taro整合Dva示例 连接

packages/taro/types/index.d.ts
Typescript版本缺乏对微信小程序配置项navigationStyle的支持 #585
=> 增加配置项navigationStyle

packages/taro/types/index.d.ts
=> 补充分包加载配置，ts声明定义

website/pages/en/index.js
=> [Refactor]使用ES6语法拼接字符串

packages/taro-cli/src/weapp.js
#674 修复了当前自定义outputRoot时会出现未创建输出目录问题。
=> fix (mkdir): 修复当不存在outputRoot时没有先创建目录便writeSync问题

docs/specials.md
=> fix(docs): 特殊问题的处理书写错误

packages/taro-cli/templates/default/config/index
=> chore: 代码对齐

packages/taro-components/types/common.d.ts
=> fix(types): detail 可根据需要定义

packages/taro-h5/src/api/createSelectorQuery/index.js
=> 修复selectorQuery.in 在H5平台上不支持的问题

packages/taro-router/src/lib/history.ts
增加兼容处理、符合taro代码规范
Issues：[#1043](https://github.com/NervJS/taro/issues/1043)
=> iOS12里面返回Hash会丢问题

packages/taro-components/src/components/swiper/index.js
主要修正由于 https://github.com/NervJS/taro/issues/1190 引起替换 Swiper.js 后的小问题。
=> fix(taro-components): Swiper 行为和微信小程序不一致的问题

CONTRIBUTING.md
=> docs(onlydocs): 贡献文档错别字修改

docs/components/viewContainer/scroll-view.md
对 ScrollView 组件横向滚动描述不清晰。
添加微信小程序 ScrollView 关于横向滚动的 Tips。
=> 添加 scroll-view 组件关于横向滚动的使用提示

packages/taro-components/types/Button.d.ts
=> fix: fix loading type in ButtonProps

packages/taro-cli/src/convertor.js
=> 修复convert转换死循环

packages/taro-h5/types/index.d.ts, packages/taro/types/index.d.ts
BREAKING CHANGE: n
Issues: #1539
=> fix: 🐛 修复类型检查。

docs/native-api.md
=> 更新 makePhoneCall 支持度

packages/taro/types/index.d.ts
add params in requestFullScreen
add method stop
add method showStatusBar
add method hideStatusBar
=> chore(types): fix some type check in VideoContext

packages/taro/types/index.d.ts
微信客户端 7.0.0 及以上版本 增加了小程序接口权限相关设置。
=> [types]: add permission type check

packages/taro-components/types/common.d.ts
添加阻止控件默认行为函数、阻止事件冒泡函数在BaseEvent中的定义
=> BaseEvent添加两个常用事件处理的函数

packages/taro-utils/rollup.config.js
=> fix: 修改 rollup.config.js name 字段的值

packages/taro-cli/src/weapp.js
在`transfromNativeComponents`函数调用了Util下的`isAliasPath`和`replaceAliasPath`解决
=> config配置 alias选项 暂不支持转换usingComponents #1704

packages/taro/src/events.js
=> once can not destory

packages/taro-components/src/components/textarea/index.js
textarea onFocus & onBlur event handler miss pass detail value
=> fix(taro-components): textarea event handler miss pass detail value

docs/spec-for-taro.md
文档中“不能在 JSX 参数中使用匿名函数”handleClick拼写错误为hanldeClick
=> docs:修改 spec-for-taro.md 中拼写错误

packages/taro-cli/src/weapp.js
新增项目配置文件可以放入sourceDir，兼容一项目多程序配置
=> 新增项目配置文件可以放入sourceDir，兼容一项目多程序配置

docs/tutorial.md
componentWillUnmout -> componentWillUnmount.
=> fix(docs): tutorial.md componentWillUnmount

docs/config-detail.md, packages/taro-cli/templates/default/tsconfigjson, packages/taro-cli/templates/mobx/tsconfigjson, packages/taro-cli/templates/redux/tsconfigjson
=> 修改 tsconfig.json 默认模版，完善 config-detail/alias 部分文档

packages/taro-cli/src/weapp.js
=> 压缩js bugfix

packages/taro-alipay/src/native-api.js
https://openclub.alipay.com/read.php?tid=12731&fid=65&ant_source=zsearch
=> my.getStorageSync，预览和调试结果返回不一致

packages/taro-components/types/PickerView.d.ts
=> fix(taro-components): 完善 PickerView 的类型定义

docs/components/media/image.md
=> 修复文档编辑错误 Icon--Image

packages/taro-cli/package.json, packages/taro-cli/yarn.lock
Added missing "fbjs" for taro-cli which is required by react native project.
=> 2121: Added missing dependency for taro-cli.

packages/taro-webpack-runner/src/index.ts
=> fix: issue #2534 自定义 webpack 配置无效

packages/taro-webpack-runner/src/index.ts
fix:disableHostCheck在window下失效
=> fix:disableHostCheck在window下失效

packages/taro-webpack-runner/src/config/devServer.conf.ts
手机端真机调试需要，建议默认开启disableHostCheck
=> feat:默认开启disableHostCheck

packages/taro-cli/templates/default/globaldts, packages/taro-cli/templates/mobx/globaldts, packages/taro-cli/templates/redux/globaldts, packages/taro-cli/templates/wxcloud/client/globaldts
见：https://nervjs.github.io/taro/docs/envs.html#processenvtaro-env
=> feat(taro-cli): 添加 process.env.TARO_ENV 的 TypeScript 定义

packages/taro-cli/templates/wxcloud/client/components/login/index
=> fix 云函数返回结果

docs/native-api.md, packages/taro-h5/src/api/system/index.js, packages/taro-h5/src/api/unsupportedApi/index.js, packages/taro-h5/src/api/utils/index.js
对接[微信jssdk](https://qydev.weixin.qq.com/wiki/index.php?title=%E5%BE%AE%E4%BF%A1JS%E6%8E%A5%E5%8F%A3)
1. scanCode
1. getLocation
1. openLocation
=> feat:scanCode，getLocation，openLocation对接[微信jssdk]

packages/taro-transformer-wx/src/render.ts
=> fix: key detection

packages/taro-components/types/Video.d.ts, packages/taro-components/types/common.d.ts
见：https://developers.weixin.qq.com/miniprogram/dev/component/video.html
=> feat(taro-components): 更新 Video 组件的类型定义

packages/taro-components/types/Button.d.ts, packages/taro-components/types/Input.d.ts, packages/taro-components/types/Swiper.d.ts, packages/taro-components/types/Textarea.d.ts, packages/taro-components/types/WebView.ts
主要在于补充常用组件 `e.detail` 的类型定义，可让 ts 开发过程更流畅。
同时，也补充了这几个组件一些新出的 api。
=> feat: 完善 Input, Button, Textarea, WebView, Swiper 组件的类型定义

packages/taro/types/index.d.ts
PR 里主要是修正了 CanvasContext 的类型定义，然后补充了部分代码注释
由于我的编辑器在保存的时候还修改了部分代码的格式问题（主要是不正确的缩进），所以 review 起来可能会比较碍事… 如果需要修改的话请加 review 请求
=> fix(index.d.ts): 修正 Canvas 的类型定义

docs/config-detail.md
=> docs: add plugin.sass config

packages/taro-cli/src/weapp.js
fix #1388 
把 styles 写到一个中间文件里，然后在组件里引用这个中间文件，这样在 css 更新的时候只要重新生成中间文件就能更新 styles 了。
=> fix: css modules doesn't update

docs/components/viewContainer/scroll-view.md
=> 更正scrollView文档示例

docs/components/forms/slider.md
=> docs: update

packages/taro/types/index.d.ts
add types `setBackgroundColor` ,`setBackgroundTextStyle` since 2.1.0
=> add `setBackgroundColor`,`setBackgroundTextStyle`

packages/taro-h5/src/api/image/chooseImage.js
https://github.com/NervJS/taro/issues/3108
=> 为chooseImage新增imageId

packages/taro-h5/src/api/image/chooseImage.js
https://github.com/NervJS/taro/issues/3108
漏修改了两处地方。
=> 为chooseImage新增imageId，漏修改了两处地方。

docs/components/forms/form.md
=> Form示例代码修正

packages/eslint-plugin-taro/constant/index.js, packages/eslint-plugin-taro/rules/class-naming.js, packages/eslint-plugin-taro/rules/custom-component-children.js, packages/eslint-plugin-taro/rules/props-reserve-keyword.js, packages/taro-transformer-wx/src/constant.ts, packages/taroize/src/utils.ts
=> fix: 删除重复的MovableView

docs/apis/interface/interactives/showActionSheet.md
=> showActionSheet实例书写错误修正

docs/components/viewContainer/scroll-view.md
文档中ScrollView使用时，onScrolltoupper属性名未使用驼峰命名修改并完善
=> 文档中ScrollView使用时，onScrolltoupper属性名未使用驼峰命名修改并完善

docs/components/forms/button.md
微信小程序写法为bindgetuserinfo，根据现有信息很难了解taro写法应为onGetUserInfo，增加此字段以便新人更清晰的使用。
=> Button文档增加属性说明

packages/taro/types/index.d.ts
[#3192](https://github.com/NervJS/taro/issues/3192)
=> fix(taro): 给Component补充$preloadData的申明

.github/PULL_REQUEST_TEMPLATE.md
=> chore: 更新 PR 模版

packages/taro-components/src/components/view/index.js
=> fix(h5): 为H5的View组件添加长按事件onLongPress支持，fix #2857

packages/taro-components/src/components/input/index.js
https://github.com/NervJS/taro/issues/2778
=> fix(component): Input 组件在 H5 模式下 iOS 10 自带输入法输入中文时内容重复(#2778)

packages/taro/types/index.d.ts
向 index.d.ts 新增加了 [wx.getLaunchOptionsSync()](https://developers.weixin.qq.com/miniprogram/dev/api/base/app/life-cycle/wx.getLaunchOptionsSync.html) API 的类型声明
=> fix(taro): 增加 getLaunchOptionsSync 类型声明

packages/taro-components/types/OfficialAccount.d.ts
修复微信小程序 `OfficialAccount` 属性类型: `onLoad` `onError`
=> fix(components): 修复 OfficialAccount 事件 types

packages/taro/src/native-apis.js, packages/taro/types/index.d.ts
增加 `Taro.reportMonitor` 类型声明, 对应 `wx.reportMonitor`.
微信官方文档更新了, 不知道能不能用正则全部替换.
```
/analysis-report.html#wxreportanalyticseventname-data
/open-api/report/wx.reportAnalytics.html
```
/report/ 这个目录结构是新增的.
=> fix(taro): 增加 Taro.reportMonitor

packages/taro/types/index.d.ts
问题：
1. 类 java-doc 注释中的代码块符号与行首最多 3 空格距离
2. 代码块中不能存在其他 markdown 符号
修改 [packages/taro/types/index.d.ts](./packages/taro/types/index.d.ts) 文件，修复注释中的 markdown 语法，使得代码示例完美展示。
修改 `index.d.ts` 文件中的注释
修改前后展示效果对比：
=> chore: 修复 index.d.ts 文档中的 markdown 语法

packages/taro-cli/src/rn/transformJS.ts
https://github.com/NervJS/taro/issues/3146
=> fix: 解决过滤 丢弃import的问题..

packages/taro/types/index.d.ts
getLogManager api 已存在, 但缺少类型定义.
=> fix(taro): 增加 getLogManager 类型定义

packages/taro-cli/bin/taro-update, packages/taro-cli/src/util/constants.ts
taro update project 可以更新 nervjs 的版本
=>  feat(taro-cli): taro update 更新 nervjs 依赖

packages/taro-rn/src/component.js
补充在rn端获取不到this.$router["path"]的问题
**这个 PR 是什么类型?** (至少选择一个)  
=> fix(rn): 补充在rn端获取不到this.$router["path"]的问题

packages/taro/types/index.d.ts
增加 Taro.getAccountInfoSync 类型定义
=> fix(taro): 增加 Taro.getAccountInfoSync 类型定义

packages/taro-components/src/components/progress/index.js, packages/taro-components/src/components/progress/index.md, packages/taro-components/types/Progress.d.ts
=> feat(taro-components): add borderRadius for Progress Component

packages/taro-cli/src/util/astConvert.ts
https://github.com/NervJS/taro/issues/3505
=> fix: 引入json包含null的问题.

docs/redux.md
修复文档，redux案例中的taro-redux引用路径错误
=> fix(docs): 案例中的taro-redux引用路径错误

packages/taro/types/index.d.ts
添加 FunctionComponent 和 Taro.memo 的类型定义
=> feat(typings): add the type definition of FunctionComponent and Taro.memo

packages/taro-cli/bin/taro-build
尽早设置watch下的NODE_ENV为development, 小程序watch时NODE_ENV应该为development
=> fix(taro-cli): 尽早设置watch下的NODE_ENV为development

packages/taro-components/types/Form.d.ts
- 补充了一个新的属性: `reportSubmitTimeout`
- 补充 `onSubmit` 事件的 `e.detail` 的定义
见：https://developers.weixin.qq.com/miniprogram/dev/component/form.html
=> feat(taro-components): 完善 Form 组件的类型定义

packages/taro/src/memo.js
抱歉前几天提交的关于Taro.memo的PR犯了一个严重的错误。
=> fix: memo对state的判断应该用逻辑或

docs/event.md
Correct the URI of `useCallback`.
教程>事件处理.函数式组件
修正了`useCallback`的跳转链接
=> Doc: Update event.md

packages/taro/types/index.d.ts
=> fix(taro): 修复 this.$router 类型错误 close #3650

packages/taro-h5/src/taro/index.js
增加page组件增加$component对象，与微信环境统一
=> fix(h5): Page组件增加$component对象，与微信小程序统一

docs/best-practice.md
修正 最佳实践 里 [组件 state 与 props 里字段重名的问题](https://nervjs.github.io/taro/docs/best-practice.html#%E7%BB%84%E4%BB%B6-state-%E4%B8%8E-props-%E9%87%8C%E5%AD%97%E6%AE%B5%E9%87%8D%E5%90%8D%E7%9A%84%E9%97%AE%E9%A2%98) 的 Typo。
=> docs(best-practice): 修正 typo

packages/taro-components-qa/src/components/scroll-view/index.ux
修复快应用Scrollview组件onScrollToUpper事件分发错误的bug
=> fix(components-qa): 修复快应用ScrollView组件事件分发错误

packages/taro-cli/src/util/constants.ts
添加 taro update 更新项目时遗漏的两个 stylelint 包
- 更新项目时同时更新 stylelint-config-taro-rn 和 stylelint-taro-rn
=> fix(taro-cli): 添加 taro update 更新项目时遗漏的两个 stylelint 包

packages/taro/types/index.d.ts
`Taro.connectSocket()` 返回的 `SocketTask` 对象字段有误，见下图：
=> feat(typings): SocketTask 中字段的类型错误，另外缺少两个字段。

packages/taro-cli/src/h5/index.ts
修正src硬编码的问题
- [ x] 在本地测试可用，不会影响到其它功能
=> 修正src硬编码的问题

packages/taro/types/index.d.ts
=> fix(index.d.ts): 修正 FunctionComponent 的类型定义

packages/taro-mobx-common/src/inject.js
=> fix(mobx): 修复注入 mobx 后，原有 props 属性无法获取的问题

packages/taro-weapp/src/lifecycle.js
=> fix(taro-weapp): 修复state上空对象变为有数据时，子组件不会去setData

docs/components/viewContainer/swiper.md
修复文档内示例代码资源引用不正确
示例代码内使用到View,并没有import
=> 修复文档内示例代码资源引用不正确

packages/taro/types/index.d.ts
[CameraFrameListener | 微信开放文档](https://developers.weixin.qq.com/miniprogram/dev/api/media/camera/CameraContext.onCameraFrame.html)
[CameraContext | 微信开放文档](https://developers.weixin.qq.com/miniprogram/dev/api/media/camera/CameraContext.html)
=> feat(taro): 补全CameraContext的类型定义

packages/taro-h5/src/api/vibrate/index.js
=> vibrate异常修复

packages/taro/src/native-apis.js, packages/taro/types/index.d.ts
添加支付宝获取用户信息接口
https://docs.alipay.com/mini/api/ch8chh
=> fix(alipay): 添加获取会员信息api

packages/taro-cli/src/convertor/index.ts
taroize传递了错误的参数，应该是JS路径而不是JS的脚本
错误修复(Bugfix)
新功能(Feature)
代码重构(Refactor)
文档修改(Docs)
这个 PR 满足以下需求:
提交到 master 分支
所有测试用例已经通过
这个 PR 涉及以下平台:
微信小程序
支付宝小程序
百度小程序
头条小程序
QQ 轻应用
Web 平台（H5）
=> repair params path error

packages/taro-components/types/Button.d.ts
=> feat(taro-alipay): 补全Button组件的类型定义

docs/debug.md
=> fix(docs): 修改文档中错别字

docs/hooks.md
=> DOC:修复错误说明

packages/taro-cli/src/convertor/index.ts
#4195 
tarozie化的问题
X错误修复(Bugfix) issue id #4203
新功能(Feature)
代码重构(Refactor)
文档修改(Docs)
这个 PR 满足以下需求:
提交到 master 分支
所有测试用例已经通过
这个 PR 涉及以下平台:
微信小程序
支付宝小程序
百度小程序
头条小程序
QQ 轻应用
Web 平台（H5）
=> fix4195 去除拼接图片的假性错误提示

docs/GETTING-STARTED.md
=> docs: 删除重复的注意事项，fix #4230

packages/taro-components-qa/src/components/taro-label/index.ux
修复拼写错误
错误修复(Bugfix) issue id #4203
新功能(Feature)
代码重构(Refactor)
文档修改(Docs)
这个 PR 满足以下需求:
提交到 master 分支
所有测试用例已经通过
这个 PR 涉及以下平台:
微信小程序
支付宝小程序
百度小程序
头条小程序
QQ 轻应用
Web 平台（H5）
=> fixlabelerror 修复拼写错误

packages/taroize/src/wxml.ts
#4188 
错误修复(Bugfix) issue id #4203
新功能(Feature)
代码重构(Refactor)
文档修改(Docs)
这个 PR 满足以下需求:
提交到 master 分支
所有测试用例已经通过
这个 PR 涉及以下平台:
微信小程序
支付宝小程序
百度小程序
头条小程序
QQ 轻应用
Web 平台（H5）
=> fix4188 支持wx:elif的mustache语法错误提示

packages/taro-components-qa/src/components/taro-canvas/index.ux
canvas不能有子组件
错误修复(Bugfix) issue
新功能(Feature)
代码重构(Refactor)
文档修改(Docs)
这个 PR 满足以下需求:
提交到 master 分支
所有测试用例已经通过
这个 PR 涉及以下平台:
微信小程序
支付宝小程序
百度小程序
头条小程序
QQ 轻应用
Web 平台（H5）
=> fix#canvas canvas不能有子组件

packages/taro-cli/src/config/manifest.default.json
在快应用里面 versioncode和minPlatformVersion必须是整型
X错误修复(Bugfix) issue id 
新功能(Feature)
代码重构(Refactor)
文档修改(Docs)
这个 PR 满足以下需求:
提交到 master 分支
所有测试用例已经通过
这个 PR 涉及以下平台:
微信小程序
支付宝小程序
百度小程序
头条小程序
QQ 轻应用
Web 平台（H5）
=> fixmanifest versioncode和minPlatformVersion必须是整型

packages/taro-components-qa/src/components/taro-image/index.ux
Image组件只有mode属性，没有model
X错误修复(Bugfix) issue id
新功能(Feature)
代码重构(Refactor)
文档修改(Docs)
这个 PR 满足以下需求:
提交到 master 分支
所有测试用例已经通过
这个 PR 涉及以下平台:
微信小程序
支付宝小程序
百度小程序
头条小程序
QQ 轻应用
Web 平台（H5）
=> fiximageTypo Image组件只有mode属性，没有model

packages/taro-components-qa/src/components/taro-map/index.ux
快应用现在可以在组件里面实现地图了， taro也需要支持
错误修复(Bugfix) issue id 
X新功能(Feature)
代码重构(Refactor)
文档修改(Docs)
这个 PR 满足以下需求:
提交到 master 分支
所有测试用例已经通过
这个 PR 涉及以下平台:
微信小程序
支付宝小程序
百度小程序
头条小程序
QQ 轻应用
Web 平台（H5）
=> feature#taro-map Taro增加对快应用map的支持

docs/quick-app.md, docs/taro-quickapp-manifest.md, packages/taro-cli/src/config/manifest.default.json, packages/taro-cli/src/mini/index.ts, packages/taro-cli/src/util/constants.ts
1. 补齐Taro和快应用的配置差异，让开发者更容易理解Taro适配的原理
2.快应用不支持enablePullDownRefresh字段
3.快应用的icon属于必填字段，建议给默认值
4.Taro的debug字段可以对应到快应用的config.logLevel字段，需要做一个映射
- [Y] 错误修复(Bugfix) issue id
新功能(Feature)
代码重构(Refactor)
- [Y] 文档修改(Docs)
这个 PR 满足以下需求:
提交到 master 分支
所有测试用例已经通过
这个 PR 涉及以下平台:
微信小程序
支付宝小程序
百度小程序
头条小程序
QQ 轻应用
- [Y ]快应用平台（QuickApp）
Web 平台（H5）
=> fix#manifestTransform 补齐Taro和快应用的配置差异，完善快应用配置生成模块

docs/template.md, packages/taro-cli/bin/taro-init, packages/taro-cli/src/create/fetchTemplate.ts, packages/taro-cli/src/create/project.ts, packages/taro-cli/src/util/index.ts
新增clone选项,拉取远程模板时可选择使用git clone，而不是http download
=> feat(cli): taro-init新增clone选项

packages/taro-components/src/components/swiper/index.js
=> bugfix: 修复H5环境下Swiper组件无法动态控制轮播的问题

packages/taro-cli/src/mini/helper.ts
#4252  三行代码搞定自动化安装快应用缺失的包@tarojs/components-qa
X错误修复(Bugfix) issue id #4252 
新功能(Feature)
代码重构(Refactor)
文档修改(Docs)
这个 PR 满足以下需求:
提交到 master 分支
所有测试用例已经通过
这个 PR 涉及以下平台:
微信小程序
支付宝小程序
百度小程序
头条小程序
QQ 轻应用
Web 平台（H5）
=> fix4252 自动化安装快应用缺失的包

docs/react-native.md
同步 taro-native-shell 中的改动
taro-native-shell 中已同步改动：https://github.com/NervJS/taro-native-shell/pull/5
=> fix(docs): react native 端的 moduleName

CONTRIBUTING.md
=> 改进贡献者描述指南说明

docs/quick-app.md
增加Taro组件和快应用组件的差异对比，指导开发者适配快应用端的开发流程
错误修复(Bugfix) 增加Taro组件和快应用组件的差异对比，指导开发者适配快应用端的开发流程
新功能(Feature)
代码重构(Refactor)
文档修改(Docs)
这个 PR 满足以下需求:
提交到 master 分支
所有测试用例已经通过
这个 PR 涉及以下平台:
微信小程序
支付宝小程序
百度小程序
头条小程序
QQ 轻应用
Web 平台（H5）
=> 增加Taro组件和快应用组件的差异对比，指导开发者适配快应用端的开发流程

docs/components/open/open-data.md
=> 修改文档 open-data.md

packages/taro/types/index.d.ts
=> canvas drawImage方法 类型检查错误

docs/apis/interface/wxml/createIntersectionObserver.md, website/versioned_docs/version-1.3.14/apis/interface/wxml/createIntersectionObserver.md
更新文档内容，新增Taro.createIntersectionObserver(Object component, Object options)
更新文档，新增**Taro.createIntersectionObserver**
=> update:  Taro.createIntersectionObserver 

packages/taro-cli/src/mini/index.ts
=> 修正快应用依赖环境安装时，因系统不同造成的命令执行问题

docs/GETTING-STARTED.md
由于taro create命令是一个可以提高开发效率的利器，因此将taro create添加到taro cli常用命令说明文档
=> docs: 将taro create添加到taro cli常用命令说明文档

packages/taro-h5/src/api/request/index.js
=> 支持fetch abort

packages/taro/types/api/media/media.video.d.ts
Taro.chooseVideo的验证Param中缺少参数补齐
Taro.chooseVideo的验证Param中缺少参数补齐
=> Taro.chooseVideo的验证Param中缺少参数补齐

packages/taro-cli/src/ui/common.ts, packages/taro-cli/src/ui/index.ts
=> feat(taro-cli): 增加UI模块快应用转换index入口

packages/taro/src/env.js
=> feat(taro): 增加快应用ENV判断，用于TARO-UI平台判断时调用

website/pages/en/versions.js
=> Update changelog URL

packages/taro-cli/src/ui/index.ts, packages/taro-cli/src/ui/quickapp.ts
=> feat(taro-cli): 增加UI模块快应用编译接口及独立文件

packages/taro-cli/src/ui/index.ts
=> feat(taro-cli): 增加UI模块快应用文件修改监控

packages/taro-components-rn/package.json
=> fix(components-rn): 修正rn build脚本对于windows兼容问题

packages/taro/types/api/ui/scroll.d.ts
=> fix(weapp): 调整 wx.pageScrollTo 类型签名

packages/taro-cli/src/rn.ts
feat: rn 配置添加onlyTaroToRn字段,支持项目构建只编译不打包
=> feat: rn 配置添加onlyTaroToRn字段,支持项目构建只编译不打包

packages/taro-cli/src/util/index.ts, packages/taro-cli/src/util/types.ts
给config的copy加上watch选项，使之可以监听并复制
=> feat(cli):给config的copy加上watch选项,使之可以监听并复制

packages/taro/types/api/location/index.d.ts
微信小程序2.9.0+版本添加了getLocation API的参数，支持搞定度定位
=> fix(weapp):添加微信小程序getLocation参数定义

packages/taro-components/types/common.d.ts
=> fix: 修复commom.d.ts的animation类型错误

packages/taro-cli/src/mini/component.ts
=> fix(taro-cli): 小程序组件打包时，将打包参数传递到依赖文件的打包中

packages/taro/types/taro.component.d.ts
=> fix(taro-router): 修复路由参数 `path`

docs/GETTING-STARTED.md, packages/taro-cli/src/build.ts, packages/taro-cli/src/util/constants.ts, packages/taro-cli/src/util/index.ts
=> fix(taro-cli)：增加taro-cli及运行时框架，版本不一致判断及提示

packages/taro-h5/src/api/image/react-wx-images-viewer/components/ImageContainer.js
修正previewImage点透问题
修正previewImage点透问题
=> fix: 修正previewImage点透问题

packages/taro-cli/package.json, packages/taro-cli/src/mini/compileStyle.ts
在头条下css background 样式未正确加载，url-loader 未正确执行copyFile
=> Bug css url loader

docs/tutorial.md, packages/taro-router-rn/src/initRouter.js, packages/taro-router-rn/src/utils.js
在 rn 环境下,app.js config 下的 window属性支持配置backgroundColor
=> feat:  在rn环境下,app.js config 下的 window属性支持配置backgroundColor

packages/taro-tt/src/create-component.js
修复 setInterval()执行 setState ，编译到头条小程序之后会报 nextTick is undefined 的问题
=> fix(tt): 修复头条小程序报nextTick is undefined

packages/taro-components/types/LivePusher.ts
=> modify live-pusher props are not required

packages/taro/types/taro.config.d.ts
=> fix: 修复页面config参数缺失pageOrientation的类型定义

packages/taro-components-qa/src/common/css/common.css, packages/taro-components-qa/src/components/taro-button/index.ux
1.改进button动画效果展示
2.引入css属性描述文件，控制需从父类引入才能生效的公共样式
3. 待增加快应用编译时转换适配后，仿照taro-ui构建全面的组件属性配置解耦
=> fix(components-qa)改进button动画效果展示，引入css属性描述文件

packages/taro-mini-runner/src/plugins/MiniPlugin.ts
1.修正快应用Manifest配置文件，在windows下json转换时反斜杆‘\\’路径问题
=> fix(mini-runner)修正快应用Manifest配置文件，在windows下json转换时反斜杆路径问题

packages/taro-components/src/components/image/index.js
=> fix(components): h5 image在unmount时取消IntersectionObserver监听

packages/taro-mini-runner/src/plugins/MiniPlugin.ts
=> fix(mini-runner)修正快应用pages中ux文件未正确生成问题

packages/taro/types/api/canvas/index.d.ts
lineCap类型不是number，是"lineCap" | "round" | "square"
=> lineCap类型不是number，是"lineCap" | "round" | "square"

packages/eslint-plugin-taro/rules/render-props.js
=> fix: enhancing the eslint checker

packages/taro-qq/src/create-component.js
=> fix(taro-qq): fix error in create-component.js

packages/taro-cli/package.json
=> fix(cli) 解决cli编译时缺少@types/react依赖问题

packages/taro-cli/src/util/index.ts, packages/taro-mini-runner/src/plugins/MiniPlugin.ts
=> fix(cli):增加递归中止条件，修正拼写符合规范

packages/taro/types/taro.config.d.ts
=> feat(weapp): add config typing

packages/taro-cli/templates/default/package.json, packages/taro-components/src/components/image/index.js
rename `componentWillUnMount` to `componentWillUnmount`
=> componentWillUnmount lifecycle

packages/taro-components-qa/src/components/taro-button/index.ux
=> feat(components-qa)增加Button Loading动画类型选择，默认与原生组件保持一致

packages/taro-transformer-wx/src/create-html-element.ts
=> fix(transform): 修复微信开发者工具key警告(使用常量key判断)

docs/components/forms/button.md
=> feat(docs)：增加Button在快应用doc中属性兼容说明

packages/taro/types/api/open-api/user-info.d.ts
`Taro.getUerInfo` 不传入 `option` ts 会报错, 应该支持不传入 `option`
=> fix(weapp): allow Taro.getUserInfo to take no param

packages/taro/types/api/canvas/index.d.ts
`Taro.canvasToTempFilePath` 函数的参数, 根据微信官方[文档](https://developers.weixin.qq.com/miniprogram/dev/api/canvas/wx.canvasToTempFilePath.html), 所有的选项均非必填
=> fix(weapp): incorrect Taro.canvasToTempFilePath typing

packages/taro-components/types/Image.d.ts, packages/taro/types/taro.component.d.ts
=> fix: 添加微信小程序webp属性

packages/taro-cli/templates/default/src/app.jsx, packages/taro-cli/templates/default/src/pages/index/index.jsx
修复cli生成的默认模板不符合 eslint(react/sort-comp) 规则
- [ x ] 代码风格更新(Code style update)
- [ x ] Commit 信息遵循 [Angular Style Commit Message Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)
- [ x ] 所有测试用例已经通过
- [ x ] 代码遵循相关包中的 .eslintrc, .tslintrc, .stylelintrc 所规定的规范
- [ x ] 在本地测试可用，不会影响到其它功能
- [ x ] 微信小程序
=> style(taro-cli): 修复默认模板不符合eslint(react/sort-comp)规则(#5302)

packages/taro-cli/templates/default/_gitignore
=> chore(taro-cli): 默认模板添加 .gitignore 配置文件

docs/components/viewContainer/swiper.md
=> docs：fix word speling

docs/components/viewContainer/swiper.md
=> docs: fix word spelling

docs/best-practice.md
=> 修改doc中的错别字

packages/taro-cli/src/mini/index.ts, packages/taro-mini-runner/src/index.ts, packages/taro-mini-runner/src/utils/types.ts
=> fix(cli, mini-runner): 修复小程序 watch 时支持压缩的问题 close #5322

packages/taro-components/types/ScrollView.d.ts
weapp scroll-view 2.10.1 new property.
=> fix(types): add refresher to ScrollViewProps

packages/taro-components-rn/src/components/Image/index.tsx
=> 保留对RN原本Image组件的其他属性的支持

packages/taro-components-qa/src/components/scroll-view/index.ux
在快应用中，scrollview组件的onScrollToLower与onScrollToUpper 都无法触发, scrollview组件中触发的事件名不对应，编译转换之后全部都是小写
=> fix(taro-components-qa): 修复快应用scrollview组件事件无法触发问题

packages/taro/types/api/ui/fonts.d.ts
=> fix(weapp):添加微信小程序loadFontFace参数定义

docs/migrate-to-2.md
=> docs(migrate): 移出多余的空格

docs/components/viewContainer/swiper.md
=> docs(swiper): fix error codes

docs/components/viewContainer/movable-view.md
=> docs(MovableView): fix error codes

docs/components/base/icon.md
=> docs(Icon): fix error codes

docs/components/base/text.md
=> docs(text): fix error codes

docs/components/base/progress.md, docs/components/base/rich-text.md, docs/components/navig/Functional-Page-Navigator.md
=> docs: fix docs error codes

packages/taro/types/taro.extend.d.ts
Append two supported environments types(QQ, JD) for Typescript type definition
补充缺少的当时目前已经支持的两个平台的ENV_TYPE定义
=> append QQ,JD ENV_TYPEs for ts type definition

packages/taro-cli/src/convertor/index.ts
=> fix(cli): 模板引用错误导致模板生成失败，进而必然导致转换失败

packages/taro-components/types/Audio.ts
=> chore: 类型定义可选

packages/taro-components/types/Input.d.ts, packages/taro-components/types/Textarea.d.ts
添加 Input/Textarea holdKeyboard 属性类型
=> fix(components): 添加 holdKeyboard 属性类型

packages/taro-components/src/components/swiper/index.js
=> fix(taro component): 1.3.9版本误删,导致无法衔接滚动

packages/taro/types/api/canvas/index.d.ts
修改了 canvas 类型中的两处定义：
微信小程序新版的 canvas 接口在调用 canvasToTempFilePath 时需要传入 canvas 的组件实例 Object 而不是 string。
CanvasContext 的属性 lineCap 和 lineJoin 不应该是 number，修改为与 setLineCap() 和 setLineJoin() 一致的可选值。
=> fix(types): 修复 CanvasContext 的部分属性类型。

packages/taro-components/package.json, packages/taro-components/yarn.lock
=> chore(components): 移除已经不需要的依赖 better-scroll

packages/taro-swan/src/component.js
修复Taro 1.3.x，百度小程序component shouldComponentUpdate不生效
=> fix(swan): 修复Taro 1.3.x，百度小程序component shouldComponentUpdate不生效

packages/taro-loader/src/component.ts
=> fix(loader): component 路径问题修复

packages/taro/types/api/ext/index.d.ts
- [] 提交到 master 分支
- [] Commit 信息遵循 [Angular Style Commit Message Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)
=> fix(types): 修复 getExtConfigSync 的部分属性类型。

packages/taro-h5/src/api/audio/index.js
=> fix(h5): Audio onError 无法捕获错误

packages/taro-mini-runner/src/plugins/MiniPlugin.ts
自定义组件的声明应为 component: true，这个错误会导致无法真机预览
=> fix(mini-runner): 自定义组件声明

packages/taro/types/api/ui/ui.animation.d.ts, packages/taro/types/taro.component.d.ts, packages/taro/types/taro.extend.d.ts, packages/taro/types/taro.hooks.d.ts
添加 Current 的 typescript 定义, 删除已经弃用的 useScope 定义
=> fix(taro): 添加 Current type definition, 删除不能使用的 useScope 定义

packages/taro-components-qa/src/components/checkbox/index.ux, packages/taro-components-qa/src/components/icon/index.ux, packages/taro-components-qa/src/components/navigator/index.ux, packages/taro-components-qa/src/components/radio/index.ux, packages/taro-components-qa/src/components/rich-text/index.ux, packages/taro-components-qa/src/components/scroll-view/index.ux, packages/taro-components-qa/src/components/swiper-item/index.ux, packages/taro-components-qa/src/components/taro-audio/index.ux, packages/taro-components-qa/src/components/taro-button/index.ux, packages/taro-components-qa/src/components/taro-camera/index.ux, packages/taro-components-qa/src/components/taro-canvas/index.ux, packages/taro-components-qa/src/components/taro-image/index.ux, packages/taro-components-qa/src/components/taro-input/index.ux, packages/taro-components-qa/src/components/taro-label/index.ux, packages/taro-components-qa/src/components/taro-picker/index.ux, packages/taro-components-qa/src/components/taro-progress/index.ux, packages/taro-components-qa/src/components/taro-slider/index.ux, packages/taro-components-qa/src/components/taro-swiper/index.ux, packages/taro-components-qa/src/components/taro-switch/index.ux, packages/taro-components-qa/src/components/taro-text/index.ux, packages/taro-components-qa/src/components/taro-textarea/index.ux, packages/taro-components-qa/src/components/taro-video/index.ux, packages/taro-components-qa/src/components/web-view/index.ux, packages/taro-quickapp/src/create-component.js, packages/taro-transformer-wx/src/create-html-element.ts
修复华为快应用下的问题（华为快应用加载器与快应用官方加载器不一致）
0. 不能使用class 关键字
0. 华为快应用会在根节点绑定事件，事件冒泡到根节点时会修改currentTarget, 导致报错。
0. 初始化时data增加属性priTaroCompReady=false
=> 2.x fix huawei qa bug

packages/taro/types/taro.component.d.ts
向 `ComponentOptions` 类型增加 `styleIsolation` 的类型定义
=> Add `styleIsolation` type definition

packages/taro-transformer-wx/src/index.ts
close #3132
添加环境变量支持ts编译配置emitDecoratorMetadata
=> feat(transformer): 添加环境变量支持ts编译配置emitDecoratorMetadata

packages/taro-mini-runner/src/utils/constants.ts
修复快应用支持 Block 标签，mini-runner 迁移遗漏代码
=> fix(quickapp): 快应用支持 Block 标签，2.x版本遗漏

docs/react.md
=> docs: fix react 内置组件代码示例

packages/taro-cli/src/util/constants.ts, packages/taro-mini-runner/src/utils/constants.ts, packages/taro-rn-runner/src/utils/constants.ts
=> fix: tt 样式文件后缀遗漏

docs/css-in-js.md
=> docs: 添加 linaria 配置和 webpack 配置

packages/taro-components/types/RichText.d.ts
https://developers.weixin.qq.com/miniprogram/dev/component/rich-text.html
=> fix(components): rich-text 属性为可选

docs/html.md
确认过 html.css 和 html5.css 的类名是 .taro_html
=> docs: fix html typo

packages/taro/types/api/media/map.d.ts
=> fix(type): 修复 mapcontext 的返回类型

packages/taro-h5/src/api/fileTransfer/uploadFile.js
解决h5模式Taro.uploadFile没携带cookies
解决h5模式Taro.uploadFile没携带cookies问题
=> fix: Taro.uploadFile携带cookie

packages/taro-cli/src/util/constants.ts, packages/taro-mini-runner/src/utils/constants.ts, packages/taro-rn-runner/src/utils/constants.ts
=> fix: qq 样式文件后缀遗漏

packages/taro-h5/src/api/fileTransfer/downloadFile.js
解决h5模式Taro.downloadFile携带cookie问题
解决h5模式Taro.downloadFile携带cookie问题
=> fix: Taro.downloadFile携带cookie

docs/virtual-list.md
=> docs: 修正 VirtualList 示例属性名

docs/join-in.md
=> doc: Update join-in.md

docs/config-detail.md
修复了文档样例一个小错误，疫情爆发前就存在，困扰了一段时间，看了webpack-chain文档才改对
chain中module下只有rules，使用rule会编译不过
=> fix(docs): 修复配置 webpackChain 的 example 小错误

packages/taro-runtime/src/dsl/common.ts
修复 Current.router 获取的数据有误
问题： https://github.com/NervJS/taro/issues/5900
=> fix(runtime): 修复 Current.router 获取的数据有误

packages/taro-cli/src/doctor/configSchema.ts
添加`configSchema`中缺失的`framework` 字段，fix #5976 
=> fix(cli): 添加 framework 检查

docs/report.md
增加友盟统计平台接入taro框架的文档
增加友盟统计平台接入taro框架的文档
=> 增加友盟统计平台接入taro框架的文档

packages/taro-cli/src/mini/index.ts
某些场景中，希望可以动态修改package.config.json中的appid参数。
所以在config/index中添加了appId参数，编译时读取并写入到pageage.config.json中
=> feat(cli): 在config中支持添加appId配置 编译时读取并写入到pageage.config.json中

packages/taro-components/types/Input.d.ts
Input 组件`maxlength` 类型声明错误；
实际绑定的值是`maxlength`但是类型`maxLength`导致书写错误不生效；
=> fix(components): input maxlength 拼写错误

packages/shared/src/components.ts
=> fix(shared): 默认属性拼写错误

packages/taro-components/src/components/scroll-view/index.js
=> fix(components): remove console.log fix #6081

packages/taro-cli/src/ui/h5.ts, packages/taro-cli/src/ui/ui.types.ts
=> fix(cli): 修复 ui 库编译中 h5 script 模式编译报错的问题

package.json, packages/taro-runtime/src/dsl/hooks.ts
=> feat(runtime): useShareAppMessage hooks 可以使用 deps

.github/workflows/publish.yml, package.json, packages/taro-components/src/components/audio/audio.tsx, packages/taro-components/src/components/input/input.tsx, packages/taro-components/src/components/textarea/textarea.tsx, yarn.lock
这个 PR 在 next 分支实现版本自动发布。
1. [项目维护者] 在本地开发版本发布分支并发起 Pull Request
2. [Taro 团队] Review 版本发布分支 PR
3. [CI] 发布版本
1. [本地] checkout 发布分支：`git checkout -b release/<semver>`
2. [本地] 使用 [`lerna version`](https://github.com/lerna/lerna/tree/master/commands/version#readme) 修改 `CHANGELOG.md` 和 `package.json` 以及 `lerna.json`
* 本地只修改文件，不发布 `git tag`, `GitHub Release` 和 NPM 版本
3. [本地] 提交版本发布分支 Pull Request
4. [GitHub] Review 并 merge 版本发布分支
* 使用 `Squash and merge` 合并分支
* 合并提交信息必须为包含 `chore(release): publish <semver>`
5. [CI] 校验版本发布分支的提交信息是否为 `chore(release): publish <semver>`
6. [CI] 添加 `git tag <semver>`
7. [CI] 将版本发布分支 PR 的标题和内容发布到 GitHub Release 页面
8. [CI] 发布版本到 NPM
=> chore(ci): 自动发布版本

packages/taro-components-qa/src/components/checkbox/index.ux, packages/taro-components-qa/src/components/icon/index.ux, packages/taro-components-qa/src/components/navigator/index.ux, packages/taro-components-qa/src/components/radio/index.ux, packages/taro-components-qa/src/components/rich-text/index.ux, packages/taro-components-qa/src/components/scroll-view/index.ux, packages/taro-components-qa/src/components/swiper-item/index.ux, packages/taro-components-qa/src/components/taro-audio/index.ux, packages/taro-components-qa/src/components/taro-button/index.ux, packages/taro-components-qa/src/components/taro-camera/index.ux, packages/taro-components-qa/src/components/taro-canvas/index.ux, packages/taro-components-qa/src/components/taro-image/index.ux, packages/taro-components-qa/src/components/taro-input/index.ux, packages/taro-components-qa/src/components/taro-label/index.ux, packages/taro-components-qa/src/components/taro-picker/index.ux, packages/taro-components-qa/src/components/taro-progress/index.ux, packages/taro-components-qa/src/components/taro-slider/index.ux, packages/taro-components-qa/src/components/taro-swiper/index.ux, packages/taro-components-qa/src/components/taro-switch/index.ux, packages/taro-components-qa/src/components/taro-text/index.ux, packages/taro-components-qa/src/components/taro-textarea/index.ux, packages/taro-components-qa/src/components/taro-video/index.ux, packages/taro-components-qa/src/components/web-view/index.ux, packages/taro-transformer-wx/src/create-html-element.ts
修复了jsx里的`className`被转成`classname`，导致样式无法生效
=> revert(quickapp): quick transformer className to class

packages/taro-helper/src/utils.ts
=> fix(helper): 修复 node_modules 路径获取方法, close #6164

packages/taro-mini-runner/src/index.ts
修复bug, 配置sass.resource无效，该地方应该传入makeConfig返回的配置项，才带有sassLoaderOption.data
=> fix(mini-runner): lose resource

docs/plugin.md, packages/taro-cli/src/presets/platforms/alipay.ts, website/versioned_docs/version-2.2.0-beta.0/plugin.md, website/versioned_docs/version-2.2.0/plugin.md
支付宝小程序是  .axml 
目前打后生成的是.awml 不能正常运行
=> fix(taro-cli): templ error

docusaurus.config.js
=> docs: correct repo name

packages/taro-cli/src/commands/build.ts
=> fix(cli): 修复编译时对 process.env.NODE_ENV 初始化设置

packages/taro-cli/src/cli.ts
=> fix(cli): 修复创建项目时丢失 typescript 选项的问题，close #6180

docs/react.md, docs/vue.md, src/pages/index.js
https://github.com/NervJS/taro/pull/6221 的补充说明
=> docs: 修改关于 onReady 的说明

docs/config-detail.md, packages/taro-mini-runner/src/index.ts, packages/taro-mini-runner/src/webpack/build.conf.ts, packages/taro-mini-runner/src/webpack/chain.ts, packages/taro-runner-utils/src/constants.ts, packages/taro-runner-utils/types/constants.d.ts
=> feat(mini-runner): 增加compile的include和exclude配置

packages/taro-components/src/components/button/button.tsx
=> fix(components): disabled 属性依然会触发点击事件，close #6216

packages/taro-mini-runner/src/plugins/MiniPlugin.ts
修复两个问题：
1. 支付宝的 tabBar 和微信小程序的 tabBar 的键值不一样
https://opendocs.alipay.com/mini/framework/app-json
https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html
2. 支付宝的 tabBar 图片资源不会被打包
=> fix(mini-runner): 支付宝 tabBar 不显示

packages/taro-h5/src/api/request/index.js
接口为 204 或 No Content 报 `Uncaught (in promise) SyntaxError: Unexpected end of JSON input` 异常
=> fix(taro): statusCode 为 204 或 No Content 报 SyntaxError 异常

packages/taro-components/types/Textarea.d.ts, packages/taro/types/taro.hooks.d.ts
=> fix(type): taro hooks增加deps参数

packages/taro-components/types/Audio.d.ts, packages/taro/types/taro.hooks.d.ts
=> fix(types): remove useScope for next

.github/workflows/auto-review.yml
提交信息带有 `[auto review]` 机器人就会自动 approve PR
=> chore(ci): 可以通过 `[auto review]`  让机器人 approve 提交

packages/taro-cli/src/presets/commands/build.ts
遗漏 await 导致 modifyWebpackChain 的插件配置可能失效
=> fix(cli): modifyWebpackChain await applyPlugins

packages/taro/types/api/ui/tab-bar.d.ts
=> fix(types): 显示隐藏 TabBar 的参数都是可选的

docs/apis/media/map/MapContext.md, docs/apis/network/request/request.md, docs/apis/ui/animation/Animation.md, docs/components/forms/textarea.md, packages/taro-components/types/Audio.d.ts, packages/taro-components/types/Textarea.d.ts, packages/taro/types/api/network/request.d.ts
=> fix(types): request dataType

packages/taro-cli/src/cli.ts, packages/taro-components-rn/src/components/Checkbox/checkboxGroup.tsx, packages/taro-components-rn/src/components/Form/index.tsx, packages/taro-components-rn/src/components/Label/index.tsx, packages/taro-components-rn/src/components/Radio/radioGroup.tsx, packages/taro-router/src/router/router.tsx, packages/taro/types/api/ui/tab-bar.d.ts
=> fix(router): switch to tabbar match err

packages/taro-cli/src/ui/common.ts, packages/taro-cli/src/ui/h5.ts, packages/taro-cli/src/ui/index.ts, packages/taro-cli/src/ui/mini.ts, packages/taro-cli/src/ui/quickapp.ts, packages/taro-cli/src/ui/rn.ts
给cli中的UI构建新增了跨平台支持，同时修复了h5端UI编译新增文件报错的问题以及入口查找中未兼容export {a as b}的问题
=> feat(taro-cli): 新增UI编译跨平台支持

README.md
=> chore: remove FeatHub in readme

packages/taro-service/src/Config.ts
插件系统改造在处理项目配置时漏掉了 terser，此处予以补上。
=> fix(service): 支持 terser 配置

packages/taro-cli/package.json, packages/taro-cli/src/doctor/configSchema.ts, packages/taro-cli/src/doctor/configValidator.ts, packages/taro-cli/src/presets/commands/build.ts, packages/taro-cli/src/presets/commands/info.ts, packages/taro-cli/src/rn.ts, packages/taro-cli/yarn.lock, packages/taro-helper/src/constants.ts, packages/taro-helper/types/constants.d.ts, packages/taro-helper/types/index.d.ts, packages/taro-mini-runner/src/index.ts, packages/taro-service/src/Config.ts, packages/taro-service/src/utils/constants.ts, packages/taro-service/src/utils/index.ts, packages/taro-webpack-runner/src/index.ts, packages/taro/types/compile.d.ts
1.项目配置 config 支持使用 typescript
2.项目编译时会优先检测 config 是否合法
1.项目配置 config 支持使用 typescript
2.项目编译时会优先检测 config 是否合法
=> refactor(cli): config 改造

packages/taro-mobx-common/src/store.js
=> fix(mobx): 修复快应用下 store 未定义的问题(#4248)

packages/taro-router/src/router/router.tsx
=> fix(router): router redirect for tabbar fix #5930

packages/taro-cli/src/presets/commands/build.ts
=> fix(cli): 修复设置环境变量失效的问题，close #6353

packages/taro-cli/src/doctor/configSchema.ts, packages/taro-cli/src/presets/commands/build.ts
=> refactor(cli): 更新配置检测 && 配置检测出错时不中断编译

packages/taro-helper/package.json, packages/taro-webpack-runner/package.json
=> chore: 升级 resolve 的版本

packages/taro-components/src/components/video/style/index.scss
=> fix(video): video controls bar style #6291

packages/taro-rn-runner/src/webpack/chain.ts
- [x ] 错误修复(Bugfix) issue id #
- [x ] 提交到 master 分支
=> fix(rn): image 未能转换成 base64 无法显示 close #6041

.github/workflows/azure-static-web-apps-nice-coast-09f62cc00.yml
=> docs: 文档多部署一份到 azure

packages/taro-components-rn/src/components/Picker/date.tsx, packages/taro-components-rn/src/components/Picker/region.tsx, packages/taro-components-rn/src/components/Picker/selector.tsx, packages/taro-components-rn/src/components/Picker/time.tsx
=> fix(components-rn): picker组件选择无效 close #5846 close #5561

packages/taro-components-rn/package.json, packages/taro-components-rn/src/components/RichText/index.tsx, packages/taro-components-rn/src/components/WebView/PropsType.tsx, packages/taro-components-rn/src/components/WebView/index.tsx
=> fix(components-rn): RichText组件不显示内容 close #5527

packages/taro-components-rn/package.json, packages/taro-components-rn/yarn.lock
=> fix(components-rn): ts error

packages/taro-rn-runner/src/loaders/utils/processAst.ts
=> fix(rn): app.js 中的 config key有引号的编译问题 close #6229

packages/taro-rn-runner/src/loaders/JSXToStylesSheetLoader.ts, packages/taro-rn-runner/src/webpack/chain.ts
=> fix(rn): 去除默认的 css_modules close #6021

packages/taro-cli/src/presets/platforms/swan.ts
=> fix(cli): 移除需要百度安装 @tarojs/swan 的警告

packages/taro/types/api/device/network.d.ts
=> fix(taro): offNetworkStatusChange回调不传是取消所有

versioned_docs/version-3.0.0-beta.5/GETTING-STARTED.md
=> docs: Update GETTING-STARTED.md

packages/taro-cli/src/cli.ts, packages/taro-cli/src/commands/build.ts
=> fix(cli): 修复 build 命令对 env 参数的支持，fix #6441

packages/taro-cli/package.json
cli inspect 用到的 cli-highlight 模块忘记安装了
```
> taro build --type weapp "--watch"
👽 Taro v3.0.0-rc.1
(node:5006) UnhandledPromiseRejectionWarning: Error: Cannot find module 'cli-highlight'
Require stack:
- ~/projects/demo/node_modules/@tarojs/cli/dist/presets/commands/inspect.js
```
=> fix(cli): `cli-highlight` 没有安装到 `@tarojs/cli` 的依赖中

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
* 修复 `@tarojs/cli` 缺少 `cli-highlight` 依赖的问题，huge thanks to @cncolder
=> chore(release): publish v3.0.0-rc.2 [auto review]

packages/taro-rn-runner/src/loaders/utils/processAst.ts
=> fix(rn-runner): alias 和 external 冲突导致替换失败

packages/taro-rn-runner/src/loaders/utils/processAst.ts
=> fix(rn-runner): 样式 require 替换成 import 导致的报错

packages/taro-components/virtual-list/vue/index.js
=> fix(components): 修复 vue 虚拟列表 this 指向不正确的问题

packages/taro-cli/src/create/project.ts
=> fix(cli): 修复 taro init 命令

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
* 修复 vue 虚拟列表 this 指向不正确的问题，fix #6467 
* 修复选择模板逻辑，fix #6457 by @Spencer17x
* 修复 html 解析 className 不正确的问题
* 修复 taro doctor 命令
=> chore(release): publish 3.0.0-rc.3

packages/taro/types/api/media/map.d.ts
修复微信小程序mapContext.getRegion的结果的类型错误
=> fix(taro):修复微信小程序mapContext.getRegion的结果的类型错误

.eslintrc.js, packages/taro-mini-runner/src/plugins/TaroLoadChunksPlugin.ts, packages/taro/src/env.js
0. TaroLoadChunksPlugin isBuildQuickapp 参数修复
0. 快应用环境判断修复
0. eslint 增加 jd
=> 快应用：TaroLoadChunksPlugin 参数修复 && 环境判断修复

packages/taro-h5/src/api/fileTransfer/uploadFile.js
=> 文件上传成功后清除计时器

packages/taro-transformer-wx/src/render.ts
=> fix(transformer): 修复百度小程序编译问题，fix #6431

packages/taro-components/src/components/swiper/index.js
=> fix: unified with wechat swiper circular fix #6277

docs/apis/media/map/MapContext.md, packages/taro-components/src/components/swiper/index.js, packages/taro-components/src/components/swiper/style/index.scss, packages/taro/types/api/location/index.d.ts, packages/taro/types/api/media/map.d.ts
=> 2.x swiper style fixed

packages/taro-mini-runner/src/webpack/base.conf.ts
=> refactor(mini-runner): import 默认 resolve .vue 文件

packages/taro-components/src/components/swiper/index.js, packages/taro-components/src/components/swiper/style/index.scss
=> feat: checkout 2.x swiper

packages/taro-cli/src/presets/platforms/plugin.ts, packages/taro-cli/src/presets/platforms/weapp.ts, packages/taro-mini-runner/src/plugins/MiniPlugin.ts, packages/taro-mini-runner/src/webpack/build.conf.ts
=> fix: 修复小程序插件编译错误，close #6627

packages/shared/src/components.ts
修复[【Taro Next】swiper组件缺少TouchEvents 属性](https://github.com/NervJS/taro/issues/6658)
=> fix(shared): fix swiper component missingtouch events

packages/taro-cli/templates/default/pkg
=> fix(cli): 修复模板

packages/taro-components/src/components/swiper/index.js
=> fix: swiper init error #6674

packages/taro-router/src/router/route.tsx, packages/taro-router/src/router/router.tsx
=> 2.x route issue fixed

packages/taro-mini-runner/src/prerender/prerender.ts
=> refactor(cli): prerender 加入新的全局变量 `__wxConfig`

packages/taro-mini-runner/src/template/index.ts
=> fix(cli): 支付宝小程序 picker 无法使用 block 作为 children

packages/taro-api/src/native-apis.js
一些 API 在 ts 中存在(因为同步自官方文档), 但是 js 中没有.
两点疑问:
1. `taro-api/src/native-apis.js` 中的 `onAndSyncApis` 和 `noPromiseApis` 两个变量有什么区别?
2. 是不是微信小程序具备的 API 都应该加入上述文件中?
=> fix(api): 添加缺失的 API

packages/taro-helper/src/constants.ts
=> refactor(helpers):  PLATFORMS 更改为全局对象

packages/taro-router/src/init.ts, packages/taro-router/src/qs.ts, packages/taro-router/src/router.ts
=> fix(router): hash 模式取不到路由参数

packages/taro-components-rn/package.json, packages/taro-components-rn/src/components/Swiper/index.tsx
=> fix(rn): swiper 问题，close #6495, #6494,  #6269, #5545, #4048

packages/taro-mini-runner/src/webpack/base.conf.ts
=> fix(mini-runner): mjs 应为 .mjs

packages/taro-components/types/ScrollView.d.ts
=> fix(types): 修复拼写错误

packages/taro-rn-runner/src/utils/codeTransform.ts
=> fix: ci type error

packages/taro-components/src/components/pull-down-refresh/index.js, packages/taro-components/src/components/radio/radio-group.js, packages/taro-components/src/components/scroll-view/index.js, packages/taro-components/src/components/swiper/index.js, packages/taro-components/src/components/video/style/index.scss
=> fix: checkout mutil fix for H5 components from 2.x

.github/workflows/nodejs.yml
=> fix: ci on push

packages/taro/types/taro.component.d.ts, packages/taro/types/taro.hooks.d.ts
1. 移除已经不再导出的 React Hooks 的类型定义
2. hooks 的类型定义对齐 runtime 的实现
由于 Taro 3 根目录有 prettier 的配置文件，在保存时编辑器自动对代码进行了一些格式化，因此也建议在 lint-staged 里做强制 prettier。
=> fix（typings）: Taro Hooks 类型定义优化

packages/taro-mini-runner/src/webpack/base.conf.ts
=> refactor(mini-runner): 开发模式也打开 tree-shaking

packages/shared/src/components.ts, packages/taro-api/src/index.js, packages/taro-runtime/src/next-tick.ts
=> refactor(runtime): nextTick 函数一定会在 onReady 之后运行

packages/taro-components/virtual-list/react/createListComponent.js
=> fix(components): 虚拟列表 scrollTo 方法无效

packages/taro-runtime/src/dsl/react.ts
=> fix(runtime): 自定义 tabbar key 报错

packages/taro-cli/src/doctor/configSchema.ts
=> fix(cli): 修复 sass 配置校验，close #6745

versioned_docs/version-3.0.0-beta.5/team.md
add youshu-logo
- [x ] 新功能(Feature)
- [ x] 提交到 master 分支
- [x ] Commit 信息遵循 [Angular Style Commit Message Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)
- [x ] 所有测试用例已经通过
- [ x] 代码遵循相关包中的 .eslintrc, .tslintrc, .stylelintrc 所规定的规范
- [ x] 在本地测试可用，不会影响到其它功能
- [x ] Web 平台（H5）
=> docs: add youshu-logo

docs/youshu.md, sidebars.js, versioned_docs/version-2.2.8/youshu.md, versioned_docs/version-3.0.0-beta.5/youshu.md, versioned_sidebars/version-2.2.8-sidebars.json, versioned_sidebars/version-3.0.0-beta.5-sidebars.json
=> docs: 添加腾讯有数埋点文档

packages/taro-api/src/index.js
=> fix(taro): expose useReady hook

versioned_docs/version-2.2.8/best-practice.md
通篇读下来 突然多了一个 啦 文档变的突然欢快. 个人感觉应该用 了
通篇读下来 突然多了一个 啦 文档变的突然欢快. 个人感觉应该用 了
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nervjs/taro/6812)
=> [Docs]更新最佳实践

packages/taro-plugin-sass/src/index.ts
=> fix(plugin-sass): platformConfig 为空的报错

packages/taro-cli/package.json, packages/taro-cli/src/create/fetchTemplate.ts, packages/taro-cli/src/create/init.ts, packages/taro-cli/src/create/project.ts, packages/taro-helper/types/index.d.ts
* 模板内部去维护所支持的框架列表
* init 时能显示模板简介
=> refactor(cli): 优化 init 命令

packages/taro-cli/templates/default/global.d.ts, packages/taro-cli/templates/default/package.json.tmpl
=> fix(cli): 默认模板加入 jd 相关

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
- 修复 h5 端编译失败的问题，close #6843 ，by @w91
=> chore(release): publish 3.0.1

packages/taro-cli/src/presets/commands/update.ts
update 时应该从 latest dist-tags 中寻找最新版本
=> fix(cli): 修复 update 命令

packages/taro-mini-runner/src/template/index.ts
=> fix(mini-runner): camera 组件也可以渲染子内容，fix #5840

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
- 类组件不需要配置 enableShareAppMessage、enableShareTimeline，#7056
- 修复 windows 下 h5 编译错误 
- 完善 PageConfig 定义、增加 Current.page.config 的定义，by @fjc0k
=> chore(release): 3.0.4

packages/taro-runtime/src/dsl/common.ts
=> fix(runtime): 修复 vue 下报错

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
=> chore(release): 3.0.5

packages/taro-loader/src/utils.ts, packages/taro-webpack-runner/__tests__/__snapshots__/vue.spec.ts.snap
修复 h5 下 vue 在生产环境不工作的问题，改 import 为 require，使代码不被 tree shaking
=> fix(loader): 修复 h5 下 vue 在生产环境不工作的问题, fix #7129

versioned_docs/version-3.0.0/guide.mdx
修复【渐进式入门教程】部分链接404的问题，如：
Please see it and let me know If there are anything that need to be corrected. Thank you :)
Signed-off-by: LinHaiming <lhming23@outlook.com>
=> docs(guide): fix broken link

packages/taro-runtime/src/dom/html/tags.ts
Add `<sub>` html tag to inline element list.
=> fix(taro-runtime): <sub> should be an inline element

packages/taro-runtime/src/dsl/react.ts
兼容 react-redux 7.20.1+ 更改了内部 forwardedRef 变量名的改动：
https://github.com/reduxjs/react-redux/pull/1553
https://github.com/reduxjs/react-redux/pull/1553/files
=> fix(runtime): 修复类组件生命周期不触发的问题

packages/taro-components/virtual-list/react/createListComponent.js
close #6863
- 修正虚拟列表 VirtualList 滚动时出现抖动的问题。 
=> fix(components): 修正虚拟列表 VirtualList 滚动时抖动的问题

packages/taro-rn-runner/package.json, packages/taro-rn-runner/src/loaders/JSXToStylesSheetLoader.ts, packages/taro-rn-runner/src/plugins/RNPlugin.ts, packages/taro-rn-runner/src/utils/debug.ts, packages/taro-rn-runner/src/webpack/chain.ts, packages/taro-rn-runner/yarn.lock
=> fix(rn): common js 样式路径错误的问题

packages/taro-components/src/components/image/index.js, packages/taro-components/src/components/image/style/index.css
=> fix(components): merge #6205

packages/taro-transformer-wx/src/class.ts
=> fix(transformer-wx): 循环体事件绑定

docs/virtual-list.md
=> docs: clear virtual list children data type

packages/babel-preset-taro/index.js, packages/babel-preset-taro/package.json
由于 webpack 里的实现的异步 import() 使用的 `document.createElement("script")`做的代码分块 ，对于其他小程序端该代码分块方式无意义且会报错。通过 [babel-plugin-dynamic-import-node](https://github.com/airbnb/babel-plugin-dynamic-import-node) 可以把 import() 转成 taro 支持的require() 写法，便于跨端项目维护。
=> feat(babel-preset-taro): 非 h5 端也支持异步 import() 语法

versioned_docs/version-3.0.5/components/forms/input.md
=> Update input.md maxLength改为maxlength

packages/taro-service/package.json
=> fix(service): 修复引用 service 包类型报错，fix #7058

versioned_docs/version-3.0.5/react.md
=> fix(typo): react.md@version-3.0.5

packages/taro-components/src/components/picker/index.js
=> fix: picker classname fix #6719

packages/taro-components/src/components/input/index.js
删除 iOS 上关于光标的优化，修复原生九宫格键盘输入英文闪烁问题
=> fix: 优化 iOS 输入体验 fix #6790

packages/taro-router/src/apis/index.ts
=> fix: relanch logic change for fix #6733

packages/taro-router/src/router.ts
=> fix(router): 修复无法正确获取路由参数的问题，fix #7133

packages/taro-components/src/components/picker/picker-group/index.js
=> feat(taro-components): 增加 Picker 鼠标事件响应

docs/config-detail.md
fix https://github.com/NervJS/taro/issues/7357
=> docs: change webpack-chain merge paramster

packages/taro-components/types/Button.d.ts, packages/taro-components/types/common.d.ts
=> feat: next typing upload

packages/taro-components/virtual-list/index.d.ts, packages/taro-components/virtual-list/react/index.d.ts
=> feat(typing): add VirtualList type #6936

packages/taro-runtime/src/dom/html/tags.ts
=> fix(runtime): 行内元素添加 <b> 标签

docs/debug-config.md
=> Update debug-config.md 修复拼写错误

packages/taro-runtime/src/dsl/react.ts, packages/taro-runtime/src/dsl/vue.ts, packages/taro-runtime/src/dsl/vue3.ts
- [ x ] 错误修复(Bugfix) issue id #
- [ x ] 提交到 master 分支
- [ x ] Commit 信息遵循 [Angular Style Commit Message Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)
- [ x ] 微信小程序
- [ x ] 支付宝小程序
- [ x ] 百度小程序
- [ x ] 头条小程序
- [ x ] QQ 轻应用
=> fix(runtime): 修复对百度统计 sdk 的支持，close #7415

docs/components/base/icon.md, versioned_docs/version-2.2.13/components/base/icon.md, versioned_docs/version-3.0.7/components/base/icon.md
=> docs: 修复文字错误

packages/taro-runner-utils/package.json, packages/taro-runner-utils/src/resolve/MultiPlatformPlugin.ts
=> fix(runner-utils): 修复 require.context 问题，fix #6920

packages/taro-cli/src/convertor/index.ts
=> chore(cli): 暂时 convert 只能转换为 react app

packages/taro-components/types/MovableView.d.ts, packages/taro-components/types/Swiper.d.ts
=> fix(components): 修复swiper和movableview的interface拼写错误

packages/taro-components/src/components/input/input.tsx
=> fix(components): 更新 input 的修复

packages/taro/types/taro.extend.d.ts
修改Taro.eventCenter的类型推导逻辑，使用 Events 定义 eventCenter 的逻辑
=> refactor(taro/type): 修改Taro.eventCenter的类型推导

packages/shared/src/template.ts
组件 LivePlayer 可以渲染子元素，fix #7552
=> fix(shared): 组件 LivePlayer 可以渲染子元素，fix #7552

packages/taro-cli/src/presets/commands/init.ts
删除 `taro init` 命令的冗余提示，close #7559
=> chore(cli): 删除taro init命令冗余提示，close #7559

packages/taro-components/src/components/canvas/index.js, packages/taro-h5/src/api/canvas/createCanvasContext.js
=> 2.x fix canvas

packages/taro-components/src/components/tabbar/tabbar.tsx, packages/taro-router/src/tabbar.ts
- 修复 tabbar 初始化不显示问题
- 修复 tabbar 不支持自定义路由问题
=> Next fix tabbar init

packages/taro-router/src/history.ts
1. 使路由模式与官方文档所述同步。
2. 解决tabbar默认被隐藏问题。
官方文档里默认路由模式为hash，但现在实际为browser。
并且因为代码其他部分默认为hash，默认值不统一也导致了tabbar显示异常。
这里改动也能解决tabbar初始化被隐藏问题，因为代码判断是用的hash模式，而这里却是browser。
=> 修复路由默认渲染模式与文档描述不同问题

packages/taro-components/types/Ad.d.ts
=> types: Ad add adType and adTheme

packages/taro/types/api/base/weapp/app-event.d.ts
types 增加 `onThemeChange` `offThemeChange` 方法
=> types: add onThemeChange and offThemeChange

packages/postcss-pxtransform/index.js, packages/taro-alipay/src/native-api.js, packages/taro-jd/src/native-api.js, packages/taro-qq/src/native-api.js, packages/taro-swan/src/native-api.js, packages/taro-tt/src/native-api.js, packages/taro-weapp/src/native-api.js
=> fix(size): 尺寸计算错误

.github/workflows/nodejs.yml, lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
=> Revert "chore(release): publish 3.0.11"

.github/workflows/nodejs.yml, lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
- 修复 baseLevel 配置不生效的问题
- 修复 TabBar 初始化不显示问题，#7290
- 修复 TabBar 自定义路由失效问题
- 修复 mode 默认配置为 hash by @zhaoguoweiLLHC 
- 新增生命周期 onThemeChange、offThemeChange by @baranwang
- 新增 adType、adTheme by @baranwang 
- init 指令冗余提示删除 by @barawang
=> chore(release): publish 3.0.11 [auto review]

packages/taro/types/api/storage/index.d.ts
Taro.getStorage和Taro..getStorageSync增加一个范型参数
=> feat: Taro.getStorage 和 Taro.getStorageSync 增加一个范型参数

packages/taro-cli/src/h5/index.ts, packages/taro-transformer-wx/src/class.ts, packages/taro-transformer-wx/src/render.ts, packages/taro-transformer-wx/src/utils.ts
- 自定义组件 ID 改为项目内路径 HEX 值
- 优化各类 variableName 的 UID 生成值
=> fix: random component id & scope id

packages/taro-h5/src/api/fileTransfer/uploadFile.js
=> fix(h5): api upload abort fix #7448

packages/taro-router/src/router.ts
使用@tarojs/runtime中的requestAnimationFrame
=> fix(tarojs/router): 使用@tarojs/runtime中的requestAnimationFrame

packages/taro-components/types/Input.d.ts
taro/components  `Input` 组件的 `type` 属性并无 `password`  值，进行纠正，赋默认值 `text`。
=> docs(input example): change Input component docs example

packages/taro-mini-runner/src/plugins/MiniPlugin.ts, packages/taro-mini-runner/src/webpack/build.conf.ts
=> fix(mini-runner): 修复对 vue3 的支持，close #7708

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
- 微信小程序添加 always-embed 属性
- 支付宝小程序增加 controlled 属性和 random-number 属性
- 修复对 vue3 的支持，close #7708
- 使用@tarojs/runtime中的requestAnimationFrame (#7742)
=> chore(release): publish 3.0.14

packages/taro-mini-runner/src/plugins/MiniPlugin.ts, packages/taro-mini-runner/src/utils/index.ts
=> fix(mini-runner): 修复插件中引用 taro-ui 组件路径错误，close #7694

packages/taro-h5/__test__/request-test.js, packages/taro-h5/package.json
- 修复 request 的单元测试。
- 添加缺失的 `jest-fetch-mock` 依赖
相关 PR #3659
=> fix(h5): fix the broken UT for request

packages/shared/src/components.ts
支付宝 swiper 增加 acceleration 属性，fix #7801
=> fix(shared): 支付宝 swiper 增加 acceleration 属性，fix #7801

packages/eslint-config-taro/package.json
=> fix(eslint-config-taro): 发布 vue3.js 文件，fix #7814

packages/taro-components/types/Button.d.ts
=> fix(taro-component): 调整 TS 类型定义，应该为可选项

packages/taro-runtime/src/dom/element.ts, packages/taro-runtime/src/dom/form.ts
表单组件设置 value 前不要 stringify，fix #7638
=> fix(runtime): 表单组件设置 value 前不要 stringify，fix #7638

packages/taro/types/api/storage/index.d.ts
使用getStorageSync时给予泛型默认值为any。目的是为了向下兼容以前没有指定泛型的情况。
=> fix(typing): 修复getStorageSync泛型，给与默认值any

packages/taro-runtime/src/dsl/common.ts, packages/taro-runtime/src/dsl/vue3.ts
=> fix(runtime): 修复 Vue3 onShow 触发时机，fix #7771

packages/taro-components/types/Map.d.ts
=> fix(types): upload map to fix #7507

packages/taro-router/src/init.ts
=> fix(router): 默认指定 h5 router mode 为 hash，close #7871

packages/taro-api/src/native-apis.js, packages/taro/types/api/device/battery.d.ts
=> fix(api): 支持 getBatteryInfo，close #7846

packages/taro/apis/alipay.js, packages/taro/apis/jd.js, packages/taro/apis/qq.js, packages/taro/apis/swan.js, packages/taro/apis/tt.js, packages/taro/apis/wx.js
=> fix(taro): 为 Taro 加上 env 属性，fix #7392

packages/taro-cli/src/presets/platforms/alipay.ts
支付宝小程序 swiper 组件的模板不套多一层 view 组件
=> fix(cli): 支付宝小程序 swiper 组件的模板不套多一层 view 组件

packages/shared/src/components.ts, packages/taro-components/types/Swiper.d.ts
=> feat(alipay/components): 支付宝小程序添加disable-touch属性

packages/taro-router/src/history/createHistory.ts
=> fix: wechat wrong location

docs/README.md
=> docs(chore): 测试预览

docs/css-in-js.md, versioned_docs/version-3.x/css-in-js.md
[linaria](https://github.com/callstack/linaria)发布了新版本`2.0.0`，文档中描述的配置文件配置已过时。
=> docs: 修复linaria@2.x的配置

packages/taro-runtime/src/dom/root.ts, packages/taro-runtime/src/next-tick.ts
=> fix(runtime): fix typo

packages/taro-runtime/src/dsl/react.ts
fix(runtime): [react]修复小程序端App componentWillMount内使用getCurrentInstance().router无法获取onLaunch参数的问题
修复小程序端App componentWillMount内使用getCurrentInstance().router无法获取onLaunch参数的问题
=> fix(runtime): [react]修复getCurrentInstance().router无法获取onLaunch参数的问题

packages/taro-runtime/src/dsl/vue.ts
=> fix(runtime): 修复 vue2 获取不到 onLaunch 参数的问题

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
- 修复 React 中 App 组件的 `componentWillMount` 内无法获取 `onLaunch` 参数的问题，by @hisanshao
- 修复 Vue2 中 App 组件的 `mounted` 内无法获取 `onLaunch` 参数的问题
- 同步微信小程序 `performance` 相关 api，#7931
- 同步微信小程序 `chooseMedia` api，#7954
- 同步支付宝 `ScrollView` 组件的 `scroll-animation-duration` 和 `trap-scroll` 属性，#7922
- 修复列表顺序变化时，部分列表项点击事件失效的问题，#7227
- 修复 `Swiper` 不能嵌套调用的问题，#7692
- 修复 `ContentType` 重复设置的问题，#7972
=> chore(release): publish 3.0.16

packages/taro-components/__tests__/swiper.spec.js, packages/taro-components/src/components/swiper/swiper.tsx
- 修复 Swiper 因为 stencil 和 react 兼容导致的问题
- 修复 Swiper 循环状态下当前 Slider 错误问题
=> fix(component): 修复 Swiper 相关的问题

docs/guide.mdx
补充「教程」文档中「状态管理」关于 vuex 部分的代码片段。
=> docs(guide): complete vuex example

versioned_docs/version-3.x/guide.mdx
补充「教程」文档中「状态管理」关于 vuex 部分的代码片段。
=> docs(guide vuex example): complete vuex example

docs/GETTING-STARTED.md, versioned_docs/version-3.x/GETTING-STARTED.md
=> Docs guide

docs/components/media/video.md, packages/taro-components/types/Video.d.ts, website/versioned_docs/version-2.0.6/components/media/video.md, website/versioned_docs/version-2.1.1/components/media/video.md
=> docs: 文字错误

packages/taro-components/types/Map.d.ts
=> fix(type):  fix MapProps

packages/taro/types/taro.extend.d.ts
=> fix(type): resubmit from #7914

.github/workflows/auto-review.yml, .github/workflows/publish.yml
- 修复 swiper 不能嵌套的问题，#8023 
- 同步百度小程序广告组件属性，#8018 
- 修复 `Swiper` 因为 stencil 和 react 兼容导致的问题，#7757 #7976 #6179 
- 修复 `Swiper` 循环状态下当前 Slider 错误问题
- 修复 `Map` 组件 types，by @gjc9620 
- 修复 `TaroEvent` 相关 types，by @SyMind
=> chore(release): publish 3.0.17 [auto review]

.github/workflows/auto-review.yml, .github/workflows/publish.yml
- 修复 swiper 不能嵌套的问题，#8023 
- 同步百度小程序广告组件属性，#8018 
- 修复 `Swiper` 因为 stencil 和 react 兼容导致的问题，#7757 #7976 #6179 
- 修复 `Swiper` 循环状态下当前 Slider 错误问题
- 修复 `Map` 组件 types，by @gjc9620 
- 修复 `TaroEvent` 相关 types，by @SyMind
=> Chore/release 3.0.17 [auto review]

.github/workflows/auto-review.yml, .github/workflows/publish.yml
- 修复 swiper 不能嵌套的问题，#8023 
- 同步百度小程序广告组件属性，#8018 
- 修复 `Swiper` 因为 stencil 和 react 兼容导致的问题，#7757 #7976 #6179 
- 修复 `Swiper` 循环状态下当前 Slider 错误问题
- 修复 `Map` 组件 types，by @gjc9620 
- 修复 `TaroEvent` 相关 types，by @SyMind
=> chore(release): publish 3.0.17 [auto review] 

docusaurus.config.js, static/css/custom.css
=> docs(fix): 暗黑模式下设置logo、代码块背景色

packages/taro-runtime/src/dsl/react.ts
修复 React 框架下因获取 app 的时机不正确导致 onLaunch 不能正确执行的问题
=> fix: 修复因 app 为 null 导致 onLaunch 不能正确执行的问题

packages/taro-api/src/native-apis.js
增加 offNetworkStatusChange api (fix #8140)
=> fix(taro-api): add offNetworkStatusChange api

packages/taro-components/virtual-list/vue/index.js
=> fix(virtual-list): H5 下报错 unknown custom element fix #8083

docs/README.md, versioned_docs/version-3.x/README.md
更新了taro文档中无法访问的案例链接。之前的链接会去到[这里](http://taro-docs.jd.com/taro/docs/showcase)，导致显示404。
=> docs(fix): 更新无法访问的案例链接

packages/taro-service/src/Kernel.ts
=> fix(taro): 编译缺少 framework 字段时报错，fix #8092

versioned_docs/version-3.x/react-native-remind.md, versioned_sidebars/version-3.x-sidebars.json
=> 迁移并更新文档：RN端开发前注意

packages/taro/types/api/canvas/index.d.ts
=> canvasToTempFilePath 中 canvasId 不再是必传项

README.md
=> docs: 修复 readme 特别鸣谢中头像超链与本人不一致问题

packages/taro-cli/package.json
=> chore(cli): 调整 taro 支持的 node 最低版本

docs/config-detail.md, versioned_docs/version-3.x/react-native.md
=> docs: 更新 RN 端构建APP, 加载 bundle 及静态资源步骤

packages/taro-runtime/src/dsl/common.ts
页面onUnmount的事件改为同步触发，避免降低微信体验评分
=> chore(runtime): 页面onUnmount的事件改为同步触发，避免降低微信体验评分

packages/taro-components/src/components.d.ts, packages/taro-components/virtual-list/index.d.ts, packages/taro-components/virtual-list/react/FixedSizeList.js, packages/taro-components/virtual-list/react/createListComponent.js, packages/taro-components/virtual-list/react/index.d.ts, packages/taro-components/virtual-list/react/index.js
- 新增特性 unlimitedSize 解开高度列表单项大小限制，默认值使用: itemSize (请注意，初始高度与实际高度差异过大会导致隐患)。
- 新增参数 renderBottom 渲染底部区域
- 修改虚拟列表计算规则「目前存在隐患，可能会导致 onScroll 事件多次调起」
如非必要请勿使用 unlimitedSize 参数；使用 unlimitedSize 参数请务必使 itemSize 和预计的节点大小相近
=> feat: 跟新虚拟列表相关优化

packages/taro-runtime/src/hydrate.ts
=> fix(runtime): 修复判断是否 pure-view  的正则表达式错误

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
- 增加生成原生自定义组件 `CustomWrapper`，以应对低端机数据更新过慢的情况
- `VirtualList` 组件支持 item 不定高
- 修复 `View` 组件不能设置属性的问题
=> chore(release): publish 3.0.20

packages/taro-runtime/package.json, packages/taro-runtime/src/dom/root.ts, packages/taro-runtime/yarn.lock
=> fix(runtime): 更换 lodash 为 es 版本

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
=> chore(release): publish 3.0.21

packages/taro-runtime/src/dom/root.ts, packages/taro-runtime/src/hydrate.ts
- [ x ] 错误修复(Bugfix) issue id #
=> fix(runtime): 兼容某些小程序没有 __data__ 属性的情况

versioned_docs/version-3.x/config-detail.md
=> doc(3.x): fix typo

packages/taro-components/types/Picker.d.ts
=> fix: make picker value optional

.github/ISSUE_TEMPLATE/config.yml
备用地址：
- https://nervjs.github.io/taro-issue-helper/
- https://tls.jd.com/taro-issue-helper
=> chore(workflow): 更新 taro-issue-helper 链接

versioned_docs/version-3.x/components/forms/input.md
https://developers.weixin.qq.com/miniprogram/dev/component/input.html
=> adjustPosition 微信官方默认值是true

packages/taro-components/src/components.d.ts, packages/taro-components/src/components/custom-wrapper/custom-wrapper.tsx, packages/taro-components/types/components.d.ts
=> feat(h5): 在 H5 平台添加 custom-wrapper 组件

packages/taro-runtime/src/dsl/hooks.ts, packages/taro-runtime/src/dsl/react.ts
修复 app 不能使用 `useDidShow` `useDidHide` 的问题，fix #8348
=> fix(runtime): 修复 app 不能使用Show/Hide钩子的问题，fix #8348

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
- 设置 `innerHTML` 支持解析 `style` 标签
- 增加 `CustomWrapper` 组件，by @vdfor 
- 补全 `window` 对象的关键属性，#8327 
- 修复 `CustomWrapper` 的一些问题
- 修复在 app 入口组件中不能使用 `onShow`、`onHide` 钩子的问题，#8348
- 修改 `Picker` 组件的 value 值为可选属性，by @taoqf
=> chore(release): publish 3.0.22

versioned_docs/version-3.x/react-native.md
=> update(docs): 更新RN端打release包方案

packages/taro-components/src/components/swiper/swiper.tsx
修复 swiper 组件 current 改变事件重复调用问题
- [ x] 在本地测试可用，不会影响到其它功能
=> fix(components): 修复 swiper 组件 current 改变事件重复调用问题

versioned_docs/version-3.x/html.mdx
img ===> image
更新 transformElement 示例代码
=> 更新 transformElement 示例代码

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
- 支持在小程序 app 对象上挂载自定义属性
- `CustomWrapper` 组件、协助递归的内部自定义组件设置为虚拟节点，解决 DOM 深度达到一定层级后 flex 样式失效问题，by @jin-yufeng 
- 修复全局样式重复打包的问题
- 修复 `window.raf` `window.caf` 以 apply 方式调用时使用报错的问题，#7749
- 修复 Vue3 运行时报错，#8426
- 修复 React、Vue、Vue3 都不能使用 vant 的 `kebab-case` 事件的问题，#8407 #8242 #8364
- 修复 Vue3 使用第三方组件时事件绑定错误的问题
- 修复 `Swiper` 组件滑动越来越快的问题
=> chore(release): publish 3.0.23

packages/taro-api/src/native-apis.js
=> fix(taro-api): add gyroscope related apis (#8496)

versioned_docs/version-3.x/react-native.md
1、更新跨端开发参考项目：[wuba/Taro-Mortgage-Calculator](https://github.com/wuba/Taro-Mortgage-Calculator)
=> update(docs):  更新三端开发参考demo

packages/taro-router/src/scroll.ts
修复 TabBar 导致的 onPageScroll 事件失效问题
=> fix(h5): scroll-page event

packages/taro-cli/src/presets/platforms/swan.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap
=> fix(cli): 修复百度 Text 不显示文本的问题

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
- 补充陀螺仪相关 API，by @ZeroTo0ne ，#8496
- 修复支付宝、百度、头条等小程序运行直接报错的问题
- 修复百度 `Text` 组件不显示文本内容的问题
- 修复 React 在事件回调里没有合并更新的问题，#8516
- 修复 react 不能取消事件监听的问题
- 修复 `View`、`Text`、`Image` 组件在切换属性或事件时，没有切换正确模板的问题, #8520
- 修复组件 id 为是 number 类型时，事件失效的问题，#8515
- 修复 TabBar 导致的 `onPageScroll` 事件失效的问题
- 修复 `navigateTo` 回调 `success` 入参的类型缺少 `eventChannel` 类型的问题，by @Aysnine ，#8506
=> chore(release): publish 3.0.24

packages/taro-rn/types/index.d.ts
发布版本，解决 ubuntu-18.04 环境下 typing 报错
=> chore(release): publish 3.2.0-canary.7

packages/taro-loader/package.json, packages/taro-loader/src/app.ts, packages/taro-loader/src/component.ts, packages/taro-loader/src/page.ts
=> fix(loader): 修正 taro-loader 处理

docs/GETTING-STARTED.md, versioned_docs/version-1.x/GETTING-STARTED.md, versioned_docs/version-2.x/GETTING-STARTED.md, versioned_docs/version-3.2.0-canary.3/GETTING-STARTED.md, versioned_docs/version-3.x/GETTING-STARTED.md
This commit also adds spaces between Chinese and Latin charater, for the
line on the top of npm-info-tarojs image...
1. 纠正了文档中的一张 Markdown 图片
2. 为图片上面的一行中的中文字符和英文字符添加空格，以与文档其它内容的中文排版风格统一
=> docs: correct Markdown syntax for npm-info-tarojs img

packages/taro-runtime/src/__tests__/html.spec.js, packages/taro-runtime/src/dom/html/style.ts
=> fix(runtime):修复解析html不显示换行问题 fix #7003 #8549

versioned_docs/version-3.x/components/forms/input.md
1、补充 Input 组件在 RN 端获取光标位置的说明文档。
=> docs: 补充 RN 端 Input 组件文档说明

packages/taro/apis/wx.js, packages/taro/types/api/cloud/index.d.ts
添加 wx.cloud.Cloud API #8623
- [] 其他，请描述(Other, please describe):
- [] 在本地测试可用，不会影响到其它功能
帮忙看一下有什么需要改的, 我再改一下, 现在 next 分支我拉取下来编译不了,所以没执行 yarn bulid, 不确定有没有问题
=> feat(taro): 添加 wx.cloud.Cloud API #8623

packages/taro-components/src/components/form/index.js, packages/taro-components/types/Form.d.ts
对传给form组件的属性做了透传处理，更新了Form.d.ts
=> fix(components): 修复form组件设置h5原生属性无效的问题

packages/taro-router/src/apis/index.ts
在首次加载调用Taro.reLaunch时，依然会出现[#6733](https://github.com/NervJS/taro/issues/6733)的问题，这个pr修复了这个问题
=> fix(router): 修复页面首次加载时调用Taro.reLaunch会跳转到空页面

packages/taro-cli/src/presets/files/generateFrameworkInfo.ts, packages/taro-cli/src/presets/platforms/swan.ts
应百度小程序官方要求，需要生成 .frameworkinfo 文件
=> fix(cli): 修复百度小程序下生成 .frameworkinfo 文件问题

packages/taro/apis/wx.js, packages/taro/types/api/cloud/index.d.ts
添加了云托管调用 wx.cloud.callContainer API
=> feat(taro): 添加 wx.cloud.callContainer API

packages/taro-redux/src/connect/connect.js
=> fix(redux): 特殊情况下redux更新无法触发视图更新, fix #8705

versioned_docs/version-3.x/config-detail.md
=> docs: 增加less-loader@7说明

packages/taro-rn-supporter/src/Support.ts
支持声明`react-native`的模块导入，比如 [styled-components](https://github.com/styled-components/styled-components/tree/master/packages/styled-components)
=> fix(rn): 修复不支持导入react-native声明的模块

packages/taro-mini-runner/src/webpack/build.conf.ts
=> fix(mini-runner): 修复react/jsx-runtime报错，fix #8750

packages/taro-mini-runner/src/plugins/TaroNormalModulesPlugin.ts
=> fix(mini-runner): 兼容 react17，fix #8756

packages/babel-plugin-transform-jsx-to-stylesheet/README.md
=> chore(release): publish 3.2.0-beta.0

packages/taro-runtime/src/dom/style.ts
修复设置 Webkit 前缀 style 失败的问题，fix #8805
=> fix(runtime): 修复设置 Webkit 前缀 style 失败的问题，fix #8805

packages/taro-runtime/src/utils/index.ts
fix #8853
修改通过属性名判断 pure-view 的正则(在 isHasExtractProp 方法中)
=> fix(runtime): 修复给 View 新增 hidden 属性无效的问题

packages/taro-api/src/index.js, packages/taro/types/api/base/index.d.ts
=> fix(taro): 修复跳转预加载 API，fix #8873

packages/taro-alipay/src/program.ts, packages/taro-alipay/types/program.d.ts
=> fix(alipay): 修复与钉钉小程序开放接口 API 的兼容问题，fix #8684

packages/taro-cli/src/commands/customCommand.ts, packages/taro-cli/src/presets/commands/build.ts
=> fix(cli): 修复环境变量失效的问题，fix #8900

packages/taro-runtime/src/__tests__/dom.spec.js, packages/taro-runtime/src/dom/element.ts
=> fix(runtime): 修复无法移除组件的class

docs/plugin.md, versioned_docs/version-2.x/plugin.md, versioned_docs/version-3.2.0-canary.3/plugin.md, versioned_docs/version-3.x/plugin.md
=> docs(plugin): typo

versioned_docs/version-3.2.0-canary.3/apis/framework/getCurrentPages.md, versioned_docs/version-3.2.0-canary.3/apis/route/EventChannel.md, versioned_docs/version-3.2.0-canary.3/apis/ui/background/setBackgroundColor.md, versioned_docs/version-3.2.0-canary.3/apis/ui/background/setBackgroundTextStyle.md, versioned_docs/version-3.2.0-canary.3/apis/ui/scroll/pageScrollTo.md, versioned_docs/version-3.2.0-canary.3/react-native-remind.md, versioned_docs/version-3.2.0-canary.3/react-native.md, versioned_docs/version-3.2.0-canary.3/tutorial.md, versioned_docs/version-3.x/envs.md, versioned_docs/version-3.x/react-native.md
1、 跨平台开发，增加 RN 端【让 node_modules 中的依赖也能解析多端文件】配置
2、完善rn的api,组件等相关文档
3、修复 RN 端浏览器加载 jsbundle 过程的相关文档 https://github.com/NervJS/taro/issues/8734
=> docs: 更新 RN 端部分文档

packages/taro-components/src/components/input/index.js
=> fix(component): 修复Input组件粘贴无效的问题(#8862)

docs/apis/open-api/authorize/authorize.md, versioned_docs/version-3.2.0-canary.3/apis/open-api/authorize/authorize.md, versioned_docs/version-3.x/apis/open-api/authorize/authorize.md
=> docs: 修复授权文档一处链接错误

packages/taro-cli/templates/default/project.tt.json
=> fix(cli): 默认模版调整头条小程序的配置文件

packages/taro-runtime/src/bom/window.ts
=> fix(runtime): 非 Taro 环境不覆盖 window 对象属性

packages/taro-webpack-runner/src/config/base.conf.ts
=> 缺少 chain 参数，导致无法识别H5的多端文件

docs/team.md
=> docs: links add anjuke

packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/README.md
- 特性支持 taro css module
- 特性支持 rn TabBar 的图片支持本地图片
- 修复设置 hoverStartTime 后，立即出现点击态问题
- 修复跳转白条问题
- 修复缺少 chain 参数，导致无法识别 H5 的多端文件问题 (#9068)，by @linshengjian  
- 修复 window 对象属性覆盖兼容非 Taro 构建环境 (#9065)，by @xughv
=> chore(release): publish 3.2.2

packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/yarn.lock, packages/babel-preset-taro/yarn.lock, packages/taro-cli/yarn.lock, packages/taro-components-react/yarn.lock, packages/taro-components-rn/package.json, packages/taro-components-rn/yarn.lock, packages/taro-components/yarn.lock, packages/taro-helper/yarn.lock, packages/taro-mini-runner/yarn.lock, packages/taro-rn-runner/yarn.lock, packages/taro-rn-style-transformer/yarn.lock, packages/taro-rn-supporter/yarn.lock, packages/taro-rn/yarn.lock, packages/taro-router-rn/yarn.lock, packages/taro-runtime-rn/yarn.lock, packages/taro-webpack-runner/yarn.lock
0. 更新yarn lock 文件
1. 解决lock更新后 components-rn 报错
=> 更新yarn lock 文件

packages/taro-components/virtual-list/react/createListComponent.js
移除 PR #8562 修复，同时修复在 resolve 定位方式下，onScroll 事件多次调用问题 （#8560）
=> fix(components): 修复虚拟列表抖动问题 fix #8936

packages/taro-router/src/router.ts
=> fix(router): 修复点击浏览器返回按钮异常的问题

packages/taro-components-rn/src/components/Input/PropsType.tsx, packages/taro-components-rn/src/components/Input/index.tsx, packages/taro-components-rn/src/components/Textarea/PropsType.tsx, packages/taro-components-rn/src/components/Textarea/index.tsx
将rn平台 input maxLength 属性 改为maxlength，与其他平台保持一致
=> fix(components-rn): change input prop maxLength to maxlength

packages/taro-router/src/router.ts
同步h5环境下页面卸载时不调用onHide，让h5与小程序行为一致
=> fix(router): 修复h5中页面卸载时生命周期行为与小程序不一致问题

packages/taro-h5/src/api/scroll/index.js
修复 `Taro.pageScrollTo` 报错，fix #9152
=> fix(h5): 修复 Taro.pageScrollTo 报错，fix #9152

packages/taro-components/src/components/pull-down-refresh/pull-to-refresh.tsx
=> fix(compoments): pull-to-refresh

packages/taro-runtime/src/hydrate.ts
优化数据结构，兼容百度小程序，fix #8987 #8958 
=> fix(runtime): 优化数据结构，兼容百度小程序，fix #8987

packages/taro-alipay/src/runtime.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
修复支付宝小程序下 Vue3 报错，fix #9153
之前为了修复 #8684，支付宝环境下 providePlugin 不提供模拟的 navigator 对象，而是使用全局自带的 navigator 对象。
但支付宝的 navigator 对象在真机中没有 userAgent 属性，只有 swuserAgent，这会引起 Vue3 报错，因此予以兼容。
=> fix(runtime): 修复支付宝小程序下 Vue3 报错，fix #9153

packages/taro-mini-runner/src/webpack/chain.ts, packages/taro-webpack-runner/src/util/chain.ts
修复 sass 解析 Webpack alias 失败，fix #9207
=> fix(mini-runner): 修复 sass 解析 alias 失败，fix #9207

docs/react-native.md, versioned_docs/version-3.x/react-native.md
=> docs: update rn doc

packages/taro-mini-runner/src/webpack/vue.ts, packages/taro-mini-runner/src/webpack/vue3.ts, packages/taro-runtime/src/dom/root.ts
为 Vue/Vue3 增加 `custom-wrapper` 组件的支持，fix #8989
=> feat(mini-runner): 为vue增加custom-wrapper，fix #8989

packages/taro-swan/src/template.ts, packages/taro-swan/types/template.d.ts
修复百度小程序 PickerView 不显示的问题，fix #9239
=> fix(swan): 修复百度小程序 PickerView 不显示的问题，fix #9239

packages/taro-qq/package.json
=> fix(qq): 修复 qq 平台的类型问题，fix #9248

packages/taro-components-rn/src/components/CustomWrapper/index.tsx, packages/taro-rn-runner/src/index.ts
0. 增加`CustomWrapper` 组件。
1. 增加编译结束后的 `onBuildFinish` 回调
=> 增加 CustomWrapper 及 onBuildFinish

docs/config-detail.md
=> docs: 编译配置详情增加 rn resolve 配置文档说明

packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/yarn.lock, packages/babel-preset-taro/yarn.lock, packages/eslint-config-taro/yarn.lock, packages/taro-cli/yarn.lock, packages/taro-components-react/yarn.lock, packages/taro-components-rn/package.json, packages/taro-components-rn/yarn.lock, packages/taro-components/yarn.lock, packages/taro-helper/yarn.lock, packages/taro-loader/yarn.lock, packages/taro-mini-runner/yarn.lock, packages/taro-rn-runner/yarn.lock, packages/taro-rn-style-transformer/yarn.lock, packages/taro-rn-supporter/yarn.lock, packages/taro-rn/package.json, packages/taro-rn/yarn.lock, packages/taro-router-rn/package.json, packages/taro-router-rn/yarn.lock, packages/taro-router/yarn.lock, packages/taro-runner-utils/yarn.lock, packages/taro-webpack-runner/yarn.lock, packages/taro-with-weapp/yarn.lock, packages/taroize/yarn.lock
0. 修复 @types/node 新版本与RN不兼容
1. update yarn lock files
=> update yarn lock

README.md, README_EN.md
=> docs(readme): add english readme

packages/taro-runtime-rn/src/app.ts, packages/taro-runtime-rn/src/current.ts, packages/taro/types/taro.extend.d.ts
0. 添加rn navigationRef 导出到 Current
1. 增加native传递的props
=> feat(runtime-rn): add navigationRef & initialProperties

packages/taro-h5/src/api/canvas/createCanvasContext.js
- drawImage: h5  CanvasRenderingContext2D 不支持字符串形式
- createCircularGradient: 新增
- measureText: 修复 measureText 获取的数据不准确， measureText 的计算依赖于当前配置的字体相关属性
=> fix(h5): 修复 createCanvasContext 相关问题

versioned_docs/version-3.x/apis/device/network/getNetworkType.md
=> fix: Taro.getNetworkType 示例代码错误

docs/config-detail.md, versioned_docs/version-3.x/config-detail.md
=> docs: 编译配置详情添加optimizeMainPackage用法以及说明 (#8135)

packages/taro-router/src/router.ts, packages/taro/types/compile.d.ts
=> fix(router): 添加 forcePath 配置

versioned_docs/version-3.x/team.md
=> feat: add tianxin logo

packages/taro-plugin-html/src/constant.ts
将 view 和 view-block 标签添加到转换的白名单中
=> fix: add view view-block in blockElements

packages/taro-alipay/src/index.ts
=> fix(alipay): 修复支付宝小程序混写原生页面编译出错，close #9471

packages/taro-loader/src/independentPage.ts, packages/taro-loader/src/native-component.ts, packages/taro-mini-runner/src/plugins/MiniPlugin.ts
=> fix(plugin): 修复在插件中无法调用 taro api 的问题，close #9457

packages/taro-runtime/src/dsl/react.ts, packages/taro-runtime/src/dsl/vue.ts, packages/taro-runtime/src/dsl/vue3.ts
=> fix(runtime): 修复 H5 初始化问题，close #9511

packages/taro-mini-runner/src/plugins/MiniSplitChunksPlugin.ts
=> fix(mini-runner): 修复window上构建失败的问题 (#9422)

packages/taro-weapp/src/program.ts, packages/taro-weapp/types/program.d.ts
解决微信小程序 sourcemap 映射失败的问题，fix #9412
=> fix(weapp): 解决微信小程序 sourcemap 映射失败的问题，fix #9412

packages/taro-runtime/src/bom/window.ts
微信的 atob 会影响 jwt 解析，所以删除 `window.atob`，fix #8360
=> fix(runtime): 微信的 atob 会影响 jwt 解析，所以删除，fix #8360

packages/taro-alipay/src/program.ts
支持支付宝小程序项目配置文件 mini.project.json，fix #9331
=> feat(alipay): 支持支付宝项目配置文件，fix #9331

packages/taro-components-rn/package.json, packages/taro-components-rn/tsconfig.json, packages/taro-components-rn/yarn.lock, packages/taro-rn-runner/src/index.ts, packages/taro-rn-style-transformer/package.json, packages/taro-rn/package.json, packages/taro-rn/yarn.lock, packages/taro-router-rn/package.json, packages/taro-router-rn/yarn.lock, packages/taro-runtime-rn/package.json, packages/taro-runtime-rn/yarn.lock
0. 更新 types 版本
1. 生成sourcemap输出目录
=> chore(rn): update types version && ensure sourcemap dir

versioned_docs/version-3.x/virtual-list.md
=> docs: 更新虚拟列表组件在 vue3 的状态

versioned_docs/version-2.x/apis/route/navigateTo.md
version： Taro 2.x
函数组件里没有this.$scope，应该使用useScope取得scope
=> docs: Update navigateTo.md

packages/taro-alipay/src/template.ts, packages/taro-alipay/types/template.d.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
修复 Vue3 使用 Swiper 时出现空白页的问题，fix #9618
=> fix(alipay): 修复 Vue3 使用 Swiper 时出现空白页的问题，fix #9618

packages/taro-webpack-runner/src/__tests__/__snapshots__/babel.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/config.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/nerv.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/sass.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/ts.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/vue.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap, packages/taro-webpack-runner/src/plugins/MainPlugin.ts
=> fix: 修复taro在低端机安卓4.4上面白屏的问题

packages/taro-components/src/components/swiper/swiper.tsx
=> fix(components): swiper 3.x 适配 fix #8564

packages/taro-jd/src/components.ts, packages/taro-jd/types/components.d.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap
=> fix(jd): 京东小程序Canvas补全type属性

packages/shared/src/template.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/nerv.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap, packages/taro-swan/src/template.ts, packages/taro-swan/types/template.d.ts
修复删除 `<input>` 内容时光标跳动的问题，fix #6632
=> fix(swan): 修复删除 input 内容时光标跳动的问题，fix #6632

packages/taro-runtime/src/dsl/vue3.ts
This reverts commit 9b87b264688142f83135124ff18c140c30adb43e.
fix(runtime): 修复 Vue3 setup 语法渲染失败的问题，fix #9691 
=> Revert "fix(runtime): 修复 Vue3 生命周期触发问题，fix #9614"

packages/taro-components-rn/package.json, packages/taro-rn/package.json, packages/taro-router-rn/package.json, packages/taro-runtime-rn/package.json, packages/taro-runtime-rn/src/page.ts
=> fix(rn): add minheight to pagecomponent
