NervJS/taro

README.md, docs/GETTING-STARTED.md, packages/taro-cli/templates/default/pkg
- 4723de7 将cli写入模板依赖，方便非全局安装模式执行build https://github.com/NervJS/taro/issues/44
- 5a2dfbe 模板增加npm script，简化开发与构建的操作
- 2b8001a 更新相关文档
cli作为模板依赖测试
小程序编译预览测试
H5编译预览测试
打包小程序代码测试
打包H5代码测试
=> 将cli写入模板依赖

packages/taro-cli/templates/default/index.js
Fixes #48 
默认 yarn 用户有一定动手能力，比如会换源，挂代理。所以不需要指定源，反而造成一些不便。
=> yarn用户不生成.npmrc

docs/events.md
events.md 文档中未引入 Events，会报错 Events is not defined
import Taro from '@tarojs/taro'
=> 应改为
import Taro,{Events} from '@tarojs/taro'
=> docs bug: events.md import 未引入 Events

packages/taro-cli/src/weapp.js
https://github.com/NervJS/taro/issues/190
=> feat(taro-cli): 为 dist/ 编译出 project.config.json，由此可把 dist/ 拖入开发者工具以避免无效编译，详见 #190

packages/taro-cli/templates/default/index.js, packages/taro-cli/templates/default/pkg, packages/taro-cli/templates/redux/index.js, packages/taro-cli/templates/redux/pkg
开启typescript时，package.json里默认没有@tarojs/plugin-typescript这个包，导致编译失败。
添加了对typescript的判断，本地测试默认模版下，开与不开typescript都能正常编译了。
=> fix(cli): pkg模版typescript与@tarojs/plugin-typescript依赖缺失, fix #233

docs/config-detail.md
主要是在使用中H5需要开启https服务，通过查阅`taro-webpack-runner/src/index.ts`中的`buildDev`方法中介绍了开启`https`设置方法，因此增加了开启`https`服务文档介绍。
如果使用的不对，请告知正确用法，谢谢。
=> h5配置开启https文档介绍

packages/postcss-pxtransform/index.js, packages/taro-cli/src/weapp.js, packages/taro-cli/templates/default/config/index
增加 `尺寸设计稿换算配置` 的可配置的设置，使用方法：
```
// config/index.js
const config = {
....
deviceRatio: {
'640': 2.34 / 2,
'750': 1 / 2,
'828': 1.81 / 2
}
....
}
```
=> feat(taro-cli | postcss-pxtransform): 增加尺寸设计稿换算配置

packages/taro-redux/src/connect/connect.js
当使用如下情况时，会出现在`componentWillReceiveProps`中取得的`this.props`会与`nextProps`相同
```javascript
@connect(({ counter }) => ({
num: counter.num,
str: counter.str,
}), (dispatch) => ({
add () {
dispatch({type: 'counter/do', payload: 1}) // 这个更新counter中的num
},
}))
class Index extends Component {
// ....
}
```
如上例子中，当调用`add`时，使得`store`订阅的`stateListener`触发时，通过`mapStateToProps`得到的`newMapState`的`keys`有2个，因此在遍历`newMapState`过程中会循环2次，第一次循环中`this.props`（旧的）会先被赋值给`this.prevProps`，并且`this.props[key] !== val`会成立，导致`this.props`更新，下一次循环的时候更新的`this.props`（新的）又会被赋值到`this.prevProps`中，导致`this.prevProps`存入最新的`prop`。
之前那个PR的commit message没有遵循CHANGELOG规范 重新提交一下....
=> fix(taro-redux): 修复connect中preProps会被覆盖成最新props的问题

packages/taro/types/index.d.ts
- 修改 `taro/types` 中的微信 API navigateBack 为可选参数
=> 微信 API navigateBack 改为可选参数

packages/taro-weapp/src/create-component.js
不同平台上的 err.stack 格式不一样
`console.log(err.stack.toString());`
开发工具格式
```
TypeError: Cannot read property 'hasOwnProperty' of undefined
at TripCard._createData (index.js:sourcemap:39)
at Object.createComponent (index.js:2168)
at index.js:sourcemap:60
at require (WAService.js:19)
at appservice?t=1534184446171:1725
```
真机 ios 格式
```
_createData@https://servicewechat.qq.com/app-service.js:12618:44
createComponent@https://servicewechat.qq.com/app-service.js:4898:60
https://servicewechat.qq.com/app-service.js:12639:83
require
global code@https://servicewechat.qq.com/app-service.js:12641:17
```
真机 android 格式
```
TypeError: Cannot read property 'hasOwnProperty' of undefined
at TripCard._createData (X5JavaBridge-5845e37c50c9e7cb17be3f591723deb:12618:44)
at Object.createComponent …
```
=> fix(taro-weapp): Taro warn 在微信内的兼容性问题

packages/taro-components/types/Picker.d.ts
onChange 在不是受控组件下，并不需要。
其余的几个事件也不是必填的。
=> picker 几个事件不是必填项

packages/taro-transformer-wx/package-lock.json, packages/taro-transformer-wx/package.json, packages/taro-transformer-wx/src/index.ts
用 taro h5 模式的时候，希望用到动态加载 import()，
但每次我在代码里面用到import()的时候就会提示
unknown: 'import' and 'export' may only appear at the top level (31:8)
这是因为在编译时 ast 解析报的错，
是否可以在taro-transformer-wx中转换的babel插件配置加上dynamicImport选项？
=> feat: 新增 taro h5 模式的动态加载 import() 功能

packages/taro-components/types/Button.d.ts
微信支持getRealnameAuthInfo的open-type，taro的typescript没有支持
=> typescript支持Button组件的open-type的实名验证

docs/components/forms/input.md
input.onConfirm()在H5版中无效，其暂时替代方法
=> doc:input.onConfirm

packages/taro-h5/src/api/request/index.js
修复仅对 `POST` 请求进行 `JSON.stringify`，导致当发送 `PUT` 、`DELETE` 等请求时，而 `body` 为对象却没有进行 `JSON.stringify`，`body `类型为 `object`， 无法发送 `body` 的问题（`Fetch` 的 `body` 类型貌似不能为 `object`）。
=> fix(h5): 修复 PUT 、DELETE 等请求 body 为对象时无法发送 body 的问题

packages/taro-webpack-runner/src/index.ts
https://nervjs.github.io/taro/docs/config-detail.html#h5webpackchain
webpackChain 应有两个参数, 但源码里只传了一个
=> fix(webpackChain): 漏传第二个参数webpack

packages/taro-cli/src/util/index.js, packages/taro-cli/src/util/resolve_npm_files.js, packages/taro-cli/src/weapp.js
fix #809 
yarn workspace 目录结构下，子项目的公共依赖被提升到了 workspace 的 node_modules 里。导致之前计算目标路径的方法出错，复制到了 workspace 目录下。
加了个 findRoot 工具函数，用于找到最接近工作目录的 package.json 所在路径。
=> fix #809 支持在 yarn workspace 目录结构下进行 build

packages/taro/types/index.d.ts
packages/taro/types/index.d.ts
1. workers 代码放置目录声明重复，导致编译期报错警告。
2. useStore h5是否开启缓存，兼容性考虑，因改为非必输入属性。
=> 修正声明文件2处问题

packages/taro-weapp/src/native-api.js
revert f5ad3e5 (fix 619)
fix #619 
fix #919
- packages/taro-weapp
之前解决 issue #619  的提交引发了 #919   
微信小程序中
```javascript
let successResult
const task = wx.connectSocket({success(result){
successResult = result
}})
task !== successResult
```
且 task instanceof SocketTask(如果有) 为true，successResult 是常规的object。
commit f5ad3e5 中将 resolve(task) 这个情况去掉了，造成没有情况返回 socketTask。
出现了 #919 （这个现象，让我误以为是api变更导致，实际上小程序api的变更，只是增加了api，并没有改变connectSocket的同步返回值，回调返回值）
会导致 [websocket测试案例](https://github.com/NervJS/taro/blob/7bbd49ca3bd2f7c7738c32c5a1f37cefc74e7fc6/packages/taro-rn/src/__tests__/websocket.test.js#L133) (如果有小程序版的)失败
此PR改善对 #619 的fix方式，通过一个microtask消除task为null的bug，顺便将success返回的结果并入socketTask上，以与其他promise化的api保证一致的预期结果。
- 上述最后的一步处理待商榷，有那么点儿不一样
=> 修复 await Taro.connectSocket 获取不到 SocketTask 的错误

packages/taro/types/index.d.ts
微信2.4.0开始小程序之间跳转需要在全局配置中增加navigateToMiniProgramAppIdList字段
=> taro类型文件中加入navigateToMiniProgramAppIdList字段支持

packages/taro-redux/src/connect/connect.js
增加了对微信端 connect 第二个参数 mapDispatchToProps 传递为对象的支持。#298
以前必须传递为函数：
```js
export default connect(mapStateToProps, (dispatch) => ({
add: () => dispatch(add())
}))(Component)
```
现在可以传递对象：
```js
export default connect(mapStateToProps, {
add,
minus,
})(Component)
```
当前未发布到新版本时，可以用以下的方法做兼容：
```js
// utils/index.js
import { bindActionCreators } from 'redux';
export function withDispatch(actionCreators) {
if (typeof actionCreators === 'object') {
return function mapDisptchToProps(dispatch) {
return bindActionCreators(actionCreators, dispatch);
};
}
return actionCreators;
}
// pages/index/index.js
import { withDispatch } from '../../utils';
// ...
export default connect(mapStateToProps, withDispatch({
minus,
plus
}))(Component);
```
上面的方法有点烦琐，其实可以直接包装一下 connect 返回一个新的 connect 函数，但是测试发现 connect …
=> feat(redux): 微信端 connect 的 mapDispatchToProps 参数支持传递对象 #298

packages/taro-h5/src/api/request/index.js
contentType 包含其他参数时导致不能正确转换data
=> 兼容ContentType 包含其他参数

packages/taro-cli/templates/default/config/index
Missing a comma before 'url' in taro/packages/taro-cli/templates/default/config/index.js line 51
=> fix a bug where miss a comma

packages/taro-alipay/src/native-api.js, packages/taro-h5/types/index.d.ts, packages/taro-swan/src/native-api.js, packages/taro-weapp/src/native-api.js, packages/taro/types/index.d.ts
修复两个问题
1. index.d.ts 中, uploadTask 缺乏progress()/abort()方法
2. wx.uploadFile() 返回值可能是 undefined, 需要判断空调用
=> fix(uploadFile): fix Taro.uploadFile()

packages/taro-components/types/Input.d.ts, packages/taro-components/types/Picker.d.ts, packages/taro-components/types/Slider.d.ts, packages/taro-components/types/Switch.d.ts, packages/taro-components/types/Textarea.d.ts, packages/taro-components/types/common.d.ts
=> fix: fix form item typing for `name` property

packages/taro-cli/templates/default/config/index, packages/taro-cli/templates/mobx/config/index, packages/taro-cli/templates/redux/config/index
当前在property中使用decorator存在无效的问题，主要原因是babel配置顺序导致，详情参见：
https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy#note-order-of-plugins-matters
=> fix(templates)：修复decorator无法作用到property的问题

packages/taro-h5/src/api/interactive/actionSheet.js, packages/taro-h5/src/api/utils.js
修改前, 只设置了 style.transform, 未设置 style.webkitTransform, 在旧浏览器中会出现菜单不能弹出的bug.
=> fix(showActionSheet): fix未设置webkitTransform导致菜单不能弹出的bug

packages/eslint-config-taro/rules/jsx.js
This eslint rule from `eslint-plugin-react`, `react/jsx-space-before-closing` is deprecated。
When I run `taro init myApp & cd myApp` then run `eslint src`, terminal will tips `The react/jsx-space-before-closing rule is deprecated. Please use the react/jsx-tag-spacing rule with the "beforeSelfClosing" option instead.`
=> Replace deprecated rule jsx-space-before-closing

packages/taro-cli/src/h5.js, packages/taro-cli/src/rn/transformJS.js, packages/taro-cli/src/util/index.js, packages/taro-cli/src/weapp.js
支持在项目配置中加入 pathAlias 选项，实现import的自定义前缀别名
在项目 config/index.js 中加入类似下面配置
```
pathAlias: {
'@': '',
'@base': 'base',
},
```
可在页面中以如下方式引入文件
`import UserService from '@/services/UserService'`
=> feat: 项目配置中支持添加 pathAlias 配置 import 路径自定义别名

packages/eslint-plugin-taro/__tests__/this-props-function.js, packages/eslint-plugin-taro/rules/this-props-function.js
例如：
```javascript
const mapDispatchToProps = dispatch =>({
dispatchA(){
dispatch(actions.Foo())
},
dispatchB(){}
})
```
=> 允许从 this.props 而来的函数名以`dispatch` 开头

packages/taro-components/types/Checkbox.d.ts, packages/taro-components/types/Input.d.ts, packages/taro-components/types/Picker.d.ts, packages/taro-components/types/Radio.d.ts
表单组件的没有name属性的继承了FormItemProps，已重复的去掉了name。
Picker选择地区组件CustomItem改为可为空
=> 表单组件props属性完善 Picker组件属性完善

packages/taro-cli/src/weapp.js
让 css modules 只对 xxx.module.[css|scss|less|styl] 样式文件做处理
并添加命名模式选项开关：
```
cssModules: {
enable: true,
config: {
generateScopedName: '[name]__[local]___[hash:base64:5]',
namingPattern: 'module' // 默认为 'global' ,如需遵循 '.module' 命名规范,则设为 'module'
}
}
```
=> css modules 处理样式文件规则与 `create-react-app` 保持一致

docs/event.md
「以下两种方式都可以向事件处理程序传递参数」似乎抄自React文档，
但Taro其实只支持 `bind` 这一种方式，
下面的代码示例也只有一种方式。
所以我把这句话去掉了，以免造成困惑。
=> 更新文档（事件处理）

packages/taro-cli/bin/taro-init, packages/taro-cli/src/project.js
解决taro init中的其他参数无法在命令行中指定的问题。
但因为参数typescript需要是boolean值，为了兼容不指定typescript参数时，在inquirer中再进行询问的情况，做了不优雅的兼容处理（如有更好的写法欢迎提出）。
=> fix: 解决taro init从命令行输入参数无效的问题

packages/taro-swan/src/create-component.js
There are two unnecessary `call`.
=> chore(taro-swan): remove unnecessary `call`

packages/taro-webpack-runner/src/util/chain.ts
=> feat: add esnextModules regex support the modules of cnpm installed

docs/event.md
In "event.md", the sample component extend from React.Component. It should be extend from Taro.Component.
在“event.md”中，示例中的组件继承于React.Component，它应该继承于Taro.Component。
=> fix(docs): Component extend from React.Component

packages/taro-components/types/common.d.ts
BaseEvent 类型优化，方便BaseEvent中的detail字段类型编写
建议使用CommonEvent代替BaseEvent，当全部BaseEvent被替换成CommonEvent后，重置BaseEventOrig为BaseEvent
BaseEventFunction同理
=> refactor(types): BaseEvent 类型优化

packages/babel-plugin-transform-jsx-to-stylesheet/src/__tests__/index.js, packages/babel-plugin-transform-jsx-to-stylesheet/src/index.js
出错示例：
**index-app.js**（文件名带连字符）中引入了 xxx.css，最终会编译成：
`import index-appStyleSheet from "./index-app_styles"`
**index-appStyleSheet** 带了连字符，不是个合法的变量命名，因而报错
ps: 
如果要完善点的话，应该对最终的 styleSheetIdentifierValue 做 js 变量名的校验，不知项目中是否已有相关的工具函数，有的话可以拿来用下，否则就处理连字符应该也就足够了（文件名中有连字符还是很常见的）
=> fix: transform scss file with hyphen(-) in the filename

packages/taro-mobx-h5/package.json
@tarojs/mobx-h5@1.2.7 缺少文件:  Provider.js
=> fix(mobx): 1.2.7 mobx-h5 丢失文件

packages/taro-router-rn/src/TaroProvider.js
taro/types/index.d.ts 中对 navigateBack 的定义是：
function navigateBack(OBJECT?: navigateBack.Param): Promise<any>
参数是可选的，其他两端不传参时不报错，RN 会报错，统一一下
=> fix(taro-router-rn): navigateBack 增加默认参数

packages/taro-components/src/components/rich-text/index.js
主要修改了两个地方：
1. RichText这个组件，nodes的type如果不是text的话，children这个属性在微信小程序的doc里是可选的，所以item.children就可能为undefined，所以加个默认值空数组。
2. 对于有些node类型，例如image，它的attrs不仅仅限于class和style，还有src、width、height等。由于情况比较多，所以这块建议直接把这些属性拿过来，统统赋给props
=> fix(taro-components): fix richText component

packages/taro-components/src/components/input/index.scss
小程序的input默认继承祖先元素的text-align
而浏览器的input默认是text-align: start;
=> input { text-align: inherit }

packages/taro-cli/src/util/resolve_npm_files.js, packages/taro-cli/src/weapp.js
=> fix(taro-cli):修复初始化 plugins 配置时操作原对象并未能正确去重(#2160) 

packages/taro-cli/src/weapp.js, packages/taro-plugin-babel/index.js
1. 修复 taro-plugin-babel  中调用 babel.transform 时未传递 config.filename 导致插件中无法访问 state.file.opts.filename问题
2. 修复 taro-cli/weapp.js 中调用 plugin-babel 时 file 参数始终传递 entryFilePath 而非 sourceFilePath ，导致插件内无法正确拿到文件路径问题
=> fix(taro-cli+taro-plugin-babel):修复babel插件内无法访问编译文件路径问题(#2168) 

packages/taro-cli/src/build.js
修改taro-cli编译开始时，需要清理的dist路径，要与工程里的config配置的输出路径保持一致，不能写死成dist
=> fix(taro-cli): fix taro cli default clean path

docs/before-dev-remind.md, packages/taro-router-rn/src/RefreshProvider.js
现在页面默认是用 ScrollView 包裹，但没加 contentContainerStyle，导致页面根节点无法继承页面高度
表现为在页面根节点上设置 flex: 1、height: 100% 时都无法实现全屏
另外文档中关于“页面怎样设置高度 100%”这块说反了，应该是设置为 disableScroll: true + height: 100% 才行，实测 RN 上有效果，但会导致微信小程序上无法滚动，加 overflow: scroll 也不行，只能最外层用 ScrollView
=> fix(taro-router-rn): 页面根节点 height: 100% 无效

packages/taro-cli/src/util/index.js
=> fix(taro-cli): 符号链接+Alias导致源代码文件被意外修改

packages/taro-cli/src/build.js
**问题描述**
configDir引入前置导致config/index获取process.env.NODE_ENV为undefined.模板为例子,配置只输出production环境
**复现步骤**
npm run build:weapp
npm run dev:weapp
配置只输出production配置
```js
// 这里可以贴代码
```
**期望行为**
对应命令钩子输出对应构建配置
**报错信息**
[这里请贴上你的**完整**报错截图或文字]
**系统信息**
Taro CLI 1.2.13 environment info:
System:
OS: macOS 10.14
Shell: 5.3 - /bin/zsh
Binaries:
Node: 11.1.0 - /usr/local/bin/node
Yarn: 1.12.3 - /usr/local/bin/yarn
npm: 6.4.1 - /usr/local/bin/npm
**补充信息**
[可选]
下面有修改代码
=> taro-cli/src/build.js的configDir引入前置导致config/index获取process.env.NODE_ENV为undefined

docs/taroize.md
=> fix: 修复文档错误

packages/taro-components/types/CoverView.d.ts
见：https://developers.weixin.qq.com/miniprogram/dev/component/cover-view.html#cover-image
=> feat(taro-components): 完善 CoverView 的类型定义

packages/taro/types/index.d.ts
=> feat(taro-weapp): 更新TabBar类型声明

packages/taro-weapp/src/native-api.js
基础库版本低于 2.2.3 时会报错，因为 wx.cloud 是 undefined，应该做下兼容处理
=> fix(weapp): 修复云开发 api 初始化

packages/taro-cli/src/util/index.js
目前 taro 的判断方式是根据文件来的，如 test.js、test.weapp.js，这对多端文件来说很 ok
但是在组件的组织上，这种方式不是很友好
```
comp
index.alipay.js
index.js
index.weapp.js
```
如果组件中包含子组件等，目录就相当混乱了
```
comp
index.alipay.js
index.js
index.weapp.js
item.alipay.js
item.js
item.weapp.js
```
希望能达到如下效果：
```
comp
index.js
item.js
comp.alipay
index.js
item.js
comp.weapp
index.js
item.js
```
=> feat(cli): 跨平台开发方式支持目录判断

packages/taro/types/index.d.ts
为 class Componen 添加了 $preload 函数类型定义
虽然 $preload 函数源码没有 `$preload(key: object): void;` 的重载
https://github.com/NervJS/taro/blob/2222051cca68fd2afecbfa045eb208703fd40b3f/packages/taro-weapp/src/component.js#L86
提交里还包含两行 Lint 删除的空格
=> fix(index.d.ts): 添加缺失的 $preload 类型定义

packages/taro-cli/src/build.js, packages/taro-cli/src/convertor.js, packages/taro-cli/src/util/index.js, packages/taro-cli/templates/default/index.js, packages/taro-cli/templates/mobx/index.js, packages/taro-cli/templates/redux/index.js, packages/taro-cli/templates/wxcloud/index.js
1. taro-cli/src/build.js 中使用 `fs.mkdirSync(outputPath)` 可能有问题，如果 outputRoot 是包含子目录的，如 `dist/weapp`，编译会报错
2. fs. mkdirpSync、fs.ensureDirSync 内部实现都是 fs.mkdirsSync，既然项目中多数都用 fs.ensureDirSync 了，那没必要单独某个地方用 fs. mkdirpSync
3. 既然第 2 点可行，那其他地方也顺便统一都改掉哈
=> refactor(cli): 创建文件夹统一使用 fs.ensureDirSync

packages/taro-components/src/components/tabbar/index.js
```
//    例子.
tabBar: {
............................
............................
"list": [
{
"pagePath": "pages/xxxx/index",   //问题点
"text": "Xx",
....
},
............................
............................
}
```
当 `pagePath` 为 **pages/xxxx/index** 
小程序环境：正常.
H5 环境：     被隐藏.
当 `pagePath` 为 **/pages/xxxx/index** // 注意：多了个 “/” 字符
小程序环境：报错 （tabBar[0].pagePath should not begin with '/'）
H5环境：正常
处理：
统一格式：**pages/xxxx/index** 
H5拿到 PagePath 后在其头部增加 '/'
=> flx(taro-components): H5 & Weapp统一pagePath.

packages/taro-cli/templates/mobx/globaldts
typescript环境下global.d.ts使用import了关键字，导致其变成一个普通模块，|
无法作为全局环境声明。修改导出JSX namespace 方式
Fixes #2437
=> fix (taro-cli): 修改了templates/mobx/globaldts 删除import React 行

CHANGELOG.md, packages/taro-cli/src/weapp.js, packages/taro-webpack-runner/src/util/chain.ts, packages/taro-webpack-runner/src/util/types.ts
generateScopedName 设为函数在某些需要高度自定义的场景下是极有用的，比如 UI 组件库。
顺便注释了暂不用的 checkCliAndFrameworkVersion 方法，因为 pre-commit 里的 eslint 不通过。
=> feat(css modules): generateScopedName 支持设为函数

packages/taro/src/interceptor/chain.js, packages/taro/src/interceptor/interceptors.js
1. timeoutInterceptor 在请求异常时没有清除计时器
2. interceptor 中建议加一个默认的 catch 处理，否则加了 interceptor 又没有处理 catch，Taro.request 将无法触发 catch （如果觉得加默认处理不合适，那得在文档里注明下 interceptor 中要对 catch 处理哈）
=> fix(taro): interceptors 没有正确处理异常

packages/taro-webpack-runner/src/config/devServer.conf.ts
=> fix:默认开启node_modules监控

packages/taroize/src/script.ts
小程序代码：
```js
Page({
data: {},
onLoad() {
console.log(1)
}
}）
```
转换后的结果（注意生命周期body没了）：
```js
class _C extends Taro.Component {
state = {}
componentWillMount
}
```
=> fix(taroize): 小程序转换Taro生命周期丢失

packages/taro-transformer-wx/src/render.ts
=> fix: only warn index key

docs/before-dev-remind.md
https://nervjs.github.io/taro/docs/before-dev-remind.html 文档该页
> 其他注意事项
> 运行时 报缺少包，需要要在 .rn_temp 目录里面安装。
> 文字要包在 Text 组件里面，否则不显示。
> display:fixed React Native 不支持
> Animation 和 transform React Native 动画不支持
> React Native 与 H5/小程序 的 Flex 布局相关属性的默认值有差异
修改第三条中 `display:fixed` 为 `position:fixed`
=> fix doc error as issue #2543

packages/taro/types/index.d.ts
实现高阶函数时，使用装饰器模式调用， 装饰器的参数和返回值都是组件类类型。
=> feat(typescript): 类型声明文件增加类类型：ComponentClass

packages/taro-plugin-sass/index.js, packages/taro-plugin-sass/package.json
In order to be able to inject scss variables globally
import scss-bundle to get bundledContent
```
plugin: {
sass: {
resource:  'path/to/global.scss',
// OR 
// resource:  ['path/to/global.theme.scss', 'path/to/global.mixin.scss',]
projectDirectory: '/path/to/project/directory'
}
}
```
resource: The absolute path of the global scss file that needs to be injected(support array).
projectDirectory: Absolute project location, where node_modules are located. 
Take effect when resource  & projectDirectory is set.
Reference #425
=> feat(scss): support global scss inject

packages/taro-h5/__test__/createAnimation-test.js, packages/taro-h5/src/api/createAnimation/index.js
fix #2749
- 修复`createAnimation`对单位判定, 根据`wx.createAnimation`参数, 如果传入为`number`则默认带上`px`, 否则延用参数值
- 添加相应测试
=> fix(h5): 修复createAnimation单位判定/添加测试

packages/taro-components/src/components/picker/index.js
目前微信小程序组件是 mode 默认为 selector，如果未传 mode="selector"，那么 onChange 时会错误。
因为：
`const eventObj = getEventObj(e, 'change', {
value: this.index.length > 1 && this.props.mode !== 'selector' ? this.index : this.index[0]
})
`
=> fix(component): 修复 Picker 组件未设置默认 mode 属性的 bug

packages/taro-rn/src/api/interface/toast.js
showLoading 后 直接调用 showToast 会导致 loadingView 泄漏，没有回收
=> fix(rn): toast 或 loading 不对称情况下防止泄漏

packages/taro/types/index.d.ts
云开发 数据库【 类型“void”上不存在属性“then”】
=> db.collection(xx).count().then,db.collection(xx).get().then

packages/taro/types/index.d.ts
修复解决 使用  微信云函数方法:  
Taro.cloud.callFunction().then()
Taro.cloud.uploadFile().then()
Taro.cloud.downloadFile().then()
Taro.cloud.getTempFileURL().then()
Taro.cloud.deleteFile().then()
tslint 提示 找不到 then属性的问题
=> fix tslint error  类型“void | Promise”上不存在属性“then”

packages/taro/types/index.d.ts
getUserInfo接口的ts文件中之前没有success, fail, complete这三个回调，导致写代码的时候编辑器报错，功能不受影响。已经将回调加上
=> 给Taro.getUserInfo接口添加回调函数

packages/taro/types/index.d.ts
1. 补充了缺失的 PageConfig 和 App WindowConfig 配置项
- backgroundColorTop
- backgroundColorBottom
- disableSwipeBack
- pageOrientation
2. 修正了仅在页面或者全局可用的配置项在 PageConfig 里的问题，如 disableScroll 出现在页面的 window 属性中
<details>
<summary>之前</summary>
disableScroll 属性可以出现在页面的 window 属性中并且不会报错，
在注释中提示开发者并不能阻止犯错
// App 全局配置
</details>
<details>
<summary>之后</summary>
现在如果在不正确的地方写窗口表现配置会有错误提示:
```text
Type '{ navigationBarBackgroundColor: string; navigationBarTextStyle: "white"; navigationBarTitleText: string; navigationStyle: "default"; backgroundColor: string; backgroundTextStyle: "light"; ... 6 more ...; disableSwipeBack: boolean; }' is not assignable to type 'WindowConfig'.
Object literal may only specify known properties, and 'disableScroll' does not exist in type 'WindowConfig'.
```
// App 全局配置
// 页面配置
// …
=> fix(taro): 补充缺失的窗口表现配置项，修正仅在页面可用的项目出现在全局的问题

docs/apis/storage/removeStorage.md
=> 修复Taro.removeStorage文档中的一个字段错误

packages/taro-components/types/common.d.ts
修复在ts模式下，`currentTarget.dataset.xxx ` 提示不存在属性`xxx` 问题。 #3151
=> fix(types): fix dataset type in Event Target

docs/components/forms/checkbox.md
文档中`CheckboxGroup`组件对应的微信端链接指向的是`button`。
=> docs: 修复CheckboxGroup微信端链接错误

packages/taro-rn/src/api/system/index.js
✅ Closes: #3036
RN端能够准确获取到所有苹果机型的状态栏高度，和小程序保持一致。
=> fix: 🐛 修复RN下获取statusBarHeight不准确的问题

packages/taro/types/index.d.ts
微信官方今日发布[公告声明](https://developers.weixin.qq.com/community/develop/doc/000868190489286620a8b27f156c01)：
> 在即将发布的7.0.5客户端版本中，页面配置中的 disableSwipeBack 属性将不再生效
=> fix(taro): disableSwipeBack 将在 7.0.5 版本失效

packages/taro-components/src/components/view/index.js
修复之前给H5端View组件添加onLongPress支持导致无法响应onTouchMove事件的bug
=> fix(h5): 修复H5 View 组件无法响应onTouchMove事件的bug

packages/taro-plugin-stylus/index.js, packages/taro-plugin-stylus/tests/fixtures/base/style.styl, packages/taro-plugin-stylus/tests/fixtures/test.styl, packages/taro-plugin-stylus/tests/index.test.js
对 taro-plugin-stylus 做了修改，合并全局配置中的目录引用，在stylus样式引用其他文件时，可以在不用alias或者一级级的向上引用的情况下直接使用，但是需要避免文件重名。
使用方法：
例如，有文件如下
```
- src
- asset
base.styl
- pages
- index
style.styl
```
在配置文件中设置
```
config/index.js
{
plugins:  {
stylus: {
paths: [ path.join(__dirname, '../src/asset')]
}
}
}
```
样式文件pages/index/style.styl中可直接使用
```
❌ 不需要再一级级的引入
@import "../../../asset/base.styl"
✅ 直接使用
@import "base.styl"
```
=> 优化 taro-plugin-stylus 配置代码

packages/taro-router-rn/src/RefreshProvider.js
fix: 🐛 修复RN中，页面开启enablePullDownRefresh后，页面下拉刷新失效
=> fix: 🐛 修复RN中，页面开启enablePullDownRefresh后，页面下拉刷新失效

packages/taro/types/index.d.ts
微信文档（又）改版之后，很多地址都 404 了，粗略扫了一遍把能修改的改了。
加了 `getWeRunData` `getShareInfo` `getUserInfo` 三个 API 的 `cloudID` 返回值
yarn test 成功，yarn build 失败，tsc 报 taro-cli convertor/index.ts 错误，我怀疑根 TypeScript 版本有关（不过应该根这个 PR 的修改没关系）
```shell
src/convertor/index.ts(476,45): error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string'.
src/convertor/index.ts(541,11): error TS2322: Type 'Set<unknown>' is not assignable to type 'Set<IComponent>'.
Type 'unknown' is not assignable to type 'IComponent'.
src/convertor/index.ts(551,33): error TS2345: Argument of type 'Set<unknown>' is not assignable to parameter of type 'Set<IComponent>'.
src/convertor/index.ts(619,11): …
```
=> fix(taro): 修复微信文档链接，添加几个 API 返回值的 cloudID

packages/taro-alipay/src/native-api.js, packages/taro-qq/src/native-api.js, packages/taro-tt/src/native-api.js, packages/taro-weapp/src/native-api.js
weapp中不带参数切换页面，`this.$router.params`中会多出一个与`path`同名的字段。详见(#3266 )
发现是这里=》[code](https://github.com/NervJS/taro/blob/master/packages/taro-weapp/src/native-api.js#L126)，取query的时候，如果没有query就将path传进去了，导致`queryToJson`这个函数返回了错误的结果。
=> fix(weapp): 修复urlQuery为空时，生成错误的params，close #3266

packages/taroize/src/template.ts
**问题描述**
微信小程序转Taro后再转RN直接运行会报TaroParseaTmpl.js文件找不到错误：
[Taro官方给出了解决方案](https://nervjs.github.io/taro/docs/taroize.html#%E8%BD%AC%E6%8D%A2-wxparse-%E6%8A%A5%E9%94%99%E4%B8%8D%E5%AD%98%E5%9C%A8%E6%96%87%E4%BB%B6)
但是，问题并没有解决，经分析发现，是因为`taro convert`命令执行完成后会在`taroConvert/src/imports/`目录下生成“TaroParse * Tmpl.js”文件，这些文件是基于微信小程序`wxParse/wxParse.xml`文件转换而来。在windows系统下，因为windows不区分文件名字母大小写，TaroParseATmpl.js文件会与TaroParseaTmpl.js文件命名冲突，导致TaroParseaTmpl.js文件生成不了，代码运行时就会报TaroParseaTmpl.js文件找不到。
>  源码中打console输出tmpl文件名生成情况：
> `taro convert`指令执行后，imports目录下的文件生成情况：
分析taro-cli源码发现，tmpl文件的命名规则是从`a, b, c, d, e, f, g, h, i, j, z`的字符集中取值作为命名关键字以区分不同的tmpl文件。调整下字符集，去掉`a`，加个`k`就可以规避了。
**复现步骤**
1.微信小程序项目中`wxParse/wxParse.xml`文件内容中循环模版只留wxParse1和wxParse2，1调2，2调1，其他wxParse2-10都去掉。
````xml
<template …
```
=> windows环境微信小程序转Taro后再转RN运行会报TaroParseaTmpl.js文件找不到错误

packages/taro-rn/src/index.ts
RN  未导出相关接口导致在使用 hooks 时抛出方法未定义的错误信息
=> fix(rn): 导出 hooks 相关接口，以解决 RN 端接口未定义问题

packages/taro-cli/bin/taro-doctor, packages/taro-cli/src/doctor/abilityXMLValidator.ts, packages/taro-cli/src/doctor/index.ts
华为的快应用中增加了一个用于定义原子服务能力定义的文件ability.xml，本次修改在doctor模块中增加了对ability.xml的规范检查。
=> 增加对华为原子服务定义文件的规范检查

packages/taroize/src/utils.ts
```js
class A extends Component {
render() {
const { name: name } = this.state // <= here
return <div>{name}</div>
}
}
```
```js
class A extends Component {
render() {
const { name } = this.state // <= here
return <div>{name}</div>
}
}
```
=> chore: Use shorthand property name in render method

packages/taro/src/memo.js
这是一个简单的解决方法，但这和react的实现仍然有一些差距。
对state进行浅比较无法精准的确定state是否发生了变化。标准应该是只要state发生了变化，就一定要重新渲染。
=> fix: 在memo中增加对state的浅判断

packages/taro-cli/src/mini/compileStyle.ts
修复小程序端非生产模式(dev)下，配置了 csso 但是不能应用的问题。
理论上这个 PR 可以应用到所有小程序端
测试步骤
测试用例 `app.scss` 如下：
```scss
/* I'm a comment 1. */
/*! I'm a comment 2. */
/** I'm a comment 3. */
// I'm a comment 4.
.test-class {
/* I'm a comment 5. */
/*! I'm a comment 6. */
/** I'm a comment 7. */
// I'm a comment 8.
color: red;
}
```
dev 模式使用命令 `~/Projects/Test/taro/packages/taro-cli/bin/taro build --type weapp --watch`
prod 模式使用命令 `~/Projects/Test/taro/packages/taro-cli/bin/taro build --type weapp`
1. taro init 一个使用 default 模版的项目
2. `config/index.js` 使用默认配置保持不变
3. `config/dev.js` 为默认，如下：
```js
module.exports = {
env: {
NODE_ENV: '"development"'
},
defineConstants: {},
weapp: {},
h5: {}
};
```
3.1 …
=> fix(taro-cli): 修复小程序端非生产模式下不应用 csso 配置问题 close #3622

packages/taro-router/src/router/router.tsx
在一些生命周期中获取getCurrentPages函数时（如页面跳转时的上一页面销毁/隐藏事件）会有只有长度没有内容的Page对象存在
```
...
render () {
const router = this
const currentLocation = Taro._$router
router.currentPages.length = this.state.routeStack.length//创建组件前先同步下长度？
return (
<div
className="taro_router"
style={"min-height: 100%"}>
...
```
从源码中看到会在render时同步一下长度，但当前this.state.routeStack已经包含下一个页面，所以导致数据不一致
=> fix(h5): 解决getCurrentPages有时候只能获取长度但没有内容的问题

packages/taro-cli/src/config/manifest.default.json
修复 CI 编译 `src/config/manifest.default.json(20,5): error TS1005: ',' expected.` 错误。
=> fix(taro-cli): 添加 json 文件缺失的逗号

docs/apis/network/request/request.md, packages/taro/types/index.d.ts
2ada5a2 为 Taro.request 添加了 abort 方法(#3654)，更新 Taro.request 的类型定义，完善了注释和示例代码。
暂不知道其他端是否支持 abort
=> fix(taro): 为 Taro.request 类型定义添加 abort 方法，完善注释 #3654

packages/taro-router-rn/src/getWrappedScreen.js
修复RN端触发不了下拉刷新事件，在getWrappedScreen文件中，首次render获取不到实例，后续也不会再次render，所以screenInstance一直是{}，所以改为传递包裹函数，在具体使用时，再去拿实例。
=> fix(taro-router-rn): 修复RN端触发不了下拉刷新事件

packages/taro-rn/src/api/interface/toast.js
修复showLoading没有使用title属性，一直都是显示默认的'loading'
=> fix(taro-rn): 修复showLoading没有使用title属性

packages/taro-h5/src/api/image/chooseImage.js
修复 chooseImage 无法两次选择相同图片
- [x ] 所有测试用例已经通过
=> fix(h5): 修复 chooseImage 无法两次选择相同图片 fix #3747

packages/taro-components-rn/src/components/Input/PropsType.tsx, packages/taro-components-rn/src/components/Input/index.tsx
修复Input组件不支持onChange事件，没有保持端一致性。当我在小程序中使用onChange时，不能平滑过渡到RN。
=> fix(taro-components-rn): 修复Input组件不支持onChange事件，没有保持端一致性

packages/taro/types/index.d.ts
`cloud.callFunction` 的 result 返回值，应该是任意的，比如云端可以这么返回：
```js
return [{id: 1}, {id: 2}];`
```
那么，`CallFunctionResult["result"]` 应该包含 `any[]`
=> set result of CallFunctionResult to any

packages/taro-cli/package.json, packages/taro-cli/src/doctor/abilityXMLValidator.ts
补充对华为原子化服务配置文件ability.xml中intent和parameter声明的合法性检查。
=> 校验华为原子化服务配置文件ability.xml中的intent和parameter合法性

packages/taro-router-rn/src/getWrappedScreen.js
让页面组件能自定义navigationOptions，方便RN开发者修改页面导航信息
参考：https://reactnavigation.org/docs/en/header-buttons.html
=> 让页面组件在RN环境能自定义navigationOptions

packages/eslint-plugin-taro/rules/render-props.js
修复render props传入单个JSX元素或箭头函数报错的问题
=> fix(eslint): 修复render props传入单个JSX元素或箭头函数报错的问题

packages/taro-transformer-wx/__tests__/template.spec.ts, packages/taro-transformer-wx/src/render.ts
修复如果模块中以对象表达式的形式，key  非字符的形式，编译后存在 ${key} is not defined.
=> fix: objectExpression property key'type

packages/taro/types/index.d.ts
修复Taro.showModal方法中的title参数必填，微信小程序官方文档提示title参数是可选项
=> fix(taro): showModal中的title参数不是必须

packages/taro/types/index.d.ts
1. 补全FC类型定义，新增类型定义SFC，setPageInfo
~~2. 使用格式化工具对这个文件做了一次格式化~~
=> feat: 补全FC类型定义，新增类型定义SFC，setPageInfo

packages/taro-cli/src/rn.ts
解决编译 RN 时顺序异常导致编译报错
1. 修改 buildTemp 方法，使所有文件编译完后再 resolve
node:  v10.16.0
=> fix(cli): 编译 RN 未编译完导致未找到文件报错 

packages/taro-components/types/Canvas.d.ts
为CanvasProps新增属性定义type, 支持微信小程序使用webgl的额外props
=> feat(taro-components): 为CanvasProps新增属性定义type, 支持微信小程序使用webgl的额外props

packages/taro-components/src/components/scroll-view/index.js
虽然说在官网的文档上说h5支持scrollIntoView，但实际上翻看源码，scroll-view并没有处理’scrollIntoView‘这个字段，这里直接通过querySelector获取相关元素并绑定相关API，实际效果与微信小程序端相同。（当然，这个只在h5生效）
兼容IE8及以上
=> feat(h5): 使scroll-view组件在h5中支持scrollIntoView属性

packages/taro-components/src/components/video/index.js
文档上虽说支持duration属性，但实际上并没有处理相关字段，这里补充了相关代码
**这个 PR 是什么类型?** 
目前 Video 下的 Controls 已知若没有设置 duration ， 会导致无法拖动进度条。核心原因是因为上个版本在 onLoadedMetadata 方法中新加的判断 #3526，导致没有办法算进度。求大佬跟进😎
=> feat(components):使组件接受 duration 属性

packages/taro-components/src/components/pull-down-refresh/index.js, packages/taro-components/src/components/pull-down-refresh/style/index.css
修复h5下onPullToRefresh缺少loading动画
=> fix(h5): 修复h5下onPullToRefresh缺少loading动画

packages/taro-h5/src/api/utils/index.js
Get请求，发现如果传递的参数是多层的，直接会变成object字符串，参考微信小程序原生功能，对多层对象进行json转string操作。
=> fix(h5): request的get请求数据为复杂结构不能正确发送的问题

packages/taro-components/src/components/swiper/index.js
当swiper数据中的swiperItem为动态加载时，且circular设置为true，当滑到最后一个元素时，此时是无法做到衔接滚动的，这个问题在[Swiper的issue](https://github.com/nolimits4web/swiper/issues/2629)中有提到过，这里添加两行代码使其手动重做循环的DOM块。
**这个 PR 是什么类型?** 
这里其实可以优化成:
```
if (
上一个children和本次children不相同
&&
circular
){
重做循环
}
```
可是不知道怎么比较children😂
=> fix(taro-components): 修复circular为true却不会循环播放的问题

packages/taroize/src/wxml.ts
wx:if后面有空格的问题通过设置参数indent_char修复，另外wxs标签不需要进行format操作,否则会报错
unexpected token, expected ;
PS:已经和yuche沟通过方案
错误修复(Bugfix) issue id 
新功能(Feature)
代码重构(Refactor)
文档修改(Docs)
这个 PR 满足以下需求:
提交到 master 分支
所有测试用例已经通过
这个 PR 涉及以下平台:
微信小程序
支付宝小程序
百度小程序
头条小程序
QQ 轻应用
Web 平台（H5）
=> fix wx:if后面有空格的问题，另外wxs标签不需要进行format操作,否则会报错

packages/taroize/src/wxml.ts
统一格式化为一行，否则在解析wxml时会有unterminate line end的错误
错误修复(Bugfix) issue id 
新功能(Feature)
代码重构(Refactor)
文档修改(Docs)
这个 PR 满足以下需求:
提交到 master 分支
所有测试用例已经通过
这个 PR 涉及以下平台:
微信小程序
支付宝小程序
百度小程序
头条小程序
QQ 轻应用
Web 平台（H5）
=> fixmax_char 统一格式化为一行，否则会有unterminate line end的错误

packages/taro-cli/src/convertor/helper.ts, packages/taro-cli/src/convertor/index.ts, packages/taroize/src/index.ts, packages/taroize/src/template.ts, packages/taroize/src/utils.ts
taroize增加绝对路径的支持
在js中支持以下写法：
require('a.js')  require('a/b.js')  require('/a/b/c.js')
在wxml中支持以下写法：
import src="/a/b/c.wxml"
错误修复(Bugfix)
新功能(Feature)
代码重构(Refactor)
文档修改(Docs)
这个 PR 满足以下需求:
提交到 master 分支
所有测试用例已经通过
这个 PR 涉及以下平台:
微信小程序
支付宝小程序
百度小程序
头条小程序
QQ 轻应用
Web 平台（H5）
=> Fix4126 2242 微信小程序转换支持绝对路径和非常规路径

packages/taro-transformer-wx/src/create-html-element.ts
#4377 
在解析jsx时遇到return null会返回一个view对象，而快应用只支持div
错误修复(Bugfix) issue id #4377
新功能(Feature)
代码重构(Refactor)
文档修改(Docs)
这个 PR 满足以下需求:
提交到 master 分支
所有测试用例已经通过
这个 PR 涉及以下平台:
微信小程序
支付宝小程序
百度小程序
头条小程序
QQ 轻应用
Web 平台（H5）
=> 在解析jsx时遇到return null会返回一个view对象，而快应用只支持div

packages/taro-router-rn/src/getWrappedScreen.js
=> 修复RN环境下，子页面的navigationOptions无法覆盖默认headerTitle的问题

packages/taro-router-rn/src/initRouter.js
参考微信小程序中的规则，如果配置了tabBar，那么在app.json的pages中配置的第一个页面应该是默认打开的tab。参考链接：
https://developers.weixin.qq.com/community/develop/doc/fe350f3043e47e58fb7abac7c668ef8b
https://reactnavigation.org/docs/en/bottom-tab-navigator.html#bottomtabnavigatorconfig
=> 在RN中的tabbar中，app.js中配置的第一个page应是默认打开的tab

packages/taro/types/index.d.ts
QQ小程序的分享功能支持传递showShareItems设置支持的分享类型，这个PR给showShareMessage的参数补全了这一属性
=> fix: 添加QQ小程序分享功能缺失的参数属性showShareItems

packages/taro-alipay/src/component.js, packages/taro-quickapp/src/component.js, packages/taro-quickapp/src/lifecycle.js, packages/taro-swan/src/component.js, packages/taro-tt/src/component.js
支付宝、百度、快应用、字节跳动中调用 forceUpdate 时，不应执行 shouldComponentUpdate
=> fix(taro): 支付宝、百度、快应用、字节跳动中调用 forceUpdate 时，不应执行 shouldComponentUpdate

packages/taro-mobx-common/src/index.js, packages/taro-mobx-common/src/utils.js, packages/taro-mobx-h5/src/index.js, packages/taro-mobx-h5/src/observer.js, packages/taro-mobx-rn/src/index.js, packages/taro-mobx-rn/src/observer.js, packages/taro-mobx/src/index.js, packages/taro-mobx/src/inject.js, packages/taro-mobx/src/observer.js, packages/taro-mobx/types/index.d.ts
修复使用 Mobx 的情况下，生命周期 getDerivedStateFromProps 不被触发的问题
=> fix(mobx): 生命周期 getDerivedStateFromProps 不被触发问题修复

packages/taro-cli/package.json, packages/taro-cli/src/mini/page.ts, packages/taro-cli/src/quickapp/template-rewriter.ts, packages/taro-cli/src/quickapp/template/constant.ts, packages/taro-cli/src/quickapp/template/node.ts, packages/taro-cli/src/quickapp/template/parser.ts, packages/taro-cli/src/quickapp/template/serialize.ts, packages/taro-cli/src/quickapp/template/tag/index.ts, packages/taro-cli/src/quickapp/template/tag/span/index.ts, packages/taro-cli/src/quickapp/template/tag/taro-camera/index.ts, packages/taro-cli/src/quickapp/template/tag/taro-canvas/index.ts, packages/taro-cli/src/quickapp/template/tag/taro-image/index.ts, packages/taro-cli/src/quickapp/template/tag/taro-input/index.ts, packages/taro-cli/src/quickapp/template/tag/taro-label/index.ts, packages/taro-cli/src/quickapp/template/tag/taro-map/index.ts, packages/taro-cli/src/quickapp/template/tag/taro-picker/index.ts, packages/taro-cli/src/quickapp/template/tag/taro-textarea/index.ts, packages/taro-cli/src/quickapp/template/tag/taro-video/index.ts, packages/taro-cli/src/quickapp/template/tag/text/index.ts, packages/taro-cli/src/quickapp/template/utils.ts
快应用支持30+组件，不同组件对子组件支持存在差异，针对这些差异点进行了父子组件转换规则定制，可减少快应用预览错误点
组件转换包含以下两类：
1、不支持子组件：label、camera、video等组件不支持子组件，若代码中包含子组件，则直接注释
2、只支持特定子组件：text组件只支持a和span子组件，若代码中包含其它子组件，则转换成span
技术选型：
使用sax解析xml代码，依据快应用规范遍历替换或注释子组件，最后转换为字符串
Eg: Taro组件写法
<Label className="label">
<Checkbox hidden="true" value={item.name} />
</Label>
<Text class="gs-text">
<Text>
公司简介
<Text>
技术服务
<Text>快点计划</Text>
</Text>
</Text>
<Text>售后服务</Text>
</Text>
转换为快应用组件后：
<taro-label class="label">
</taro-label>
<text class="gs-text">
<span>
公司简介
<span>
技术服务
<span>快计划</span>
</span>
</span>
<span>售后服务</span>
</text>
技术参考：
1、https://github.com/isaacs/sax-js
2、https://github.com/dcloudio/uni-migration
错误修复(Bugfix) issue id
X新功能(Feature)
代码重构(Refactor)
文档修改(Docs) …
=> 增加快应用子组件定制规则，减少快应用端的预览错误

packages/taro-components/src/components/video/controls.js
修复视频控件没有获取到getProgressBallRef 实例，而导致使用```this.progressBallRef.style.left = ${percentage * 100}%``` 报错
- [x ] Commit 信息遵循 [Angular Style Commit Message Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)
- [x ] 所有测试用例已经通过
- [x ] 代码遵循相关包中的 .eslintrc, .tslintrc, .stylelintrc 所规定的规范
=> fix(video) this.progressBallRef is undefined

packages/taro-webpack-runner/package.json, packages/taro-webpack-runner/src/index.ts, packages/taro-webpack-runner/src/util/chain.ts, packages/taro-webpack-runner/src/util/types.ts
=> fix: 修复h5环境下plugins-sass配置不生效的问题

packages/taro-components/src/components/picker/picker-group/index.js
修复了picker在iOS8下无法滑动的问题，增加webkit前缀即可，希望官方在其他组件也注意下webkit前缀的添加
=> fix: Picker组件需要为iOS8添加webkit前缀

packages/taro-h5/src/api/clipboard/index.js
主要修复两个问题: 
1. setClipboardData方法在ios环境下无效的问题；
2. 在Android手机上, 如果页面超过一屏时, 调用setClipboardData会滚动到页面最底部(判断是input.focus()造成)。
=> fix: 修复h5环境下setClipboardData在ios无效, 在android滚动到页面最后的问题

packages/taro-h5/src/api/request/index.js
fetch请求当响应体no-content时，调用response.arrayBuffer()、response.json()、response.text()时会报错，所以应该提前抛出response进入reject状态
- [ x ] 错误修复(Bugfix) issue id #
- [ x  ] 提交到 master 分支
- [ x ] 所有测试用例已经通过
- [ x ] 代码遵循相关包中的 .eslintrc, .tslintrc, .stylelintrc 所规定的规范
- [ x ] 在本地测试可用，不会影响到其它功能
- [ x ] Web 平台（H5）
=> h5 使用fetch请求时，响应体无数据时抛错进入reject

packages/taro-transformer-wx/__tests__/babel.spec.ts, packages/taro-transformer-wx/src/options.ts
>  // babel-traverse 无法生成 Hub
// 导致 Path#getSource|buildCodeFrameError 都无法直接使用
// 原因大概是 babylon.parse 没有生成 File 实例导致 scope 和 path 原型上都没有 `file`
// 将来升级到 babel@7 可以直接用 parse 而不是 transform
https://github.com/NervJS/taro/blob/master/packages/taro-transformer-wx/src/index.ts#L236-L239
主要解决taro-transformer-wx 在执行transform的时候，babel 插件不能通过 state.opts.file.filename 获取当前正在转换的文件名。
目前需要通过 __tests__/babel.spec.ts 中的hack 方法来实现。
=> fix: 解决babel插件path.hub 中无法获取文件名

packages/taro/types/api/share/share.d.ts
=> feat(taro): 分享参数增加动态消息相关字段

packages/taro-webpack-runner/src/index.ts, packages/taro-webpack-runner/src/util/index.ts
实现H5开发环境,配置devServer.host为0.0.0.0时默认以本地ip地址打开网页; 若配置为其它地址则以配置的host打开网页
=> feat(webpack-runner): dev-server配置host为0.0.0.0时, 默认以本地ip打开

packages/taro/src/hooks.js
修复小程序生命周期 hook 在 rerender 后只触发最后一个，下面是复现代码
```jsx
export default function PageHook () {
console.log('---- rerender ----')
useDidShow(() => {
console.log('didShow1 called')
})
useDidShow(() => {
console.log('didShow2 called')
})
const [count, setCount] = useState(0)
return (
<View>
<Button onClick={() => setCount(count + 1)}>cout: {count}</Button>
</View>
)
}
```
页面载入完成后，点击 button 触发 rerender，切换后台后，console 输出
```
---- rerender ----
didShow1 called
didShow2 called
---- rerender ----
didShow2 called
```
预期结果
```
---- rerender ----
didShow1 called
didShow2 called
---- rerender ----
didShow1 called
didShow2 called
```
之前的逻辑在触发了 rerender 后，赋值给 lifecycle 的新的闭包中 originalLifecycle …
=> fix(taro): 修复小程序生命周期 hook 在 rerender 后只触发最后一个

packages/taro-weapp/src/create-component.js, packages/taro-weapp/src/lifecycle.js, packages/taro-weapp/src/propsManager.js
修改了 propsManage 中提前更新了props的逻辑，改为updateComponent中做实际更新
updateComponent 中原本使用了
```
prevProps = props;
componennt.props = prevProps
// didUpdate 前的各种生命周期
....
componennt.props  = props
```
的逻辑来适应生命周期函数
现在使用额外的nextProps后，不需要重复的修改`props`来适应生命周期函数中的需求
应该只能算一个优化？
暂时就修改了weapp， 如果可以的话，应该还是要同步修改其他平台的
=> 从prevProps改为使用nextProps，避免props的提前赋值，及避免component.props = prevProps的操作

packages/taro-cli/src/mini/index.ts
修正编译时，taro cli 忽略project.qq.json 而使用project.config.json，导致同时使用微信小程序及qq 轻应用时出现appid 不正确，即配置文件错误的问题。
- [x ] 提交到 master 分支
- [x ] 在本地测试可用，不会影响到其它功能
=> fix(cli for qq): 修正qq轻应用配置文件读取

packages/taro-components-qa/src/components/taro-button/index.ux
1.重构样式响应的内容，增加plain透明度、type类型、size大小、disabled禁用、 circle圆角、 loading动画载入 等多种属性的样式
2.通过active伪类，实现点击时变色
3.可通过scss父类样式载入，实现flex纵向换行等布局操作
4.因div组件的特性，text被div包裹时，字体设定无法生效，可通过父类样式引入继承，使得字体大小、种类、颜色等进行设定
=> 增强快应用button组件，增加属性判断及点击变色等

packages/taro-components/src/components/image/index.js, packages/taro-components/src/components/image/style/index.scss
改进了h5的Image组件mode=aspectFill时的表现
改动后效果如下
=> fix(components): h5下Image的aspectFill与小程序不一致(#4620)

docs/config-detail.md, packages/taro-webpack-runner/src/config/dev.conf.ts, packages/taro-webpack-runner/src/config/prod.conf.ts, packages/taro-webpack-runner/src/util/chain.ts, packages/taro-webpack-runner/src/util/types.ts
解决生产接入sentry需要使用sourceMap更便捷的定位代码问题, 而默认cheap-module-eval-source-map格式不支持生产环境(参见webpack官网devtool配置)的问题。
=> feat(webpack-runner): h5环境支持自定义source-map格式

packages/taro-cli/src/mini/native.ts
支持npm安装第三方原生组件包时，使用usingComponents引用
我们为了兼容以前用wepy的小程序，公共包通常用原生组件封装，这个方式是在路径中查找node_modules来判断是不是npm包，使用者需在usingComponents中使用相对路径引用`../../node_modules/component/xxx/xxx`第三方包。
#2926
=> feat(cli): 引入第三方原生组件支持

packages/taro-alipay/src/create-component.js
支付宝小程序函数式 Page 组件在页面卸载后不执行 useEffect 的回调。
=> fix(alipay): 函数 Page 组件没有触发effect cleanup

packages/taro-tt/src/create-component.js
最近更新的RefsArray对象如果被map函数遍历会执行构造函数,造成错误。所以将map改为forEach
=> fix(tt): ref在头条小程序中不能使用的BUG(#4912)

packages/taro-cli/src/mini/helper.ts
=> fix(cli)修正2.0快应用依赖项安装命令在windows不兼容问题

packages/taro-components/types/Image.d.ts
微信小程序 image 组件有一个 show-menu-by-longpress 属性，taro-component 中缺失对应的类型定义。
=> feat(weapp): add missing type for image component

packages/taro/types/api/ext/index.d.ts
修复 Taro.getExtConfigSync 返回值类型。
Taro.getExtConfigSync() 返回的是自定义数据，外层没有 `extConfig`。
=> fix(typescript types): 修复 Taro.getExtConfigSync 返回值类型。

packages/taro-components/types/ScrollView.d.ts
- 给 `ScrollViewProps` 增加了 `enableFlex` 属性
- 样式中使用了 `display: flex` 但未使用`enableFlex`props时开发者工具会警告👇
=> chore(types): add enableFlex to ScrollViewProps

packages/taro-mini-runner/src/plugins/MiniPlugin.ts, packages/taro-mini-runner/src/utils/helper.ts
对快应用自定义组件调用进行特殊处理，将持绝对路径转换为相对路径，修复issue:https://github.com/NervJS/taro/issues/5094
=> fix(mini-runner) 修复快应用自定义组件调用不支持绝对路径调用的问题

packages/taro-rn/src/api/image/previewImage.tsx
场景：`RN`环境下使用`previewImage`进行大图预览时，图片加载过程中无loading效果。
原因：`loadingRender` 函数返回的仅是 `<Text>loading</Text>`, 无任何颜色样式等，此时字体颜色为默认颜色，即黑色，与背景颜色重叠。
修复：使用 `RN` 组件 `ActivityIndicator`，图片资源 `loading` 状态时返回一个转动的小菊花，与其他端保持一致。
=> fix(RN): 修复 previewImage 加载中的 loading 提示

packages/taro-h5/src/api/image/react-wx-images-viewer/components/ImageContainer.js, packages/taro-h5/src/api/image/react-wx-images-viewer/components/WxImageViewer.css
场景：H5 环境下，使用 `Taro.previewImage()` 进行图片预览时，左右滑动会触发浏览器前进、后退功能，譬如当滑动到第一页时，继续右滑会导致浏览器返回上一页。常发生于 UC浏览器 及 Android自带浏览器（如OPPO的ColorOS等）。
修复：首先通过给预览图片容器 `WrapViewr` 添加 css 样式 `touch-action: none;` 禁止浏览的触摸交互功能，此方法亦可消除 `chrom`使用`preventDefault`时报错，此时可消除左右滑动时导致的浏览器返回问题。另，实测此方法在`UC浏览器IOS版`不能达到预期效果，此时需在`ImageContainer`中的处理`touch`相关事件时开启`preventDefault` 及 `stopPropagation` 方法阻止事件的传递。
=> fix: h5环境previewImage左右滑动时触发浏览器前进、后退

packages/taro-cli/src/util/resolve_npm_files.ts
windows下配置weapp.compile.exclude 为npm包时路径问题 #4775
=> windows下配置weapp.compile.exclude 为npm包时路径问题 #4775

packages/taro-alipay/src/native-api.js
解决支付宝 request 与微信 success 回调不一致， 解决request complete 回调参数为undefined
1. 修复了支付宝 request success与微信不一致，将支付宝 fail 回调code（11：无权跨域， 19：HTTP错误）转为 success 回调
2. 避免支付宝 request complete 回调参数为 undefined
=> fix(taro-alipay): 兼容支付宝和微信 request 回调函数

packages/taro/types/api/cloud/index.d.ts
目前 `Taro.cloud` 下函数的返回类型有问题, 导致在 typescript 下使用时 ts 会报错, 比如下图
原因在于 typing 定义中没有根据传入的参数来决定返回类型, 应当根据传入的 `option` 是否包含 `success | fail | complete` 等回调函数决定是否返回 `void` 还是 `promise`. 具体的实现参考微信官方提供的[类型定义](https://github.com/wechat-miniprogram/api-typings/blob/master/types/wx/lib.wx.cloud.d.ts)
=> fix(weapp): 修复 Taro.cloud 部分函数返回错误的类型定义

packages/taro-swan/src/native-api.js
支付方法以微信小程序的api名称为标准,把requestPolymerPayment赋值给requestPayment,这样不需要做多端处理
- [√] 错误修复(Bugfix) issue id #
- [√] 百度小程序
taro在转换成百度小程序的时候requestPayment方法判断在swan对象下面存在,所以没有提示该方法不存在, 但是实际不可调用, 百度的支付方法实际是requestPolymerPayment ,所以把requestPolymerPayment 赋给requestPayment, 以weapp为标准统一调用requestPayment
=> chore(taro-swan): requestPolymerPayment赋值给requestPayment方法

packages/taro-plugin-sass/index.js
关联issue： https://github.com/NervJS/taro/issues/5110
taro-rn，如果配置中使用了 sass.resource，会有 Error: Invalid CSS after "null": expected "{", was "" 这种报错，经排查，发现是因为一个变量传入为null，然后当做字符串合并导致。
=> 修复RN下使用sass.resource配置后报错的问题

packages/taro-mini-runner/src/utils/constants.ts, packages/taro-mini-runner/src/utils/index.ts
fix(taro-mini-runner): 修复引入lodash.xxx时候报错的问题
报错原因：Function('return this')() 返回的结果是空的，导致root.Date.now()等报错，如果用到其他对象比如String,Array,Map等也会出错
这个PR只更新了编译器相关的代码
这个PR是针对2.x版本的taro-mini-runner包的更新，master不存在该包
=> fix(taro-mini-runner): 修复引入lodash.xxx时候报错的问题

packages/taro-mini-runner/src/webpack/chain.ts
v3.0.0-alpha.3版本，小程序的配置中postcss的url配置不生效，
且默认配置和文档中描述的 `limit: 10240` 不一致
=> fix(taro-mini-runner): 修复postcss中url配置不生效的bug

packages/taro-components/src/components/checkbox/checkbox-group.js
修复：当Checkbox想要条件渲染时，并且Checkbox占位符为null时引发的异常
=> 修复：当Checkbox想要条件渲染时，并且Checkbox占位符为null时引发的异常

packages/taro-mobx-h5/src/inject.js, packages/taro-redux-h5/react-redux/components/connectAdvanced.js, packages/taro-router/src/history/createHistory.ts, packages/taro-router/src/router/route.tsx, packages/taro-router/src/router/router.tsx
新增页面级别的路由拦截功能 beforeRouteLeave，只有在页面中声明该拦截函数，页面才具有路由拦截功能，否则页面不具有拦截功能，该函数有三个参数分别为**from**，**to**，**next**
- from：表示从哪个Location离开
- to：表示要跳转到哪个Location
- next: 函数，其入参为boolean；next(true)，表示继续跳转下一个页面，next(false)表示路由跳转终止
使用方式如下：
```js
import Taro, { Component } from '@tarojs/taro'
import { View, Button } from '@tarojs/components'
beforeRouteLeave(from, to, next) {
Taro.showModal({
title: '确定离开吗'
}).then((res) => {
if (res.confirm) {
next(true);
}
if (res.cancel) {
next(false);
}
})
}
render () {
return (
<View>
<Button onClick={() => {
Taro.navigateBack();
}}>返回</Button>
</View>
)
}
}
```
=> feat(taro-router): 新增路由拦截功能beforeRouteLeave

packages/taro-cli/src/ui/common.ts
修复基于taro第三方ui 组件循环依赖时打包失败
原因是analyzeFiles函数在递归调用时提前清空processedScriptFiles集合的问题
=> fix(taro-cli): 修复基于taro第三方ui 组件循环依赖时打包失败 Closes #5620

packages/taro-components-rn/src/components/Input/index.tsx
Input获取焦点时同步tmpValue，防止props.value改变后，onBlur事件参数不正确
_multiline, _autoHeight同时满足时才更新Input高度
=> fix(taro-components-rn): 修复Input组件

packages/taro-h5/src/api/video/index.js
H5修复chooseVideo生成的blob对象缺少类型的问题
=> H5修复chooseVideo生成的blob对象缺少类型的问题

packages/taro-components/src/components/button/index.js
=> fix: 修复定时器在组件更新时未取消问题

packages/taro-runtime/src/dsl/common.ts, packages/taro-runtime/src/dsl/instance.ts
[小程序允许反复跳转同一路由](https://github.com/NervJS/taro/commit/93188261f339593247c16270426fcc2a71cf5a6a)，这个fix 方式，应该还是有点bug。
由于「小程序允许反复跳转同一路由」，事实上现在会对应多个实例。因为 [instance](https://github.com/NervJS/taro/blob/next/packages/taro-runtime/src/dsl/common.ts#L78) 只有在[onLoad](https://github.com/NervJS/taro/blob/next/packages/taro-runtime/src/dsl/common.ts#L97)时候才会重新赋值，会导致同一个路由下的`safeExecute `这些事件永远只通知了最后一个（也就是最后onLoad那个）
我主要修改了下获取实例的方式。不知道满不满足你的设计思路
=> fix(runtime): 修复小程序跳转同一路由时，事件通知处理有误

packages/taro-components/src/components/swiper/index.js
在官方文档和 types/Swiper.d.ts 中用的都是 onAnimationFinish，而在 swiper/index.js 中为 onAnimationfinish ，类型推断错误
=> fix: 函数名错误

packages/taro-runner-utils/src/constants.ts
解决 qq小程序样式文件不压缩, app.qss 不引入 common.qss 文件导致组件样式不生效 
**这个 PR 是什么x类型?** (至少选择一个)
=> fix(qq): qq小程序样式不压缩, app.qss 不引入 common.qss 文件导致组件样式不生效

packages/taro-mini-runner/src/plugins/MiniPlugin.ts
`app.alipay.tsx`, 会输出成 `app.json` , 正则替换了 `alipay.tsx` 为 `json`
=>  fix(mini-runner): `app.[TARO_ENV].tsx` 支持多端配置文件编译成 `app.json`

packages/taro-rn/src/__tests__/request.test.js, packages/taro-rn/src/api/request/index.js
此PR用于修复同步ReactNative与微信的网络请求参数，例如有下面一段代码：
```
return new Promise((resolve) => {
const complete = (result) => {
const networkErrorCode = 600
formatResult = {
...handleData(result.data || {}, result.statusCode || networkErrorCode),
header: result.header || {},
status: result.statusCode || networkErrorCode
}
handleTips(tips, formatResult)
if (formatResult.code !== 0) {
errorReport.api({ code: formatResult.code, msg: formatResult.msg, url: newUrl, params: data })
}
resolve(formatResult)
}
// @ts-ignore
Taro.request({ ...opt, complete })
})
```
此种写法在微信、支付宝小程序可以正常运行，但是无法在ReactNative上正常运行，原因是ReactNative没有接收complete等参数。
=> fix: 同步ReactNative与微信的网络请求参数

packages/taro-h5/src/api/utils/index.js
fix:  #5682 
taro-h5/api/utils.js handleBeforeDestroy()函数中
document.body.style = bodyInlineStyle报错（attempted to assign to readonly property） 中断了js的执行，导致hide toast等js代码没有执行。
ios 11以下，不支持直接操作style的方式，可以通过设置属性进行style，像这样：
document.body.setAttribute('style', bodyInlineStyle)
=> Fix/ios 10.x style operate

packages/taro-quickapp/src/api/router/index.js, packages/taro-quickapp/src/create-component.js
#4375
实现思路：通过当前页面的绝对路径对路由API的url参数进行绝对化
错误修复(Bugfix) issue id #4375
新功能(Feature)
代码重构(Refactor)
文档修改(Docs)
这个 PR 满足以下需求:
提交到 master 分支
所有测试用例已经通过
这个 PR 涉及以下平台:
微信小程序
支付宝小程序
百度小程序
头条小程序
QQ 轻应用
Web 平台（H5）
=> fix4375 解决快应用中路由跳转API不支持相对路径的问题

packages/taro-react/src/props.ts, packages/taro-runtime/src/dom/style.ts
让 taro-runtime & taro-react 支持 CSS Variables，[react-dom](https://github.com/facebook/react/blob/6498f62edc/packages/react-dom/src/shared/CSSPropertyOperations.js#L36) 也是支持该特性的，同时也能让 [callstack/linaria](https://github.com/callstack/linaria) 之类的 Zero-runtime CSS in JS library 可以方便的动态改变 CSS 属性。
（使用 linaria 一段时间了，遇到的问题是对 animation 之类的 [非标准 html 属性进行了过滤](https://github.com/callstack/linaria/blob/ce926c84cc/src/react/styled.ts#L74-L75)，现在只能打一个 patch 在项目中）
=> feat(runtime): 支持 CSS Variables

packages/taro-alipay/src/index.js, packages/taro-qq/src/index.js, packages/taro-tt/src/index.js
使用taroconvert 转换的代码，再编译到支付宝，qq，头条小程序会报错，p.setIsUsingDiff is not a function 
setIsUsingDiff 目前只开放给百度和微信，也需要开发给其他小程序。
=> fix: 头条,qq,阿里小程序报错 p.setIsUsingDiff is not a function

packages/taro-cli/src/mini/helper.ts, packages/taro-mini-runner/src/loaders/wxTransformerLoader.ts, packages/taro-mini-runner/src/plugins/MiniPlugin.ts
1.x可在config中使用defineConstants定义的全局变量，但2.x 却无法使用，增加2.x也支持
=> fix: #5655 2.x中无法在config中使用defineConstants定义的全局变量

packages/taro-mini-runner/src/prerender/prerender.ts
在 windows 下 getRealPath 生成的路径为 ‘\xx\xx’ 在转换字符串的时候会再次被转义成 `xxxx`，
然后在用 vm2 执行 app.onLaunch() 的时候没有捕捉错误
=> fix(mini-runner): windows 下的路径问题 

packages/taro-mini-runner/src/webpack/build.conf.ts
version:`3.0.0-beta.1`
webpack配置中，`output`参数`saas-loader`中的参数
有两个多余参数，导致启动编译，参数校验失败。
原因是因为，`taro-mini-runner/src/webpack/build.config.ts`中`emptyObj`做为多个参数的默认值，内部添加`env`配置，导致所有引用`emptyObj`的配置有额外参数
=> fix(mini-runner): webpack配置多余参数导致webpack,loader参数校验失败

packages/taro-mini-runner/src/plugins/MiniPlugin.ts, packages/taro-mini-runner/src/plugins/TaroLoadChunksPlugin.ts, packages/taro-mini-runner/src/utils/constants.ts, packages/taro-mini-runner/src/webpack/build.conf.ts, packages/taro-mini-runner/src/webpack/chain.ts
0. 增加了 PARSE_AST_TYPE.EXPORTS 类型，用于导出入口文件，目前用于微信小程序插件开发。
0. 修复了TaroLoadChunksPlugin重复初始化，导致的renderWithEntry重复触发的问题。[webpack tapable无法直接删除，使用了flag方案](https://github.com/webpack/tapable/issues/109)
0. plugin.json 还是用的copy方案，需手动把index.ts 改为 index.js。
=> 支持导出微信插件入口文件

packages/taro-redux/src/connect/connect.js
https://github.com/NervJS/taro/issues/3844
修复redux同步dispatch多个action时prevProps被覆盖，导致`componentWillReceiveProps()` `componentDidUpdate()` 中的props比较变的不可靠
=> fix(redux): 快速dispatch redux actions情况下无法正确记录prevProps

packages/taro-h5/src/api/utils/index.js
fix: #5682  注：之前已经对2.x分支提了pr，修复代码已经合并进去。但本公司taro版本仍未升级到2.x，所以需要对master进行修改。
taro-h5/api/utils.js handleBeforeDestroy()函数中
document.body.style = bodyInlineStyle报错（attempted to assign to readonly property） 中断了js的执行，导致hide toast等js代码没有执行。
ios 11以下，不支持直接操作style的方式，可以通过设置属性进行style，像这样：
document.body.setAttribute('style', bodyInlineStyle)
=> fix: issue #5682 ,修复ios 10.x系统中，由于不支持document.body.style = bodyInlineStyle写法导致js被中断的问题

packages/taro-runner-utils/src/constants.ts
修复`tt`小程序公共样式文件`commom.ttss`没有引入
`@tarojs/runner-utils`中缺少tt样式文件的匹配，导致`@tarojs/mini-runner`中`TaroLoadChunksPlugin`中没有在app.ttss 中引入 commom.ttss
=> fix(runner-utils): 缺少ttss样式文件匹配

packages/taro-mini-runner/src/webpack/base.conf.ts
修复 webpack `resolve.modules` 设置绝对路径导致的依赖包的加载使用了错误的优先级，当node_modules 里存在多个同名不同版本号的依赖时，可能会加载到错的。类似webpack中的[这个issues](https://github.com/webpack/webpack/issues/6538)
当 node_modules 存在多个依赖时，下面的配置会导致总是先加载这个`path.join(appPath, 'node_modules'),` 路径下的。
如下的包目录结构，**`这个配置会导致 a-package@1.0.0 依赖到错误的 x-dependency@1.0.0 ❌而不是正确的  x-dependency@2.0.0✅`**
```
a-package@1.0.0
├─ x-dependency@2.0.0
│ 
x-dependency@1.0.0
```
```js
modules: [
path.join(appPath, 'node_modules'),
'node_modules'
]
```
**修复方式：**
我试了下调整下顺序就好了， 优先使用 'node_modules'
```js
modules: [
'node_modules', // 优先
path.join(appPath, 'node_modules')       
]
```
=> fix(mini-runner): 修复 webpack `resolve.modules` 设置绝对路径导致的不同版本依赖包「优先级」加载错误

packages/taro-mini-runner/src/webpack/base.conf.ts
同 PR ：https://github.com/NervJS/taro/pull/5858   提到2.x版本
=> fix(mini-runner): 修复 webpack `resolve.modules` 设置绝对路径导致的依赖引用错误

docs/apis/media/image/chooseImage.md, docs/apis/media/image/chooseMedia.md, packages/taro/src/native-apis.js, packages/taro/types/api/media/image.d.ts
修复 chooseMessageFile 返回类型错误；增加对 chooseMedia API 的支持。
chooseMedia API 微信官方文档的示例中的返回值是错误的，所以没有完全照搬官网示例。
=> 修复 chooseMessageFile 返回类型错误；增加对 chooseMedia API 的支持。

packages/taro-components/types/common.d.ts
在 Taro Next 中不需要传 `{ actions: xxx }` 合并 2.x 定义文件时出现了问题。
=> fix(components): animation 定义出错

packages/taro/types/taro.component.d.ts
Taro.Current.router 的值是在 runtime 中定义的, 形如:
```json
{"params":{"episode":"1","scene":"3"},"path":"/pages/shot/edit"}
```
类型却指向 taro/types/taro.components.d.ts 中的 RouterInfo, 这是用于 2.0 `this.$router` 的类型.
这个 PR 临时添加 path 字段.
=> fix(type): 路由信息增加 path 字段

docs/config-detail.md, packages/taro-webpack-runner/src/__tests__/index-test.ts, packages/taro-webpack-runner/src/config/dev.conf.ts, packages/taro-webpack-runner/src/config/prod.conf.ts, packages/taro-webpack-runner/src/util/chain.ts, packages/taro-webpack-runner/src/util/types.ts
1. taro-webpack-runner 添加 `miniCssExtractLoaderOption` 的配置支持，修复从外部传入 `miniCssExtractPluginOption` 无法修改内部的 loader option的问题;
2. 文档添加对应配置 `h5.miniCssExtractLoaderOption` 的说明；
3. 修改ts 类型 `TaroH5Config`，新增 `miniCssExtractLoaderOption` 属性支持。
=> feat(taro-webpack-runner): add miniCssExtractLoaderOption support

packages/shared/package.json, packages/taro-api/package.json, packages/taro-api/rollup.config.js, packages/taro-react/package.json, packages/taro-runtime/package.json
在给 Taro UI 写单元测试，发现 @tarojs/api 只分发了 ESM 格式的文件（如下图），导致 Jest Runtime 报错（部分无关内容已经删除）：
```text
Details:
/Users/hagongyi/Projects/GitHub/taro-ui/node_modules/@tarojs/api/dist/index.esm.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { Events, eventCenter, Current, useDidShow, useDidHide, usePullDownRefresh, useReachBottom, usePageScroll, useResize, useShareAppMessage, useTabItemTap, useTitleClick, useOptionMenuClick, usePullIntercept, useRouter, options, nextTick } from '@tarojs/runtime';
^^^^^^
SyntaxError: Cannot use import statement outside a module
at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1086:14)
at Object.<anonymous> (../../node_modules/@tarojs/taro/index.js:1:103)
``` …
=> feat: api 增加 cjs 分发，规范部分包的文件包含

packages/taro-runtime/src/dom/root.ts, packages/taro-runtime/src/dsl/common.ts, packages/taro-runtime/src/next-tick.ts
**需求背景：**
`Taro.nextTick`目前触发时机是js线程下一个event loop，在小程序运行环境中，这个时机不能确保视图数据渲染完成；场景：在渲染某个元素之后，需要使用`Taro.createSelectorQuery()`去获取元素的样式信息时，目前触发时元素可能还没渲染完成，无法准确获取；
**修改点：**
在小程序环境且支持渲染回调下，调用`Taro.nextTick`，则回调在`setData`渲染完成之后执行；在其他环境，则是下一个event loop;
=> refactor(runtime): nextTick适配小程序setData回调

packages/taro-components/types/ScrollView.d.ts
=> fix(type):  修复 ScrollView 监听函数类型

packages/taro-components-qa/src/components/taro-image/index.ux, packages/taro-mini-runner/src/quickapp/style/declaration/font/index.ts
1. 快应用的图片组件设置mode不生效
2. font-family参与编译，快应用中可使用字体
=> 快应用图片组件mode不生效与font-family能编译，支持iconfont

packages/taro-react/src/props.ts, packages/taro-runtime/src/dom/event_target.ts, packages/taro-runtime/src/dom/node.ts
https://github.com/NervJS/taro/commit/0369c987f1a463701ddb26bb48c5e6e66471d792
会在元素被从 DOM 树中清除时，同时清理它的所有子元素，以及他们的引用
https://github.com/NervJS/taro/commit/97efc4579838c64e7872f5275e3a04d416b7e823
重构 react 的事件代理机制，从前使用 weakMap 实现，但由于小程序开发者工具没有可以找到对象引用关系的工具，无法定位问题。目前的实现把事件代理机制绑定到 DOM 本身，利用 `TaroEventTarget` 的内部对象实现。
=> perf(runtime): 降低使用 react 的内存占用

packages/taro-components/stencil.config.ts, packages/taro-h5/package.json, packages/taro-h5/rollup.config.js, packages/taro-webpack-runner/src/util/chain.ts
* taro-components 合并父子组件到同一文件，减少资源请求
* babel loader 不处理 node_modules 里的文件，加快构建速度
=> perf(h5): 加快 h5 webpack 构建速度

packages/taro-webpack-runner/src/plugins/MainPlugin.ts
将 subpackages 的页面路径加入到 app.json 的 pages 字段中，让路由能够识别分包页
=> fix(webpack-runner): 修复h5 跳转到分包页报错的问题

packages/taro-mini-runner/src/quickapp/template/serialize.ts
=> fix(mini-runner): 修复快应用动态class不支持三目运算符问题 (#5556)

packages/taro-h5/src/api/image/chooseImage.js
修复h5的chooseImage API无法动态设置souceType的问题，对齐小程序端
问题复现代码如下：
- 1、新建两个页面`Index`和`Second`：
```js
// Index页面，sourceType:为['album', 'camera']
import Taro, { Component } from '@tarojs/taro'
import { View, Text, Button } from '@tarojs/components'
render () {
return (
<View>
<Button onClick={() => {
Taro.chooseImage({
sourceType: ['album', 'camera']
});
}}>选择图片</Button>
<Button onClick={() => {
Taro.navigateTo({
url: '/pages/second/index'
});
}}>下一页</Button>
</View>
)
}
}
// Second页面，sourceType为['camera']
import Taro, { Component } from '@tarojs/taro'
import { View, Text, Button } from '@tarojs/components'
export default class Second …
```
=> fix(taro-h5): 修复h5的chooseImage API无法动态设置souceType的问题，对齐小程序端

.github/workflows/publish.yml, package.json
这个 PR 在 `2.x` 分支实现版本自动发布。
1. [项目维护者] 在本地开发版本发布分支并发起 Pull Request
2. [Taro 团队] Review 版本发布分支 PR
3. [CI] 发布版本
1. [本地] checkout 发布分支：`git checkout -b release/<semver>`
2. [本地] 运行 `npm run versionup ` 和 `npm run changelog` 修改 `CHANGELOG.md` 和 `package.json` 以及 `lerna.json`
* 本地只修改文件，不发布 `git tag`, `GitHub Release` 和 NPM 版本
3. [本地] 提交版本发布分支 Pull Request
4. [GitHub] Review 并 merge 版本发布分支
* 使用 `Squash and merge` 合并分支
* 合并提交信息必须为包含 `chore(release): publish <semver>`
5. [CI] 校验版本发布分支的提交信息是否为 `chore(release): publish <semver>`
6. [CI] 添加 `git tag <semver>`
7. [CI] 将版本发布分支 PR 的标题和内容发布到 GitHub Release 页面
8. [CI] 发布版本到 NPM
提交信息若以 `chore(release):` 开头，但又包含 `[skip ci]` 可以跳过此流程。
=> chore(ci): 2.x 自动发布版本

packages/taro-mini-runner/package.json
因为 h5-runner 用了 3.0，且 url-loader 3.0 有一些 breaking Changes，因此同步一下版本
=> chore(mini-runner): 升级 url-loader 到 3.0，fix #6148

packages/taro-mini-runner/src/plugins/MiniPlugin.ts
在实际的应用中 app.wxss 通常放入的是全局通用性的样式,
然后根据需要会在各个页面或者组件中覆盖或重写这些样式.
那么这就需要 common.wxss 在后, app.wxss 的内容在前.
这样 common.wxss 内容优先级会更高.
- [ ✅] 错误修复(Bugfix) issue id #
- [ ✅] Commit 信息遵循 [Angular Style Commit Message Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)
- [ ✅] 所有测试用例已经通过
- [ ✅] 代码遵循相关包中的 .eslintrc, .tslintrc, .stylelintrc 所规定的规范
- [ ✅] 在本地测试可用，不会影响到其它功能
- [ ✅] 微信小程序
=> 将 common.wxss 放入 app.wxss 的最底部

packages/taro-mini-runner/src/prerender/prerender.ts
目前 prerender 对属性变量是使用字符串模板转换为字符串，当变量为对象时转换会出错。因此如果属性值为对象时，首先尝试使用 JSON.stringify 进行转换。
=> fix(mini-runner): prerender 能够正确处理对象属性

packages/taro-runtime/src/current.ts, packages/taro-runtime/src/dsl/common.ts, packages/taro/types/taro.extend.d.ts
形如以下代码：
```jsx
class Test extends React.Component {
componentDidMount () {
Taro.eventCenter.once(Taro.Current.router.onReady, () => {
const query = Taro.createSelectorQuery()
query.select('#only').boundingClientRect()
query.exec(res => {
console.log(res, 'res')
})
console.log('onReady')
})
}
render () {
return (
<View id="only">
</View>
)
}
}
```
=> feat(runtime): 普通组件可以通过 eventCenter 触发页面组件的 onReady 事件

packages/taro-mini-runner/src/utils/parseAst.ts
当 App 的 config 为静态属性(static prop)时，componentClassName(_App) 与 left.object.name(App)不匹配，造成获取不到 config 对象的问题。
```diff
class App extends Taro.Component {
+  public static config: Taro.Config = {
-  public config: Taro.Config = {
pages: [
'pages/index/index'
],
window: {
backgroundTextStyle: 'light',
navigationBarBackgroundColor: '#fff',
navigationBarTitleText: 'WeChat',
navigationBarTextStyle: 'black'
}
}
public render(): JSX.Element {
return (
<Index />
)
}
}
```
=> fix: 修复 App 的 config 为静态属性时获取不到 config 对象的问题

packages/taro-cli/src/cli.ts, packages/taro-cli/src/create/creator.ts, packages/taro-cli/src/create/init.ts, packages/taro-cli/src/presets/commands/build.ts, packages/taro-cli/templates/default/_editorconfig, packages/taro-cli/templates/default/_eslintrc, packages/taro-cli/templates/default/_gitignore, packages/taro-cli/templates/default/_npmrc, packages/taro-helper/package.json, packages/taro-service/package.json
* taro-init 会创建 .editorconfig、.eslintrc、.gitignore、.npmrc
* 优化 taro-init 的 logs
* taro init 支持使用参数 --name 指定项目名称
* 修复 modifyWebpackChain 异步问题
* taro-helper、taro-service 两个包发布时加上 types 文件夹
=> fix(cli): 修复 cli 若干问题

packages/taro-mini-runner/__tests__/__snapshots__/alipay.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/bytedance.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/jd.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/qq.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/swan.spec.ts.snap, packages/taro-mini-runner/__tests__/fixtures/react/src/pages/index/index.jsx, packages/taro-mini-runner/package.json, packages/taro-mini-runner/src/webpack/base.conf.ts, packages/taro-mini-runner/yarn.lock
* mini-runner 内置 **regenerator-runtime@0.11**，并让 webpack alias 到它。避免其它包使用到 regenerator-runtime@0.13 而令小程序报错。
* 更新测试用例
=> fix(mini-runner): 修复支付宝使用 async await 报错，fix #6278

packages/taro-alipay/src/lifecycle.js, packages/taro-jd/src/lifecycle.js, packages/taro-qq/src/lifecycle.js, packages/taro-swan/src/lifecycle.js, packages/taro-tt/src/lifecycle.js, packages/taro-weapp/src/lifecycle.js
修复 useLayoutEffect 触发时机以解决 useImperativeHandle 的问题
=> fix(mini): 修复 useLayoutEffect 触发时机，fix #6069

packages/taro-cli/src/util/resolve_npm_files.ts, packages/taro-mobx-common/src/store.js
=> fix(mobx)：修复快应用下 store 未定义及页面不刷新问题（#4248）

docs/apis/ui/tab-bar/hideTabBar.md, docs/apis/ui/tab-bar/showTabBar.md, packages/babel-plugin-transform-taroapi/src/__tests__/index-test.ts, packages/taro-components-rn/src/components/Checkbox/checkboxGroup.tsx, packages/taro-components-rn/src/components/Form/index.tsx, packages/taro-components-rn/src/components/Label/index.tsx, packages/taro-components-rn/src/components/Radio/radioGroup.tsx, packages/taro-router/src/apis/index.ts, packages/taro-router/src/router/route.tsx, packages/taro-router/src/router/router.tsx, packages/taro-transformer-wx/src/class.ts, packages/taro-transformer-wx/src/jsx.ts, packages/taro-transformer-wx/src/render.ts, packages/taro/types/api/ui/tab-bar.d.ts
=> fix(router): checkout 2.x router fixed

packages/taro-mini-runner/src/webpack/base.conf.ts, packages/taro-runner-utils/src/index.ts, packages/taro-runner-utils/src/resolve/MultiPlatformPlugin.ts, packages/taro-runner-utils/types/index.d.ts, packages/taro-runner-utils/types/resolve/MultiPlatformPlugin.d.ts, packages/taro-webpack-runner/src/config/base.conf.ts, packages/taro-webpack-runner/src/index.ts
增加了一个 [enhance-resolve](https://github.com/webpack/enhanced-resolve) 插件。用于根据当前编译的平台，解析多端文件的后缀。
>    @example
>    there's filepath 'src/index'
>    when platform is weapp, we get "src/index.weapp.[js|ts|jsx|tsx]"
>    when platform is h5, we get "src/index.h5.[js|ts|jsx|tsx]"
>    by default, we get "src/index.[js|ts|jsx|tsx]"
=> feat(runner): 支持解析多端文件，close #6231

packages/taro-helper/yarn.lock, packages/taro-mini-runner/__tests__/__snapshots__/alipay.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/babel.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/bytedance.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/common-style.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/config.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/css-modules.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/custom-tabbar.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/jd.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/nerv.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/parse-html.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/prerender.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/qq.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/sass.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/subpackages.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/swan.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/tabbar.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/ts.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/vue.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/wx-hybrid.spec.ts.snap, packages/taro-runtime/src/dsl/common.ts, packages/taro-webpack-runner/__tests__/__snapshots__/babel.spec.ts.snap, packages/taro-webpack-runner/__tests__/__snapshots__/css-modules.spec.ts.snap, packages/taro-webpack-runner/__tests__/__snapshots__/nerv.spec.ts.snap, packages/taro-webpack-runner/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-webpack-runner/__tests__/__snapshots__/subpackages.spec.ts.snap, packages/taro-webpack-runner/__tests__/__snapshots__/ts.spec.ts.snap, packages/taro-webpack-runner/__tests__/__snapshots__/vue.spec.ts.snap
runtime 内保存的组件实例，页面关闭没有被清除。
重复进出多几次页面，导致内存占用过高
=> perf(runtime): 页面组件卸载时组件引用

packages/taro-components-rn/src/components/Block/index.tsx
=> fix(components-rn): rn上Block组件会被编译成View组件，会有样式问题 close #5505

docs/apis/network/upload/uploadFile.md, packages/taro-h5/src/api/fileTransfer/uploadFile.js, packages/taro/types/api/network/upload.d.ts
uploadFile可配置withCredentials（仅H5）
- [] 提交到 master 分支
当Access-Control-Allow-Origin为*并且withCredentials为true时，会跨域。而上传未能进行配置。因此为uploadFile可配置项withCredentials（仅H5）
=> feat(h5): uploadFile可配置withCredentials

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/__tests__/update.spec.ts, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
* 新增 `taro inspect` 命令
* 修复 `scroll-view` 组件没有下拉刷新相关属性的问题，fix #6426
* 修复移动 DOM 元素会卸载子组件的问题，fix #6442, #6156
* 修复微信小程序 PC 端打开报错的问题，fix #6451, #5820
* 修复 `taro update` 命令，fix #6430
* 修复 `taro build` 命令无法设置自定义 `env` 参数的问题，fix #6441
* 修复 `text` 组件小程序/H5 表现不一致的问题
* 修复 CLI 无法解析多端文件的问题，fix #6231
* 修复部分类型错误，by @cncolder and @fupengl
* 修复支付宝小程序 `button` 属性缺失的问题，
* 所有小程序环境的 `window` 对象上都会有 `requestAnimationFrame`, `cancelAnimationFrame`, `Date`, `setTimeout` 函数
* 兼容 Taro 1/2 访问页面 `config` 属性的方法
* 普通组件也可以访问页面组件的 `onShow`/`onHide` 生命周期
* 移除需要安装 `@tarojs/swan` 的警告
* Taro 配置检查错误不停止编译
* 页面组件卸载时组件引用, by @fupengl
=> chore(release): publish v3.0.0-rc.1

packages/taro-cli/yarn.lock, packages/taro-mini-runner/__tests__/__snapshots__/alipay.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/babel.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/bytedance.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/common-style.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/config.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/css-modules.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/custom-tabbar.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/jd.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/nerv.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/parse-html.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/prerender.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/qq.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/sass.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/subpackages.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/swan.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/tabbar.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/ts.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/vue.spec.ts.snap, packages/taro-mini-runner/__tests__/__snapshots__/wx-hybrid.spec.ts.snap, packages/taro-runtime/src/dom/html/parser.ts, packages/taro-webpack-runner/__tests__/__snapshots__/babel.spec.ts.snap, packages/taro-webpack-runner/__tests__/__snapshots__/css-modules.spec.ts.snap, packages/taro-webpack-runner/__tests__/__snapshots__/nerv.spec.ts.snap, packages/taro-webpack-runner/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-webpack-runner/__tests__/__snapshots__/subpackages.spec.ts.snap, packages/taro-webpack-runner/__tests__/__snapshots__/ts.spec.ts.snap, packages/taro-webpack-runner/__tests__/__snapshots__/vue.spec.ts.snap
目前的实现会把 HTML 的 className 设置为 tagName 两次，而忽略了传入的原有 className。
修复之后的 className = tagName + 原有 className
=> fix(runtime): html 解析 className 不正确

docs/apis/canvas/Canvas.md, packages/taro/types/api/canvas/Path2D.d.ts, packages/taro/types/api/canvas/index.d.ts
修复微信小程序canvas部分属性类型缺失，并且定义Path2D接口
=> fix: 修复微信小程序canvas部分属性类型缺失, 定义Path2D接口

packages/taro-cli/src/create/init.ts
修复：使用taro init 进行自定义初始化时，文件的changeExt配置无效
=> fix(cli): 模板初始化时changeExt 无效

packages/taro-router/src/router/route.tsx, packages/taro-router/src/router/router.tsx
=> fix: custom-routes for path-match fix #6388

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
- 新增组件 `slot` 和 `slot-view`，用于原生小程序组件， [文档](https://nervjs.github.io/taro/docs/next/mini-third-party#%E4%BD%BF%E7%94%A8-slot)
- 路由配置支持 `basename`，close #6577
- 路由模式支持 `hash`，close #6228
- 路由配置支持 `customRoutes`
- loader 生成的代码无法在非 ES6 环境下运行，close #6547
- 使用函数式组件作为入口组件不会报错，close #6517
- 第三方组件的属性无法使用短横线风格，close #6509
- view 模板没有 bindTransitionEnd 事件，close #6558 by @ziruozimi
- `Taro.getAccountInfoSync` by @cncolder
- 默认 import 支持 resolve `.vue` 文件
- navigate 相关 API 支持 promise 调用
=> chore(release): publish v3.0.0-rc.4 [auto review]

packages/taro-runtime/src/dsl/hooks.ts, packages/taro/types/taro.hooks.d.ts
taro-runtime 中特有的 hooks 一直以来需要传递两个参数, 第一个参数 callback 不会更新, 而第二个参数 deps 会造成 callback 重复执行. 一直以来都是不建议传递第二个参数的.
这个 PR 移除了第二个参数, 使用 `React.useRef` 包装第一个 callback 参数, 从而实现小程序生命周期调用的函数不变, 但内部实际执行的永远是最新的 callback 参数. 这符合 class 组件中的使用方式.
=> refactor(runtime): 使用引用代替 Taro hooks 依赖

.vscode/launch.json, packages/taro-webpack-runner/src/config/dev.conf.ts, packages/taro-webpack-runner/src/config/prod.conf.ts, packages/taro-webpack-runner/src/util/chain.ts
=> refactor(webpack-runner): 同步 2.x 的 sourceMapType 配置项

packages/taro-components/src/components/swiper/swiper.tsx, packages/taro-h5/src/api/image/preview_image.js
=> fix(taro-h5): 修复 previewImage bug，fix #6656

packages/taro-components/types/common.d.ts
目前组件的 ref 属性传入 useRef 值时类型不匹配.
```tsx
const r = useRef<typeof View>()
const c = <View ref={r} />
```
由于 StandardProps 类型没有传递泛型, 暂时只能用 any.
=> fix(type): 修复组件 ref 类型以支持 useRef 用法

packages/taro-api/src/index.js
taro3.0.0-rc.5新增了 `getCurrentInstance` api，但这个api无法从 `@tarojs/taro` 中导出，此PR即修复此问题 
=> fix(taro): 修复 @tarojs/taro 未导出 getCurrentInstance 的问题

packages/shared/src/components.ts
[解决QQ小程序bindLongTab不存在的bug，参考这个issues](https://github.com/NervJS/taro/issues/5706#issue-581518178)
=> fix(mini-runner): qq小程序已不存在bindLongTab事件

packages/taro-router/src/api.ts
=> fix(router): navigateBack API支持配置 delta，close #6740

packages/taro-runner-utils/src/resolve/MultiPlatformPlugin.ts
require.context 的情况下不使用多端文件判断逻辑
=> fix(runner-utils): 修复 resolve 插件，fix #6720

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runner-utils/src/resolve/MultiPlatformPlugin.ts, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
- `@tarojs/taro` 未导出 `getCurrentInstance`，by @vdfor
- 虚拟列表 scrollTo 方法无效，close #6751
- 无法使用 require.context，fix #6720 
- 路由无法跳转参数不同的同一页面， close #6612
- navigateBack API支持配置 delta，close #6740
- 自定义 tabbar key 报错, close #6297
- input 组件光标位置初次聚焦在最左边，#6632
- QQ 小程序 `bindLongTab` 事件不存在，by @disflyer
- 修复 `false` 拼写错误, by @kokororin
- 自定义 Hooks 不准确，by @fjc0k
- 修复 sass 配置校验，close #6745
- 开发模式现在也会打开 `tree-shaking`, close #6705
- nextTick 函数一定会在 onReady 之后运行 , close #6501
=> chore(release): publish v3.0.0-rc.6

packages/taro-components-rn/src/components/Image/index.tsx
> Image 组件在ReactNative端使用时，若 mode 设为 widthFix 则可能导致图片不能显示，其原因是图片高度计算为0。
原因：widthFix 模式下，其高度根据容器宽度`this.state.layoutWidth` 和图片宽高比 `this.state.ratio` 计算所得，而 `onLayout` 函数执行一次后，即标志已渲染完成，此时忽略了 `setState` 是异步执行的，故而导致此时 `ratio` 依然为初始值 0。
=> fix(rn): RN Image 组件 widthFix 时,部分图片不显示问题

packages/taro-cli/__tests__/inspect.spec.ts, packages/taro-cli/src/presets/commands/inspect.ts, packages/taro-service/src/Kernel.ts, packages/taro-service/types/index.d.ts
* 目前 inspect 命令对 Taro 项目配置的解析不正确，应该把 mini、h5 里的配置项扁平化。
* isWatch 根据 process.env.NODE_ENV 确定
=> fix(cli): 修复 inspect 命令对 config 的整理

packages/taro-components/package.json, packages/taro-webpack-runner/src/config/prod.conf.ts, packages/taro-webpack-runner/src/config/vue.ts, packages/taro-webpack-runner/src/config/vue3.ts
增加dist-h5导出，修复h5项目编译报错，by @w91
=> fix(h5): 增加dist-h5导出，修复h5项目编译报错，fix #6843

packages/taro-extend/src/jquery/zepto.js
=> fix(extend): 选择器 API 没有添加 '#' 开头，

README.md
=> docs: 更新 readme

packages/taro-mini-runner/src/template/index.ts
修复支付宝 picker 报错，支付宝 picker 的 children 只能为一个节点，现在先套一个 view 。
=> fix(mini-runner): 修复支付宝 picker 报错，fix #6804

packages/taro-runtime/src/dom/form.ts
修复百度小程序 input 跳焦问题。
表单内容改变时，需要同步 Taro FromElement 的 value 值，但之前是会触发 setData，导致百度表单跳焦点。因此现在改为不触发 setData。
=> fix(runtime): 修复百度小程序 input 跳焦问题, fix #6943

packages/taro/types/taro.component.d.ts, packages/taro/types/taro.config.d.ts
为该 PR 添加用户侧的类型定义：https://github.com/NervJS/taro/pull/6996
同时希望官方在功能改动时也考虑同步类型的改动。
另外，我觉得 https://github.com/NervJS/taro/pull/6996 带来的 breaking changes 似乎不太妥当，似乎用 disableShareAppMessage、disableShareTimeline 更为合适，一是因为这样不会带来任何不兼容更新，二是其实更多的需求是让用户分享，而不是禁止用户分享，一个十分常用的功能却要手动在每个页面开启是十分令人抓狂的。
=> fix(types): 添加缺失的类型定义

packages/shared/src/components.ts
=> fix(shared): 给 Map 组件的 setting 添加默认值, fix #6949

packages/taro-mini-runner/__tests__/__snapshots__/prerender.spec.ts.snap, packages/taro-mini-runner/src/prerender/prerender.ts
=> fix(mini-runner): 修复支付宝小程序预渲染报错, fix #7111

packages/taro-mini-runner/src/loaders/wxTransformerLoader.ts
修复babel.transform 未传递 config.filename 导致插件中无法访问 state.file.opts.filename问题, 同issue #2168
正常 babel 插件中应可以通过 state.file.opts.filename 访问到当前编译文件的绝对路径，但是 taro 中调用的 babel 插件中获取的 filename 始终是 unknown, 这个问题在1.x的版本解决了, 但是目前发现在2.x的版本上还是存在该问题。
=> fix(taro-mini-runner): 修复babel.transform 未传递 config.filename问题

packages/taro-webpack-runner/src/config/devServer.conf.ts
H5模式下，webpack-dev-server打开浏览器时ip使用的0.0.0.0，无法正常打开预览地址。
webpack4.x版本新增useLocalIp配置项。
=> fix(H5):webpack devServer open the browser with wrong Host

packages/taro-h5/src/api/request/index.js
在 taro-h5/src/api/request/index.js (80行) 的 response.headers —— 在支持fetch的浏览器其为Map对象，在不支持fetch的浏览器上，通过unfetch/polyfill兼容，其值为普通对象（如下图），不可使用 forEach 进行遍历。
=> fix(h5): 修复不支持fetch的浏览器调用request无法返回结果

packages/taro-runtime/src/dsl/react.ts
给每个页面的 key 增加一个独立 id，避免 key 重复而报错
两种情况下以 path + options 组成的 key 可能重复：
1. custom-tab-bar
2. Taro 页面 A 使用原生 API 跳转新页面 A'，且不带参，这时 A 与 A' 路径一样，所以会重复。（Taro 跳转API 添加了随机参数，所以不会重复）
=> fix(runtime): 给每个页面的 key 增加一个独立 id，避免 key 重复而报错

packages/taro-mini-runner/src/webpack/vue3.ts, packages/taro-runtime/src/dsl/react.ts, packages/taro-runtime/src/dsl/vue.ts, packages/taro-runtime/src/dsl/vue3.ts
* 字节基础库 1.70+ `App` 构造器不支持传入类实例，这里改为传入使用 Object.create 创建的对象。
* 修复在进入页面时 Vue3 不触发 `onShow` 的问题。
* 兼容 Vue3 3.0.0-rc.3 新增的两个编译配置：`__VUE_OPTIONS_API__` 和 ` __VUE_PROD_DEVTOOLS__`
=> 修复头条、Vue3 等问题

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
- 修复虚拟列表 VirtualList 滚动时抖动的问题，#6863，by @Leechael 
- 修复使用 **react-redux@7.20.1+** 时，类组件生命周期不触发的问题
- 兼容 Vue3 3.0.0-rc.3 新增的两个编译配置：__VUE_OPTIONS_API__ 和 __VUE_PROD_DEVTOOLS__，#7143
- 修复字节跳动小程序在基础库 1.70+ 下白屏问题，#6929
- 修复在初次进入页面时 Vue3 不触发 `onShow` 的问题
- 为 `Map` 组件的 setting 属性添加默认值，#6949
- 修复支付宝小程序预渲染报错，#7111
- 修复使用原生 API 不带参数跳转页面栈中已有的页面时报错的问题。
- 修复 `<sub>` 标签样式，by @Songkeys 
- **webpack-dev-server** 使用 local IP 打开网页，by @southorange1228 
- 修复 Vue 在生产环境不工作的问题，#7129
- 修复不支持 fetch 的浏览器调用 request 无法返回结果的问题，#7161，by @vdfor
=> chore(release): publish 3.0.6

versioned_docs/version-3.0.5/guide.mdx
修复了一个文档中的示例代码错误
在虚拟列表中，`itemData` 传入给`item`组件的是一整个数组。而不是数组中的单项。因此在这个示例的Row中，如果直接用传入的`data` 将会引发错误，因为data是一个数组。
因此需要在子组件中对data进一步处理，使用`data[index]` 来获得当前子组件Row应该渲染的单项数据。
=> 修正虚拟列表Vue示例中的数据引用错误

packages/taro-components/types/common.d.ts
React 把这个属性放在 DOMAttributes 上, 所有 tag 都支持. Taro 的实现方式也没有限定在 View 组件上. 所以决定把这个类型放在 StandardProps 上面.
=> fix(types): 增加组件标准属性 dangerouslySetInnerHTML

packages/shared/src/components.ts, packages/taro-components/src/components/canvas/canvas.tsx
* 修复 H5 Canvas 组件样式问题, fix #6990
* Canvas 的 type 需要默认值 '2d'
* Map 的数组类型需要默认值，否则头条下会报错，fix #7207
* 修复地图组件属性，fix #7178
* 补充 `Ad` 组件确实的属性，fix #7237
=> 修复 Canvas、Map、Ad 组件

packages/taro-runtime/src/dom/html/parser.ts, packages/taro-runtime/src/dom/html/scaner.ts
修复以下这种情况，属性名后的 `=` 旁多出空格会解析错误的问题
```js
<p style = "font-size:35px;color:grey">
```
=> fix(runtime):  修复 html 解析器分析属性时对空格的错误处理，fix #6911

packages/shared/src/components.ts, packages/taro-runtime/src/hydrate.ts
为 `SwiperItem` 设置 style 属性会覆盖小程序自动添加的 `transform` 等 style，因此直接不许设置 style。
=> fix(runtime/share): swiperitem不设置style属性，fix #7147

packages/taro-react/__tests__/props.spec.js, packages/taro-react/src/props.ts
=> fix(react): 修复使用第三方组件不能触发 onClick 事件的问题，fix #7182

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
- 修复引用 `@tarojs/service` 包时的类型报错, fix #7058
- 修复 react 组件卸载问题, fix #7206
- 模板为 `Video` 组件补充微信小程序端缺失属性, by @wuchangming 
- 模板为 `Swiper` 组件补充缺失属性与事件, by @alexlees 
- 模板为 `Canvas` 组件的 `type` 属性补充默认值 '2d'
- 模板为 `Map` 组件修复属性, fix #7207 #7178 
- 模板为 `Ad` 组件补充缺失属性, fix #7237
- 修复 **html parser** 分析属性时对空格的错误处理, fix #6911
- `SwiperItem` 不再允许设置 **style** 属性, fix #7147
- 修复使用第三方组件不能触发 `onClick` 事件的问题，fix #7182
- 修复 `Canvas` 组件样式问题, fix #6990
- 修复页面组件 id 带有 undefined 的问题
- 增加组件标准属性 `dangerouslySetInnerHTML`, #7236, by @cncolder
- 小程序端也支持异步 `import()` 语法, by @wuchangming
=> chore(release): publish 3.0.7

packages/shared/src/components.ts, packages/taro-components/types/LivePlayer.d.ts
补全 LivePlayer 微信端缺失属性,
参考文档：https://developers.weixin.qq.com/miniprogram/dev/component/live-player.html
=> fix(shared): 补全 LivePlayer 微信端缺失属性

packages/taro-components/src/components/radio/index.js, packages/taro-components/src/components/radio/radio-group.js
radio-group 的子组件包裹会导致 事件多次触发，且部分事件 value 值错误设置
> input change 会在值变更时自动触发，并冒泡触发上层事件，导致 onChange 被多次执行
=> fix: 修复 radio-group 子组件 wrapper 导致事件错误问题 fix #6475

packages/taro-components/src/components/picker/index.js
当用户使用多列picker时, 想要动态增减列(即改变range属性的长度), 改动之后再操作picker会报错, 这个PR修复了这个问题
=> picker组件为多列选择器时range的长度变化不能正确工作的bug修复

packages/taro-router/src/router/route.tsx
=> feat: switchTab on pages route to fix #6878

packages/taro-helper/__tests__/babel.spec.ts, packages/taro-helper/src/utils.ts
允许用户覆盖helper 默认的 babel 配置，修复 #7345
=> fix(helper): babel-preset-env 配置不起作用 close 7345

packages/taro-runtime/src/dom/html/tags.ts
修复 Vue3 静态节点渲染错误的问题。
Vue3 的静态节点会使用 `node.innerHTML` 渲染 DOM 树，小程序端渲染 `innerHTML` 时需要识别出所有小程序对应组件。
目前是静态列出若干 H5 标签对应的小程序组件，但不齐全，这里予以补全。
=> fix(runtime): 修复 Vue3 静态节点渲染错误的问题，fix #7128

packages/babel-preset-taro/index.js
修复Vue SFC使用TS语法报错的问题，`@babel/preset-typescript` 增加 `allExtensions: true` 配置，使得可以识别 `.vue` 文件
=> fix(babel-preset): 修复Vue SFC使用TS语法报错的问题，fix #7335

packages/taro-mini-runner/src/loaders/miniTemplateLoader.ts
#5824
#5577 
更改文件：更改了 `@taro/mini-runner` 下的 `loaders/miniTemplateLoader.ts` 文件
更改内容：给loader中拿到的source源文件内容字符串包裹了一层根节点，使sax可以正确解析出需要import的文件，使之正确打包。注释中也列出了第二种方案，但推荐采用本次PR中使用的方案。
1. 在添加代码之前，mini-runner 包中的测试用例已有一些不通过。
=> fix(mini-runner): [next]修复小程序混写时模板引入只有第一个生效的问题 close #5824 #5577

packages/taro-mini-runner/src/loaders/miniTemplateLoader.ts
#5824
#5577 
更改文件：更改了 `@taro/mini-runner` 下的 `loaders/miniTemplateLoader.ts` 文件
更改内容：给loader中拿到的source源文件内容字符串包裹了一层根节点，使sax可以正确解析出需要import的文件，使之正确打包。注释中也列出了第二种方案，但推荐采用本次PR中使用的方案。
1. 在添加代码之前，mini-runner 包中的测试用例已有一些不通过。
=> fix(mini-runner): [2.x]修复小程序混写时模板引入只有第一个生效的问题

packages/taro-components/virtual-list/react/createListComponent.js, packages/taro-runtime/src/dom/style_properties.ts
* 修复 H5 虚拟列表滚动后不能点击的问题
* 修复小程序端不能设置 pointer-events 样式的问题
=> fix(components): 修复 H5 虚拟列表滚动后不能点击的问题，fix #7140

docs/react.md, versioned_docs/version-1.3.45/react.md, versioned_docs/version-3.0.7/react.md
修复文字错误，componentDidMount声明周期内可以访问`getCurrentInstance().router`
=> docs: 修复react.md文案错误

packages/taro-components/types/common.d.ts
完善组件 ref 属性的类型推导，解决如下类型推导报错。
```typescript
import Taro, {useRef} from '@tarojs/taro'
const MyComponent = () => {
const ref = useRef()
return <View ref={ref} /> // Error: the expected type comes from property 'ref'.
}
```
=> fix: 完善ref类型推导

packages/taro-components/__tests__/swiper.spec.js, packages/taro-components/src/components.d.ts, packages/taro-components/src/components/swiper/swiper.tsx, packages/taro-components/types/components.d.ts
同步来自 2.x 的修复
- 页面切换 aotuplay 失效
- 多 Swiper 指示器样式错乱
- 循环状态下标错乱
- 非循环状态和微信小程序不一致
=> fix(components): 更新 swiper 的修复

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
组件 LivePlayer 可以渲染子元素，#7552
- 页面切换 `aotuplay` 失效，#6892
- 多 `Swiper` 指示器样式错乱
- 循环状态下标错乱
- 非循环状态和微信小程序不一致
- 删除 iOS 上关于光标的优化，修复原生九宫格键盘输入英文闪烁问题，#7330
- 修复 `Swiper` 和 `Movableview` 的 interface 拼写错误，by @csolin 
- 完善 `pxTransform` 的 d.ts，增加第二个参数 `designWidth`，by @xiaoyao96 
- 修改 `Taro.eventCenter` 的类型推导逻辑，使用 `Events` 定义 `eventCenter` 的逻辑，by @Symind
=> chore(release): publish 3.0.10

packages/taro-mini-runner/src/plugins/MiniPlugin.ts
全局 CLI 和项目里 mini-runner 包引用的 share 包是不同的，这里 instanceof 永不会为 true。
因此改为使用 isSupportRecursive 属性进行判断。
=> fix(mini-runner): 修复 baseLevel 配置不生效的问题

.github/workflows/nodejs.yml, lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
- 修复 baseLevel 配置不生效的问题
- 修复 TabBar 初始化不显示问题，#7290
- 修复 TabBar 自定义路由失效问题
- 修复 mode 默认配置为 hash by @zhaoguoweiLLHC 
- 新增生命周期 onThemeChange、offThemeChange by @baranwang
- 新增 adType、adTheme by @baranwang 
- init 指令冗余提示删除 by @barawang
=> chore(release): publish 3.0.11

packages/taro-cli/src/presets/platforms/ui.ts, packages/taro-cli/src/ui/h5.ts, packages/taro-cli/src/ui/ui.types.ts, packages/taro-cli/src/util/types.ts
=> fix(cli): build ui with plugins

packages/taro-h5/__test__/request-test.js, packages/taro-h5/src/api/request/index.js
将 `Taro.request` 中 `content-type` 的默认值设置为 `application/json`，使其和官方文档中的描述一致，方便开发者使用。
这个 issue 最初报在 #1280, 现在可以使用 https://github.com/yuezk/taro_bug/tree/master/h5_request__contentType 复现
翻了一下代码的历史记录，发现 #1280 被 https://github.com/NervJS/taro/commit/103f7301f1be726ecc5ab2a164ff009cd0ffdb25 这个 commit 修复，但随后又[被 revert 了](https://github.com/NervJS/taro/commit/ae5c42ba05a84378fe30a0319fc02d5df8de8d00)。看了一下修复的方法，发现原来的方案中添加默认的 `content-type` 的位置不对，这会导致给所有的没有设置 `content-type` 的请求设置一个 `application/json` 的 `content-type`，进而会使一些请求出问题。
比较的合适的时机应该当传入的 `data` 是 object，并且没有指定 `content-type` 的时候，给 `content-type` 一个默认值 `application/json`。
=> fix(h5): unify the default content-type

packages/shared/src/components.ts, packages/taro-cli/src/presets/platforms/alipay.ts
1. setting 默认值改为 {}，避免钉钉安卓真机地图定位失败
2. 支付宝中用户的 polygons 属性应该绑定小程序的 polygon 属性
=> fix(shared/cli): 修复 map 组件，fix #7762

packages/shared/src/components.ts, packages/taro-react/src/props.ts, packages/taro-runtime/src/dom/event_target.ts
* 在微信中 Map 组件 setting 属性还是要用 [] 做默认值，用 {} 会报错
* 可以绑定 onRegionChange
=> fix(shared/react/runtime): 修复 map 组件

packages/taro-router/src/history/createHistory.ts
=> fix: wechat wrong location

packages/taro-mini-runner/src/webpack/vue3.ts
修复 Vue3 swiper 渲染问题:
vue-loader 识别出内置组件时，把 tagType 置为 0，表示是内置组件。
不然有可能为 1，也就是为自定义组件，从而导致奇怪的问题。
=> fix(mini-runner):  修复 Vue3 swiper 渲染问题，fix #7481

packages/taro/types/api/files/index.d.ts
将packages\taro\types\api\files\index.d.ts中saveFile下SuccessCallbackResult中的saveFilePath类型从number更改为string
- [√] TypeScript 类型定义修改(Typings)
- [√] 提交到 master 分支
- [√] Commit 信息遵循 [Angular Style Commit Message Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)
- [√] 所有测试用例已经通过
- [√] 代码遵循相关包中的 .eslintrc, .tslintrc, .stylelintrc 所规定的规范
- [√] 在本地测试可用，不会影响到其它功能
- [√] 微信小程序
=> 修复saveFile下的SuccessCallbackResult中的savedFilePath类型定义问题

packages/taro-runtime/src/dsl/react.ts
修复h5端使用下拉后不能触发componentDidShow
=> fix(runtime): 修复h5端使用下拉后不能触发componentDidShow

packages/taro-runtime/src/dom/html/html.ts
修复设置有默认值时的innerHTML时失败的问题
使用 removeChild 代替 textContent = ''，不同点在于：
removChild 的 hydrate 时会重新算 children 节点数据，
而 textContent 会把 cn 置为 []，并不会算 children，又因为 textContent = '' 后 appendChild 增加的数据会因为 performUpdate 的 resetPaths 逻辑被删掉，从而导致了问题。
=> fix(runtime): 修复设置有默认值时的innerHTML时失败的问题，fix #7127

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
- 将 **file-loader** 的 `esModule` 参数默认设置为 **false**
解决 Vue `template` 中不能直接使用图片链接的问题，#7869
开发者在 Taro v3.0 - v3.0.14 中，**require** 资源需要加 `.default`， v3.0.15 之后直接 **require** 即可：
```html
// v3.0.0 - v3.0.14
<Image src="{require('someImage').default}" />
// v3.0.15+
<Image src="{require('someImage')}" />
```
- 支持支付宝小程序 `Swiper` 组件的 `disable-touch` 属性，by @Jetsly 
- 修复 `PickerView` value 设置问题，#7638
- 修复 Vue3 eslint 配置没有发布的问题， #7814
- 修复钉钉小程序地图组件问题，#7762
- 修复 Map 组件 `onRegionChange` 触发失败的问题，#7687
- 修复 Vue3 `onShow` 无法访问 this 中属性的问题，#7771
- 修复获取不到 Taro.env 的问题，#7392
- 修复支付宝小程序 `Swiper` 组件模板多嵌套了一层 `View` 组件的问题
- 修复 Vue3 `Swiper` 组件渲染问题，#7481
- 修复设置带有默认值的 `innerHTML` 时失败的问题，#7127
- 支持 `getBatteryInfo` API，#7846
- 支持 `Swiper` 组件的 `acceleration` 属性，#7801 
- 修复 Taro request API 的 …
=> chore(release): publish 3.0.15

packages/taro-runtime/src/dom/node.ts
修复列表顺序变化时，部分列表项点击事件失效的问题。
`insertBefore` 时会先调用新节点的 `remove` 方法，此时会把此节点从 `eventSource` 删除，从而导致事件因 `getElementById` 找不到对应节点而不触发。
=> fix(runtime): 修复列表顺序变化时，部分列表项点击事件失效的问题，fix #7227

packages/shared/src/template.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap
修复 Swiper 不能嵌套调用的问题，默认可以循环 4 次。
=> fix(shared): 修复 Swiper 不能嵌套调用的问题，fix #7692

packages/taro-h5/src/api/request/index.js
=> fix(h5): 修复 h5 ContentType 重复设置的问题，fix #7972

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
- 修复 swiper 不能嵌套的问题，#8023 
- 同步百度小程序广告组件属性，#8018 
- 修复 `Swiper` 因为 stencil 和 react 兼容导致的问题，#7757 #7976 #6179 
- 修复 `Swiper` 循环状态下当前 Slider 错误问题
- 修复 `Map` 组件 types，by @gjc9620 
- 修复 `TaroEvent` 相关 types，by @SyMind
=> chore(release): publish 3.0.17

docusaurus.config.js
在 2.0.0-alpha.68 中需要设置 dark 模式下 logo 路径，不然 logo 会消失
=> docs(fix)，在 2.0.0-alpha.68 中需要设置 dark 模式下 logo 路径

static/css/custom.css
996像素下侧边导航顶部底色为白色、导致logo不可见，首页顶部导航按钮为黑色，现改为白色
=> docs(fix) 修复在996像素下侧边导航顶部logo不可见，首页顶部导航按钮对比度低的问题

packages/taro-cli/src/presets/platforms/weapp.ts
用户可以通过在config/index.js、config/dev.js或者其它配置文件里面添加projectConfigName: "project1.config.json"
来指定project.config.json的源文件.
可以用于在不同的编译目标里指定不同的appid,实现一份代码同时编译成多个不同appid的小程序，上传给不同的商家使用。
使用场景不限于上面描述的。
目前该改动只支持微信小程序, 未对其它程序类型做支持。
该改动兼容老的逻辑，无副作用。
weapp.ts在拷贝project.config.json文件时检查项目配置里面是否有projectConfigName,如果有，则拷贝projectConfigName指向的文件,没有则拷贝默认的project.config.json文件。
该功能在微信群8讨论过，没有收到异议。
=> feat: 让微信小程序可以自定义project.config.json文件的源文件名

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
- 让微信小程序可以自定义 `project.config.json` 文件的源文件名，by @younthu 
- 缺少 framework 配置时会进行报错提示
- 修复 `onLaunch` 不能正确执行的问题，by @digiaries 
- 补全 `offNetworkStatusChange` API，#8140，by @ZeroTo0ne 
- 修复支付宝小程序 `getStorageSync` 返回 false 值时的判断错误，#8150，by @GoodbyeNJN 
- 支付宝 `Textarea` 增加 `enableNative` 属性，#8138
- 修复 `Video` 不能嵌套组件的问题，#8126
- QQ 小程序同步 `Button` 组件属性，#8150
- 修复 `VirtualList` 报错 "unknown custom element"，#8083
- 补全 `taro-h5` 导出的散装 API，#8189
- 修复初始路由参数未被传递的问题
=> chore(release): publish 3.0.18

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
- 组件 `View` 增加 `catchMove` 属性，提供直接阻止滚动穿透的能力
-  支持支付宝小程序 `getPhoneNumber` API，#8177
- `window` 对象能获取到小程序 `global` 上挂载的属性，by @atzcl 
- 修复短期内重新开启小程序白屏，#8103
- 修复嵌套到第 15 层碰到 `Text` 组件导致子文本节点丢失，#6054
- 补充了 `uploadFile` API 的 timeout、fileName 参数功能，by @zhaoguoweiLLHC 
- 增加 `pageScrollTo` 函数的 `selector` 参数支持，by @zhaoguoweiLLHC 
- 修复 `pageScrollTo` 函数的 `tabbar` 判断方式有误导致的滚动异常问题，by @zhaoguoweiLLHC 
- 修复 `Radio` 组件 `disabled` 属性不生效，#8017，by @ZeroTo0ne
- 修复 `Canvas` 同步方法，by @Ininit 
- 修复 `canvasToTempFilePath` 节点获取，by @Ininit 
- 修复 `Video` methods，by @helsonxiao 
- 修复 `Canvas` & `pull-down-refresh` 相关的问题，#7280 #7072
- `canvasToTempFilePath` 中 `canvasId` 不再是必传项，by @Swordword 
- 调整 Taro 支持的 node 最低版本到 12
- Taro 3 不再支持 `componentWillPreload`、`$preload` API，改为: `Taro.preload()`
- …
=> chore(release): publish 3.0.19

packages/taro-components/virtual-list/react/createListComponent.js
relative 布局模式下，itemSize 和实际子节点高度不一致会导致显示错误
=> fix: virtual-list relative size

packages/taro-runtime/src/bom/window.ts
京东、支付宝小程序没有 global，会导致 React 必须的 Date、setTimeout 对象没有赋值在 global 上。
因此作一个兜底，当 window 没有这些对象时，直接赋值。
=> fix(runtime): 补全 window 对象的关键属性, fix #8327

packages/taro-rn-transformer/src/app.ts, packages/taro-rn/src/api/index.ts, packages/taro-router-rn/src/navigationBar.ts, packages/taro-router-rn/src/provider.ts, packages/taro-router-rn/src/router.ts, packages/taro-router-rn/src/tabBar.ts, packages/taro-router-rn/src/utils/index.ts, packages/taro-router-rn/src/view/Badge.tsx, packages/taro-router-rn/src/view/TabBar.tsx, packages/taro-router-rn/src/view/TabBarItem.tsx, packages/taro-runtime-rn/package.json, packages/taro-runtime-rn/src/app.ts, packages/taro-runtime-rn/src/current.ts, packages/taro-runtime-rn/src/index.ts, packages/taro-runtime-rn/src/page.ts, packages/taro-runtime-rn/src/types/index.ts, packages/taro-runtime-rn/src/utils.ts
- config 中增加让 rn 导航配置透传
- 增加 rn pageScrollTo，start/stopPulldown 相关 API
- 解决 rn 全局 enablePullDownRresh 兼容性问题
=> config 中增加让 rn 导航配置透传 && 解决 rn 兼容性问题 && 增加相关 api

versioned_docs/version-3.x/react-native.md
=> fix: 修复文档【RN端开发注意】失效链接

packages/taro-mini-runner/src/plugins/MiniPlugin.ts
修复 app 样式时，重复 concat app css 的问题
before:
```sass
// app css
@import base
// app css
@import taro
```
after
```sass
// app css
@import base
@import taro
```
=> fix(mini-runner): 修复 app 样式打包错误的问题

packages/taro-runtime/src/bom/raf.ts
=> fix(runtime): 在微信中clearTimeout要绑定global，fix #7749

packages/taro-mini-runner/src/webpack/build.conf.ts
修复 Vue3 运行时报错：
Vue3 使用了 `Element` 对象，小程序环境使用 `ProvidePlugin` 直接替换为 `TaroElement`
=> fix(mini-runner): 修复 Vue3 运行时报错，fix #8426

packages/taro-runtime/src/dsl/common.ts
微信小程序 `2.11.2` 起支持 [虚拟化组件节点](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E8%99%9A%E6%8B%9F%E5%8C%96%E7%BB%84%E4%BB%B6%E8%8A%82%E7%82%B9)，在 `options` 中将 `virtualHost` 设置为 `true` 可以不渲染自定义组件本身
这样就可以解决类似于 #7349 的问题，样式不会被出现的夹层影响
=> fix: 修复超过一定层数出现一个自定义组件夹层影响样式的问题 #7349

packages/shared/src/template.ts, packages/shared/src/utils.ts, packages/taro-mini-runner/src/webpack/vue3.ts, packages/taro-runtime/src/dom/event.ts, packages/taro-runtime/src/dsl/react.ts, packages/taro-runtime/src/dsl/vue3.ts, packages/taro-runtime/src/reconciler.ts
1. 修复 react、vue、vue3 都不能使用 vant 的 kebab-case 事件的问题
2. 修复 vue3 使用第三方组件时事件绑定错误的问题
=> fix(runtime): 修复使用vant时一系列问题，fix #8407 #8242 #8364

packages/taro-runtime/src/dsl/instance.ts, packages/taro-runtime/src/dsl/react.ts
同步 3.1 修改，让小程序 app 对象上可以挂载自定义属性。
用法：
```js
import { Component } from 'react'
import './app.scss'
class App extends Component {
taroGlobalData = {
x: 1,
userInfo: {
name: 'jack',
age: 20
},
foo () {
console.log('foo')
}
}
// this.props.children 是将要会渲染的页面
render () {
return this.props.children
}
}
export default App
```
=> feat(runtime): 同步 3.1 修改，让小程序 app 对象上可以挂载自定义属性

static/css/custom.css
修复网站字体.
字体名带空格时可以用双引号括起来避免歧义, 但多个字体放在一个双引号里意义不同, 浏览器会认为是一个名字很长的字体.
**Before**
```css
--ifm-font-family-base: "-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji";
```
**After**
```css
--ifm-font-family-base: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
```
=> docs: fix font family base

packages/taro/types/api/route/index.d.ts
navigateTo.success 的回调入参类型定义，缺少 eventChannel，在此补全
=> fix(type): navigateTo.success with eventChannel

packages/taro-runtime/src/dom/event.ts, packages/taro-runtime/src/dsl/react.ts, packages/taro-runtime/src/reconciler.ts
修复 react 事件回调里没有 batchedUpdates 的问题
=> fix(runtime): 修复react事件回调里没有合并更新的问题，fix #8516

packages/taro-components/src/components/video/video.tsx
fix(h5):修复Video组件ref为空而无法暂停播放的问题(NervJS#8550)
=> fix(h5):修复Video组件ref为空而无法暂停播放的问题(NervJS#8550)

packages/taro-mini-runner/src/utils/logHelper.ts
当使用 `dev:weapp` 调试小程序时, 多次修改代码并保存后 console 里面只会有一大串 `编译成功` , 并不能确定最后一次更改是否生效.
=> feat(mini-runner/logHelper): 编译成功时输出时间

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
- 增加原生混合 Taro 的编译模式
- 引用原生组件支持 alias，#8472
- CLI 插件增加 `onCompilerMake` 钩子用于获取 Webpack `Compilation` 对象
- 修复解析 html 不显示换行问题，#7003 #8549，by @mosqlee
- 修复 `Video` 组件 ref 为空而无法暂停播放的问题，#8550，by @wangjuerong
- 编译提示文案中一并输出时间，by @kdxcxs
=> chore(release): publish 3.0.25

packages/taro-runtime/src/dom/element.ts
修复pure-view设置属性后不能变为static-view的问题
=> fix(runtime): 修复pure-view设置属性后不能变为static-view的问题

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
- 修复 Vue3 页面 `onShow` 生命周期的触发时机，#8326，by @koalaink 
- 修复 `pure-view` 在设置属性后不能改变为 `static-view` 的问题
- 补全支付宝 `Input` 组件的 `enableNative` 属性，#7226
- 补全 `previewMedia` API，#8594
- 允许 `live-pusher` 组件设置子组件，#8490
- 修复 `useRouter` 中获取的 `router.path` 字段为空字符串的问题，#7296，by @ZeroTo0ne 
- 修复使用 `pageScrollTo` 将 `scrollTop` 设置为 0 会报错的问题，#8408，by @jin-yufeng
- 修复使用 taro-ui 编译报错的问题
=> chore(release): publish 3.0.26

packages/taro-router/src/router/route.tsx
修复#8238，实际上调用`Taro.redirectTo`和`Taro.reLaunch`方法都会触发若干次`componentDidShow`钩子。
=> fix(router): 修复Taro.redirectTo和Taro.reLaunch方法导致多次componentDidShow的问题

packages/taro-components-rn/src/components/Video/index.tsx
根据 [expo-av](https://docs.expo.io/versions/latest/sdk/video/) 的文档描述，Video 的 onError 参数是一个字符串。原代码中错误的将其当做对象处理，导致报错。这个 PR 修复了这个问题。
无
=> fix(components-rn): 修复 rn 下 video onError 报错

lerna.json, packages/babel-plugin-transform-taroapi/package.json, packages/babel-preset-taro/package.json, packages/eslint-config-taro/package.json, packages/eslint-plugin-taro/package.json, packages/postcss-plugin-constparse/package.json, packages/postcss-pxtransform/package.json, packages/shared/package.json, packages/taro-api/package.json, packages/taro-cli/package.json, packages/taro-components/package.json, packages/taro-extend/package.json, packages/taro-h5/package.json, packages/taro-helper/package.json, packages/taro-loader/package.json, packages/taro-mini-runner/package.json, packages/taro-react/package.json, packages/taro-router/package.json, packages/taro-runner-utils/package.json, packages/taro-runtime/package.json, packages/taro-service/package.json, packages/taro-webpack-runner/package.json, packages/taro-with-weapp/package.json, packages/taro/package.json, packages/taroize/package.json
- 修复 `VirtualList` 组件调用 `scrollTo` 后回到顶部的问题，#8560，by @GitaiQAQ
- 补全云托管调用 `wx.cloud.callContainer` API，by @logix-o
- 修复百度小程序下生成 **.frameworkinfo** 文件问题
- 修复 `Taro.pageScrollTo` 在参数 `duration = 0` 时无法跳转的问题，by @CallMeXYZ
=> chore(release): publish 3.0.28

packages/taro-runtime/src/dom/style.ts
修复 Vue3 为 style 设置以驼峰形式命名的 css 变量时，解析错误的问题
=> fix(runtime): 修复Vue3 style设置css变量解析错误问题，fix #8736

packages/taro-components/types/common.d.ts
实际测试在H5和微信小程序中，changedTouches的类型都是`Array<ITouch>`，原代码使用的`Array<CanvasTouch>`与实际不符。
从https://github.com/NervJS/taro/issues/5592 中 @ZakaryCode 提到的类型同步自https://github.com/wechat-miniprogram/api-typings/blob/master/types/wx/lib.wx.event.d.ts 的`TouchEvent`也可以看出`changedTouches`应和`touches`类型一致且都为`Array<ITouch>`（在微信小程序声明文件中实际为`Array<TouchDetail>`，其中`TouchDetail`等于Taro声明文件中的`ITouch`）。
=> fix(types): 修复ITouchEvent里的changedTouches属性的类型错误

packages/taro-rn/package.json, packages/taro-rn/src/lib/getLocation/index.ts
因为国内很多安卓机不支持 GMS, 导致 expo-location 无法正常获取位置,现改为
调用 @react-native-community/geolocation
=> fix(taro-rn): 修复 getLocation 在安卓上报错

packages/taro-runtime/src/dom/event.ts, packages/taro-runtime/src/utils/index.ts
修复阻止跨代组件事件冒泡失败的问题，fix #8757 #8605 
=> fix(runtime): 修复阻止跨代组件事件冒泡失败的问题，fix #8757

packages/taro/types/api/open-api/user-info.d.ts
=> types: getUserProfile

packages/taro-h5/src/api/unsupportedApi/index.js
目前直接将小程序转为 H5，`Taro.hideHomeButton` 调用会导致报错 
```
"export 'hideHomeButton' (imported as '_hideHomeButton') was not found in '@tarojs/taro'
```
=> feat(h5): hideHomeButton 提示不支持

packages/taro-mini-runner/src/webpack/build.conf.ts, packages/taro-runtime/src/bom/document.ts
自 `vue@3.0.8` 起，`@vue/runtime-dom` 开始支持将 app 挂载到 svg 容器（[runtime-dom: support mounting app to svg container](https://github.com/vuejs/vue-next/pull/2929)）。这会导致 Taro Vue3 框架的 vue 依赖更新到 `3.0.8` 后，出现 `SVGElement is not defined` 的错误。
本 PR 主要将 `SVGElement` 指向 `TaroElement`, 并在 `taro-runtime/src/bom/document.ts ` 中添加 `createElementNS` 方法，以实现对 `SVGElement` 的伪支持。
=> fix(runtime): SVGElement not defined since vue@3.0.8

packages/taro-extend/src/jquery/zepto.js
=> fix(extend): 修复小程序使用 $.width() 获取不到正确宽度的问题

packages/taro-mini-runner/package.json
=> fix(mini-runner): 修复 css 单位转换出错的问题，fix #8089

packages/taro-components/src/components/input/input.tsx
`Input` 组件的 `type` prop 目前的类型是 `"number" | "text" | "idcard" | "digit" | undefined`，当传入 `undefined` 时，初次 render 效果符合预期，但在组件更新 rerender 时会抛出 `unexpected type` 错误（如图）：
在排查后发现：初次渲染效果是正常的，是因为 `Input` 组件实例的 `type` prop 被设置了默认值；而在 rerender 的时候，`Input` 内部对新旧 props 进行对比，认为 type=undefined 是 newVal 并将原有的默认值 `"text"` 置为 `undefined`，导致后续 `getTrueType` 方法抛出了错误。
=> fix(components): taro input unexpected type

packages/taro-cli/templates/default/project.tt.json
默认模版中，增加字节小程序的配置文件 `project.tt.json`，避免字节小程序 IDE 打开项目失败
=> fix(cli): 默认模版增加头条小程序的配置文件

packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/__tests__/index.spec.js, packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/src/index.ts
fix(jsx-to-stylesheet): 修复当只有 css module 样式时表达式报错
1. 修复当只有 css module 样式时表达式报错
=> 修复 RN 端当只有 css module 样式时表达式报错

.github/PULL_REQUEST_TEMPLATE.md, packages/eslint-config-taro/index.js, packages/taro-components-react/package.json, packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/nerv.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap, packages/taro-weapp/src/components.ts, packages/taro-weapp/types/components.d.ts
- 修复兼容性组件库引用报错的问题
- 移除微信端 `Input` 组件废弃属性 `auto-focus`，fix #9102 
- 修复使用 TS 时出现 ESLint 报错 `no-shadow`，fix #9089 
=> fix(components-compact): 修复兼容性组件库引用报错的问题

packages/taro-swan/src/component.js
- 修复百度小程序 componentDidShow 无法获取props #8537
#8537
=> fix(swan):百度小程序componentDidShow 获取props为空

packages/taro-runtime/src/dsl/common.ts
fix(runtime): 修复多次跳转相同参数的同一页面时生命周期不触发的问题，fix #8874
=> fix(runtime): 修复多次跳转相同参数的同一页面时生命周期不触发的问题，fix #8874

packages/taro-mini-runner/src/webpack/vue.ts
修复 vue2 出现多余空格文本节点的问题，fix #8884
=> fix(mini-runner): 修复 vue2 出现多余空格文本节点的问题，fix #8884

packages/taro-runtime/src/dom/event_target.ts, packages/taro-runtime/src/reconciler.ts
runtime 增加 `onAddEvent` 钩子，支持在 `addEventListener` 的时刻插入逻辑。
=> feat(runtime): 增加 onAddEvent 钩子

packages/taro-mini-runner/src/webpack/chain.ts, packages/taro-webpack-runner/src/util/chain.ts
=> fix: sass-loader @import 不带scss后缀的文件时编译报错问题

packages/taro-components/src/components.d.ts, packages/taro-components/src/components/swiper/swiper.tsx, packages/taro-h5/src/api/image/index.js, packages/taro-h5/src/api/image/previewImage.js
previewImage API，会先等所有大图都加载完毕才会展示出预览的界面，如果有图片特别大或者网速慢的情况下，实际体验极差
=> fix(h5): previewImage 加载图片改为异步

packages/taro-h5/src/api/createSelectorQuery/index.js
修复getPropertyValue拿不到值时再直接用property获取style的属性值，实际上应该还会有其他的property拿不到的case，通过getPropertyValue拿不到时，直接通过属性property访问获取。
=> fix(h5): 修复getPropertyValue拿不到style属性值

packages/taro-api/src/index.js, packages/taro-api/src/tools.js
修复获取不到 `Taro.preload` 预加载数据的问题，fix #9175
=> fix(api): 修复获取不到 Taro.preload 预加载数据的问题，fix #9175

packages/taro-router-rn/src/rootNavigation.ts, packages/taro-runtime-rn/src/instance.ts, packages/taro-runtime-rn/src/page.ts
0. 修复 getCurrentPages 页面实例错误bug
1. 增加options参数
=> fix(runtime-rn): 修复 getCurrentPages 页面实例错误bug

packages/taro-mini-runner/package.json, packages/taro-mini-runner/src/webpack/chain.ts, packages/taro-webpack-runner/package.json, packages/taro-webpack-runner/src/util/chain.ts
当前 fibers 不再兼容新版本 nodejs，且 sass-loader 已不再推荐使用 fibers 来改善性能。所以 fibers 的依赖可以移除。
[https://github.com/NervJS/taro/issues/9291](url)
=> fix: 移除sass-loader 中不必要的 fibers 依赖 #9291 #9322

packages/shared/src/events.ts, packages/shared/src/utils.ts, packages/taro-alipay/src/runtime-utils.ts, packages/taro-alipay/types/runtime-utils.d.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/nerv.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap, packages/taro-runtime/src/__tests__/event.spec.js, packages/taro-runtime/src/reconciler.ts, packages/taro-runtime/src/utils/index.ts
小程序平台对于冒泡事件有明确的定义，对于非冒泡事件不需要在祖先节点批量触发。fix 9344, 9316
详见微信小程序事件系统文档： https://developers.weixin.qq.com/miniprogram/dev/framework/view/wxml/event.html
=> fix(runtime): 区分冒泡事件，对于非冒泡事件不需要在祖先节点批量触发

packages/taro-components/src/components/image/style/index.css
scaleToFill模式为【缩放模式，不保持纵横比缩放图片，使图片的宽高完全拉伸至填满 image 元素】，object-fit属性值应为fill
h5编译的image组件scaleToFill模式为【缩放模式，不保持纵横比缩放图片，使图片的宽高完全拉伸至填满 image 元素】，object-fit属性值应为fill
- [*] 错误修复(Bugfix) issue id #
- [*] Web 平台（H5）
=> fix: taro-img__mode-scaletofill修改为fill

packages/taro-cli/src/presets/platforms/rn.ts, packages/taro-router-rn/src/rootNavigation.ts, packages/taro-router-rn/src/router.ts, packages/taro-router-rn/src/utils/index.ts, packages/taro-runtime-rn/src/app.ts
0. platform 默认值设置为 android
1. 透传react-navigation参数
2. rn 启动支持动态传入参数,跳转指定页面
=> rn 启动支持动态传入参数,跳转指定页面，增加透传react-navigation参数

packages/taro-runtime/src/dom/form.ts
修复 Vue2 Input 组件数据绑定问题，fix #9360
=> fix(runtime): 修复 Vue2 Input 组件数据绑定问题，fix #9360

packages/babel-preset-taro/package.json
@tarojs/taro-rn 依赖至于 dependencies 中会导致rn相关依赖被安装。
移动至 devDependencies 中，因为cli在启动rn时会安装 @tarojs/taro-rn 固不影响使用。
=> fix: 将taro-rn依赖移到devDependencies

packages/taro-components/src/components/video/utils.js
fix(h5): 修复h5 Video组件在为获取到视频时长时(time可能为null或者undefined)显示NaN:NaN问题
=> fix(h5): 修复h5 Video组件在为获取到视频时长时(time可能为null或者undefined)显示NaN:NaN问题

packages/babel-preset-taro/package.json, packages/babel-preset-taro/yarn.lock, packages/taro-components-rn/package.json, packages/taro-components-rn/yarn.lock, packages/taro-rn-runner/package.json, packages/taro-rn-runner/src/index.ts, packages/taro-rn-runner/yarn.lock, packages/taro-rn-style-transformer/src/index.ts, packages/taro-rn-supporter/package.json, packages/taro-rn-supporter/yarn.lock
RN各版本差异较大，next分支会以最新版本的兼容为主，其他版本提供兼容方案。
注意：
此改动会影响 RN 0.60-0.63版本。
RN 0.60-0.63版本，需加入resolutions（package.json），将metro版本固定为  0.58
```json
{
"resolutions": {
"metro": "^0.58.0",
"metro-cache": "^0.58.0",
"metro-config": "^0.58.0",
"metro-core": "^0.58.0",
"metro-react-native-babel-transformer": "^0.58.0",
"metro-resolver": "^0.58.0"
}
}
```
> 相关知识学习：
> https://developer.mozilla.org/zh-CN/docs/Tools/Debugger/How_to/Use_a_source_map
> 
>  https://github.com/react-native-community/cli/blob/master/docs/commands.md#--sourcemap-output-string
```
{
rn: {
output: {
iosSourceMapUrl: '',
iosSourcemapOutput: '',
iosSourcemapSourcesRoot: '',
androidSourceMapUrl: '',
androidSourcemapOutput: '',
androidSourcemapSourcesRoot: ''
}
}
}
```
**这个 PR …
=> feat(rn): udpate metro & @react-native-community/cli version

packages/taro/types/api/cloud/index.d.ts
close https://github.com/NervJS/taro/issues/9455
=> fix(types): 自 TypeScript 4.3.2 起需为接口字段显式指定类型

packages/taro-runtime/src/__tests__/dom.spec.js, packages/taro-runtime/src/dom/node.ts
`vue@3.1.2` 对静态内容插入逻辑进行了[更改](https://github.com/vuejs/vue-next/commit/4de5d24aa72f6bc68da967ead330147032983e30)，其中使用了 Taro Runtime 尚未支持的 `insertAdjacentHTML` 方法。
本 PR 为 `TaroNode` 新增了 `insertAdjacentHTML` 方法，以适配 `vue@^3.1.2`。  
=> feat(runtime): support insertAdjacentHTML

packages/taro-components/package.json, packages/taro-components/types/Button.d.ts, packages/taro-components/types/View.d.ts, packages/taro-components/yarn.lock
RN端hoverStyle的原有类型是string，但hoverStyle的写法和 style 类似，这导致了项目中不必要的类型检查报错。
本PR修复了hoverStyle的类型为StyleProp，使类型更加准确，减少了不必要的报错。
第二次pr，更新了@types/react-native的版本为0.64.10
=> fix(type): 修复RN端hoverStyle类型问题

packages/taro-components-rn/package.json, packages/taro-components-rn/yarn.lock
=> chore(deps): [security] bump react-native-webview from 10.10.2 to 11.6.4

packages/taro-runtime/src/dsl/vue3.ts
修复 Vue3 生命周期触发问题，fix #9614
Vue3 `resolveMergedOptions` 函数里有 cache 逻辑，用户编写的页面对象的 mixins 只会被 merge 一次。
因此反过来，每次打开新页面时，使用新对象进行渲染，用户编写的页面对象作为 mixin。
虽然 Vue3 使用 WeakMap 实现 cache，还需要关注是否会导致内存泄漏。
=> fix(runtime): 修复 Vue3 生命周期触发问题，fix #9614

packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap, packages/taro-swan/src/program.ts, packages/taro-swan/src/template.ts, packages/taro-swan/types/template.d.ts
暂时移除 `<input>` 的 `cursor`、`section-start`、`section-end` 属性
=> fix(swan): 修复 input 光标跳动问题

packages/taro-runtime/src/dom-external/index.ts
自定义包依赖 `@tarojs/components` `3.3+`，
运行 jest 测试时提示
`ReferenceError: ENABLE_INNER_HTML is not defined`
需自行加上全局变量配置
```json
"jest": {
"globals": {
"ENABLE_INNER_HTML": true,
"ENABLE_ADJACENT_HTML": true,
"ENABLE_SIZE_APIS": true
}
},
```
或者由 taro 做兼容
---
参考例子
增加配置前，提示错误
https://github.com/miaoxing/mxjs-m-ret/runs/3044454333?check_suite_focus=true
增加配置后，运行成功
https://github.com/miaoxing/mxjs-m-ret/runs/3045186096?check_suite_focus=true
=> fix: 解决 `ENABLE_INNER_HTML is not defined`

packages/taro-components/h5/vue3/createFormsComponent.js, packages/taro-components/src/components/input/input.tsx
修复 Vue3 使用 `input` 组件时 `v-model` 失效的问题，fix #9775
=> fix(components): 修复 Vue3 使用 input 组件时 v-model 失效的问题，fix #9775

packages/taro-mini-runner/src/__tests__/fixtures/mini-split-chunks/src/packageA/detail/index.jsx, packages/taro-mini-runner/src/__tests__/fixtures/mini-split-chunks/src/packageB/list/index.jsx, packages/taro-mini-runner/src/__tests__/mini-split-chunks.spec.ts, packages/taro-mini-runner/src/plugins/MiniSplitChunksPlugin.ts
1、分包提取插件不处理external module
2、修复没有分包配置时报'getCacheGroups' of null的错误
3、格式化path使用helper内的normalizePath方法
=> fix(mini-runner): 修复external module导致的错误 (#9862)

packages/taro-rn/src/lib/network.ts
问题：`Taro.onNetworkStatusChange` 和 `Taro.offNetworkStatusChange` 表现形式与文档不一致，且 `Taro.offNetworkStatusChange` 无效。
解决：对事件回调机制进行了重构。
=> refactor(rn): 重构网络状态回调机制

packages/taro-rn/src/lib/keyboard.ts, packages/taro/types/api/ui/keyboard.d.ts
1、`Keyboard.removeListener` 已废弃，故改为 `removeAllListeners` 实现;
2、修改 `Keyboard` 相应的类型文件；
=> refactor(rn): replace deprecated keyboard api

packages/taro-runtime/src/__tests__/html.spec.js, packages/taro-runtime/src/dom-external/inner-html/style.ts
=> fix(runtime): 修复对 style 标签的解析问题，fix #9885

packages/taro-router/src/router.ts, packages/taro-runtime/src/dsl/common.ts, packages/taro-runtime/src/dsl/instance.ts
修复 Vue3 在 H5 下 `onPullDownRefresh` 不触发的问题，fix #10103
=> fix(h5): 修复 Vue3 在 H5 下 onPullDownRefresh 不触发的问题，fix #10103

packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap, packages/taro-swan/src/runtime-utils.ts
修复百度小程序中 `Map` 组件不触发 regionchange 的问题，fix #10185
=> fix(swan): 修复百度地图组件不触发 regionchange 的问题，fix #10185

packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/__tests__/index.spec.js, packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/jest.config.js, packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/src/index.ts
=> feat(rn-stylesheet): 修复 css module 条件判断表达式不生效问题

packages/taro-components-react/src/components/swiper/index.tsx
修复轮播销毁时的报错问题
Uncaught TypeError: Cannot read properties of undefined (reading 'children')
at Swiper.swiper_loopDestroy [as loopDestroy]
=> fix(swiper): 修复轮播销毁时的报错问题

packages/taro-h5/src/api/createAnimation/index.js
微信小程序下 createAnimation 样式权重是 行内style
h5下 createAnimation 样式权重是 属性选择器
h5下权重过低，无法覆盖初始样式
在生成的样式后增加 `!important`
=> fix(h5): 修复 h5 下 createAnimation 创建的样式权重过低的问题，fix #10245

packages/taro-rn-style-transformer/__tests__/index.spec.js, packages/taro-rn-style-transformer/src/transforms/sass.ts, packages/taro-rn-style-transformer/src/utils/index.ts, packages/taro-rn-style-transformer/src/utils/lessImport.ts
fix(rn-style-transformer): 修复样式文件不能引入以 npm 包形式引入问题
1. 解决样式文件里面引入 npm 包文件失效问题
2. less importer 插件重写，更合理的给 less 文件 import url 变基
=> fix(rn-style-transformer): 修复样式文件不能引入以 npm 包形式引入问题

packages/taro-transformer-wx/src/render-props.ts
在使用 `render props` 这一特性的时候，发现获取的参数值常常为 `undefined` ，偶尔又能正常获取值。观察编译后的小程序代码发现是父组件所 `listen` 和子组件 `emit` 的事件名称不一致导致，父组件修改了部分代码，热更新后更加明显的观察到这一问题。假如多个父组件使用同一子组件的 `render props` ，事件名称也会出现不一致。
在父组件注入监听事件时，先查询 `renderPropsMap` 中以**子组件名称+属性名称**为 `key` 的事件名称是否存在，假如已存在不再重新生成，保证每次编译父子组件事件名称保持一致。
=> fix(2.x): 微信小程序父子组件`render props`编译后事件名称不一致

packages/taro-components-rn/__tests__/__snapshots__/richText.spec.tsx.snap, packages/taro-components-rn/src/components/RichText/PropsType.tsx, packages/taro-components-rn/src/components/RichText/index.tsx
RichText 组件默认为自适应宽高
并默认添加viewport，与小程序和h5一致
```html
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
```
=> feat(rn): add auto width & height for RichText

packages/taro/types/api/ui/interaction.d.ts
微信小程序的 Toast 新增了 [error 类型](https://developers.weixin.qq.com/miniprogram/dev/api/ui/interaction/wx.showToast.html)，可以在类型定义中加上此类型，以防在编写代码时出现 ts error。
=> chore: add error icon type for toast

packages/taro-harmony/src/components/components-harmony/radio/index.hml, packages/taro-harmony/src/components/components-harmony/radio/index.js
=> fix(harmony): input组件用作radio时，同一group的item，name必须相同，这里使用groupId作为name

docs/plugin-mini-ci.md, versioned_docs/version-3.x/plugin-mini-ci.md
修改CI插件示例代码中的 "微信小程戏" 为 "微信小程序"
=> docs: 修复ci插件使用示例文案错误

packages/taro-alipay/src/create-component.js, packages/taro-jd/src/create-component.js, packages/taro-qq/src/create-component.js, packages/taro-quickapp/src/create-component.js, packages/taro-swan/src/create-component.js, packages/taro-tt/src/create-component.js, packages/taro-weapp/src/create-component.js
修复事件回调中调用 `preventDefault` 后 `defaultPrevented` 值不存在的问题。
事件处理中模拟了 `preventDefault` 方法，但实现仅仅是一个空方法，在此基础上增加了对 `defaultPrevented` 的模拟，让其更符合规范。虽然实质上不会发生什么（小程序还不支持默认行为的阻止），但自定义组件的封装能基于 `defaultPrevented` 来决定自定义默认行为的调用。
=> fix: 修复事件调用 preventDefault 后 defaultPrevented 值不存在的问题

packages/taro-components-rn/src/components/Swiper/carousel.tsx
父组件导致组件重新渲染，导致UNSAFE_componentWillReceiveProps 被调用，进而导致swiper调回初始化位置
=> fix(rn): swiper selectIndex updated when props change

packages/taro-components-rn/src/components/Input/index.tsx, packages/taro-components-rn/src/components/Swiper/PropsType.tsx, packages/taro-components-rn/src/components/Swiper/carousel.tsx
0. Android input default padding 0
1. swiper 1 item bug
2. swiper current > count -1 bug
=> fix: swiper 1 itme & input padding

packages/taro/types/api/base/weapp/app-event.d.ts
=> fix(types): 事件回调类型 fix #10954

packages/taro-runtime-rn/src/compute.ts
1. pxTransform 计算值与小程序端保持统一，https://github.com/NervJS/taro/blob/37075f081e55481347bd0bbd606d367d2215e842/packages/postcss-pxtransform/index.js#L52
=> fix(rn): 修复 pxTransform api 计算值与小程序端不统一

packages/taro-router/src/animation.ts
给taro_page样式增加z-index: 0，如果没有此属性，在切换页面动画过程中，下层页面如果有设置了z-index的元素，会有层级覆盖问题
=> fix(h5): taro_page z-index

docs/react-overall.md, versioned_docs/version-3.x/react-overall.md
修复文档中跳转 mini.debugReact 配置项的链接错误
=> fix: 修复跳转mini.debugReact链接错误

packages/taro-plugin-vue-devtools/src/index.ts, packages/taro-service/package.json, packages/taro-service/src/Config.ts
修复 Vue DevTools 失效的问题，fix #11095
- 使用 `webpack-merge` 代替 `lodash merge` 去合并用户的 webpack 配置，在对数组的合并上（如 merge([B,C], [A]) ），前者是 [B,C,A]，后者是 [A,C]
- Vue DevTools 需要用到 `node.contains` 方法
=> fix(vue-devtools/service): 修复 vue devtools 失效的问题，fix #11095

packages/taro-components-rn/src/components/Picker/date.tsx
对日期格式的支持，Hermes 与 jsc 不一致。改为都支持的模式。
closes #11166
=> fix(rn): date picker format error

packages/taro-rn/package.json, packages/taro-rn/src/lib/chooseImage/index.ts, packages/taro-rn/src/lib/previewImage/index.tsx, packages/taro-router-rn/src/router.ts, yarn.lock
修复android 11加载相册一直loading
closes #11167
=> fix(rn): image picker loading on android 11

packages/css-to-react-native/__tests__/index.spec.js, packages/css-to-react-native/src/index.js
1. 修复关闭scalable value 有多个单位时只有第一个值不转换成 scalePx2dp
=> 修复关闭scalable value 有多个单位时只有第一个值不转换成 scalePx2dp

packages/taro-router/src/router/page.ts
- [query-string](https://github.com/sindresorhus/query-string#decode) 这个库 decode 默认是 true，H5 不进行 decode 与小程序的 query 保持一致
=> fix(h5): query 不进行 decode

packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap, packages/taro-plugin-vue3/src/runtime/connect.ts
=> feat(vue3): 支持vue3类组件

packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/__tests__/index.spec.js, packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/src/index.ts
在rn端的babel-plugin-transform-react-jsx-to-rn-stylesheet中， 会将className解析为style，在某些场景下可能产生问题。
例如：
```typescript
function demo () {
return <ChildComp className="header1 header2" style={{color: ‘black’}}/>
}
function ChildComp ({ style }) {
// 在rn端style为array类型，解构操作会导致样式失效。
return <View style={{...style, color:  'red'}}/>
}
```
当子组件需要操作父组件传递的style时， 在rn端中style的类型为array，其他端中为object，如果不对rn做单独处理会导致样式失效。（较难排查）
该变更将style转为object，保持各端操作的一致性。
=> feat(babel-plugin-transform-react-jsx-to-rn-stylesheet): 当style为array，需要转换为object #11476

packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap, packages/taro-plugin-vue3/src/runtime/connect.ts
修复 Vue3 使用原生组件时事件触发失败的问题，#9794
examples: `<com type='primary' @my-event='handleClick'></com>`
Vue3 会 `addEventListener('my-event')`，因此触发时不需要去掉小程序 e.type 中的 `-`
=> fix(vue3): 修复 Vue3 使用原生组件时事件触发失败的问题，#9794

packages/taro-weapp/src/program.ts, packages/taro-weapp/src/template.ts
让 `<Input>` 支持 `<KeyboardAccessory>`，fix #11510
=> feat(weapp): 让 Input 支持 KeyboardAccessory，fix #11510

packages/taro-h5/src/api/media/image/chooseImage.ts
=> fix(taro-h5): chooseImage 支持 sourceType

packages/taro-h5/src/api/media/image/getImageInfo.ts
=> fix(h5): getImageInfo missing path value

packages/taro-components-rn/src/components/Input/PropsType.tsx, packages/taro-components-rn/src/components/Input/index.tsx, packages/taro-components/types/Input.d.ts
1. 处理 input 组件 ts 错误
2. 完善 input 组件 placeholder Color 属性设置，支持 `placeholderTextColor` 和 `placeholderStyle` 两种方式
=> refactor(rn): 实现 rn 端 input 组件中 placeholder color 的设置

packages/taro-mini-runner/src/plugins/MiniPlugin.ts
问题：
1、独立分包页面的 page构造器 被重复调用（分别被主包和子包的 runtime.js 调用），报页面重复注册异常
2、独立分包页面 base.wxml 依赖引用异常
问题场景：小程序独立分包
问题原因：
1、独立分包和主包配置了相同的 jsonpFunction ，存在命名冲突，导致独立分包页面初始化 Page() 重复执行
2、独立分包页面的 base.wxml  依赖错误引用主包的 base.wxml 路径，而独立分包无法引用主包资源
问题修复：
1、独立分包的 jsonpFunction 增加包名标识
2、base.wxml  依赖路径修正为引用独立分包内的 base.wxml
=> fix(mini-runner): 修复独立分包场景下 jsonpFunction 配置和 base.wxml 引用路径问题

packages/taro/types/taro.config.d.ts
目前最新版本的微信小程序的`subPackages`配置项是支持`plugins`选项，而目前taro的全局配置类型文件是没有给`subPackages`配置加`plugins`属性，导致在ts环境下配置会提示类型错误，这个pr解决了这个问题，加上了这个选项类型声明
=> feat: add global config option: subpackages support plugins config

packages/eslint-config-taro/package.json, packages/taro-cli/templates/default/package.json.tmpl, yarn.lock
更新 eslint 插件的版本以兼容 eslint8
主要是 `@typescript-eslint/eslint-plugin@^4` 和 eslint8 不兼容需要升级到 `5`。而 `eslint-plugin-vue` 是顺手升级的。
=> chore(eslint): 更新 eslint 插件的版本以兼容 eslint8

packages/taro-rn/src/lib/setClipboardData/index.ts, packages/taro-router-rn/src/router.tsx
0. 修复生产环境下，iOS后退 crash https://github.com/react-navigation/react-navigation/issues/9015
1. setClipboardData 提示修改
=> fix: iOS screen is frozen when swiping to previous page

packages/taro-plugin-vue3/src/index.ts, packages/taro-plugin-vue3/src/webpack.h5.ts, packages/taro-plugin-vue3/src/webpack.mini.ts
允许用户给插件 `@tarojs/plugin-framework-vue3` 传递配置项，以更改 `vue-loader` 配置项.
同时，调整 `compilerOptions` 参数的配置，优先读取 `vueLoaderOption` 内的参数:
```js
const config = {
plugins: [
[
"@tarojs/plugin-framework-vue3",
{
mini: {
compilerOptions: {  // 兼容旧版配置
hotReload: false
},
},
vueLoaderOption: {
reactivityTransform: true,
compilerOptions: {  // 优先读取
hotReload: true
},
},
},
],
],
}
```
=> feat(vue3): 允许用户对vue-loader传入配置项

packages/taro-components/src/components/view/view.tsx
解决原有处理stencil slot与react render冲突时删除注释节点引起的vue中语法失效的问题，改为判断是否是stencil插入的节点，并将其中的属性变更
=> fix(h5): stencil slot 与 react render冲突问题 #11379

packages/taro-components/src/components/pull-to-refresh/pull-to-refresh.tsx
=> fix: 跳转进入到可下拉刷新的页面无法下拉刷新

packages/taro-harmony/src/components/components-harmony/rich-text/index.hml, packages/taro-harmony/src/components/components-harmony/rich-text/index.js, packages/taro-harmony/src/template.ts
新增rich-text组件。nodes属性只支持string入参，不支持Array
=> feat(harmony): 新增rich-text组件

packages/shared/src/template.ts
编译平台基类增加 `mergeThirdPartyComponents` 接口，支持为第三方自定义组件的属性设置默认值，fix #11575
=> feat(shared): 支持为第三方自定义组件的属性设置默认值，fix #11575

packages/taro-cli/src/doctor/configSchema.ts
配置文件中的 [designWidth](https://taro-docs.jd.com/taro/docs/config-detail#designwidth) 支持配置为整数和函数，当配置为函数时，无法启动项目，会有报错。检查，发现校验schema少了项对函数的判断，在此加上。
=> fix: 修复 designWidth 配置为函数，cli 校验不通过的问题

packages/taro-h5/src/api/media/audio/InnerAudioContext.ts
this.Instance?.paused 为 false 时 paused 会返回 true
把 `||`改成 `??` 以确保 `this.Instance?.paused = false`时可以返回 `false`
=> fix: innerAudioContext paused

packages/taro-cli/src/presets/platforms/h5.ts
=> fix: 修复cli的port参数设置无效问题

packages/taro-webpack5-runner/src/plugins/H5Plugin.ts
h5plugin get pageName in view of os.修复从filePath获取pageName时没考虑到Windows路径问题，这个问题会导致编译H5端失败.
修复webpack5-runner h5plugin 获取pageName未考虑Windows系统路径问题
=> fix(h5 webpack5): h5plugin pageName in view of os

packages/taro-components-rn/src/components/ClickableSimplified/index.tsx, packages/taro-components-rn/src/components/View/index.tsx
在React Native端可以获取到原生View组件的ref引用，将原生View组件的ref挂在ref.current.$ref属性上
1. 可以调用ref.current.$ref.current来使用原生View上的方法或者属性
2. 可以使用React Native measure相关的API获取当前原生View节点在屏幕上的位置
=> feat(components-rn): enable access to rn native View ref

packages/taro-mini-runner/package.json, packages/taro-mini-runner/yarn.lock, packages/taro-rn-runner/package.json, packages/taro-rn-runner/yarn.lock, packages/taro-webpack-runner/package.json, packages/taro-webpack-runner/yarn.lock
升级mini-css-extract-plugin插件至^0.8.0,接收ignoreOrder参数,消除css引入顺序警告问题
``` js
chunk sub-modules_approvel_training-report_training-report-item_index~sub-modules_approvel_training-report~6c0ccc6a [mini-css-extract-plugin]
Conflicting order. Following module has been added:
* css ./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-0-0!./node_modules/@tarojs/webpack-runner/node_modules/postcss-loader/lib??postcss!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--4-1!./.temp/components/no-data/NoData.scss
despite it was not able to fulfill desired ordering with these modules:
* css ./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-0-0!./node_modules/@tarojs/webpack-runner/node_modules/postcss-loader/lib??postcss!./node_modules/resolve-url-load …
```
=> chore: 升级mini-css-extract-plugin插件至^0.8.0,接收ignoreOrder参数

packages/taro-webpack5-prebundle/src/h5.ts, packages/taro-webpack5-runner/src/index.h5.ts
```js
// config/index.js
{
h5: {
publicPath: '/taro-playground/',
}
```
remoteEntry 加载链接为：
/taro-playground/remoteEntry.js
解决方法：
为 static 加上 publicPath
=> fix(h5): devserver publicPath error

.github/dependabot.yml, .github/workflows/publish.yml
距离 Taro 3.5 的 Beta 版本发布已有两个月的时间，期间我们在不断地对基于 Webpack5 的编译系统、基于 Next.js 的 SSR 等功能进行打磨的同时，新增了对 pnpm 的支持等新功能。此外 Taro 社区也有很多同学参与共建，如 Taro 合作者 [@biorz](https://github.com/biorz) 为 ReactNative 侧贡献了重要特性：支持把 Taro 组件编译为 RN 组件。
日前 Taro v3.5 已正式发布，下文将介绍关于 3.5 的主要特性与重要修复，以及后续的版本规划。
Taro v3.5 基于 Webpack5 构建了新的编译系统，利用持久化缓存、依赖预编译、SWC 等方法与工具，大幅降低了编译所需耗时。开发者可以自由选择切换使用 Webpack5 进行编译，也可以继续保持使用 Webpack4，另外在 v3.6 中 Taro 还将支持使用 Vite 进行编译。
> 依赖预编译可以预先把项目的第三方依赖打包为一个模块联邦 remote 应用，再次编译时 Webpack 无需再对这些依赖进行编译，从而提升编译速度。关于 Webpack5 编译系统的实现细节，请浏览 《Taro v3.5 beta 编译提速》
> 
v3.5 Beta 发布后，我们补全了 H5 端的依赖预编译功能，并且把依赖预编译作为一个通用能力提取了出来。可供 Taro 以外的使用 Webpack5 的 H5 项目使用，通过 `@tarojs/webpack5-prebundle` 进行编译编译提速，具体使用方法可参考[相关文档](https://docs.taro.zone/docs/next/prebundle#%E7%AC%AC%E4%B8%89%E6%96%B9%E6%8E%A5%E5%85%A5)。
以 [NutUI …
=> chore(release): publish 3.5.0

packages/taro-components/types/common.d.ts
修复StandardProps children字段类型，解决“XXX组件”不能用作 JSX 组件问题
=> fix(types): 修复 “View”不能用作 JSX 组件问题

packages/taro-webpack5-runner/src/plugins/MiniSplitChunksPlugin.ts
修复当引用了 sub-common 组件的主入口文件不引用样式，不生成 wxss 导致页面渲染无样式的问题。
=> fix: 修复当主入口不引用样式文件不生成 assets 时也不生成页面的 wxss 文件问题

packages/taro-runtime-rn/src/instance.ts, packages/taro-runtime-rn/src/page.ts
…age component
将taro-rn环境下注册的hooks关联到当前页面**实例**，而不是挂载到同一Page Component下。
=> fix(taro-runtime-rn): register hooks in current instance instead of Page Component

packages/shared/src/runtime-hooks.ts, packages/taro-plugin-react/src/loader-meta.ts, packages/taro-runtime/src/dsl/common.ts
开发者可以通过 `getMiniLifecycle` 钩子去添加类似 `onShareAppMessage` 等有副作用的生命周期，#12217
=> feat(runtime): 允许插件配置有副作用的生命周期，#12217

packages/taro-runtime-rn/src/page.ts
1. fix #12305
2. 透传 ref, 方便函数式组件配置回调 (如: componentDidShow)
=> fix: 页面为函数式组件时不再额外包裹 View #12305

packages/taro-components/src/components/textarea/style/index.scss
fix #12317
修复textarea组件高度设置无法生效的问题
style属性在taro-textarea-core，会被内层的taro-textarea的150px替代
=> fix(textarea): 修复textarea组件高度设置无法生效的问题

packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/__tests__/__snapshots__/index.spec.js.snap, packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/__tests__/index.spec.js, packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/src/index.ts, packages/taro-webpack5-runner/src/webpack/Combination.ts
如 [issue](https://github.com/NervJS/taro/pull/12236)
当开启 `css Module` 时，使用类似表达式 `style.a`，在 RN 中获取到的是 `style` 对象，而在其他端获取的是 `className` 的字符串，此处差异会导致在多种场景下需要对 `RN` 做额外处理，否则样式表现异常。
1. 使用如 `classnames` 的开源库
```typescript
import styles from 'index.module.scss'
import classnames from 'classnames'
// rn 中表现异常
const rootClassName = classnames('bar', styles.a)
```
2. 设置多个 `classname`
```typescript
import styles from 'index.module.scss'
import { View } from '@tarojs/components'
import classnames from 'classnames'
export default function () {
// rn 中表现异常
return <View className={`${styles.a} ${styles.b}`} />
}
```
**解决方案**
当识别到类似 `import styles from 'xxx'` 的语法时，将 styles 的默认取值处理成 `{[classname]: classname}` 的形式。并将原始 `styles` 合并到页面唯一的 `styleSheet` 集合中。
后续逻辑等同 `String` 类型的 …
=> feat(jsx-to-rn-stylesheet): 当开启 cssModule 时，支持在 className 中设置多个值

packages/taro/types/api/location/index.d.ts
=> Fix type definition for latitude and longitude

packages/postcss-pxtransform/__tests__/index.test.js, packages/postcss-pxtransform/index.js, packages/taro-webpack-runner/src/util/index.ts, packages/taro-webpack5-runner/src/webpack/H5WebpackPlugin.ts
=> fix(postcss): pxtransform baseFontSize 取值问题

packages/taro-components/package.json, packages/taro-components/types/Canvas.d.ts, packages/taro-components/types/Input.d.ts, packages/taro-components/types/Progress.d.ts, packages/taro-components/types/Video.d.ts, pnpm-lock.yaml
=> fix(types): 修复类型及属性名错误的问题

packages/taro-jd/src/index.ts, packages/taro-swan/src/index.ts, packages/taro-webpack5-prebundle/src/prebundle/index.ts, packages/taro-webpack5-prebundle/src/prebundle/scanImports.ts
- prebundle 编译小程序依赖为 es5
- scanModule 接受 define 参数移除不需要的依赖
=> fix(prebundle): 修复部分小程序不支持语法问题 fix #12414

packages/taro-components/src/components/input/input.tsx
优化 H5 端 input 组件 type 为 number 或 digit 时, 输入特殊符号导致交互异常问题。
描述：Web 的 input 组件 type=number时，当开发者输入特殊符号或者多个小数点时，input 组件的 value 值会表现为空，从而在业务场景下，会出现不符合预期的多种表现。在唤起 Web 端数字键盘时，通过对特殊符号的输入拦截可以做到一定交互体验优化。
=> fix(taro-components): 优化 input 组件 type 为 number 或 digit 时,输入特殊符号导致交互异常问题

packages/taro/html5.css
https://caniuse.com/mdn-css_properties_width_stretch
https://github.com/postcss/autoprefixer/issues/1035
基于警告`autoprefixer: Replace fill-available to stretch, because spec had been changed`, 较新版本的`autoprefixer`需要使用新的写法, 编译结果为:
```css
.h5-marquee {
display: inline-block;
width: -webkit-fill-available;
width: -moz-available;
width: fill-available;
}
```
该属性历史有关的PR: #9891 #11106
=> style: 支持较新版本的autoprefixer(7.0.0+)

packages/taro/types/api/media/image.d.ts
=> feat(types): Update compressImage types

packages/taro-h5/__tests__/utils.ts, packages/taro-h5/src/api/base/weapp/life-cycle.ts, packages/taro-router/src/router/mpa.ts, packages/taro-router/src/router/spa.ts, packages/taro-webpack-runner/src/__tests__/__snapshots__/babel.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/compiler-macros.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/config.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/nerv.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/sass.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/ts.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/vue.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap
`onLaunch`的查询参数在微信小程序中的与`h5`不一致, 抹平它.
小程序:
H5:
=> chore: 部分抹平h5与小程序参数差异

packages/taro-h5/__tests__/network/request.test.ts, packages/taro-h5/src/api/network/request/index.ts
1. revert https://github.com/NervJS/taro/pull/4599, 它造成了与小程序网络处理逻辑不一致; 比如 http 401 在小程序走success, h5走了fail. 其实小程序的`request`本身就是参照web的`Fetch API`的. 没必要再搞差异出来.
无数据就无数据, 和状态应该没关系. #4599 的做法不规范.
2. 再抹平状态和文本字段.
再参照小程序
=> feat: revert #4599, 并参照小程序抹平err时字段

packages/babel-preset-taro/README.md, packages/babel-preset-taro/index.js
优先探测 browserslist 配置, 如果没有才设置 targets, 因为设置了targets会优先, 不设置又会默认.
单一配置原则.
=> feat: 没有配置targets时先探测 browserslist 配置, 仍然没有才设置默认值

packages/taro-plugin-react/src/runtime/connect.ts
因为`React 18`中 `componentDidMount` 比小程序 `onShow` 触发相对较晚，在第一次触发`onShow`事件时，`AppWrapper`尚未挂载，无法取到 `App` 实例，所以第一次的 `componentDidShow` 相关生命周期都无法触发，此PR仿照解决`onLaunch`的
竟态解决方案，等待`App` 实例完全挂载后再触发 `componentDidShow` 相关事件
=> fix(taro-plugin-react): 修复3.5小程序中app不会触发首次componentDidShow系列生命周期

packages/taro-components/__tests__/style.spec.js, packages/taro-react/__tests__/props.spec.js, packages/taro-react/src/props.ts
修复taro在小程序内会自动为数字类型的css变量与部分属性(like: animation-iteration-count)自动添加px后缀，这与原生小程序和web端行为不一致，抹平差距
相关issue: https://github.com/NervJS/taro/issues/12617
=> #fix(taro-react): 修复taro在小程序会自动为数字类型css变量与部分属性自动添加px后缀

packages/taro-cli/src/doctor/configSchema.ts, packages/taro-plugin-mini-ci/README.md, packages/taro-plugin-mini-ci/package.json, packages/taro-plugin-mini-ci/src/AlipayCI.ts, packages/taro-plugin-mini-ci/src/BaseCi.ts, packages/taro-plugin-mini-ci/src/DingtalkCI.ts, packages/taro-plugin-mini-ci/src/QRCode.ts, packages/taro-plugin-mini-ci/src/SwanCI.ts, packages/taro-plugin-mini-ci/src/TTCI.ts, packages/taro-plugin-mini-ci/src/WeappCI.ts, packages/taro-plugin-mini-ci/src/hooks.ts, packages/taro-plugin-mini-ci/src/index.ts, packages/taro-plugin-mini-ci/src/types.d.ts, packages/taro-plugin-mini-ci/src/utils/compareVersion.ts, packages/taro-plugin-mini-ci/src/utils/npm.ts, packages/taro-plugin-mini-ci/src/utils/qrcode.ts
去年的PR实现了从0到1，经过一年的项目沉淀和反馈，此次更新以灵活性、输入输出规范统一为特点
- `Taro` 插件参数支持传入函数体，并应用到了`@taro/plugin-mini-ci` 插件
之前Taro插件做了强验证，只支持传入对象作为参数，新增了支持传入函数作为参数，更加灵活。
举个例子，比如“构建微信小程序时根据`jenkins`注入的构建号动态分配机器人编号”这个需求
- 支持独立的 `open`、`preview`、`upload` 命令，操作自定义目录
适用于将`taro`作为项目一部分（混合开发）的开发场景
- 重新联调了各个平台的`CI`，一年过去了，各大平台的`CI`包都有不同程度的更新（特别是头条、支付宝）
- 新增 钉钉 小程序`CI`
- 统一所有平台CI构建后的输出数据，并将数据传递给新增的`onPreviewComplete`、`onUploadComplete`两个钩子
用户可以编写新的插件，基于这个钩子实现 `飞书`、`钉钉` 的 `CI` 推送功能，我计划晚点推一个新插件实现这个功能,有强烈特殊定制的用户可基于这两个钩子可自行实现通知插件（比如发发布时短信通知之类的）
- 运行时动态加载各端CI包的方式变更，旧的`require`方式不支持`pnpm link`, 不方便调试
- 编写了一些 `ts` 类型供开发插件时使用，维护更友好
- 部分选项统一了字段，不兼容的选项已经在文档加了说明
=> feat(taro-plugin-mini-ci):  Taro 小程序端构建CI（持续集成）插件重大更新

packages/shared/src/native-apis.ts, packages/taro-alipay/src/apis.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap, packages/taro-swan/src/apis.ts, packages/taro-tt/src/apis.ts
#11879
字节小程序存在部分api没有与Taro（或者说微信）对齐，目前只发现一个Taro.showToast比较影响，先修复下，[具体表现见ssues/11879抖音小程序showtoast icon为error时显示错误](https://github.com/NervJS/taro/issues/11879)
TODO：应该还存在部分api有差异，后续想个方案看看怎么能全量对比下
=> fix(tt): 抹平部分API

packages/taro-webpack-runner/src/util/chain.ts, packages/taro-webpack5-runner/src/webpack/H5WebpackModule.ts
`stylus` 的 webpack module rule 的名称不一致
- `taro-mini-runner` 中是 `stylus`
- `taro-webpack5-runner `中是 `styl`
- `taro-webpack-runner `中是 `styl`
`webpack-chain` 获取的时候需要兼容,感觉没必要,希望统一修改成`stylus`
=> fix: 统一stylus的rule名称,方便webpack-chain获取

packages/taro-service/src/platform-plugin-base.ts
1. 自定义编译配置根据不同端打包输出到不同的目录
```js
mini: {
output: {
path: path.resolve(process.cwd(), 'dist_tt'),
}
}
```
2. 编译详情重新指定output后小程序的project.config还是输出到的dist
3. 本次修改在初始化平台插件时，重新更新outputPath为对应平台指定的path 
=> fix(mini): 修复project.config位置

packages/taro-webpack-runner/src/index.ts, packages/taro-webpack5-runner/src/index.h5.ts
修复 `h5.devServer.port` 为字符串时， h5 端启动时的端口对比逻辑不正确导致展示不必要提示的问题（[issue #12946](https://github.com/NervJS/taro/issues/12946#issue-1482322960)）。
=> fix(webpack-runner): 修复端口对比逻辑不正确的问题

packages/taro-webpack5-prebundle/src/prebundle/bundle.ts
`const` 导致报错`The keyword 'const' is reserved`
Taro 开启 `prebundle` , 支付宝开启 `小程序基础库2.0构建` 后，由于代码中存在`const`导致支付宝小程序加载报错 `The keyword 'const' is reserved`
比如如下代码：
```
const m = __webpack_require__(/*! ./react.core.js */ "./node_modules/.taro/alipay/prebundle/react.core.js")
module.exports = m.default
exports["default"] = module.exports
```
故将 `const` 改为 `var`
fix #12879
=> fix(prebundle): 修复支付宝开启小程序基础库2.0构建报错，fix #12879

packages/taro-alipay/src/apis.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
修复Issue#13073：Taro.showToast的icon的error需要支持支付宝type图标显示，fail可以，error不行
=> fix(taro-alipay): 修复支付宝showToast的option.icon的error与fail的映射问题

package.json, packages/taro-plugin-react/src/webpack.mini.ts, packages/taro-react/README.md, packages/taro-react/package.json, packages/taro-react/rollup.config.js, packages/taro-react/src/props.ts, packages/taro-react/src/reconciler.ts, packages/taro-react/src/render.ts, pnpm-lock.yaml
本 PR 主要内容
1. 修复 `createContainer` 入参问题
1. 在 Taro v3.5 版本中将 `react-reconciler` 升级到 v0.27 版本，在0.27版本中 `createContianer` 方法调整了若干个入参，新增入参如下：
```jsx
function createContainer(
containerInfo: Container,
tag: RootTag,
hydrationCallbacks: null | SuspenseHydrationCallbacks,
isStrictMode: boolean,
concurrentUpdatesByDefaultOverride: null | boolean,
identifierPrefix: string,
onRecoverableError: (error: mixed) => void,
transitionCallbacks: null | TransitionTracingCallbacks,
): OpaqueRoot {
// ...
}
```
而 Taro 内调用的该方法没有做相关兼容，从而引起异常。本PR修复了该问题。
2. 修改 render 与 createRoot 方法的入参，以适应 createContianer 的调用
2. 更新包 `@types/react-reconciler` 版本
react-reconciler 升级后，也顺便升级了包 `@types/react-reconciler` 版本， v0.26.1 —> v0.28.1
3. 调整 HostConfig 字段顺序
为了方便开发迭代与维护，调整了 HostConfig 字段顺序，该顺序遵循 React …
=> refactor(react): 因升级react-reconciler而做的必要代码调整

packages/taro-webpack5-runner/src/webpack/BaseConfig.ts
当配置文件为 ts 时， 由于 cache 的 配置是通过递归merge 得到的， 导致 config/index.js 配置用户无法覆盖
`
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve 'xx/node_modules/@tarojs/webpack5-runner/dist/webpack' in 'xxx'
<w> while resolving 'xxx/node_modules/@tarojs/webpack5-runner/dist/webpack' in xxx as file
<w>  at resolve commonjs xx/node_modules/@tarojs/webpack5-runner/dist/webpack
`
修改  cache.buildDependencies 中 config 的 默认值， 通过 resolveScriptPath 方法， 与 Config 中解析的配置文件保持一致
**需要测试验证**
=> fix: modify buildDependencies default value

packages/taro-plugin-react/src/runtime/connect-native.ts, packages/taro-plugin-vue3/src/runtime/connect-native.ts
- 修复微信小程序宿主页面同时使用插件组件和插件页面场景中，插件页面回退到宿主页面之后未正确处理插件中页面实例对象而导致宿主环境中使用的插件组件二次加载异常。
=> fix(wx): TypeError: Cannot read property 'route' of null 修复宿主环境同时使用插件页面和插件组件时currentPage.route异常中断插件组件渲染

packages/taro-helper/src/utils.ts
修复readConfig函数读取页面index.config.js配置文件(来自软链接)报错, 在createSwcRegister的only选项configPath参数添加realpathSync解析
=> fix(taro-helper): 修复readConfig时,createSwcRegister没有对软链接的.config.js进行编译,导致Unexpected token 'export'

packages/taro-webpack5-runner/src/webpack/H5Combination.ts
fix: https://github.com/NervJS/taro/issues/13167
删除h5Combination中cacheGroup多余的filename配置
=> 修复修改filename对common chunks不生效的问题

packages/taro-h5/src/api/network/request/index.ts
fix(h5): request 更严谨的判断 options.data 为 Object ，可以避免部分问题。
比如，当 options.data 为 FormData 时，原本的写法 `typeof options.data === 'object'` 会返回 true 。
相关 issues: 
- https://github.com/NervJS/taro/issues/9786
- https://github.com/NervJS/taro/issues/5514
=> fix(h5): request 更严谨的判断 options.data 为 Object #9786

packages/taro-api/src/tools.js, packages/taro-h5/src/api/taro.ts, packages/taro-h5/src/utils/valid.ts, packages/taro-rn-style-transformer/src/types/index.ts, packages/taro-rn-supporter/src/types/index.ts, packages/taro-rn-transformer/src/types/index.ts, packages/taro-router-rn/src/utils/index.ts, packages/taro-runtime-rn/src/compute.ts, packages/taro-runtime-rn/src/types/index.d.ts, packages/taro-runtime-rn/src/utils.ts, packages/taro/types/compile/config/project.d.ts
- 修复 designWidth 函数类型导致的 API 错误 （修复小程序、RN，并对齐 web 端逻辑）
- 对齐 designWidth 类型，并优化 isFunction 函数写法
=> fix(pxtransform): 修复 designWidth 函数类型导致的 API 错误 fix #12078

packages/taro-plugin-html/src/constant.ts
在某些情况下，html `a` 标签转换为小程序 `navigator` 标签并不符合要求，比如：
```
import {Link} from 'react-router-dom'
<Link to="a/b/c" />   // 期望拦截点击，更改location，而非触发小程序跳转
```
由于支付宝小程序 `navigator` 标签无法触发 `onTap` 事件，从而无法进一步触发 `a` 标签绑定的 `onClick` 事件，路由切换失败。
本PR支持 `<a as="xxx">` 传入 `as` 属性，以支持转换为自定义小程序标签
=> feat(plugin-html): 支持a标签转换为自定义小程序标签

packages/taro-h5/src/api/ui/interaction/index.ts, packages/taro-h5/src/api/ui/interaction/toast.ts, packages/taro/types/api/ui/interaction.d.ts
fix(types): hideLoading.Option / hideToast.Option 添加 noConflict 可选字段/类型
`Taro.hideLoading({ noConflict: true })` ts 类型报错，2.22.1 [wx.hideLoading](https://developers.weixin.qq.com/miniprogram/dev/api/ui/interaction/wx.hideLoading.html) 新增 `noConflict` 参数
目前没有提相关issue
=> fix(types): hideLoading.Option 添加 noConflict 可选字段

packages/taro-plugin-inject/src/index.ts
当通过 `@tarojs/plugin-inject` 插件修改 `componentsMap` 选项时，会将 `@tarojs/components` 依赖重定向到 `@tarojs/plugin-inject/dist/components-react.js` 中，而通过 `export * from ""` 的抛出形式无法被webpack正常解析。从而 moduleUsedExports 异常（只能获取到 `export const xxx = yyy` 的内容）
https://github.com/NervJS/taro/blob/181aa1eccf26b7c7d70a0898ef32d04375b81809/packages/taro-webpack5-runner/src/plugins/TaroLoadChunksPlugin.ts#L168
修改 webpack 的 `optimization.providedExports = false` 即可
=> fix(plugin-inject): 修复新增componentsMap时未正确识别 export * 的问题

packages/taro-plugin-mini-ci/src/utils/qrcode.ts
小程序自动上传时，控制台生成的预览二维码尺寸过大，不方便扫码
=> perf(plugin-mini-ci): 控制台预览二维码尺寸过大，不方便扫码

packages/taro-plugin-react-devtools/src/index.ts, packages/taro-plugin-react-devtools/src/runtime.ts, packages/taro-plugin-vue-devtools/src/index.ts, packages/taro-plugin-vue-devtools/src/runtime.ts
因为公司的小程序开发者工具需要走公司的网络代理，默认的 localhost 不能访问，所以才有这个 pr，可以指定局域网的 ip。
如果公司网络复杂的情况下，可以自定义 taro 连接 vue 和 react 的 devtools 主机名，默认为 localhost。
custom connect devtools hostname，default is localhost.
=> feat: custom connect devtools hostname

packages/taro/types/api/wxml/index.d.ts
增加了 SelectorQuery 下 selectAll 方法的回调函数返回值的 ts 类型。在 SelectorQuery 下有两个方法，分别是 select 以及 selectAll，select 返回首个选中元素，而 selectAll 使用数组返回所有选中元素，目前类型定义仅定义了 select 的返回值，因此补充 selectAll 的返回值类型。
=> chore(SelectorQuery): add callback function return value type

packages/taro-runtime/src/dom/event.ts
=> fix(runtime): falsy event detail 的判断导致 vant 原生组件 e.detail 为 0 或空字符串时被强改成object

packages/taro-h5/src/api/audio/index.js
修复H5在执行destroy报错的问题，查看了commit记录，以前是appendChild在body上的，现在是直接new了一个Audio对象，在destroy的时候不需要再执行removeChild
=> fix: 修复Taro.createInnerAudioContext执行destroy异常的问题

packages/taro-components-advanced/rollup.config.js, packages/taro-components-library-react/rollup.config.js, packages/taro-components-library-vue2/rollup.config.js, packages/taro-components-library-vue3/rollup.config.js, packages/taro-components-react/rollup.config.js, packages/taro-loader/src/h5.ts, packages/taro-platform-h5/rollup.config.js, packages/taro-plugin-html/rollup.config.js, packages/taro-plugin-http/rollup.config.js
- 修复 H5 loader 和 component rollup 配置问题
=> fix(h5): 修复 H5 loader 和 component rollup 配置问题

packages/taro-components/src/components/tabbar/tabbar.tsx, packages/taro-h5/__tests__/utils.ts
- 修补 tabbar 生命周期错误（stencil 升级后 document.createElement 将会直接执行 constructor 导致错误）
- 补充 tabbar 测试用例
=> fix(h5): 修补 tabbar 生命周期错误 fix #13581

packages/taro-components/src/components/swiper/swiper.tsx
回滚 change 事件错误设置，修改为 slideChangeTransitionEnd 阶段
> - slideChangeTransitionStart 触发太早，swiper 各个参数并未准备好（会导致错误事件抛出）
> - 在 slideChangeTransitionStart 事件中抛出 change 事件会导致 current 监听被打乱
> - 该模式下与 sliderTo 结合时，动画会被中断，导致类似 slider 展示不完整或衔接模式错误等
=> revert(swiper): 回滚 change 事件设置 #12357

packages/taro-router/src/router/page.ts, packages/taro-router/src/router/spa.ts
在 h5 中，从普通页面返回 tabbar 页面的时候，动画会消失，这个 PR 会修复这个问题，有 2 个场景：
1. 从 tabbar 页面进入普通页面，然后返回；
2. 直接进入普通页面，点击返回 tabbar 页面 。
=> fix: 从普通页面返回 tabbar 页面时展示动画

packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap, packages/taro-mini-runner/src/plugins/MiniPlugin.ts, packages/taro-webpack5-runner/src/__tests__/__snapshots__/mini-split-chunks.spec.ts.snap, packages/taro-webpack5-runner/src/plugins/MiniPlugin.ts
修复 app 样式引用 common 样式的语法问题
修复前，位于样式文件底部的 `@import` 不符合规范，容易导致各种错误：
```css
/* app.wxss */
/* some app global styles */
.global {...}
/* common styles */
@import "./common.wxss";
```
修复后，当存在 common 样式时，抽取 app 样式到一个独立的文件，app样式文件只保留 `@import` 语句。这样可以兼顾样式层叠顺序和 css 语法的准确性：
```css
/* app.wxss */
@import "./app-core.wxss";
@import "./common.wxss";
```
```css
/* app-core.wxss */
.global {...}
```
（顺着处理了 #13764 的语法问题）
=> fix(webpack5): 修复 app 样式引用 common 样式的语法问题

packages/taro-components/src/components/picker/picker.tsx, packages/taro-components/types/Picker.d.ts
组件内部文本props，新增textProps对象，为h5，rn等组件解决国际化问题，例Picker 组件， 传入 
```js
textProps={{
okText: 'ok',
cancelText: 'cancel'
}}
```
其他组件有类似需求的话，一样通过textProps, 在类型注释和文档中写明对应的可传的值
fix #12489 
=> feat(component): picker textProps

packages/taro-components-library-react/src/react-component-lib/utils/attachProps.ts, packages/taro-h5/package.json, packages/taro-h5/src/api/location/chooseLocation.ts
- 修复在 web 端使用 react 框架时，classnames 赋值为空时错误判断导致的问题
- 修复地图样式抖动 & 重复注入等问题
=> fix(h5): 修复类空判断导致的问题 fix #13781

packages/taro-webpack5-runner/src/postcss/postcss-alias.ts, packages/taro-webpack5-runner/src/postcss/postcss.h5.ts, packages/taro-webpack5-runner/src/postcss/postcss.mini.ts, packages/taro-webpack5-runner/src/webpack/H5WebpackModule.ts, packages/taro-webpack5-runner/src/webpack/MiniWebpackModule.ts
修复 CSS 内静态资源路径 alias 不生效的问题，fix #13906
新增 postcss 插件，在 postcss-url 处理之前先把 alias 后的静态资源路径进行还原
=> fix(webpack5): 修复 CSS 内静态资源路径 alias 不生效的问题，fix #13906

packages/taro-h5/src/api/media/audio/InnerAudioContext.ts
在**web**中调用音频实例的销毁方法报错
```ts
const audioContext = Taro.createInnerAudioContext()
audioContext.destroy() // 报错
```
我理解的报错原因是
web实际上就是创建一个`audio`元素去调用方法，但是压根就没有插入body中，destroy却调用了document.body.removeChild，所以就报错了
=> fix(h5): inneraudiocontext destroy

packages/taro-h5/src/api/media/audio/InnerAudioContext.ts, packages/taro-h5/src/api/media/background-audio/BackgroundAudioManager.ts
Issues: #13945 
修复在 H5 环境中InnerAudioContext和BackgroundAudioManager出现错误时未触发onError监听的事件的问题
- 存在个问题，H5的onerror事件的参数([MediaError - MDN](https://developer.mozilla.org/en-US/docs/Web/API/MediaError))与小程序的[onError](https://developers.weixin.qq.com/miniprogram/dev/api/media/audio/InnerAudioContext.onError.html)是不一样的，如果有更好的写法，可以直接修改。
=> fix(h5): InnerAudioContext和BackgroundAudioManager出现错误时未触发onError

packages/taro/types/api/network/request.d.ts
=> fix(type): update type of request

packages/taro/types/api/base/crypto.d.ts
修改了微信小程序用户加密模块 getLatestUserKey success 返回的参数类型。
success 返回的参数类型应为 SuccessCallbackResult 而非 TaroGeneral.CallbackResult。
=> fix(types): 修改用户加密模块类型错误

packages/taro-components/types/index.vue3.d.ts
这么久才发现react的事件名和vue的不太一样   #11445 
=> fix(types): transform react CamelCase event name to vue Camelcase name

packages/taro-plugin-react/src/webpack.mini.ts
修复 `@tarojs/plugin-framework-react@3.6.10` 在Windows环境下编译报错问题
=> fix: react alias bug on windows

packages/taro-alipay/src/apis.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap, packages/taro-webpack5-runner/src/__tests__/__snapshots__/mini-platform.spec.ts.snap, packages/taro-webpack5-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
`Taro.showModal` 方法 `showCancel==false` 时实际调用的是[my.alert](https://opendocs.alipay.com/mini/api/ui-feedback?pathHash=2ad09662)方法，此时，回调只返回了 `{success:true}`，此处作统一兼容，同时返回 `confirm`属性
=> fix(alipay): add my.alert success callback compatibility

packages/taro-components-rn/src/components/Input/index.tsx
修复这样写无法获得最新的post，导致值被重置的问题
```js
<Input onInput={e => setPost({ ...post, key: e.detail.value })} />
```
- [+] 错误修复(Bugfix) issue: fix #
- [+] 移动端（React-Native）
=> fix: 修复输入框事件传入的函数不会更新

packages/taro-plugin-mini-ci/src/AlipayCI.ts, packages/taro-plugin-mini-ci/src/BaseCi.ts
**问题背景：**
使用`@tarojs/plugin-mini-ci`在 CI 中上传小程序时，不传版本号，默认为`1.0.0`
**实际结果：**
导致无法实现官方文档中所说的，不提供版本号时，版本号patch自增
**期望结果：**
去掉默认版本号 `1.0.0`
去掉默认版本号 `1.0.0`
=> feat: 删除默认版本号；不传自定义版本号时， alipay 平台使用默认自增版本号

packages/taro-components/src/components/button/style/index.scss
修复h5中components下的btn组件丢失warn样式
=> fix: 修复button组件丢失warn

packages/taro-components-library-vue2/src/components-loader.ts
Vue2 语法转 H5 端时，所有的节点都变成了 taro-xxx，没有成功渲染为 taro-xxx-core 的 webComponent 组件，导致所有组件能力都失效。
不正常：
预期：
本次修改，主要调整了组件初始化时的 initVue2Components 函数中的判断逻辑，因为 Vue.extend 返回的亦是一个构造函数，且仅需判断是否存在即可。
=> fix(component): 修复H5端创建webComponent标签组件失效问题

packages/taro-components-react/src/components/pull-down-refresh/style/index.css, packages/taro-components/src/components/pull-to-refresh/style/index.scss, packages/taro-router/src/style.ts
修复H5页面中sticky失效问题，原因是祖先节点中存在无用的overflow:hidden;
自测验证场景：
spa: （局部滚动）
Taro.pageScrollTo:1
usePullDownRefresh:1
usePageScroll:1
useReachBottom:1
Toast滚动穿透:1
切换路由回到顶部：1
tabbar表现：1
使用下拉刷新时sticky是否生效：1
不使用下拉刷新时sticky是否生效：1
mpa: （全局滚动）
Taro.pageScrollTo:1
usePullDownRefresh:1
usePageScroll:1
useReachBottom:1
Toast滚动穿透:1
使用下拉刷新时sticky是否生效：1
不使用下拉刷新时sticky是否生效：1
=> fix(h5): 修复sticky失效问题

packages/taro-mini-runner/src/index.ts, packages/taro-mini-runner/src/plugins/TaroNormalModulesPlugin.ts, packages/taro-service/src/utils/types.ts, packages/taro-webpack-runner/src/index.ts, packages/taro-webpack-runner/src/plugins/TaroComponentsExportsPlugin.ts, packages/taro-webpack5-runner/src/plugins/TaroComponentsExportsPlugin.ts, packages/taro-webpack5-runner/src/plugins/TaroNormalModulesPlugin.ts, packages/taro-webpack5-runner/src/webpack/Combination.ts, packages/taro/types/compile/config/project.d.ts, packages/taro/types/compile/hooks.d.ts
- 修复 webpack-runner 钩子不支持修改 componentConfig 问题
- 修复 h5 端 componentConfig.includeAll 参数失效问题
- 优化 modifyConfig 参数类型，预备 modifyViteConfig 使用
=> fix(runner): 修复 web 端组件导出参数问题

packages/taro-components/types/Textarea.d.ts
更改`Textarea`组件的`confim-hold`属性的类型
参考: 
微信小程序文档： https://developers.weixin.qq.com/miniprogram/dev/component/textarea.html#%E9%80%9A%E7%94%A8%E5%B1%9E%E6%80%A7
字节小程序文档：
https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/component/list/textarea/
=> fix(weapp): 修改Textarea组件confirm-hold属性的类型

packages/taro-plugin-inject/src/index.ts
通过 @tarojs/plugin-inject 添加自定义组件配置之后，运行 H5 端编译时会报错。
配置：
报错：
原因：主要是 @tarojs/service 模块的 platform-plugin-base 做了 mini 和 web 拆分之后，web 端也会调用 onSetupClose 方法，并最终触发了 plugin-inject 中的自定义组件注册逻辑。
处理方式： web 端不需要执行 plugin-inject 逻辑，所以判断平台类型进行拦截即可。
=> fix(plugin-inject): 修复@tarojs/plugin-inject配置在H5端编译报错问题

packages/taro-components-react/src/components/pull-down-refresh/style/index.css, packages/taro-components/src/components/pull-to-refresh/style/index.scss, packages/taro-components/src/components/video/style/index.scss, packages/taro-components/src/global.css, packages/taro-router/src/style.ts
There will be scrollbar if use min-height:100vh on Chrome. Better choice is use height:100%.
使用 height:100% 代替 min-height:100vh 解决 chrome浏览器会有滚动条问题；
给 video 标签设置 display:block 以便于调整大小和定位
=> fix(style): use 100% instand of 100vh

packages/taro-mini-runner/src/plugins/BuildNativePlugin.ts, packages/taro-webpack5-prebundle/src/utils/webpack.ts, packages/taro-webpack5-runner/src/plugins/BuildNativePlugin.ts, packages/taro-webpack5-runner/src/plugins/MiniPlugin.ts
【修复问题】
用来修复14371问题。
https://github.com/NervJS/taro/issues/14371
【问题原因】
path.relative在window环境下路径是反斜杆\，导致引入的wxss路径出现错误（ ./..\..\app.wxss）
该错误是历史代码问题，非新融合特性导致，该问题存在packages/taro-webpack5-runner/src/plugins/BuildNativePlugin.ts的代码里面，新融合特性也使用了这块有问题的代码，故需要进行修复。
【修复方式】
强制指定posix方式获取路径避免该错误的发生。
path.posix.relative
- [ x ] 错误修复(Bugfix) issue: fix #14371
- [ x ] 所有小程序
=> fix(14371): 修复window环境下路径错误的问题

packages/taro-mini-runner/src/webpack/chain.ts, packages/taro-webpack5-runner/src/webpack/MiniWebpackModule.ts
- 修复 file-loader 和 webpack 使用 posix 的路径形式，导致拼接路径在 windows 系统上失效的问题
=> fix: 修复 file-loader 和 webpack 使用 posix 的路径形式，导致拼接路径在 windows 系统上失效的问题

packages/taro-components/src/components/image/style/index.scss
按照小程序规范添加 image 组件默认宽高，避免部分模式由于缺少宽高导致无法正常显示
=> fix(components): add image default height & width

packages/taro-components/src/components/tabbar/style/index.scss, packages/taro-router/src/router/page.ts, packages/taro-router/src/style.ts
- 通过 css 选择器控制，避免多个非 tab 页面同时显示
> 如果 style 切换失败，则通过修改 class 也会在该情况下失效，故而选择改用 css 控制（理论上不存在除去 tabbar 页面以外，需要显示前序路由的情况）
- 改用 css 变量控制 tabbar 高度
=> fix(route): 不显示最后一个注入以外的非 tab 页面 fix #14478

packages/taro-components/__tests__/view.e2e.ts, packages/taro-components/scripts/stencil/stencil.config.ts, packages/taro-components/src/components/scroll-view/scroll-view.tsx, packages/taro-components/src/components/view/view.tsx, packages/taro-components/src/utils/helper.ts
scroll-view 同步禁用 stencil 的 slot-relocation 特性，避免子节点顺序错乱
=> feat(h5): handle scroll-view slot-relocation fix 14502

packages/taro-router/src/style.ts
修复 max-height 错误配置导致的普通页面高度限制问题
=> fix(route): normal page max-height fix #14592

packages/taro-components/src/components/picker/picker.tsx
#14042
当 picker组件传入的 value 不在 start和end 范围内时，默认采用start值，不报错
=> fix(h5): use start time if the value prop of Picker is out of range

packages/taro-router/src/style.ts
当配置了app.config.js中的animation为false的情况下，发生路由跳转。上一个页面元素节点没有被隐藏
=> fix: h5模式下app.config.js中animation：false路由调整问题修复

packages/taro-h5/types/overlay.d.ts, packages/taro-rn/types/overlay.d.ts, packages/taro/types/api/device/accelerometer.d.ts, packages/taro/types/api/device/accessibility.d.ts, packages/taro/types/api/device/battery.d.ts, packages/taro/types/api/device/bluetooth-ble.d.ts, packages/taro/types/api/device/bluetooth-peripheral.d.ts, packages/taro/types/api/device/bluetooth.d.ts, packages/taro/types/api/device/calendar.d.ts, packages/taro/types/api/device/clipboard.d.ts, packages/taro/types/api/device/compass.d.ts, packages/taro/types/api/device/gyroscope.d.ts, packages/taro/types/api/device/iBeacon.d.ts, packages/taro/types/api/device/keyboard.d.ts, packages/taro/types/api/device/memory.d.ts, packages/taro/types/api/device/motion.d.ts, packages/taro/types/api/device/network.d.ts, packages/taro/types/api/device/nfc.d.ts, packages/taro/types/api/device/phone.d.ts, packages/taro/types/api/device/scan.d.ts, packages/taro/types/api/device/screen.d.ts, packages/taro/types/api/device/sms.d.ts, packages/taro/types/api/device/vibrate.d.ts, packages/taro/types/api/device/wifi.d.ts
=>  更新设备相关types

packages/taro-h5/src/api/network/request/index.ts
Sync default value of timeout param with Wechat Mini Program
Web 平台（H5）版本中的 request 的 timeout 默认值与微信小程序的 request 的 默认值保持一致
=> Sync default value of timeout param with Wechat Mini Program

packages/taro-webpack5-prebundle/src/utils/webpack.ts
prebundle的资源引用不需要强制走posix，里面已经调用了promoteRelativePath函数来做处理，调用posix获取路径会导致window平台引用资源路径错误。
=> fix: 14771问题修复，window下代码引入路径异常

packages/taro-components/src/components/video/video.tsx
**问题：** 视频组件中，全屏后点击浏览器的退出全屏按钮报错：Uncaught (in promise) TypeError : Failed to execute ‘exitFullScreen’ on ‘Document’: Document not active
**原因：** 全屏后，"退出全屏"是浏览器按钮是浏览器内部按钮，非html按钮，点击"退出全屏"按钮是浏览器内部实现功能。此时再次调用exitFullscreen反而会报错。
**修复方案：** 区分出退出全屏方法是由浏览器调用还是api调用，对浏览器调用来源的不再执行exitFullscreen方法。
=> fix: 视频组件，浏览器退出全屏出错

packages/taro-service/src/platform-plugin-base/mini.ts, packages/taro-service/src/platform-plugin-base/webpack/hmr-plugin.ts
=> feat(service): Webpack5 兼容小程序开发者工具的 hmr 功能

packages/taro-h5/__tests__/ui/tab-bar.test.tsx, packages/taro-h5/__tests__/utils.ts, packages/taro-h5/src/api/ui/fonts.ts, packages/taro-h5/src/api/ui/tab-bar.ts
- 修改taro-h5的loadFontFace接口成功回调时反馈的信息，与微信小程序保持一致
- 修改taro-h5的setTabBarBadge接口可显示中文的长度不超过两字符
=> fix: 优化loadFontFace成功回调信息以及setTabBarBadge上标显示

packages/shared/src/runtime-hooks.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap, packages/taro-runtime/src/dom/element.ts, packages/taro-tt/src/runtime-utils.ts, packages/taro-webpack5-runner/src/__tests__/__snapshots__/mini-platform.spec.ts.snap
修复小程序 `Input` 组件使用 async onInput 回调时输入框闪烁的问题
原因：
https://github.com/NervJS/taro/pull/13191 在修复 #13166 的时候，把所有 React 事件回调函数的返回值作为小程序事件回调的返回。但对于 Input 等表单组件来说，在小程序规范中，回调的返回值会修改输入框的值。因此使用 async onInput 时，React 事件回调返回了 Promise，接着这个 Promise 又被作为小程序回调的返回值，进而错误地修改了输入框的值。
因此，此 PR 新增了一个 Taro Runtime 钩子，让各个平台定义哪些组件的哪些事件可以透传出返回值。
=> fix(miniapp): 修复小程序Input组件使用async onInput回调时输入框闪烁的问题

packages/taro-platform-h5/build/utils/ast.ts
修正taro-platform-h5的generateDocumentation 中的路径问题
=> fix: 修复window环境无法生成definition.json文件

packages/taro-mini-runner/src/plugins/TaroNormalModulesPlugin.ts, packages/taro-webpack-runner/src/plugins/TaroComponentsExportsPlugin.ts, packages/taro-webpack5-runner/src/plugins/TaroComponentsExportsPlugin.ts, packages/taro-webpack5-runner/src/plugins/TaroNormalModulesPlugin.ts
esbuild-loader 会影响到 taroNormalModulesPlugin 中对于 ast 的解析处理：
正常这里是可以获取到所有的标签 name 的，但是使用了 esbuild-loader 之后，只有一个 View 了，导致解析到的标签只有一个View：
同样的代码 不用这个配置，所有的标签模版都会解析到：
webpack 这里拿到的 ast ，使用这种配置和不使用时，不一样，要加个兼容， esbuild 这里是没有 _ 的
=> fix: esbuild-loader 的 ast 兼容问题

crates/taro_init/src/async_fs.rs, crates/taro_init/src/constants.rs, crates/taro_init/src/utils.rs
=> fix(rs): 文件经过 copy 或者 write 后，在 Unix 系统上继承原文件的权限

packages/taro-components-rn/src/__tests__/__snapshots__/camera.spec.tsx.snap, packages/taro-components-rn/src/__tests__/__snapshots__/video.spec.tsx.snap, packages/taro-components-rn/src/components/Image/index.tsx, packages/taro-components-rn/src/components/View/index.tsx, packages/taro-components-rn/src/components/hooks/PropsType.tsx, packages/taro-components-rn/src/components/hooks/useClickable.tsx, packages/taro-components/__tests__/__snapshots__/picker-view.spec.tsx.snap
RN组件性能优化：火焰图显示ClickableSimplified这个hoc包裹的view和image这两个高频组件，会额外创建新的实例
- 1000节点view耗时为380ms、优化后为295ms（原生269ms）
- 1000节点的image耗时为900ms、优化后为830ms（原生670ms）
=> feat: 优化rn的clickable组件，1000节点增加20%渲染速度

packages/taro-plugin-react/src/webpack.h5.ts, packages/taro-plugin-vue3/src/webpack.h5.ts
=> fix(h5): 修复 harmony-hybrid 配置导致的 h5 babel 配置覆盖问题

packages/taro-rn-style-transformer/src/transforms/sass.ts, packages/taro-rn-style-transformer/src/utils/index.ts
当使用 resource 全局注入 scss 时，如果第三方组件中有 `@use` 规则会报错：`@use` rules must be written before any other rules
因此在该 PR 中添加 `sortStyle` 方法将 `@use` 前置
相关问题：https://github.com/NervJS/taro-ui/issues/1746
=> fix(sass): fix @use rules sorting problem

packages/taro/types/api/media/audio.d.ts
=> fix:  微信createInnerAudioContext 接口类型

packages/taro-webpack-runner/src/index.ts, packages/taro-webpack5-runner/src/index.h5.ts
- 将组件编译模式开发环境配置与常规项目通用，供开发者自行配置
- 设置开发模式 `allowedHosts` 默认值为 'all'，便于开发者本地调试
=> feat(h5): update dev server config

packages/taro-router/src/router/mpa.ts, packages/taro-router/src/router/spa.ts, packages/taro-router/src/tabbar.ts, packages/taro-runtime/src/dsl/instance.ts
新增 H5 端 app.onShow 和 app.onHide 生命周期支持
=> feat(router): 新增H5端app.onShow和app.onHide生命周期

packages/taro-components-library-react/src/component-lib/reactify-wc.ts, packages/taro-components-library-react/src/react-component-lib/createOverlayComponent.tsx, packages/taro-components-library-react/src/react-component-lib/utils/attachProps.ts
- 修复 flushSync 引入导致低版本 react 抛出错误
=> fix(h5): 修复 flushSync 导致低版本 react 抛出错误

packages/taro-cli/templates/default/tsconfig.json
上一个 PR #15069 忘了跑一下项目，还遗留了一个启动时的警告：
```
[WARNING] Non-relative path "src/*" is not allowed when "baseUrl" is not set (did you forget a leading "./"?) [tsconfig.json]
```
对应的 TSC 错误：
```
TS5090: Non-relative paths are not allowed when 'baseUrl' is not set. Did you forget a leading './'?
```
=> fix(cli): 修复 tsc 错误以及项目启动时的警告 , close #15321

packages/taro-platform-harmony-hybrid/src/program.ts
=> fix(harmony-hybrid): 修复路由函数无法hook的问题

packages/taro-h5/src/utils/index.ts, packages/taro-platform-harmony-hybrid/src/api/apis/utils/index.ts
=> fix errorMsg

examples/blended-taro-component-vue3/h5/package.json, examples/blended-taro-component-vue3/taro-project/package.json, packages/taro-cli/templates/default/package.json.tmpl
```
Error: Cannot find module 'vue/compiler-sfc'
```
=> fix(cli): 修复默认模板 Vue3 搭配 pnpm8 低版本使用时报错的问题

packages/taro-platform-harmony-hybrid/src/api/apis/media/image/previewImage.ts
修复bug：harmony hybrid 模式下 previewImage根据微信小程序api设置了正确的current url时索引多加了一个
=> fix: 修复previewImage索引错误的bug

packages/taro-platform-harmony-hybrid/build/config/harmony-definition.json, packages/taro-platform-harmony-hybrid/src/api/apis/NativeApi.ts, packages/taro-platform-harmony-hybrid/src/api/apis/base/update/getUpdateManager.ts, packages/taro-platform-harmony-hybrid/src/api/apis/network/request/index.ts, packages/taro-platform-harmony-hybrid/src/api/apis/request.ts, packages/taro-platform-harmony-hybrid/src/api/apis/storage/setBackgroundFetchToken.ts
部分接口注释修以及request接口js实现添加onHeadersReceived和offHeadersReceived监听
=> fix: 部分接口注释修以及request接口js实现添加onHeadersReceived和offHeadersReceived监听

packages/taro-jd/src/components.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap, packages/taro-webpack5-runner/src/__tests__/__snapshots__/mini-platform.spec.ts.snap
为京东小程序的 Textarea 组件补充 disable-default-padding 属性
=> feat: 为京东小程序的 Textarea 组件补充 disable-default-padding 属性

packages/taro-webpack5-prebundle/src/web.ts
…ing 检查问题
**问题描述：**
webpack 升级到 v5.90+ 版本后，编译 h5 时会提示目标环境不支持 `async/await` 的提示
```
WARNING in external "taro_app_library@/remoteEntry.js"
The generated code contains 'async/await' because this module is using "external script".
However, your target environment does not appear to support 'async/await'.
As a result, the code may not run as expected or may cause runtime errors.
```
**问题原因：**
webpack v5.90 版本新增了一个 `async/await` 环境不支持的警告检查逻辑
详见：https://github.com/webpack/webpack/pull/17967
Taro webpack 的默认输出目标是 `['web', 'es5']`，由于 es5 并不支持 `async/await`，所以在开发模式下会产生 `WARNING`
```js
export class BaseConfig {
private _chain: Chain
constructor (appPath: string, config: Config) {
const chain = this._chain = new Chain()
chain.merge({
target: ['web', 'es5']
```
问题一：为什么更改了 …
=> fix(prebundle): 兼容 webpack v5.90+ 后新增的 EnvironmentNotSupportAsyncWarn

packages/taro-platform-harmony-hybrid/build/config/harmony-definition.json, packages/taro-platform-harmony-hybrid/src/api/apis/base/getAppAuthorizeSetting/index.ts, packages/taro-platform-harmony-hybrid/src/api/apis/base/getSystemSetting/index.ts, packages/taro-platform-harmony-hybrid/src/api/apis/base/getSystemSetting/oschannel.ts, packages/taro-platform-harmony-hybrid/src/api/apis/device/keyBoard/hideKeyboard/index.ts, packages/taro-platform-harmony-hybrid/src/api/apis/device/phone/index.ts
=> 默认走native，不走oschannel通道

packages/taro-router/src/style.ts
使用 navigateBack 的时候，在动画开始的时候就展示上一个页面；使用 navigateTo 的时候，在动画结束后再隐藏上一个页面
使用 navigateBack 的时候，在动画开始的时候就展示上一个页面；使用 navigateTo 的时候，在动画结束后再隐藏上一个页面
=> feat: 使用 navigateBack 的时候，在动画开始的时候就展示上一个页面；使用 navigateTo 的时候，在动画结束后再隐藏上一个页面

packages/taro-platform-harmony-hybrid/src/api/apis/comments.ts, packages/taro-platform-harmony-hybrid/src/api/apis/taro.ts, packages/taro-platform-harmony-hybrid/src/runtime/apis/index.ts
Taro Api采用继承export的方式，不再复制taro-h5、taro-plugin-react、taro-plugin-vue3里的代码，解决vue框架下缺少的api
问题复现方法：vue3框架的Taro程序，在harmony-hybrid平台下，Taro.setGlobalDataPlugin为undefined
=> [harmony-hybrid]Taro Api采用继承export的方式，不再复制taro-h5、taro-plugin-react、taro-plugin-vue3里的代码，解决vue框架下缺少的api

packages/taro-platform-harmony-hybrid/build/config/harmony-definition.json, packages/taro-platform-harmony-hybrid/src/api/apis/media/video/compressVideo.ts
=> 【harmony-hybrid】compressVideo改为canNotUse

packages/taro-platform-harmony-hybrid/src/api/apis/taro.ts, packages/taro-platform-harmony-hybrid/src/program.ts
继承Taro-H5的api的方式，由匿名继承改为显式继承，匿名继承对于CommonJS模块依赖时需要.default才能处理
=> [harmony-hybrid]继承Taro-H5的api的方式，由匿名继承改为显式继承，匿名继承对于CommonJS模块依赖时需要.default才能处理

packages/taro-platform-harmony-hybrid/src/api/apis/NativeApi.ts, packages/taro-platform-harmony-hybrid/src/api/apis/NativeApiSyncCacheProxy.ts
=> [Harmony-hybrid]Api调用支持缓存监听的机制更新，用于减少通信次数

examples/mini-program-example/src/pages/api/network/request/index.tsx, packages/taro-platform-harmony-hybrid/src/api/apis/NativeApi.ts, packages/taro-platform-harmony-hybrid/src/api/apis/interface/ClassInstanceManager.ts, packages/taro-platform-harmony-hybrid/src/api/apis/interface/NativeAContextApi.ts, packages/taro-platform-harmony-hybrid/src/api/apis/interface/NativeRequest.ts, packages/taro-platform-harmony-hybrid/src/api/apis/interface/NativeUploadFile.ts, packages/taro-platform-harmony-hybrid/src/api/apis/network/request/nativeRequest.ts, packages/taro-platform-harmony-hybrid/src/api/apis/network/upload.ts
=> feat: 优化JSBridge中类实例方法过多问题

examples/mini-program-example/src/pages/component/map/map.js, packages/taro-platform-harmony-hybrid/src/components/components-react/Map/Map.tsx
=> feat: [harmony-hybrid]同层渲染Map组件新增Marker属性支持。

examples/mini-program-example/src/pages/api/media/video/index.tsx, packages/taro-platform-harmony-hybrid/src/api/apis/media/video/chooseMedia/chooseMedia.ts, packages/taro-platform-harmony-hybrid/src/api/apis/media/video/chooseMedia/chooseMedium.ts, packages/taro-platform-harmony-hybrid/src/api/apis/media/video/chooseMedia/index.ts, packages/taro-platform-harmony-hybrid/src/api/apis/media/video/index.ts
=> 【harmony-hybrid】chooseMedia适配两种实现方式

packages/taro-platform-harmony-hybrid/src/api/apis/comments.ts, packages/taro-platform-harmony-hybrid/src/api/apis/wxml/IntersectionObserver.ts, packages/taro-platform-harmony-hybrid/src/api/apis/wxml/index.ts
[Harmony-Hybrid] createIntersectionObserver修改为独立实现，回调参数支持id和dataset
=> fix: [Harmony-Hybrid] createIntersectionObserver修改为独立实现，回调参数支持id和dataset

packages/taro-platform-harmony-hybrid/src/api/apis/NativeApi.ts, packages/taro-platform-harmony-hybrid/src/api/apis/interface/NativeFileSystemManager.ts, packages/taro-platform-harmony-hybrid/src/api/apis/media/image/NativeImage.ts, packages/taro-platform-harmony-hybrid/src/api/apis/media/image/previewImage.ts, packages/taro-platform-harmony-hybrid/src/components/components-react/Map/Map.tsx
=> feat: [harmony-hybrid]新增previewImage桥接原生

examples/mini-program-example/src/pages/api/wxml/index.tsx, packages/taro-platform-harmony-hybrid/src/api/apis/wxml/IntersectionObserver.ts
解决IntersectionObserver相关接口无效问题
=> 【harmony-hybrid】解决IntersectionObserver相关接口无效问题

packages/taro-cli/package.json, packages/taro-cli/src/create/fetchTemplate.ts, packages/taro-cli/src/create/project.ts, pnpm-lock.yaml
=> feat(cli): 支持更改 CLI 展示的模板名称

packages/taro-cli/src/cli.ts, packages/taro-cli/src/presets/commands/init.ts
`taro init` 命令新增 `autoInstall` 配置，支持关闭自动安装依赖的功能
```
Usage: taro init [options]
Options:
--name [name]                       项目名称
--description [description]         项目介绍
--typescript                        使用TypeScript
--npm [npm]                         包管理工具
--template-source [templateSource]  项目模板源
--clone [clone]                     拉取远程模板时使用git clone
--template [template]               项目模板
--css [css]                         CSS预处理器(sass/less/stylus/none)
--autoInstall                       自动安装依赖
-h, --help                          output usage information
```
=> feat(cli): taro init 命令新增 autoInstall 的配置支持

packages/taro-vite-runner/src/h5/entry.ts, packages/taro-vite-runner/src/utils/index.ts
windows 环境下，vite h5 dev 和 build 时候，resolveId 根据 configPath 判断是否 app.config.ts，但 resolve 后的路径为 posix，configPath 未转换，导致逻辑失效。
这里将 configPath 路径进行转换，同时对 dev 模式下生成 code 路径进行转换，避免 dev 解析失效
=> fix(taro-vite-runner): 修复 vite h5 dev & build 路径未转 posix 导致的异常

examples/mini-program-example/src/pages/index/index.tsx, examples/mini-program-example/src/util/nativeApi.ts, packages/taro-platform-harmony-hybrid/build/config/harmony-definition.json, packages/taro-platform-harmony-hybrid/src/api/apis/NativeApi.ts, packages/taro-platform-harmony-hybrid/src/api/apis/harmony-native/ApiDecorator.ts, packages/taro-platform-harmony-hybrid/src/api/apis/harmony-native/StorageCacheAndSyncProxy.ts
优化Taro Storage缓存，解决跨Web容器修改Storage后缓存不更新
=> 【Harmony-Hybrid】优化Taro Storage缓存，解决跨Web容器修改Storage后缓存不更新

packages/taro-cli/templates/default/template_creator.js, packages/taro-cli/templates/default/tsconfig.json, packages/taro-cli/templates/default/types/global.d.ts, packages/taro-cli/templates/default/types/solid.d.ts, packages/taro-components/types/index.solid.d.ts, packages/taro-framework-solid/src/webpack.mini.ts
修复#16357
- taro-components solid的类型定义
- solid默认模板tsc配置
- solid默认模板global.d.ts 关联taro-components类型
- solid默认模板新增solid.d.ts 拓展指令类型
- 删除solid插件dev环境下，对于solid-js包的引入重复打包的代码，因为这里会导致dev环境下，solid-js文件指向DEV环境变量丢失的问题，导致createStore使用不了等问题
=> fix: 添加solid的taro-components的类型定义 & solid的默认模板配置 & createStore api开发环境下报错的问题

packages/taro-rn-style-transformer/src/transforms/StyleSheet/ImageStylePropTypes.ts, packages/taro-rn-style-transformer/src/transforms/StyleSheet/LayoutPropTypes.ts, packages/taro-rn-style-transformer/src/transforms/StyleSheet/TextStylePropTypes.ts, packages/taro-rn-style-transformer/src/transforms/StyleSheet/TransformPropTypes.ts, packages/taro-rn-style-transformer/src/transforms/StyleSheet/ViewStylePropTypes.ts
=> feat(react-native): 更新 ReactNative 支持的 PropTypes

packages/taro-components/types/Picker.d.ts
将 textProps 移动到 PickerStandardProps 以获得准确的 ts 提示
=> fix: move textProps into the PickerStandardProps

packages/taro-components-react/src/components/swiper/index.tsx, packages/taro-components/src/components/swiper/swiper.tsx
问题表象：@tarojs/components 4.0.5版本下，使用ScrollView内嵌Swiper时，滑动Swiper失效。
问题原因：
@tarojs/components 4.0.5版本里，引用的swiper版本是11.1.0。这个版本的swiper的滑动监听touchmove默认绑定在document上（冒泡阶段）。
但使用ScrollView时，在touchmove中会调用event.stopPropagation()拦截掉事件的冒泡，导致其内嵌的Swiper滑动无响应。
问题处理思路：
修改默认参数nested，将其默认设置为true。这样的话，swiper的touchmove还是document上监听，但是是捕获阶段监听，就不会被ScrollView拦截掉。
=> fix: 修复4.0.5版本下ScrollView内嵌Swiper时，Swiper滑动无响应的问题

packages/taro-webpack5-runner/src/webpack/WebpackModule.ts
关闭 Dart Sass 的 `legacy-js-api` 的 warnings
https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#js-api
=> chore: 调整 Dart Sass 的 warnings 配置

package.json, packages/shared/src/is.ts, packages/shared/src/template.ts, packages/taro-cli-convertor/__tests__/__snapshots__/config.test.ts.snap, packages/taro-framework-solid/package.json, packages/taro-h5/package.json, packages/taro-platform-harmony/package.json, packages/taro-platform-weapp/src/components.ts, packages/taro-runtime/package.json, packages/taro-transformer-wx/package.json, pnpm-lock.yaml, tests/__tests__/__snapshots__/babel.spec.ts.snap, tests/__tests__/__snapshots__/compiler-macros.spec.ts.snap, tests/__tests__/__snapshots__/config.spec.ts.snap, tests/__tests__/__snapshots__/css-modules.spec.ts.snap, tests/__tests__/__snapshots__/framework.spec.ts.snap, tests/__tests__/__snapshots__/mini-platform.spec.ts.snap, tests/__tests__/__snapshots__/parse-html.spec.ts.snap, tests/__tests__/__snapshots__/prerender.spec.ts.snap, tests/__tests__/__snapshots__/sass.spec.ts.snap, tests/__tests__/__snapshots__/skyline.spec.ts.snap, tests/__tests__/__snapshots__/subpackages.spec.ts.snap, tests/__tests__/__snapshots__/tabbar.spec.ts.snap, tests/__tests__/__snapshots__/ts.spec.ts.snap, tests/__tests__/__snapshots__/wx-hybrid.spec.ts.snap, tests/__tests__/bundled/globby/index.js
1. 优化 isNumber 判断逻辑；
2. 修复微信 Map 组件 `setting` 属性的默认设置值问题；
=> fix(weapp): 修复微信 Map 组件在 Android 环境下且小程序基础库 v3.4.10+  出现的属性配置异常

packages/taro-framework-solid/src/runtime/connect.ts
=> fix: 修复solid的onShow,onHide不生效的bug

packages/taro-webpack5-runner/src/loaders/miniTemplateLoader.ts, packages/taro-webpack5-runner/src/utils/index.ts
Taro使用原生页面（小程序）时, 如果原生的小程序页面wxml有如下代码:（一个标签的src属性被赋值为一个data中的state值）
```
<web-view src="{{ url }}"></web-view>
```
来自data中的state值url会被异常解析
=> fix: 修复Taro使用原生页面（微信小程序）时, .wxml中的src={{url}},来自data的url被异常解析的bug

packages/taro-components-react/src/components/swiper/index.tsx, packages/taro-components/__tests__/__snapshots__/swiper.spec.tsx.snap, packages/taro-components/src/components/swiper/swiper.tsx
=> fix: 修复swiper在item数量太少时无法循环的问题

packages/babel-preset-taro/rn/index.js, packages/taro-rn-transformer/src/component.ts, packages/taro-rn-transformer/src/utils.ts
Call new api in new linaria version to implement the same functionality.
- [y ] 代码重构(Refactor)
- [y ] 移动端（React-Native）
=> upgrade linaria to latest version

packages/taro-h5/src/api/media/video/chooseMedia.ts
IOS端浏览器环境，Taro.chooseMedia，选中视频时，无法触发成功/失败的回调
=> fix: 修复IOS端H5-选中视频-不触发成功/失败回调【3.x】

packages/taro-vite-runner/src/utils/html.ts
该PR在`getHtmlScript`中使用`normalizePath`处理了路径.
此Bug应在上游处理以期彻底解决此类问题, 但我对该框架不熟悉不敢轻易修改上游代码.
类似PR: https://github.com/NervJS/taro/pull/16124
**bug简述**
Windows 下使用 vite 构建时, 由于html代码注入了有误的路径"\\app.config.ts", 导致不能被解析.
https://github.com/NervJS/taro/blob/0828d8d26a6012a88f6da7753d119218c729af6d/packages/taro-vite-runner/src/h5/config.ts#L202-L203
=> fix(vite-runner): 修复Windows环境下使用vite构建时路径错误

README.md, README_EN.md
=> chore(README): update taroify link

packages/taro/types/api/media/audio.d.ts
…at docs
Updated the `decodeAudioData` method in `WebAudioContext` to match the official WeChat Mini Program documentation:
- Modified the return type to `Promise<AudioBuffer>` instead of `AudioBuffer`, because of this method' actual response.
- Adjusted method parameters to accept `audioData`, `successCallback`, and `errorCallback`.
This fixes the TypeScript error and aligns the implementation with the expected API behavior. Closes #17080
修复了 WebAudioContext.decodeAudioData 的签名
=> fix: align WebAudioContext.decodeAudioData signature with weapp doc

packages/taro-vite-runner/src/harmony/postcss/compile.ts, packages/taro-vite-runner/src/harmony/style.ts, packages/taro/types/compile/viteCompilerContext.d.ts
为harmony下添加cssVariables选项配置，用于控制是否自动载入变量解析插件
=> feat: 鸿蒙配置添加是否支持css变量解析开关

packages/taro-h5/src/api/base/weapp/app-event.ts
=> fix(h5): the value called by `onThemeChange` callback reversed

packages/eslint-config-taro/package.json, packages/taro-framework-vue3/package.json
解决官方cli 4.0初始化时，选择vue3+vite时，存在依赖冲突 `packages/taro-framework-vue3/package.json`：
``` json
{
"devDependencies": {
"vite": "^4.2.0",
},
"peerDependencies": {
"@vitejs/plugin-vue": "^5",
"vite": "^4",
},
}
```
`@vitejs/plugin-vue` 应该和`vite`统一大版本号，否则会冲突，最小的改动就是将`@vitejs/plugin-vue` 改为：
``` sh
"@vitejs/plugin-vue": "^4",
```
这样`vite`的最低版本就是v4，如果后续需要统一将`vite`设置高一点的版本，需要将这3个同时升级。
**另外**
初始化时，和官方模板还存在一个`eslint-plugin-vue`的版本冲突：
`eslint-config-taro@4.0.9`中，`packages/eslint-config-taro/package.json`:
``` json
"peerDependencies": {
"eslint-plugin-vue": "^9.17.0"
}
```
模板 `https://github.com/NervJS/taro-project-templates/blob/v4.0/vue3-NutUI/package.json.tmpl`：
``` json
"eslint-plugin-vue": "^8.0.0",
```
这个`pr`也一并调整了，模板项目那边需要改动2处，也是考虑到最小改动，仅将`packages/eslint-config-taro`中的依赖 …
=> fix: 修复vue3框架选中vite编译工具时依赖冲突

packages/taro-runtime/src/dom-external/element.ts
ref: https://github.com/NervJS/taro/issues/17351
解决无法在alipay小程序上正常使用`getBoundingClientRect`的问题
=> fix: getBoundingClientRect在alipay小程序上的兼容

packages/taro-components/__tests__/__snapshots__/form.e2e.ts.snap, packages/taro-components/src/components/checkbox/checkbox.tsx, packages/taro-components/src/components/radio/radio.tsx
修复h5开发中Checkbox组件设置class样式不起作用
=> fix: react中Checkbox组件设置className不起作用，页面刷新之后类样式才有效果

packages/taro-platform-harmony/src/runtime-framework/solid/reconciler/props.ts, packages/taro-react/src/props.ts
taro-react 的 IS_NON_DIMENSIONAL 正则表达式中，添加了 max 字符串的判断，导致内联样式 style 中的 max 开头的属性值（如：maxHeight, maxWidth），无法正确添加 px 单位后缀，样式展示不正确。
=> Fix/style max 

packages/taro-platform-alipay/src/apis.ts, packages/taro-rn/src/lib/index.ts, tests/__tests__/__snapshots__/mini-platform.spec.ts.snap, tests/__tests__/__snapshots__/tabbar.spec.ts.snap
支付宝小程序 saveImage 已经停止维护，取消对 saveImageToPhotosAlbum 的 alias 改为直接使用 saveImageToPhotosAlbum
=> feat: 从 alipay apiDiff 移出 saveImageToPhotosAlbum

packages/taro-vite-runner/src/h5/entry.ts
本次pr修复了在Win环境下vite打包build:h5时tabbar的iconPath时路径不兼容问题。
前提准备：使用官方脚手架`npx @tarojs/cli init myApp`创建项目，选择vue3+vite构建的项目，模板选择了gitee的(为了快速)。
node版本：v22.13.1
pnpm版本：v10.6.5
可直接复现仓库：[https://github.com/gk-shi/taro-vite-h5-tabbar-error](https://github.com/gk-shi/taro-vite-h5-tabbar-error)
- 问题详述：
由于`path.join`的返回结果在Win环境和Mac/Linux环境下返回存在`/`和`\`兼容性问题，造成tabBar的icon在打包后路径出现错误，因此使用`path.posix.join`来统一路径转换的过程。
- 修改前情况：
红色箭头指的图片是在scss文件中设置的background-image能使用vite正常解析(查了vite内部用了`path.posix.join`)，用来对比
- 修改后情况：
- 另一个可能的问题：
-此处iconPath.replace(/^./, '')代码存疑：如果在tabBar配置iconPath: 'assets/images/tabbar-icon.svg'时，在vite下使用 dev:h5时会把路径第一个a字符替换掉，造成路径错误，只有配置iconPath: './assets/images/tabbar-icon.svg'才有效。
如果只是想匹配将第一个可能存在的`.`字符去掉，正则考虑改为：`/^\./`
=> fix: 修复vite打包h5时tabBar图标路径转换平台不统一造成无法展示的问题

packages/taro-h5/src/api/wxml/IntersectionObserver.ts
Taro.createIntersectionObserver， 在 **没有设定initialRatio和thresholds** 或者 **设定的initialRatio小于等于thresholds中的最小元素** 的情况下，不会在初始调用时触发回调，和微信小程序环境表现不一致
=> fix: 🐛 taro-h5 处理IntersectionObserver初始调用不触发回调的问题

packages/taro-runner-utils/src/resolve/MultiPlatformPlugin.ts
在Windows平台，reslove的路径为：D:\\projects\\example\\node_modules\\@test\\test... 执行filePath = filePath.replace(path.sep, '/');后的路径为： D:/projects\\example\\node_modules\\@test\\test...
原来的replace只能替换第一个斜杠，导致外部配置带斜杠的不会生效。如：include=['@test/test']
修复Windows下MultiPlatformPlugin无法识别斜杠的问题
=> 修复Windows下MultiPlatformPlugin无法识别斜杠的问题

.github/workflows/build-rust-binding.yml, packages/taro-alipay/src/components.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap, packages/taro-webpack5-runner/src/__tests__/__snapshots__/mini-platform.spec.ts.snap, packages/taro-webpack5-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
支付宝小程序button组件编译出来的模板缺少app-parameter，导致open-type为launchApp时无法跳转
=> fix(taro-alipay): 支付宝小程序编译button缺少appParameter
