docs/apis/open-api/payment/requestPayment.md, versioned_docs/version-3.x/apis/open-api/payment/requestPayment.md
修改 Taro.requestPayment() 当中配置参数 signType 的内容，使其并同步到微信官方最新的 wx.requestPayment 的接口文档
=> docs: 同步微信小程序支付功能文档

packages/taro-jd/src/components.ts, packages/taro-jd/types/components.d.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap
补全 `Button` 的 `bindgetphonenumber` 属性，fix #9633
=> fix(jd): 补全Button的 bindgetphonenumber 属性，fix #9633

packages/taro-rn/src/lib/file.ts
调整 formdata append 顺序以支持百度云文件上传
调整 formdata 顺序解决 百度云文件上传 400 问题
=> refactor(taro-rn): 调整 formdata append 顺序

docusaurus.config.js
=> feat: tabbar add NutUI

packages/taro-jd/src/template.ts, packages/taro-jd/types/template.d.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap
=> fix(jd): 修复京东小程序onLongPress事件失效

docs/config-detail.md, docs/react-native.md, versioned_docs/version-3.x/config-detail.md, versioned_docs/version-3.x/react-native.md
=> feat(rn): add sourcemap document

packages/taro-rn-runner/src/index.ts, packages/taro-router-rn/src/provider.ts, packages/taro-router-rn/src/router.ts
0. 修复rn build 报错
1. 修改navigationBar默认值，与小程序一致
=> fix(rn): build failed when sourcemapoutput is undefined & change default navigationBar style

packages/taro-components/h5/react/utils/reactify-wc.js, packages/taro-router/src/router.ts, packages/taro-runtime/src/dom/event.ts
- 修复小程序获取不到 `dataset` 的问题
- 修复 H5 不能设置 `dataset` 的问题，fix #9798 
- 修复 H5 多次触发 onReady 的问题
=> fix(runtime): 修复获取不到 dataset 的问题

packages/taro-router/src/api.ts
修复路由跳转时 `complete` 回调函数的触发时机，fix #9758
=> fix(router): 修复路由跳转 complete 回调的触发时机，fix #9758

packages/taro-components/src/components/input/input.tsx
修复 input 改变 focus 值时不聚焦的问题，fix #9777
=> fix(h5): 修复 input 改变 focus 值时不聚焦的问题，fix #9777

packages/taro-components-react/src/components/swiper/index.tsx, packages/taro-components/src/components/swiper/swiper.tsx
更新 Swiper 相关内容
- React 版本切换时间不准确
- Stencil 版本报错
=> fix(react): swiper 问题修复

packages/taro-router/src/api.ts
=> fix(api): router api complete

docs/components/canvas/canvas.md, versioned_docs/version-3.x/components/canvas/canvas.md
=> Update canvas.md 兼容支付宝小程序

packages/babel-preset-taro/README.md, packages/babel-preset-taro/index.js, packages/babel-preset-taro/package.json, packages/babel-preset-taro/yarn.lock, packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap, packages/taro-webpack-runner/src/config/dev.conf.ts
- 调整 `babel-preset-taro` 的 `useBuiltIns` 配置的行为，fix #9705
- 修复使用 Vue 时引入了 `fast-refresh` 的问题，fix #9843
=> fix(babel-preset-taro): 调整 useBuiltIns 的行为，fix #9705

docs/guide.mdx, versioned_docs/version-3.x/guide.mdx
=> update guide.mdx 兼容支付宝分包，修改tabBar错误配置

packages/taro-components-rn/src/components/Progress/PropsType.tsx, packages/taro-components-rn/src/components/Progress/index.tsx
1、组件 Progress 支持 borderRadius 属性；
=> feat: progress 支持 borderRadius 属性

packages/taro-components-rn/src/components/MovableArea/index.tsx, packages/taro-components-rn/src/components/MovableView/index.tsx
1、修复组件 `MovableView` 属性状态更改无效的问题；
2、修复组件 `MovableView`  `direction` 属性发生变化后，移动时元素位置跳变的问题；
=> fix(rn): 修复 MovableView 组件状态变更无效及滑动时跳变的问题

packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/__tests__/index.spec.js, packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/src/index.ts
=> fix: 修复 css module 变量多次赋值判断失效

packages/taro-runtime-rn/src/page.ts
1、`Taro.pageScrollTo` 支持以 Promise 风格调用
=> feat(rn): pageScrollTo 支持以 Promise 风格调用

packages/taro/types/api/device/motion.d.ts
1、修复类型错误；
https://docs.taro.zone/docs/apis/device/motion/offDeviceMotionChange，参数可为空
=> fix: offDeviceMotionChange types

packages/taro-rn/src/lib/clearStorageSync/index.ts, packages/taro-rn/src/lib/getStorageInfoSync/index.ts, packages/taro-rn/src/lib/getStorageSync/index.ts, packages/taro-rn/src/lib/removeStorageSync/index.ts, packages/taro-rn/src/lib/setStorageSync/index.ts, packages/taro-rn/src/lib/unsupportedApi.ts
=> refactor(rn): refactor unsupported api

packages/shared/src/template.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-qq/src/index.ts, packages/taro-qq/src/program.ts, packages/taro-qq/types/index.d.ts, packages/taro-qq/types/program.d.ts, packages/taro-service/src/utils/index.ts, packages/taro-weapp/src/index.ts, packages/taro-weapp/src/program.ts, packages/taro-weapp/src/template.ts, packages/taro-weapp/types/index.d.ts, packages/taro-weapp/types/program.d.ts, packages/taro-weapp/types/template.d.ts
- 修复 `Textarea` 组件的 `showConfirmBar` 属性失效的问题 ，fix #9923
- 为微信小程序插件增加 `enablekeyboardAccessory` 参数，用于支持使用 `<keyboard-accessory>` 组件，#9548
=> fix(weapp): 修复 textarea 组件，fix #9923

CONTRIBUTING.md
- 支持使用 Vue DevTools，详细用法请见[文档](https://docs.taro.zone/docs/vue-devtools)
- `Progress` 组件支持 `borderRadius` 属性，by @iChengbo 
- `startPullDownRefresh`、`stopPullDownRefresh`、`pageScrollTo` 支持以 Promise 风格调用，by @iChengbo  
- 调用 `setStorageSync` 等 RN 端不支持的 API 时，提示不支持，by @iChengbo 
- 重构**设备方向**相关 API，并新增 `offDeviceMotionChange`，by @iChengbo 
- 实现 `setKeepScreenOn` API 的按需加载，by @iChengbo 
- 提供二维码打印，供后续APP扫码加载 
- 优化分包提取插件，by @huangcj99 
- 修复开发者工具因找不到 `sub-common` 下的文件而导致报错的问题，by @huangcj99 
- 修复分享朋友圈后再进入页面，显示白屏的问题，fix #9899
- 修复 `catchMove` 设置 `false` 时失败的问题，fix #9916
- 修复 `catchMove` 不能动态切换的问题，fix #9488
- 优化对 `comment` 节点的处理，fix #9864
- 修复 `Textarea` 组件的 `showConfirmBar` 属性失效的问题 ，fix #9923
- 为微信小程序插件增加 `enablekeyboardAccessory` 参数，用于支持使用 `<keyboard-accessory>` 组件，fix #9548
- 修复 `onShow` 时调用 …
=> chore(release): publish 3.3.2

packages/taro-components-rn/src/components/Button/index.tsx
=> fix(rn): add default hoverStyle for button

versioned_docs/version-3.x/nutui.mdx, versioned_sidebars/version-3.x-sidebars.json
=> docs: feat 社区生态 vue3 nutui 使用说明

packages/taro-components-rn/src/components/Switch/PropsType.tsx, packages/taro-components-rn/src/components/Switch/index.tsx
=> feat(rn): switch 组件支持 disabled 属性

versioned_docs/version-3.x/nutui.mdx
=> docs: fix nutui 主题定制使用方式描述修改

docs/codebase-overview.md, versioned_docs/version-3.x/codebase-overview.md
=> docs: update rn packages

README.md
=> docs(badge)

lerna.json, package.json, yarn.lock
- 升级 lerna 4
- 优化 `lerna version` 的流程，现在只需要 `npm run version --lerna-version=<version>` 就会跑 `lerna version`、`git` 提交、输出 change log。
=> chore: lerna

docs/treasures.md
=> docs(taro-hooks): add taro-hooks repo info

packages/taro-components-rn/__tests__/__snapshots__/checkbox.spec.tsx.snap, packages/taro-components-rn/src/components/Button/index.tsx, packages/taro-components-rn/src/components/Checkbox/index.tsx, packages/taro-components-rn/src/components/CheckboxGroup/index.tsx, packages/taro-components-rn/src/components/Label/index.tsx, packages/taro-components-rn/src/components/Radio/index.tsx, packages/taro-components-rn/src/components/RadioGroup/index.tsx, packages/taro-components-rn/src/components/Switch/index.tsx
1、修复打包后 CheckBox 和 Radio 报错的问题；
2、修复 release 包 child.type.name 错误的问题;
=> fix(rn): 修复 release 版本中，checkbox、radio 等组件异常情况

docs/config-detail.md, versioned_docs/version-3.x/config-detail.md
文档 rn 配置增加 enableMultipleClassName && enableMergeStyle
=> docs: rn 配置增加 enableMultipleClassName && enableMergeStyle

docs/config-detail.md, versioned_docs/version-3.x/config-detail.md
=> docs: rn 配置 rn.resolve 描述修改

docs/58anjuke.md, sidebars.js, versioned_docs/version-3.x/58anjuke.md, versioned_sidebars/version-3.x-sidebars.json
=> doc: add 58anjuke team

docs/react-native.md, versioned_docs/version-3.x/react-native.md
=> docs: update react native doc

packages/shared/src/components.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/nerv.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap
修复 Button 组件不触发 touch 事件的问题，fix #10074 
=> fix(shared): 修复 Button 组件不触发 touch 事件的问题，fix #10074

packages/taro-rn/src/lib/connectSocket/index.ts, packages/taro-rn/src/lib/connectSocket/socketTask.ts, packages/taro-rn/src/lib/file.ts, packages/taro-rn/src/lib/getClipboardData/index.ts, packages/taro-rn/src/lib/getLocation/index.ts, packages/taro-rn/src/lib/getStorageInfo/index.ts, packages/taro-rn/src/lib/getSystemInfo/index.ts, packages/taro-rn/src/lib/makePhoneCall/index.ts, packages/taro-rn/src/lib/media.ts, packages/taro-rn/src/lib/network.ts, packages/taro-rn/src/lib/openUrl/index.ts, packages/taro-rn/src/lib/permission.ts, packages/taro-rn/src/lib/removeStorage/index.ts, packages/taro-rn/src/lib/request/index.ts, packages/taro-rn/src/lib/setClipboardData/index.ts, packages/taro-rn/src/lib/showActionSheet/index.tsx, packages/taro-rn/src/lib/showModal/index.tsx, packages/taro-rn/src/lib/showModal/toast.tsx, packages/taro-rn/src/lib/vibrate.ts
0. openSetting getSetting 参数改为可选
1. 写法统一
=> fix(rn): getSetting, openSetting opt optional

packages/taro-rn/src/lib/createCameraContext/index.ts
=> chore(rn): update CameraContext.takePhoto

packages/taro/types/api/open-api/navigate.d.ts
=> fix: exitMiniProgram 的参数应该是可选的

packages/taro-rn/src/lib/media.ts, packages/taro-rn/src/lib/permission.ts, packages/taro-rn/src/lib/vibrate.ts
1、优化 promise 调用方式，统一使用 `successHandler` 和 `errorHandler`
=> chore(rn): 优化代码写法

packages/taro-plugin-vue-devtools/src/index.ts
- 修复 vue devtools 报错，fix #10153
=> fix(vue-devtools): 修复 vue devtools 报错，fix #10153

packages/taro-rn/src/lib/keyboard.ts, packages/taro/types/api/ui/keyboard.d.ts
1、替换 keyboard.d.ts 失效地址；
2、hideKeyboard 支持 Promise 方式进行调用；
=> chore(rn): hideKeyboard 支持 promise 及修复 types 参考链接

packages/taro-runtime-rn/src/compute.ts
=> chore(rn): replace parseInt with ~~

packages/taro-components-rn/src/components/Button/PropsType.tsx, packages/taro-components-rn/src/components/Button/index.tsx
问题：Button 组件连续改变 loading 时，动画会出现异常的情况
方案：重构 Button 组件的 loading 实现方式
=> refactor(rn): 重构 Button 组件 loading 实现方式

packages/taro-rn/src/lib/clearStorage/index.ts, packages/taro-rn/src/lib/getStorage/index.ts, packages/taro-rn/src/lib/getStorageInfo/index.ts, packages/taro-rn/src/lib/setStorage/index.ts
1、统一 Storage 相关 API 的写法：使用 `successHandler` 和 `errorHandler`
=> chore(rn): 更新 Storage 相关 API 的代码风格

packages/taro-rn-style-transformer/src/transforms/sass.ts
=> fix(rn-style-transformer): 解决 sass import 报错

packages/taro-runtime/src/dom/root.ts, packages/taro-runtime/src/next-tick.ts
fix(mini): 修复 nextTick 没有触发的问题，fix #10179
=> fix(mini): 修复 nextTick 没有触发的问题，fix #10179

packages/taro-rn/src/lib/chooseImage/index.ts, packages/taro-rn/src/lib/compressImage/index.ts
=> fix(rn): 修复压缩图片时尺寸问题,并更新代码风格

packages/taro-components-rn/src/components/Slider/index.tsx
1、修复 Slider 组件设置 showValue 时, 其 value 不随滑动而改变的问题
=> fix(rn): 修复 Slider 设置 showValue 时, 其 value 不随滑动而改变的问题

packages/taro-alipay/src/components.ts, packages/taro-components/types/Text.d.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap, packages/taro-tt/src/components.ts, packages/taro-tt/src/template.ts
- 补全 `Text` 组件的 `userSelect` 属性的类型，fix #10058
- 修复字节小程序不支持 `onLongPress` 事件的问题，fix #10069
- 补全字节小程序 `TextArea` 组件的属性，fix #10083
- 补全支付宝小程序 `Canvas` 组件的 `type` 和 `onReady` 属性，fix #9990
=> 修复各小程序组件、API 问题

packages/taro-components-rn/src/components/Button/index.tsx
1、修复 Button 组件设置 hoverStyle 文本样式时，点击不能生效的问题; fix https://github.com/NervJS/taro/issues/10173
=> fix(rn): 修复 Button 组件设置 hoverStyle 文本样式无效的问题

packages/taro-alipay/src/runtime-utils.ts
=> fix(alipay): 补充导出钉钉小程序插件需要的内容，fix #10075

packages/taro-rn/src/lib/request/index.ts
1、request 支持 timeout，fix https://github.com/NervJS/taro/issues/10214
=> feat(rn): request add timeout option

packages/taro-rn-style-transformer/__tests__/config.spec.js, packages/taro-rn-style-transformer/__tests__/index.spec.js, packages/taro-rn-style-transformer/__tests__/platform.spec.js, packages/taro-rn-style-transformer/jest.config.js, packages/taro-rn-style-transformer/package.json, packages/taro-rn-style-transformer/src/transforms/index.ts, packages/taro-rn-style-transformer/src/transforms/less.ts, packages/taro-rn-style-transformer/src/transforms/postcss.ts, packages/taro-rn-style-transformer/src/transforms/sass.ts, packages/taro-rn-style-transformer/src/transforms/stylus.ts, packages/taro-rn-style-transformer/src/types/index.ts, packages/taro-rn-style-transformer/src/utils/index.ts, packages/taro-rn-style-transformer/src/utils/reporterSkip.ts, packages/taro-rn-style-transformer/yarn.lock
=> feat(rn-style-transformer): RN 样式错误日志优化以及代码调整

docs/react-native.md, versioned_docs/version-3.x/react-native.md
=> feat(rn): 补充对rn版本的兼容情况

.gitignore, docs/project-config.md, versioned_docs/version-3.x/project-config.md
- 修改了飞书小程序配置为project.lark.json
- 补充了相关的说明，提示飞书插件版本需为1.0.2以上
=> docs: 修改飞书小程序配置文件名与补充说明

versioned_docs/version-3.x/components/forms/button.md
修改支付宝支持props
修改支付宝 form button支持props
=> 修改支付宝支持props

packages/taro-runtime/src/bom/raf.ts
修复 Illegal invocation 报错，fix #9888
#10007 
=> fix(runtime): 修复 Illegal invocation 报错，fix #9888

docs/plugin-mini-ci.md
=> docs(@taro/plugin-mini-ci): 文档同步

lerna.json, packages/taro-plugin-mini-ci/README.md
将 `@tarojs/plugin-mini-ci` 纳入 `lerna` 版本管理
=> fix: 将 @tarojs/plugin-mini-ci 纳入 lerna 版本管理;文档包名有误

docusaurus.config.js, i18n/en/docusaurus-plugin-content-docs/current.json, i18n/en/docusaurus-theme-classic/navbar.json, package.json
=> docs:  优化文档导航与无用配置删除

packages/taro-components-rn/src/components/Button/index.tsx, packages/taro-router-rn/src/rootNavigation.ts, packages/taro-router-rn/src/router.ts, packages/taro-router-rn/src/utils/index.ts, packages/taro-runtime-rn/src/page.ts
1. 去除redirectTo跳转的动画效果
2.  button组件卸载时与app 退到后台时的warning
=> fix(router-rn): fix rn router memory leak & remove redirect animate

packages/taro-router-rn/src/rootNavigation.ts, packages/taro-router-rn/src/router.ts, packages/taro-router-rn/src/utils/index.ts
=> fix: revert fix(rn): 去除redirectTo的动画效果

packages/taro-service/src/Kernel.ts, packages/taro-service/src/Plugin.ts
=> fix(service): registerMethod 支持注册同名方法

packages/taro-cli/src/doctor/configSchema.ts
=> fix(cli): esnextModules 配置可为正则

README.md
=> docs: 更新链接 #10319

packages/taro-harmony/src/components/components-harmony/scroll-view/index.css, packages/taro-harmony/src/components/components-harmony/scroll-view/index.hml, packages/taro-harmony/src/components/components-harmony/scroll-view/index.js, packages/taro-harmony/src/template.ts
- 新增鸿蒙的 `ScrollView` 组件
```jsx
import { Component } from 'react'
import { View, Text, ScrollView } from '@tarojs/components'
import './index.scss'
state = {
scrollTop: 0,
scrollLeft: 0
}
upper (e) {
console.log('on scroll to upper: ')
console.log(JSON.stringify(e))
}
lower (e) {
console.log('on scroll to lower: ')
console.log(JSON.stringify(e))
}
render () {
return (
<View className='demo'>
<View onClick={() => {
this.setState({
scrollTop: this.state.scrollTop + 50
})
}}
>
<Text>click: {this.state.scrollTop}</Text>
</View>
<View className='page-section-spacing'>
<ScrollView
className='scroll-view'
scrollY
scrollTop={this.state.scrollTop}
onScrollToUpper={this.upper}
onScrollToLower={this.lower}
>
<View …
```
=> feat(harmony): 增加 ScrollView 组件

packages/taro-harmony/src/components/components-harmony/slider/index.hml, packages/taro-harmony/src/components/components-harmony/slider/index.js, packages/taro-harmony/src/components/index.ts
```
import { Component } from 'react'
import { View, Text, Slider } from '@tarojs/components'
import './index.less'
constructor(props) {
super(props)
}
componentWillMount () { }
componentDidMount () { }
componentWillUnmount () { }
componentDidShow () { }
componentDidHide () { }
handleChange(e) {
console.info('handleChange----' + JSON.stringify(e.detail))
}
handleChanging(e) {
console.info('handleChanging----' + JSON.stringify(e.detail))
}
render () {
return (
<View className='index'>
<View>
<Text>测试事件</Text>
</View>
<View>
<Slider onchanging={this.handleChanging} onchange={this.handleChange}></Slider>
</View>
<View>
<Text>测试属性</Text>
</View>
<View>
<Slider show-value …
```
=> feat(harmony): 新增 slider 组件

packages/taro-harmony/src/components/components-harmony/radio-group/index.hml, packages/taro-harmony/src/components/components-harmony/radio-group/index.js, packages/taro-harmony/src/components/components-harmony/radio/index.hml, packages/taro-harmony/src/components/components-harmony/radio/index.js, packages/taro-harmony/src/components/index.ts
新增Taro适配harmony radio&radio-group组件
**组件测试代码:**
```
constructor(props) {
super(props);
this.bindChange = this.bindChange.bind(this)
}
state = {
list: [
{
value: '美国',
text: '美国',
checked: false
},
{
value: '中国',
text: '中国',
checked: true
},
{
value: '巴西',
text: '巴西',
checked: false
},
{
value: '日本',
text: '日本',
checked: false
},
{
value: '英国',
text: '英国',
checked: false
},
{
value: '法国',
text: '法国',
checked: false
}
]
}
render() {
return (
<View className='container'>
<Text className='text-title'>默认样式</Text>
<View className='radio-orientation'>
<Label>
<Radio value='选中' checked id='0' group-id='group1' />
<Text className='title'>选中</Text>
</Label>
<Label>
<Radio …
```
=> Harmony comp radio

packages/taro-harmony/src/components/components-harmony/image/index.css, packages/taro-harmony/src/components/components-harmony/image/index.hml, packages/taro-harmony/src/components/components-harmony/image/index.js, packages/taro-harmony/src/components/index.ts
```
// index.jsx
import { Component } from 'react'
import { View, Text, Image, Label } from '@tarojs/components'
import './index.less'
constructor(props) {
super(props)
}
componentWillMount () { }
componentDidMount () { }
componentWillUnmount () { }
componentDidShow () { }
componentDidHide () { }
onload(e) {
console.info('onload----' + JSON.stringify(e.detail))
}
onerror(e) {
console.info('onerror----' + JSON.stringify(e.detail))
}
render () {
return (
<View className='index'>
<View>
<Text>测试demo</Text>
</View>
<View className='small'>
<Image
onload={this.onload}
src="https://img11.360buyimg.com/imagetools/jfs/t1/207234/35/4004/67873/615e9fd4E7bf0d7fc/6510e3405b94869a.jpg"> …
```
=> 重新提交 image 组件

packages/taro-router/package.json, packages/taro-router/src/router.ts, packages/taro-router/yarn.lock
https://github.com/remix-run/history/commit/04a01ad4500720e26ebbf3d9cfefbd6c1a86be84
history 库近期升级修改了类型，taro-router lock文件未更新，导致 [ci build 报错](https://github.com/NervJS/taro/runs/4100492875?check_suite_focus=true)
=> fix(taro-router): type error

packages/taro-harmony/src/components/components-harmony/web-view/index.hml, packages/taro-harmony/src/components/components-harmony/web-view/index.js, packages/taro-harmony/src/template.ts
- 新增Webview组件
DEMO
```jsx
import { Component } from "react";
import { WebView } from "@tarojs/components";
componentWillMount() {}
componentDidMount() {}
componentWillUnmount() {}
componentDidShow() {}
componentDidHide() {}
onLoad = (e) => {
console.log(e.detail.url);
};
onError = (e) => {
console.log(e.detail.url);
};
render() {
return (
<WebView
src='https://www.baidu.com'
onLoad={this.onLoad}
onError={this.onError}
></WebView>
);
}
}
```
**须在config.json中配置网络权限**
```json
{
"module": {
"reqPermissions": [
{
"name": "ohos.permission.INTERNET"
}
]
}
}
```
=> feat(harmony): 新增Webview组件

docs/treasures.md, versioned_docs/version-3.x/treasures.md
=> docs: 增加社区优秀物料

versioned_docs/version-3.x/README.mdx
=> docs: 添加飞书链接

versioned_docs/version-3.x/vant.mdx
=> docs: 丰富Taro社区生态

README.md
=> chore: 更新 readme

packages/taro-components/src/components/checkbox/checkbox.tsx
=> fix(h5): add disabled prop to checkbox #8500

README.md
为 readme.md 文档中的 UI 库添加 git repo 地址
=> chore: 添加 UI 组件库的 git repo 地址

packages/taro-h5/src/taro/index.js, packages/taro-router/src/api.ts
1. 修复 getApp 方法，fix #9586
2. 修复路由跳转 api 回调监听错误，fix #10602 
=> fix(api): 修复 h5 api 若干

packages/taro-components/src/components/swiper/swiper.tsx
优化 swiper 组件 circular 状态下 previousMargin、nextMargin 参数
=> fix(component): swiper 播放 next-margin 参数优化

packages/taro-runtime/src/__tests__/html.spec.js, packages/taro-runtime/src/dom-external/inner-html/parser.ts
=> fix: Taro.options.html.transformText invalid

packages/taro/types/global.d.ts, packages/taro/types/taro.extend.d.ts
=> fix(types): 优化类型实体写法 fix #10652

README.md
=> 可以运行在 xxx 上运行的应用 > 可以运行在 xxx 上的应用

packages/taro-swan/src/runtime-utils.ts
百度小程序在 onInit 中初始化taro,显著提升页面首屏速度
=> 百度小程序在onInit 中初始化taro

docs/codebase-overview.md, i18n/en/docusaurus-plugin-content-docs/current/codebase-overview.md, i18n/en/docusaurus-plugin-content-docs/version-3.x/codebase-overview.md, versioned_docs/version-3.x/codebase-overview.md
=> docs: taojs to tarojs

docs/react-native.md, i18n/en/docusaurus-plugin-content-docs/current/react-native.md, versioned_docs/version-3.x/react-native.md
=> fix(docs): 关于rn版本兼容的说明

packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/nerv.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap, packages/taro-weapp/src/apis-list.ts, packages/taro/types/api/device/network.d.ts
增加对 `getLocalIPAddress` API 的支持，fix #10631
=> feat(weapp): 增加对 getLocalIPAddress API 的支持，fix #10631

packages/taro-runtime/src/dom/element.ts
修复 Vue3 Input 设置自动聚焦失败的问题，fix #10579
=> fix(runtime): 修复 Vue3 Input 设置自动聚焦失败的问题，fix #10579

versioned_docs/version-3.x/components/forms/picker.md
=> fix(picker): 单词拼写

README_EN.md
=> docs(readme): fix english readme

packages/taro-rn-style-transformer/src/transforms/postcss.ts
=> feat(rn-style-transformer): postcss 支持插件自定义

packages/taro-harmony/src/apis/index.ts, packages/taro-harmony/src/apis/router/index.ts, packages/taro-harmony/src/components/components-harmony/navbar/index.js, packages/taro-harmony/src/components/components-harmony/navigator/index.js, packages/taro-harmony/src/components/components-harmony/tabbar/index.js, packages/taro-harmony/src/runtime-utils.ts
测试demo： https://github.com/JSZabc/demo
=> feat(harmony): 新增 router api

packages/taro-components-rn/__tests__/__snapshots__/richText.spec.tsx.snap, packages/taro-components-rn/src/components/RichText/index.tsx
=> fix: update rn rich text height on load again

packages/taro-router/src/router/index.ts, packages/taro-router/src/router/page.ts, packages/taro-router/src/router/stack.ts
- delta 未知情况下调整计算方案（取最小值，避免有 tabbar 情况异常，同时也考虑到移动端大部分情况只返回一次）
- 堆栈为空时强行刷新页面，避免白屏情况
=> fix(router): 路由优化

packages/taro-components/src/components/tabbar/tabbar.tsx, packages/taro/types/taro.component.d.ts
=> feat(components): tabbar 初始配置修复

packages/postcss-pxtransform/index.js, packages/taro-mini-runner/src/webpack/postcss.conf.ts
引入 2.x PR 修复小程序单位转换问题（不与 ifdef 同时有效） fix #10752
=> fix(postcss): 小程序单位转换问题修复 fix #10752

packages/taro-harmony/src/components/components-harmony/button/index.hml
修复button组件类名及类型不统一问题
测试代码：
```
export default class ButtonTest extends React.Component {
onHandleChange = e => {
console.log(e)
}
formSubmit = e => {
console.log(JSON.stringify(e))
}
formReset = e => {
console.log(e)
}
render() {
return (
<View className='components-page'>
<Form onSubmit={this.formSubmit} onReset={this.formReset}>
<View className='components-page_body'>
<View className='components-page__body-example'>
<View className='example-body'>
<Input
name='text'
type='text'
placeholder={'请输入文字'}
onChange={this.onHandleChange} ></Input>
</View>
<View className='example-body'>
<Input
name='number'
type='number'
placeholder={'请输入数字'}
onChange={this.onHandleChange} ></Input>
</View>
<View className='example-body'> …
```
=> fix(harmony) 修复button组件类名及类型不统一

packages/taro-components-rn/package.json, packages/taro-components-rn/src/components/Image/PropsType.tsx, packages/taro-components-rn/src/components/Image/index.tsx, packages/taro-components-rn/yarn.lock, packages/taro-components/types/Image.d.ts, packages/taro-rn-supporter/package.json, packages/taro-rn-supporter/src/Support.ts, packages/taro-rn-supporter/src/defaults.ts, packages/taro-rn-supporter/src/taroTransformer.ts, packages/taro-rn-supporter/src/types/index.ts, packages/taro-rn-supporter/yarn.lock
1. 支持远程 svg 图片。不支持定义 mode。
```jsx
<Image className="load-header-icon" src="https://wos2.58cdn.com.cn/DeFazYxWvDti/frsupload/a09e0f9edc9a76b3e9e69aeff9c794f1_homer-simpson.svg" />
```
2. 支持本地 svg 图片。不支持定义 mode。需显式设置prop svg 为true。
```jsx
import ReactSvg from "@/assets/react.svg";
<Image className="load-header-icon" src={ReactSvg} svg />
```
4. 支持 svgx 组件。将 svg 文件重命名为 svgx。
```jsx
import Logo from "@/assets/react.svgx";
<Logo width={120} height={40} />
```
5. 支持 svg 组件。需开启 enableSvgTransform，此时 2 无效（存在冲突）
```jsx
import Logo from "@/assets/react.svg";
<Logo width={120} height={40} />
```
```js
module.exports = {
rn: {
enableSvgTransform: false
}
}
```
Closes wuba#211
=> Feat rn add svg support

packages/taro-router/src/router/index.ts
=> fix(h5): 配置 basename 后没有设置上 HTML 标题

packages/taro-router/src/router/index.ts, packages/taro-router/src/tabbar.ts, packages/taro/types/taro.config.d.ts
https://developers.weixin.qq.com/miniprogram/dev/reference/configuration/app.html
- H5 添加 `entryPagePath` 支持
- 补充类型
=> feat: add `entryPagePath` support

blog/2021-12-08-Taro-3.5-canary.md, docs/harmony.md, versioned_docs/version-3.x/harmony.md
=> fix: fix harmony build doc

packages/shared/src/template.ts, packages/taro-alipay/src/template.ts, packages/taro-mini-runner/src/plugins/TaroNormalModulesPlugin.ts
=> fix( alipay): 兼容支付宝 2.0 构建，fix #10162

packages/taro-runtime/src/dsl/common.ts, packages/taro-runtime/src/dsl/vue3.ts
- 修复 Vue3 首次进入页面会触发两次 onShow 的问题，fix #10728
- 修复微信小程序热重载报错的问题，fix #10722
=> fix(runtime): 修复 Vue3 首次进入页面会触发两次 onShow 的问题，fix #10728

packages/taro-mini-runner/src/webpack/vue.ts
修复 Vue2 `Video` 组件不能设置 muted 的问题，fix #9550 
=> fix(mini-runner): 修复 Vue2 video 组件不能设置 muted 的问题，fix #9550

packages/taro-components/__tests__/block.spec.js, packages/taro-components/h5/react/index.js
在 React 中 Block 组件使用 React.Fragment，fix #10285
=> fix(components): 在 React 中 Block 组件使用 React.Fragment，fix #10285

docs/components/viewContainer/scroll-view.md, versioned_docs/version-3.x/components/viewContainer/scroll-view.md
=>  docs: 修复拼写

packages/taro/types/api/ui/interaction.d.ts
https://developers.weixin.qq.com/miniprogram/dev/api/ui/interaction/wx.showActionSheet.html
=> fix(type): add new option in showActionSheet

packages/taro/types/taro.extend.d.ts
=> feat(types): add Events fix #10880

packages/taro-components/__tests__/button.spec.js, packages/taro-router/src/api.ts, packages/taro-router/src/router/index.ts, packages/taro-router/src/router/stack.ts
修复同页参数缺失问题 fix #10903 
reLaunch 清空路由栈 fix #9724 fix #8347
=> feat(router): last page index fix #10903

packages/taro-components/src/components/navigator/navigator.tsx, packages/taro-components/src/components/pull-to-refresh/pull-to-refresh.tsx, packages/taro-components/src/components/tabbar/tabbar.tsx, packages/taro-components/stencil.config.ts, packages/taro-components/virtual-list/react/createListComponent.js, packages/taro-router/rollup.config.js, packages/taro-router/src/api.ts, packages/taro-router/src/router/index.ts, packages/taro-router/src/utils.ts, packages/taro-router/types/index.d.ts
=> feat(router): 多路由配置 fix #9289

packages/taro-components-rn/.eslintrc.js, packages/taro-components-rn/src/components/Swiper/carousel.tsx, packages/taro-components-rn/src/components/Swiper/pagination.tsx
=> fix(rn): swiper support circular

packages/taro-components-rn/src/components/Swiper/carousel.tsx
0. 安卓在swiper 无限滑动的情况下，第一个左滑，有些卡顿
=> fix: android swiper bug

packages/taro-h5/src/api/base/system/index.ts, packages/taro-h5/src/api/device/accelerometer.ts, packages/taro-h5/src/api/device/compass.ts, packages/taro-h5/src/api/device/motion.ts, packages/taro-h5/src/api/location/index.ts, packages/taro-h5/src/api/network/websocket/index.ts, packages/taro-h5/src/api/storage/index.ts, packages/taro-h5/src/api/ui/animation/index.ts, packages/taro-h5/src/api/ui/pull-down-refresh.ts, packages/taro-h5/src/api/utils/index.ts, packages/taro-h5/src/api/wxml/nodesRef.ts, packages/taro-h5/src/api/wxml/selectorQuery.ts, packages/taro/types/api/ui/animation.d.ts
- 优化 animation 类型，并补齐代码提示
- 修复 animation 部分遗漏
- 补齐部分 API 导出缺失
=> fix(h5): createAnimation 部分 API 错误修复

packages/taro-alipay/src/template.ts
=> fix(alipay): fix #10162

packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/__tests__/index.spec.js, packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/src/index.ts
1. jsx className 表达式返回 style 对象代替数组
=> feat(jsx-to-style): jsx className 表达式返回 style 对象代替数组

packages/taro-rn/.eslintrc.js, packages/taro-rn/src/lib/scanCode/index.tsx
扫码api调用时，默认为全屏模式
closes #10896
=> feat: scancode has fullscreen as default

packages/taro-runtime-rn/src/page.ts
closes #10907
受影响
0. getCurrentInstance().router
1. useRouter
2. Current.router
3. getCurrentPages
可能受影响，页面的各种跳转接口
=> fix(runtime-rn): update route from getCurrentPages

packages/taro-components/__tests__/audio.spec.js, packages/taro-components/__tests__/button.spec.js, packages/taro-h5/rollup.config.js, packages/taro-runtime/src/dsl/vue3.ts
- 修复 h5 vue3 appid 获取
- h5 api 打包排除 @bable/runtime/*
=> fix(h5): 修复 vue3 appId fix #10974

packages/taro-h5/rollup.config.js, packages/taro-h5/src/api/network/download.ts, packages/taro-h5/src/api/network/upload.ts
- 避免 rollup tree-shaking 移除关联样式 fix #10958
- 断言修复 task 问题 fix #10980
=> fix(h5): 避免 rollup 移除样式 fix #10958

docs/config-detail.md, versioned_docs/version-3.x/config-detail.md
=> docs: add rn.enableSvgTransform

packages/taro/types/api/media/image.d.ts, packages/taro/types/api/media/video.d.ts
=> feat(types): 添加 openVideoEditor 方法的类型定义

package.json
防止提交不符合规范的代码
项目内`lint-staged`只配置了 `js` format ,新增了 `ts` `json` 的格式化,避免提交不规范代码,且项目内大多数文件都是ts,目前eslint都支持格式化
=> pref: 修改 `lint-staged` 新增 `ts` `json` 格式化

packages/taro-router/babel.config.json, packages/taro-router/rollup.config.js, packages/taro-router/src/animation.ts, packages/taro-router/src/router/page.ts, packages/taro-router/tsconfig.json, packages/taro-runtime/src/dsl/common.ts
- 调整页面栈推入时机
- browser 模式 search 参数问题 fix #11004
=> fix(router): browser 模式 search 参数问题 fix #11004

packages/taro-h5/src/api/canvas/CanvasContext.ts, packages/taro-h5/src/api/canvas/createCanvasContext.ts, packages/taro-h5/src/api/media/image/previewImage.ts, packages/taro-h5/src/api/ui/animation/index.ts, packages/taro-h5/src/api/wxml/nodesRef.ts, packages/taro-h5/src/api/wxml/selectorQuery.ts, packages/taro/types/api/canvas/index.d.ts
支持 NodesRef.node & NodesRef.context (video、canvas) 方法 fix #9461
修复 canvasContext API 错误 fix #10931
修复 SelectorQuery.selectViewport API 错误 fix #7553
=> fix(h5): canvas context api fix #10931

packages/taro-components-rn/src/components/Button/index.tsx
=> fix(components-rn): button hasSibling 逻辑调整

packages/taro-cli/src/presets/commands/help.ts, packages/taro-cli/src/presets/index.ts, packages/taro-service/src/Kernel.ts
=> feat(cli): 增加 help 命令

README.md
开发小程序应用时我们经常会受到包体积的掣肘，大型应用常常为了“尺土寸金”的包体积开展瘦身行动。在此背景下 React 将近 100k 的体积则显得有点过于奢侈。因此 Taro v3.4 实现了对 Preact 的支持，仅需少量配置即可从 React 切换到 Preact，有效地降低了包体积。
> [Preact](https://preactjs.com/) 是一款体积超小的类 React 框架，提供和 React 几乎一致的 API，兼容 React 生态，而体积只有 5k 左右。
> 
适配思路与具体用法请参阅  [《Taro v3.4 发布 beta 版本 —— 支持使用 Preact 进行开发》](https://docs.taro.zone/blog/2021-11-24-Taro-3.4-beta#%E6%94%AF%E6%8C%81%E4%BD%BF%E7%94%A8-preact)
> [文档地址](https://docs.taro.zone/docs/next/composition-api)
> 
Vue 3.2 正式推出了 [script setup](https://v3.vuejs.org/api/sfc-script-setup.html#basic-syntax) 语法，过去 Taro 的 Options 式小程序生命周期钩子难以配合 script setup 语法进行使用。因此 Taro v3.4 提供了 Composition API 版本的小程序生命周期钩子，方便开发者配合 setup 语法组织和复用代码逻辑。
例子：
```html
<script setup>
import { useDidShow } from '@tarojs/taro'
useDidShow(() => console.log('onShow')) …
```
=> chore(release): publish 3.4.0

packages/postcss-pxtransform/index.js, packages/taro-rn-style-transformer/src/transforms/index.ts, packages/taro-runtime-rn/src/compute.ts
=> fix(rn-style): 修改RN 样式计算逻辑与小程序保持一致

docs/external-libraries.md
=> update: require webpack package

packages/taro-components/types/Input.d.ts
https://developers.weixin.qq.com/miniprogram/dev/component/input.html
=> fix(types): 添加 Input 组件的类型定义

docs/external-libraries.md
Fix undefined issue when Taro component used;
Load Taro component style;
Run initPxTransform() automatic before storybook loaded;
Fix undefined issue when Taro component used;
Load Taro component style;
Run initPxTransform() automatic before storybook loaded;
=> update: enhance storybook usage in Taro project

packages/taro-router/src/api.ts
=> fix(h5): router relative-path

packages/babel-preset-taro/package.json
@tarojs/taro-rn
放在dependencies会导致安装一系列的rn包，影响用户初始化
=> fix(babel-preset-taro): babel-preset-taro remove taro-rn Dependencies

docs/external-libraries.md
Make the rendered components of the storybook the same size as the design
Make the rendered components of the storybook the same size as the design
使storybook渲染结果与设计稿一致
- [x ] 所有小程序
- [x ] Web 平台（H5）
=> improve storybook usage experience

packages/taro-components/h5/vue/components/picker.js
修复H5页面picker组件显示仍存在的undefined问题
- [ √] 错误修复(Bugfix) issue id #
- [ √] Web 平台（H5）
=> fix(h5:picker)：修复H5页面picker组件显示仍存在的undefined问题

docs/react-native.md, i18n/en/docusaurus-plugin-content-docs/current/react-native.md, i18n/en/docusaurus-plugin-content-docs/version-3.x/react-native.md, versioned_docs/version-3.x/react-native.md
=> fix(rn): rn version docs

packages/taro-components-rn/src/components/Picker/date.tsx
=> fix(rn): date picker bug

packages/babel-preset-taro/index.js
=> fix(babel): skip env check for h5 test

packages/taro-h5/src/api/network/upload.ts, packages/taro-h5/src/api/ui/animation/index.ts
=> fix(h5): animation style inject fix #11135

packages/taro-components/src/components/input/input.tsx, packages/taro-components/src/components/scroll-view/scroll-view.tsx
- 避免 ScrollView 嵌套导致的事件错误 fix #11124
- 修复 input 组件 composition & paste 事件导致的 input 事件漏发 fix #11155
=> fix(h5): disabled scroll-view events fix #11124

packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap, packages/taro-swan/src/template.ts
修复 `CoverView` 里的文本在 iOS 不显示的问题，fix #11116
=> fix(swan): 修复 CoverView 里的文本在 iOS 不显示的问题，fix #11116

packages/taro-h5/src/api/canvas/CanvasContext.ts
=> fix(h5):修复canvas中measureText调用错误

packages/taro-h5/src/api/utils/handler.ts
修复h5上传监听进度this指向错误
- [x ] 错误修复(Bugfix) issue id #
- [x ] Web 平台（H5）
=> fix(h5): 修复h5上传监听进度this指向错误

versioned_docs/version-3.x/folder.md
改为 next 分支下 eslint-config-taro 包链接
=> fixed: 修复 ESLint 配置参考链接 Page Not Found

versioned_docs/version-3.x/folder.md
=> fix(typo): folder.md

docs/plugin.md
Add description of  `onBuildComplete` hook and how it differs to `onBuildFinish`.
Refer to https://github.com/NervJS/taro/pull/11264#issuecomment-1039335096
=> docs: describe `onBuildComplete`

i18n/en/docusaurus-plugin-content-docs/current/plugin.md
在英文文档里补充对 `onBuildComplete` 的说明。
=> docs: describe `onBuildComplete`  in English

packages/taro-rn/package.json, packages/taro-runtime-rn/package.json, packages/taro-runtime-rn/src/app.tsx, yarn.lock
升级 react-native-root-siblings 并在app节点加入 RootSiblingParent
https://github.com/magicismight/react-native-root-siblings#for-react-native--062
=> feat(rn): update root siblings

packages/css-to-react-native/__tests__/index.spec.js, packages/css-to-react-native/src/css-to-react-native/transforms/border.js, packages/css-to-react-native/src/css-to-react-native/transforms/index.js
1. rn 支持 border-[direction] 值简写，不只是 border 简写
```
border-left: 1px solid red;
```
=> feat(css-to-react-native): 支持 border-[direction] 值简写

.github/workflows/related-issues.yml
新增 gitHub action，其可在新建 issue 时在 www.algolia.com 存入索引，之后，有开发者新建相似 issue 该 action 提供相似issue 以供参考。如图
=> 新增 Action，可搜索关联 issues

packages/taro/types/api/open-api/settings.d.ts
添加 getSetting 方法缺少 withSubscriptions 类型声明
=> fix(types): Add getSetting withSubscriptions

packages/taro/types/api/cloud/index.d.ts
修复 new一个新的 cloud 实例后，调用 callContainer 类型报错！
=> fix(types): new cloud instance add callContainer

packages/taro-components/types/LivePlayer.d.ts
=> fix(weapp): LivePlayerProps notes error

docs/react-native.md, i18n/en/docusaurus-plugin-content-docs/current/react-native.md, i18n/en/docusaurus-plugin-content-docs/version-3.x/react-native.md, versioned_docs/version-3.x/react-native.md
=> feat(docs): add rn 0.67 support

packages/taro-cli/src/presets/platforms/rn.ts, packages/taro-components-rn/package.json, packages/taro-components/package.json, packages/taro-rn/package.json, packages/taro-router-rn/package.json, packages/taro-runtime-rn/package.json, yarn.lock
=> feat(rn): use react native 0.67

.github/workflows/nodejs.yml
=> fix: 修复nodejs自动构建问题

packages/taro-components/types/PageContainer.d.ts
1. 修复customStyle和overlayStyle 类型定义错误
2.  修复closeOnSlideDown和overlayStyle 注释错误
https://developers.weixin.qq.com/miniprogram/dev/component/page-container.html
=> fix: 修复PageContainerProps 类型定义和注释错误

README.md
=> feat: add tard of taro

docs/components/forms/button.md, versioned_docs/version-3.x/components/forms/button.md
=> docs: 增加 open-type chooseAvatar 的内容

blog/2021-10-14-Taro-React-Native-update.md, docs/react-native.md, i18n/en/docusaurus-plugin-content-docs/current/react-native.md, i18n/en/docusaurus-plugin-content-docs/version-3.x/react-native.md, versioned_docs/version-3.x/react-native.md
=> feat: update rn docs

docs/components/viewContainer/page-container.md, packages/taro-components/types/PageContainer.d.ts, versioned_docs/version-3.x/components/viewContainer/page-container.md
1. 修复closeOnSlideDown的说明
2. overlayStyle和customStyle的类型和说明
官方文档: https://developers.weixin.qq.com/miniprogram/dev/component/page-container.html
根据#11401 合并修复文档
=> fix(docs): 修复PageContainerProps 类型和说明

versioned_docs/version-3.x/router.mdx
=> docs(Router): 文档示例有误

packages/taro-rn-runner/package.json, packages/taro-rn-runner/src/index.ts, yarn.lock
@react-native-community/cli 同步为 ^6.0.0 与 react native 0.67 保持一致
=> feat(rn): upgrade metro

packages/taro-components-rn/src/components/Form/index.tsx
=> fix(rn): image in form bug

packages/taro-components-rn/src/components/Form/index.tsx
如 input 组件未设置value
form重复提交会重置input等组件的值
=> fix(rn): form value resetted

packages/taro-rn/src/__tests__/request.test.js, packages/taro-rn/src/lib/request/index.ts
修复 taro-rn request 对 header content-type 的处理，fix https://github.com/NervJS/taro/issues/11502
=> fix(rn): 修复 request 对 header content-type 的处理，fix https://github.com/NervJS/taro/issues/11502

packages/shared/src/template.ts
让 `<Slot>` 组件支持设置 style 属性，支持 `<ScrollView>` 自定义下拉刷新组件，fix #11495
=> fix(shared): 让 Slot 组件支持设置 style，fix #11495

packages/taro-router-rn/package.json, yarn.lock
修复报错 "RNSScreenNavigationContainer" was not found in the UIManager
与 https://github.com/software-mansion/react-native-reanimated/blob/main/package.json#L81 依赖的react-native-screens保持一致，避免安装多个包
=> fix: react-native-screens version

packages/taro-components-rn/src/components/CheckboxGroup/index.tsx, packages/taro-components-rn/src/components/Form/index.tsx, packages/taro-components-rn/src/components/Input/index.tsx, packages/taro-components-rn/src/components/Picker/index.tsx, packages/taro-components-rn/src/components/RadioGroup/index.tsx, packages/taro-components-rn/src/components/Slider/index.tsx
form 数据搜集使用 displayName 作为判断，否则生产环境下有误
=> fix(components-rn): use displayName

packages/taro-components-rn/package.json, packages/taro-rn/package.json, packages/taro-router-rn/package.json, yarn.lock
调整 unimodules 依赖
相关RFC
https://github.com/NervJS/taro/discussions/11565
=> feat(rn): mv unimodules deps

packages/taro-mini-runner/package.json, packages/taro-rn-style-transformer/package.json, packages/taro-rn-style-transformer/src/transforms/sass.ts, packages/taro-webpack-runner/package.json, yarn.lock
webpack-runner mini-runner 原版本
"sass": "1.32.11",
rn-style-transformer 原版本
"sass": "1.35.2",
更新至
1.50.0
=> feat: update sass version

packages/taro-mini-runner/src/webpack/chain.ts, packages/taro-webpack-runner/src/util/chain.ts
修复 Vue 不能使用 module 模式 css module 的问题，#6662
修改自 #11481 
=> fix(runner): 修复Vue不能使用module模式css module的问题，#6662

packages/taro-cli/src/cli.ts, packages/taro-cli/src/commands/customCommand.ts
修复在taro编译配置文件中获取不到TARO_ENV的问题，fix #11634 
=> fix(cli): 修复在taro编译配置文件中获取不到TARO_ENV的问题，fix #11634

packages/taro-runtime/src/dsl/common.ts
=> 支持 onUnload 生命周期

packages/taro-components/src/components/tabbar/tabbar.tsx, packages/taro-router/src/router/spa.ts
=> feat(h5): h5支持中文页面路径名称

packages/taro-cli/src/cli.ts
修复因错误设置 NODE_ENV 导致的 `taro init` 没有为项目安装 devDependencies 的问题
=> fix(cli): 修复 taro init 没有为项目安装 devDependencies 的问题

packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/__tests__/index.spec.js, packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/src/index.ts
1. 修复 css module Object.assign 等 callExpression 问题
=> fix(jsx-to-stylesheet): 修复 css module Object.assign 等 callExpression 问题

packages/taro-alipay/src/apis.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
修复在支付宝小程序平台，调用部分api未正确获取返回值的问题
fix #11703 
=> fix(alipay): 修复调用部分api未正确获取返回值的问题, fix #11703

packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/compiler-macros.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap, packages/taro-swan/src/components.ts, packages/taro-tt/src/components-react.ts, packages/taro-tt/src/components.ts, packages/taro-weapp/src/components.ts
- 修复 `Button` 组件不支持 `onLogin` 事件的问题，fix #11546
- 为 `Input` 组件新增安全键盘属性，fix #11315
- 补全 `RtcRoom` 组件，fix #11460
=> fix: 补充一些组件和属性

packages/taro/types/api/ui/animation.d.ts, packages/taro/types/taro.component.d.ts
修复 `page.animate` 方法的类型问题，fix #11700
=> fix(types): 修复 page.animate 方法的类型问题，fix #11700

packages/taro-rn/src/lib/previewImage/index.tsx, yarn.lock
使用 modal 可以避免 iOS 触发后退 （原生路由的场景，原生页再加载rn页）
=> fix(rn): previewImage use modal

packages/taro-helper/src/utils.ts
修复配置文件 import json 文件报错的问题，fix #11295
=> fix(helper): 修复配置文件 import json 文件报错的问题，fix #11295

packages/taro-plugin-mini-ci/src/TTCI.ts
针对plugin-mini-ci中所用tt-ide-cli 的用法进行了升级
背景：之前的用法，在编译tt小程序时会报错
措施：将使用到的方法进行了升级
效果：upload & preview这两个方法已正常运行
=> feat: 更新tt-ide-cli最新用法

packages/taro/types/api/ui/scroll.d.ts
https://developers.weixin.qq.com/miniprogram/dev/api/ui/scroll/wx.pageScrollTo.html
=> fix(types): 添加  pageScrollTo 的类型定义

packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap, packages/taro-tt/src/components.ts
补充字节小程序textarea组件的属性
close #11776
=> feat(tt): add props for tt textarea

packages/taro-alipay/src/template.ts
修复支付宝小程序 PickerViewColumn 类名(className) 和 style 编译后未添加上的问题 #10264
=> fix(alipay): picker-view-column 类名(className)和style 编译后未添加上的问题

packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/compiler-macros.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap, packages/taro-plugin-react/src/runtime/connect-native.ts, packages/taro-runtime/src/current.ts, packages/taro-runtime/src/dsl/common.ts, packages/taro-runtime/src/next-tick.ts
=> fix(runtime): 调整路由参数逻辑, fix #11713

packages/taro-runtime/src/dom/style.ts, packages/taro-runtime/src/dom/style_properties.ts
支持 style 设置部分 webkit 样式，fix #8109 #11802 #8330
=> fix(runtime): 支持 style 设置部分 webkit 样式，fix #8109 #11802

packages/taro-components/types/RichText.d.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/compiler-macros.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap, packages/taro-weapp/src/components.ts
补全 RichText 组件的 userSelect 属性的类型
=> feat(weapp): 补全 RichText 组件的 userSelect 属性，fix #11839

packages/taro-components/__tests__/video.spec.js, packages/taro-components/src/components/video/style/index.scss, packages/taro-components/src/components/video/utils.ts, packages/taro-components/src/components/video/video-control.tsx, packages/taro-components/src/components/video/video.tsx
- 修复 iOS 视频组件全屏事件导致的错误
- 修复 iOS 视频组件层级问题
- 修复 iOS 视频组件在沉浸式状态栏下，退出全屏时的定位问题
=> fix: 修复 iOS 全屏事件 & 控制条问题

packages/taro-h5/src/api/network/upload.ts
=> fix(h5): wrong params name fix #11749

packages/taro-h5/src/api/base/weapp/app-event.ts, packages/taro-h5/src/types/api.d.ts, packages/taro/types/api/base/weapp/app-event.d.ts, packages/taro/types/api/base/weapp/life-cycle.d.ts
- 支持 onAppShow、onAppHide 相关 API
- 更新 onAppShow 相关类型
=> feat(h5): support app-show fix #11715

packages/css-to-react-native/__tests__/index.spec.js, packages/css-to-react-native/src/css-to-react-native/tokenTypes.js, packages/css-to-react-native/src/css-to-react-native/transforms/border.js
1. fix(css-to-react-native): 修复 border-color 设置 rgb(a) 报错问题
=> fix(css-to-react-native): 修复 border-color 设置 rgb(a) 报错问题

packages/shared/src/native-apis.ts, packages/taro-api/src/interceptor/chain.js
在原生小程序中调用 `request/downloadFile/uploadFile` 等返回的是 Task 对象，Taro返回的是 Promise 对象，此PR兼容这个差异性
fix #11904 
=> fix(api): 修复 Taro.request 未正确返回 onHeadersRecieved 等字段方法的问题, fix #11904

packages/taro-mini-runner/src/plugins/MiniPlugin.ts
=> fix(mini-runner): 修复字节小程序独立分包报错的问题，fix #11915

packages/taro-loader/src/page.ts
=> fix: 兼容webpack 5在微信小程序下缓存不存在的情况

packages/taro/types/taro.config.d.ts
=> feat(types): 补充AppConfig的字段

packages/taro-components/types/ScrollView.d.ts
=> docs: 修复 ScrollView 组件的文档例子错误

packages/taro-mini-runner/src/plugins/MiniPlugin.ts
=> fix(helper): 修复小程序使用 preact 框架报错 #11962

packages/taro-cli/src/cli.ts
=> fix(cli): 修复编译小程序插件时报错的问题，fix #11932

packages/taro-plugin-react/src/runtime/index.ts
修复 preact 地图组件 onRegionChange 事件报错的问题，fix #11462
=> fix(react): 修复 preact 地图组件 onRegionChange 事件报错的问题，fix #11462

packages/taro-runtime/src/dom/event.ts
修复 vue event.self 不能使用的问题，fix #11967
=> fix(runtime): 修复 vue event.self 不能使用的问题，fix #11967

packages/shared/src/template.ts
修复了在 3.5.0-theta.1 中出现的 slot 组件编译到 base.wxml 出错的问题。
=> fix: 修复 template.ts 中生成 slot 模板的错误方式。

packages/taro-api/src/polyfill.js, packages/taro-api/src/utils.js
=> fix(taro-api): exclude null from isObject

packages/taro-plugin-react-devtools/src/runtime.ts
https://github.com/NervJS/taro/blob/9633c5e7e7ccd2941f57726f6c8dc9bf2848b752/packages/taro-plugin-react-devtools/src/runtime.ts#L6
This can't use wsl2 [localhostForwarding](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configuration-setting-for-wslconfig).
=> fix(react-devtools): fix error under wsl2

packages/taro-mini-runner/src/index.ts
#11515 
- [o] 新功能(Feature)
- [o] 所有小程序
- [] 微信小程序
=> feat(mini-runner): 支持用户对内置配置进行修改

packages/taro-tt/src/create-app.js
feat(tt): 抖音交易组件2.0所需的方法
文档为 https://bytedance.feishu.cn/docx/doxcnUB6roC88VLuywndKCCbM5e
=> feat(tt): 抖音交易组件2.0所需的方法

packages/taro/types/taro.config.d.ts
=> 补充AppConfig中requiredPrivateInfos字段类型

packages/taro-runtime/src/dsl/common.ts
修复生成分享 config 时因为历史原因导致的无法正确获取虚拟 dom 导致的后续无法正确设置分享问题。
=> fix: 修复 taro 无法正确生成分享配置问题

.github/workflows/nodejs.yml, packages/taro-h5/src/api/canvas/canvasToTempFilePath.ts
`image/jpg`在h5中不是合法的值，会被当作`image/png`处理，间接导致qulity参数失效。
https://www.w3.org/TR/2011/WD-html5-20110405/the-canvas-element.html#dom-canvas-todataurl
=> fix: fileType为jpg时，表现不符合预期

.github/PULL_REQUEST_TEMPLATE.md, packages/taro-webpack5-prebundle/src/mini.ts
修复预编译导致的运行时报错: `TypeError: Cannot read property 'userAgent' of undefined`，fix #12128
=> fix(runtime): 修复预编译导致的运行时报错，fix #12128

packages/taro-runtime-rn/src/page.ts
合并无效的可选链二次判断逻辑
> 编译成js之后代码很长，而且会再判断一次，不如直接进行链式调用
Tiny performance improvment.
=> perf(taro-runtime-rn): remove verbose optional chaining check

packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/compiler-macros.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap, packages/taro-mini-runner/src/__tests__/mocks/taro.ts, packages/taro-mini-runner/src/__tests__/utils/compiler.ts, packages/taro-plugin-react/src/runtime/connect.ts
修复 react18 `creatRoot` 和小程序 `onLoad` 竞态的问题
=> fix(react): 修复 react18 运行问题

packages/taro-rn-supporter/src/taroTransformer.ts
修复rn在Windows下运行报错，Closes #12174
=> fix: isEntryFile path error on windows

packages/taro-rn-runner/src/config/build-component.ts, packages/taro-rn-supporter/src/rollupResolver.ts
1. 透传 platform，支持读 ios/android 文件
=> fix(rn-support/rn-runner): 支持 ios/android 文件读取

packages/taro-rn/src/api/index.ts, packages/taro-runtime-rn/src/hooks.ts, packages/taro-runtime-rn/src/page.ts, packages/taro-runtime-rn/src/types/index.d.ts
=> feat(taro-runtime-rn): implement useUnload hook in taro-rn

packages/taro-rn/src/api/index.ts, packages/taro-runtime-rn/src/hooks.ts, packages/taro-runtime-rn/src/page.ts, packages/taro-runtime-rn/src/types/index.d.ts
简述：taro-rn中实现onLoad hook
细节： 一开始打算放在组件构建函数中，但是调用不生效
查看代码后，发现只能在组件挂载后进行调用
遂在mount后最早的时机进行调用
=> feat(taro-runtime-rn): implement useLoad hook in taro-rn

packages/taro-rn-runner/src/config/build-component.ts, packages/taro-rn-style-transformer/__tests__/config.spec.js, packages/taro-rn-style-transformer/__tests__/index.spec.js, packages/taro-rn-style-transformer/__tests__/platform.spec.js, packages/taro-rn-style-transformer/src/index.ts, packages/taro-rn-style-transformer/src/transforms/index.ts, packages/taro-rn-style-transformer/src/transforms/less.ts, packages/taro-rn-style-transformer/src/transforms/postcss.ts, packages/taro-rn-style-transformer/src/transforms/sass.ts, packages/taro-rn-style-transformer/src/transforms/stylus.ts, packages/taro-rn-style-transformer/src/types/index.ts, packages/taro-rn-style-transformer/src/utils/index.ts, packages/taro-rn-style-transformer/src/utils/lessImport.ts
1. rollupTransform 参数格式化
2. rn-style-transform 类型调整
=> feat(rn-runner/rn-style): rollupTransform 参数格式化,解决参数丢失问题 && 调整类型声明文件

packages/taro-components/types/Video.d.ts
=> feat(types): update video types

packages/taro-router/src/router/multi-page.ts, packages/taro-router/src/router/page.ts, packages/taro-router/src/router/spa.ts, packages/taro-webpack-runner/src/__tests__/__snapshots__/babel.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/compiler-macros.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/config.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/nerv.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/sass.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/ts.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/vue.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap
=> fix(router): 优化自定义路由入口判断 fix #12214

CONTRIBUTING.md
=> fix(doc): replace lerna's script with pnpm

packages/taro-components/types/Map.d.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/compiler-macros.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap, packages/taro-tt/src/components.ts, packages/taro-weapp/src/components.ts
=> feat: 补充Map组件的属性和事件

packages/taro-webpack5-prebundle/src/h5.ts, packages/taro-webpack5-prebundle/src/mini.ts, packages/taro-webpack5-prebundle/src/prebundle/index.ts
排除 remote 应用打包时，继承不必要的 host 应用 webpack 依赖
=> fix(prebundle): 删除继承 webpack 冗余配置 fix #12240

packages/taro-rn/src/__tests__/__snapshots__/scanCode.test.tsx.snap, packages/taro-rn/src/lib/scanCode/index.tsx, packages/taro-router-rn/src/view/TabBar.tsx
=> fix: scancode safe area

packages/taro-runtime-rn/src/page.ts, packages/taro-runtime-rn/src/utils.ts
=> fix(taro-runtime-rn): 修复rn 函数式组件中hook多实例触发问题

packages/taro-rn-runner/src/config/preview.ts, packages/taro-rn-runner/src/index.ts, packages/taro-rn-runner/src/utils.ts
相关issue：
https://github.com/NervJS/taro/issues/12306
window下不使用小二维码：
https://github.com/gtanner/qrcode-terminal/pull/14/files
=> feat: use big qr in windows

packages/taro-components-rn/src/components/Picker/multiSelector.tsx, packages/taro-components-rn/src/components/Picker/selector.tsx, packages/taro-components/types/Picker.d.ts
rn 端@tarojs/components 的Picker中单列选择器和多列选择器增加每列样式和indicator 样式入参。
=> PickerComponent add itemStyle and indicatorStyle

packages/taro-webpack5-prebundle/src/prebundle/index.ts, packages/taro-webpack5-runner/src/index.h5.ts, packages/taro-webpack5-runner/src/webpack/H5Combination.ts
修复自定义 devServer proxy 导致的参数合并错误
=> fix(runner): 修复 proxy 合并错误问题 fix #12265

packages/taro-components-rn/src/components/Video/index.tsx, packages/taro-components/types/Video.d.ts
修正 Video 组件的 onWaiting 事件注释，fix #12329
=> fix(typings): 修正 Video 组件的 onWaiting 事件注释，fix #12329

packages/shared/src/utils.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/compiler-macros.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap
修复在不同平台生成的模板不一致的问题，fix #12320
可能将修复 #12237
=> fix(shared): 修复在不同平台生成的模板不一致的问题，fix #12320

packages/taro-mini-runner/src/plugins/TaroNormalModulesPlugin.ts, packages/taro-webpack5-runner/src/plugins/TaroNormalModulesPlugin.ts
=> fix(runner): remove duplicate id of native components

packages/taro-runtime-rn/src/page.ts
修复当 Page 为 Function Component 的 warning
=> fix(runtime-rn): function components cannot be given refs

packages/taro-h5/src/api/navigate/index.ts, packages/taro/types/api/navigate/index.d.ts
=> feat(weapp): 补充 openBusinessView 的类型定义

packages/taro-router-rn/src/view/TabBar.tsx
=> fix: tabbar paddingbottom error

packages/css-to-react-native/__tests__/index.spec.js, packages/css-to-react-native/src/css-to-react-native/transforms/border.js
=> fix: 修复 RN 样式 warning

packages/taro-router-rn/src/view/TabBar.tsx
tabbar 需要撑起页面高度，与其他端保持一致。  [issue](https://github.com/NervJS/taro/issues/12404)
=> fix(router-rn): tabbar 调整为 reletive 定位，撑起页面高度 (#12404)

packages/taro-cli/src/presets/platforms/rn.ts
=> feat: update auto install expo version

packages/taro-rn/src/lib/showActionSheet/ActionSheet.tsx
1. 修复 showActionSheet rn android 端与其他端不一致的问题
=> fix(taro-rn): 修复 showActionSheet rn android 端与其他端不一致的问题

packages/taro/types/api/canvas/index.d.ts
=> feat(types): 更新API `wx.createOffscreenCanvas` 的签名

packages/taro-components/src/components/input/input.tsx
修复 input 组件 type=number 并且 maxlength=-1 情况下,内容无法输入问题
=> fix(taro-components): 修复 input type=number maxlength=-1 情况下,内容无法输入问题

packages/taro-components/package.json, packages/taro-components/stencil.config.ts, packages/taro-components/tsconfig.json
添加 taro-components 模块 H5 组件 stencil 构建的 sourceMap 配置
=> build(taro-components): 添加 H5 组件 stencil 构建 sourceMap 配置

packages/taro-components-rn/src/components/Input/PropsType.tsx, packages/taro-components-rn/src/components/Input/index.tsx, packages/taro-components-rn/src/components/Textarea/index.tsx, packages/taro-components-rn/src/utils/index.ts
1. RN 端  Input TextArea 解决 focus 变更,聚焦失焦不同步
=> fix(component-rn): Input TextArea 解决 focus 变更,聚焦失焦不同步

packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/__tests__/__snapshots__/index.spec.js.snap, packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/__tests__/index.spec.js, packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/src/index.ts
=> fix(jsx-to-stylesheet): 引入同名 style 文件时变量名冲突

packages/taro-components/types/Ad.d.ts, packages/taro-components/types/AdCustom.d.ts, packages/taro-components/types/Button.d.ts, packages/taro-components/types/CheckboxGroup.d.ts, packages/taro-components/types/CoverView.d.ts, packages/taro-components/types/Editor.d.ts, packages/taro-components/types/Form.d.ts, packages/taro-components/types/Input.d.ts, packages/taro-components/types/LivePusher.d.ts, packages/taro-components/types/Map.d.ts, packages/taro-components/types/MovableView.d.ts, packages/taro-components/types/PageContainer.d.ts, packages/taro-components/types/PageMeta.d.ts, packages/taro-components/types/Picker.d.ts, packages/taro-components/types/Progress.d.ts, packages/taro-components/types/Radio.d.ts, packages/taro-components/types/RichText.d.ts, packages/taro-components/types/ScrollView.d.ts, packages/taro-components/types/Swiper.d.ts, packages/taro-components/types/Textarea.d.ts, packages/taro-components/types/Video.d.ts, packages/taro-components/types/View.d.ts, packages/taro-components/types/VoipRoom.d.ts, packages/taro-components/types/common.d.ts, packages/taro/types/api/location/index.d.ts, packages/taro/types/api/share/index.d.ts
=> fix(types): 修复部分类型自动同步错误

.github/workflows/dependabot-update-lockfile.yml
修复 dependabot-ci 提交报错问题，优化 ci git init 步骤
修复 dependabot-ci 提交报错问题
=> fix(ci): dependabot update pnpm-lock

packages/taro-webpack5-runner/src/utils/types.ts, packages/taro-webpack5-runner/src/webpack/Combination.ts
=> fix(runner): 修复自定义环境变量导致的 mode 错误 fix #12436

packages/taro-h5/src/api/canvas/CanvasContext.ts
修复canvasContext的createLinearGradient循环调用的问题
=> fix: 修复canvasContext的createLinearGradient循环调用的问题

packages/taro-webpack5-runner/src/index.h5.ts
修复 开启多页模式时，启动 devServer，未正确的在浏览器中自动打开预期页面。
=> fix(webpack5-runner): 开启多页模式时 devServer 初始页未正常打开, fix #12582

packages/postcss-pxtransform/index.js
fix https://github.com/NervJS/taro/issues/12607
=> fix: 不带单位不支持在calc表达式中参与计算

packages/taro-components-rn/package.json, packages/taro-components-rn/src/components/Image/index.tsx, pnpm-lock.yaml
react-native-svg 包过大，优化成可选
Closes #12637
=> make react-native-svg optional

README_EN.md
=> fix: readme typo

packages/taro-alipay/src/components.ts, packages/taro-components/types/Camera.d.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap, packages/taro/types/api/media/camera.d.ts
=> fix(alipay): support camera component

packages/taro-with-weapp/src/index.ts
微信小程序转 Taro 工具，小程序 `triggerEvent` 事件，事件名兼容短横线（**kebab case**）类型
=> fix(weapp): eventName support kebab case

.github/workflows/sync-components-types.yml, packages/taro-components/package.json, packages/taro-components/scripts/json-schema-to-types.ts, packages/taro-components/scripts/tsconfig.json, pnpm-lock.yaml
=> refactor: 实现小程序组件类型自动同步的功能

packages/taro-cli/templates/default/package.json.tmpl
升级默认模板的 vue-loader 到最新版本 `v17.0.0`
=> fix(cli): 升级默认模板的 vue-loader 到最新版本，fix #12602

packages/shared/src/template.ts, packages/taro-webpack5-runner/src/index.mini.ts, packages/taro-webpack5-runner/src/prerender/prerender.ts
修复 Webpack5 prerender 报错，fix #12622
=> fix(webpack5): 修复 prerender 报错，fix #12622

packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap, packages/taro-tt/src/components-react.ts, packages/taro-tt/src/components.ts
支持 PayButton、ConsumeCard 组件，fix #12650
=> fix(tt): 支持PayButton、ConsumeCard组件，fix #12650

packages/taro-runtime/src/dsl/common.ts
#12558
修复tmpl_0_view not found 警告，fix #12558
=> fix(runtime): 修复tmpl_0_view not found 警告，fix #12558

packages/css-to-react-native/package.json, packages/stylelint-taro-rn/package.json, packages/taro-cli/package.json, packages/taro-transformer-wx/package.json, packages/taroize/package.json
prettier 更新以支持 singleAttributePerLine
=> chore: taro-transformer-wx 等 prettier 更新2.x以支持 singleAttributePerLine

packages/taro-plugin-react/src/runtime/index.ts
=> preact h5编译undefined

packages/taro-service/src/utils/types.ts
=> fix(style): eslint fix

packages/taro/types/api/media/editor.d.ts
- 更新 EditorContext.insertImage的types，增加nowrap
- https://developers.weixin.qq.com/miniprogram/dev/api/media/editor/EditorContext.insertImage.html
- 新功能(Feature)
这个 PR 涉及以下平台:
- 微信小程序
=> feat(types): Update EditorContext.insertImage types

packages/taro-router-rn/src/provider.ts
=> fix(router-rn): setOptions assign error

packages/taro-alipay/src/template.ts
新版本加入了native-slot，支付宝2.0构建不兼容slot模版，需要删除
=> fix: 兼容alipay删除native-slot

packages/taro-h5/src/utils/index.ts
=> fix(h5): 补充 API 抛出事件遗漏的参数

packages/taro/types/api/alipay/index.d.ts
修复 alipay - getOpenUserInfo 返回结果类型不正确的问题
=> fix(types): 修复 alipay - getOpenUserInfo 返回结果类型不正确的问题

packages/taro-components/types/index.vue3.d.ts
=> fix(types): add reserved props for vue3 custom element

packages/taro-components/types/index.vue3.d.ts
fix https://github.com/NervJS/taro/issues/12880
=> fix(types): resolve vue native slot tag  type conflict

packages/taro/types/api/navigate/index.d.ts
增加打开半屏小程序api注释
wx.openEmbeddedMiniProgram
- [ x] TypeScript 类型定义修改(Typings)
- [x ] 微信小程序
=> type(api): openEmbeddedMiniProgram

packages/taro-webpack5-prebundle/src/prebundle/index.ts
预编译排除继承 copyPlugin 和babel-loader，fix #12839
=> fix(prebundle): 预编译排除继承 copyPlugin 和babel-loader，fix #12839

packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap, packages/taro-swan/src/template.ts
=> fix(swan): 修复百度小程序模板的循环语法错误问题，fix #12864

packages/taro-webpack5-runner/src/loaders/miniTemplateLoader.ts, packages/taro-webpack5-runner/src/loaders/miniXScriptLoader.ts, packages/taro-webpack5-runner/src/webpack/MiniWebpackModule.ts, packages/taro-webpack5-runner/src/webpack/WebpackModule.ts
=> fix(webpack5): 自动分析小程序模板里依赖的wxs文件，fix #9055

packages/taro-rn/src/lib/file.ts
=> fix(rn): uploadFile file response

packages/taro-helper/package.json, packages/taro-webpack5-prebundle/package.json, pnpm-lock.yaml
=> fix(swc): 升级@swc/core版本,解决link @tarojs/webpack5-runner后编译报错问题

packages/taro-components-rn/src/components/RichText/index.tsx
=> feat(rn): richText support extenal prop

packages/taro-transformer-wx/package.json, packages/taro-transformer-wx/src/options.ts, packages/taro-transformer-wx/yarn.lock
=> fix: issue-12866

packages/taro-plugin-react/src/index.ts
prebundle 排除 mobx 相关依赖(包括mobx-react 等)，减少重复代码和避免对象引用冲突的问题
=> fix(react): prebundle 排除 mobx 相关依赖

packages/taro-plugin-vue3/src/webpack.mini.ts
=> fix(vue3): 修复 v-html 缺失组件模板的问题，#12973

packages/taro-h5/package.json, packages/taro-h5/src/api/wxml/IntersectionObserver.ts, packages/taro-h5/src/api/wxml/index.ts, packages/taro/types/api/wxml/index.d.ts, pnpm-lock.yaml
- 增加H5端wxml的IntersectionObserver的API支持
=> Feature/增加H5 IntersectionObserver, createIntersectionObserver 的API支持

packages/taro-components/src/components/swiper/swiper.tsx
- 修复 swiper 在 circular 模式下自动播放故障
- 移除 loopDestroy 避免重建循环导致的性能问题
=> fix(components): 修复 swiper 在 circular 模式下自动播放故障

packages/taro-cli/templates/default/types/global.d.ts
更新 vue 默认类型导出，支持非 native 标签开发类型提示
=> fix(template): 新增类型导出适配 vue 开发插件

packages/taro-h5/package.json, packages/taro-webpack5-prebundle/src/h5.ts
- 优化 prebundle-h5 打包 remote 应用模块加载规则（继承自 webpack5 提供的 rules）
- 修复 @tarojs/taro-h5 依赖 sideEffects 配置
=> fix(h5): API 样式缺失问题 #13018

packages/taro-components-advanced/src/components/virtual-list/index.ts
=> fix: virtual list 代码剔除不生效

packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap, packages/taro-tt/src/runtime-utils.ts
=> fix: add tt regionchange

packages/taro-h5/src/api/base/system.ts, packages/taro/types/api/base/system.d.ts
更新getDeviceInfo types
https://developers.weixin.qq.com/miniprogram/dev/api/base/system/wx.getDeviceInfo.html
=> feat(types): update getDeviceInfo types

packages/taro-cli/templates/default/template_creator.js, packages/taro-cli/templates/default/types/global.d.ts, packages/taro-cli/templates/default/types/vue.d.ts
- 优化 global.d.ts 生成逻辑
- 优化 vue 补充拓展逻辑 https://github.com/vuejs/core/pull/3399
=> fix(types): 优化 vue 类型补充 fix #13081

packages/taro-components/types/LivePusher.d.ts
https://developers.weixin.qq.com/miniprogram/dev/component/live-pusher.html
=> feat(types): update LivePusherProps

packages/taro-webpack5-runner/src/webpack/BaseConfig.ts
=> fix typo: 修正命令行里的一个提示

packages/taro-components/src/components/swiper/swiper-item.tsx
修复移除高损耗 loop 修复方案后，复制 swiper-item 占位帧结构错误问题
> 由于 swiperjs 调用 cloneNode 导致，当前暂无更好的方案修复 https://github.com/ionic-team/stencil/issues/2197
=> fix(components): update swiper-item for circular

packages/taro-mini-runner/src/plugins/MiniPlugin.ts, packages/taro-webpack5-runner/src/plugins/MiniPlugin.ts
修复独立分包, 提取公共方法 common 后，产物未引用公共 common 文件
=> fix(runner): 修复独立分包下, 产物未引用公共 common 文件

packages/taro-runtime/src/dsl/common.ts
修复 onReady 偶现不触发的问题，fix #12424
=> fix(runtime): 修复 onReady 偶现不触发的问题，fix #12424

packages/taro-cli/src/presets/platforms/rn.ts, packages/taro-components-rn/package.json, packages/taro-components-rn/src/components/MovableView/PropsType.tsx, packages/taro-rn-supporter/package.json, packages/taro-rn-supporter/src/taroResolver.ts, packages/taro-rn/package.json, packages/taro-rn/src/lib/compressImage/index.ts, packages/taro-router-rn/package.json, pnpm-lock.yaml
=> feat(rn): add pnpm support

packages/taro-plugin-mini-ci/package.json, packages/taro-plugin-mini-ci/src/BaseCi.ts, packages/taro-plugin-mini-ci/src/JdCI.ts, packages/taro-plugin-mini-ci/src/index.ts
=> feat: jd mini ci

packages/taro-components/src/components/navigator/navigator.tsx, packages/taro-components/types/Navigator.d.ts
=> feat(h5): 更新 navigator 组件支持参数

packages/taro-components-advanced/src/components/virtual-list/react/list.ts, packages/taro-components-advanced/src/components/virtual-list/vue/list.ts
=> fix(components): VirtualList restCount可能是负数

packages/taro-components-rn/src/__tests__/utils.spec.tsx, packages/taro-components-rn/src/components/Image/index.tsx, packages/taro-components-rn/src/components/Map/index.tsx, packages/taro-components-rn/src/components/WebView/index.tsx, packages/taro-components-rn/src/utils/index.ts
=> fix(rn): image component error

packages/taro-plugin-mini-ci/src/utils/qrcode.ts
关闭问题 [#13278](https://github.com/NervJS/taro/issues/13278)
=> fix(taro-plugin-mini-ci): 修复初始化报错的问题

packages/taro/types/api/qq/index.d.ts, packages/taro/types/taro.api.d.ts
=> fix(qq): add declaration of qq api openQzonePublish

packages/taro-plugin-mini-ci/README.md, packages/taro-plugin-mini-ci/package.json, packages/taro-plugin-mini-ci/src/BaseCi.ts, packages/taro-plugin-mini-ci/src/WeappCI.ts, packages/taro-plugin-mini-ci/src/index.ts, packages/taro-plugin-mini-ci/src/utils/qrcode.ts, pnpm-lock.yaml
1.  之前的 [PR](https://github.com/NervJS/taro/pull/13300) 在不升级 [jimp](https://www.npmjs.com/package/jimp) 版本号前的写法有问题
2.  废弃未维护的 [qrcode-reader](https://www.npmjs.com/package/qrcode-reader) 扫码器， 实际运行中发现某些二维码图片不能正确识别， 会报错 "couldn't find enough alignment pattern string"
3.  引入新的扫码器 [jsqr](https://www.npmjs.com/package/jsqr), 更稳定
4. 微信小程序预览和上传新增编译配置(https://github.com/NervJS/taro/issues/13174)
5. 相关文档更新
=> feat(plugin-mini-ci): jimp 升级、二维码扫码器更换

packages/taro-webpack5-runner/src/postcss/postcss.h5.ts
修复样式文件 import 后静态资源路径错误的问题
cause: https://github.com/NervJS/taro/pull/13014
fix: https://github.com/jdf2e/nutui/issues/2089
=> fix(webpack5): 修复样式文件 import 后静态资源路径错误的问题

packages/taro-h5/src/api/open-api/favorites.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/compiler-macros.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap, packages/taro-weapp/src/apis-list.ts, packages/taro/types/api/open-api/favorites.d.ts
#13325
补充 `Taro.checkIsAddedToMyMiniProgram` 类型并`Promise`化
https://developers.weixin.qq.com/miniprogram/dev/api/open-api/my-miniprogram/wx.checkIsAddedToMyMiniProgram.html
=> fix(type): add checkIsAddedToMyMiniProgram type

packages/taro-router-rn/src/rootNavigation.ts, packages/taro-router-rn/src/router.tsx, packages/taro-router-rn/src/utils/index.ts
=> fix(rn): 去除redirect动画(#11263)

packages/taro/types/api/media/video.d.ts
``` 
interface mediaType {
/** 只能拍摄视频或从相册选择视频 */
video
/** 只能拍摄图片或从相册选择图片 */
image
/** 可同时选择图片和视频 */
mix
}
```
=> feat(api): ChooseMedia types mediaType add 'mix'

packages/taro-alipay/src/components.ts, packages/taro-components/types/Button.d.ts, packages/taro-components/types/index.d.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
- 补充 支付宝小程序按钮 `onGetUserInfo`, `onGetPhoneNumber`事件
https://opendocs.alipay.com/mini/component/button
- 修复`Lottie`组件类型未导出问题
=> fix(alipay): update property of `button`

packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/compiler-macros.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap, packages/taro-weapp/src/components.ts
=> fix(weapp): 修复 ChannelVideo autoplay 属性拼写错误

packages/taro-runtime-rn/src/page.ts, packages/taro-runtime-rn/src/utils.ts
=> fix:  useTabItemTap第一次点击tab时不会触发

packages/taro-webpack5-prebundle/src/prebundle/index.ts, packages/taro/types/compile/compiler.d.ts
=> chore: 调整 prebundle 类型

packages/taro-components/types/Ad.d.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap, packages/taro-qq/src/components.ts
=> feat(types):完善QQ小程序广告类型 #13445

.eslintrc.js, packages/taro-alipay/src/apis.ts, packages/taro-cli/src/create/project.ts, packages/taro-cli/src/index.ts, packages/taro-plugin-mini-ci/src/AlipayCI.ts, packages/taro-plugin-mini-ci/src/index.ts, packages/taro-plugin-react/src/webpack.h5.ts, packages/taro-rn-supporter/src/taroResolver.ts, packages/taro-router-rn/src/router.tsx, packages/taro-runtime/src/__tests__/location.spec.js, packages/taro-webpack5-runner/src/utils/webpack.ts
=> fix: 修复 ora 和 inquirer 版本升级，造成 cli init 时异步拉取社区模版终端退出的 bug

packages/taro-components/types/LivePlayer.d.ts, packages/taro/types/api/network/request.d.ts
- add request method `PATCH`; 
- modify enableAutoRotation of LivePlayer to boolean
=> fix(type): add request method `PATCH`; modify enableAutoRotation

packages/taro-webpack5-runner/src/webpack/BaseConfig.ts
根据 [webpackbar](https://www.npmjs.com/package/webpackbar) 文档描述，修正 basic 与 fancy 配置项的取值
=> fix(mini-runner): 修复 logger.quiet 配置项未对 webpackbar 正确生效的问题

packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap, packages/taro-swan/src/index.ts, packages/taro-swan/src/program.ts, packages/taro-swan/src/template.ts
修复百度小程序 Text 组件嵌套不显示的问题，fix #13511
=> fix(swan): 修复百度小程序 Text 组件嵌套不显示的问题，fix #13511

packages/taro-loader/src/h5.ts, packages/taro-webpack5-prebundle/package.json, pnpm-lock.yaml
- 升级虚拟模块依赖版本
- 移除 bootstrap 模块缓存禁用
=> feat(h5): 启用虚拟模块缓存

packages/taro-components-advanced/src/components/virtual-list/index.ts
为虚拟列表的方法添加类型声明
**备注**
build 时发现注释会重复生成，但不影响使用
=> feat(virtual-list): add type definition for VirtualList methods

packages/taro-components-advanced/rollup.config.js, packages/taro-components-library-react/rollup.config.js, packages/taro-components-library-vue2/rollup.config.js, packages/taro-components-library-vue3/rollup.config.js, packages/taro-components-react/rollup.config.js, packages/taro-platform-h5/rollup.config.js, packages/taro-plugin-html/rollup.config.js, packages/taro-plugin-http/package.json
禁用 rollup 打包时移除 dev 依赖，避免 ts 未启用时的依赖报错
=> fix(plugin): 修复禁用 ts 导致的插件导入报错 fix #13547

packages/taro-mini-runner/src/webpack/chain.ts, packages/taro-webpack-runner/src/index.ts, packages/taro-webpack-runner/src/utils/chain.ts
在 Taro 仓库的本地开发编译过程中，有个别 ts 类型错误造成本地编译流水线中断，造成不好的开发体验，将 ts 类型错误补齐
=> fix(type): 完善代码的类型推断

package.json, packages/babel-plugin-transform-taroapi/__tests__/__snapshots__/index.spec.ts.snap, packages/babel-plugin-transform-taroapi/__tests__/index.spec.ts, packages/babel-plugin-transform-taroapi/babel.config.json, packages/babel-plugin-transform-taroapi/jest.config.js, packages/babel-plugin-transform-taroapi/package.json, packages/babel-plugin-transform-taroapi/tsconfig.test.json, packages/taro-components-advanced/package.json, pnpm-lock.yaml
- babel-plugin-transform-taroapi 添加测试用例
添加 babel-plugin-transform-taroapi 测试用率
=> test(taro-babel): babel-plugin-transform-taroapi 添加测试用例

packages/taro-router/src/router/multi-page.ts, packages/taro-router/src/router/page.ts
=> feat(router): 支持根据 html 模板自定义节点位置 fix #13382

packages/taro-cli/templates/default/src/app.js, packages/taro-cli/templates/default/src/pages/index/index.jsx
React 18 已成为目前主流的版本，官方推荐使用 FC 函数组件开发 react 应用，且官方文档也建议初学者直接学习 React Hook，而非 Component。
本 PR 将 Taro 默认模板的 `app.js`  `index.jsx` 更改为 函数组件 形式。  
=> feat(template): 默认模板使用 React 函数组件

packages/taro-components/types/ScrollView.d.ts
=> fix(types): ScrollView 的 type  参数调整为可选

packages/taro-components/src/components/checkbox/checkbox-group.tsx, packages/taro-components/src/components/form/form.tsx, packages/taro-components/src/components/radio/radio-group.tsx
修复组件内，私有 value 引用错误，包括以下组件
- form
- checkbox-group
- radio-group
=> fix(components): 修复 value 引用错误 fix #13641

packages/taro-h5/__tests__/network/request.test.ts, packages/taro-h5/package.json, packages/taro-h5/src/api/network/request/index.ts, pnpm-lock.yaml
修复 taro-h5 request 参数 timeout 不生效
=> fix(taro-h5): request timeout use AbortController abort

packages/taro-runtime/src/__tests__/location.spec.js, packages/taro-runtime/src/bom/URL.ts, packages/taro-runtime/src/bom/URLSearchParams.ts
修复 taro runtime 中 URL 实例使用同一个 URLSearchParams
=> fix(taro-runtime): one URL use same URLSearchParams

package.json, packages/taro-helper/jest.config.js, packages/taro-helper/package.json, packages/taro-helper/src/__tests__/__mocks__/app.config.ts, packages/taro-helper/src/__tests__/__mocks__/app2.config.ts, packages/taro-helper/src/__tests__/config.spec.ts, packages/taro-helper/src/utils.ts, packages/taro-helper/tsconfig.json, pnpm-lock.yaml
更新 webpack 版本后(#13625)存在部分问题，导致使用 register 二次调用后，读取统一路径报错，综合考量后改用 transformFileSync + require-from-string 替代之前读取 config 的方法
=> fix(helper): 修复获取配置问题

packages/taro-helper/src/__tests__/__mocks__/app.config.json, packages/taro-helper/src/__tests__/__mocks__/app.config.ts, packages/taro-helper/src/__tests__/__mocks__/app.define.config.ts, packages/taro-helper/src/__tests__/__mocks__/app.import.config.ts, packages/taro-helper/src/__tests__/__mocks__/app.require.config.ts, packages/taro-helper/src/__tests__/config.spec.ts, packages/taro-helper/src/utils.ts
- 支持 import / require
- 支持读取 json
- 补充测试用例
=> feat(helper): readConfig 支持读取 json

packages/taro-components/types/Input.d.ts, packages/taro-components/types/Map.d.ts, packages/taro-components/types/Picker.d.ts, packages/taro/types/api/canvas/index.d.ts, packages/taro/types/api/cloud/index.d.ts, packages/taro/types/api/network/request.d.ts, packages/taro/types/api/open-api/favorites.d.ts, packages/taro/types/api/open-api/my-miniprogram.d.ts, packages/taro/types/compile/config/project.d.ts
=> chore(types): sync type form docs

packages/taro-components/src/components/textarea/textarea.tsx, packages/taro-components/types/Input.d.ts, packages/taro-components/types/Textarea.d.ts
=> feat(components): support textarea onConfirm #12911

packages/taro-h5/src/api/network/request/index.ts, packages/taro/types/api/network/request.d.ts
- 补充 web 端缺失的 cleanInterceptors 方法
- 补充类型
=> feat(h5): add cleanInterceptors

packages/taro-components/virtual-list/index.js
=> fix: virtual-list export

packages/taro/types/api/base/crypto.d.ts
- 修复 taro getRandomValues 方法类型问题
=> fix(types): 修复 taro getRandomValues 方法类型问题

packages/taro/types/taro.extend.d.ts
=> docs(miniprogram): getAppInfo 补充文档 types

packages/taro-mini-runner/package.json, packages/taro-webpack5-runner/package.json, pnpm-lock.yaml
=> chore: 移除不必要的依赖

.github/workflows/sync-components-types.yml, packages/taro-components/scripts/json-schema-to-types.ts, packages/taro-components/types/ShareElement.d.ts, packages/taro-components/types/Swiper.d.ts, packages/taro-components/types/Textarea.d.ts
=> fix(ci): 修复类型同步问题

packages/create-app/src/createApp.ts
=> fix: 修复create-app不询问包管理工具，导致项目初始化后自动安装依赖报错的bug

packages/shared/src/native-apis.ts, packages/taro-h5/src/api/taro.ts, packages/taro-rn-runner/src/types/index.ts, packages/taro-rn-style-transformer/src/types/index.ts, packages/taro-rn-supporter/src/types/index.ts, packages/taro-rn-transformer/src/types/index.ts, packages/taro-runtime-rn/src/types/index.d.ts, packages/taro/types/api/taro.extend.d.ts, packages/taro/types/compile/config/project.d.ts
- 在 web 端支持 getAppInfo 方法
- 修补 designWitdh 类型
=> feat(h5): 支持 getAppInfo

packages/taro-components/types/Textarea.d.ts
修改 Textarea 组件 showCount、controlled 的类型定义。
支付宝小程序文档链接：https://opendocs.alipay.com/mini/component/textarea
=> fix(textarea): 修改 showCount、controlled 类型定义

.github/workflows/sync-components-types.yml, package.json, packages/taro-components/__tests__/text.e2e.ts, packages/taro-components/src/components/rich-text/readme.md, packages/taro-components/src/components/rich-text/rich-text.tsx, packages/taro-components/src/components/rich-text/style/index.scss, packages/taro-components/src/components/text/readme.md, packages/taro-components/src/components/text/style/index.scss, packages/taro-components/src/components/text/text.tsx, packages/taro-components/types/RichText.d.ts, packages/taro-components/types/Text.d.ts
- 为 Text 组件补充 userSelect、space、numberOfLines 参数支持
- 为 RichText 组件补充 userSelect、selectable、space 参数支持
=> feat(text): 新增参数支持 fix #13747

packages/taro-rn/src/api/index.ts, packages/taro-router-rn/src/rootNavigation.ts, packages/taro-router-rn/src/router.tsx, packages/taro-router-rn/src/utils/index.ts, packages/taro-runtime-rn/src/app.tsx, packages/taro-runtime-rn/src/hooks.ts, packages/taro-runtime-rn/src/instance.ts, packages/taro-runtime-rn/src/page.ts, packages/taro-runtime-rn/src/utils.ts
1. rn 中入口组件支持函数式组件
2. 入口组件支持 useLaunch，useDidShow，usePageNotFound生命周期hooks
=> fix(rn): RN入口支持函数式组件及相关生命周期hooks

packages/taro-h5/src/api/media/audio/InnerAudioContext.ts
=> fix(h5): InnerAudioContext 暂停后再播放没有继上次进度播放

packages/taro-h5/src/api/network/request/index.ts
修改了h5-runtime的request api 在post请求下传递array数据类型导致的序列化问题
=> fix(h5): 修改Taro.request传入array类型数据序列化问题

packages/taro-loader/src/h5.ts, packages/taro-webpack-runner/src/plugins/H5Plugin.ts, packages/taro-webpack5-runner/src/plugins/H5Plugin.ts
修复在 win 下，配置 h5.router.mode 为 multi 后，页面不显示的问题
=> fix(h5): 修复 win 下开启 multi router 后页面不显示的问题 fix #13134

packages/create-app/package.json, packages/taro-cli/package.json, pnpm-lock.yaml
修复 cli 和 create-app 中依赖的第三方包因为版本问题造成的安全警告
=> chore(deps): update npm-check fix

package.json, packages/css-to-react-native/yarn.lock, packages/stylelint-taro-rn/yarn.lock, packages/taro-async-await/yarn.lock, packages/taro-cli/yarn.lock, packages/taro-components/package.json, packages/taro-components/yarn.lock, packages/taro-plugin-sass/package.json, packages/taro-plugin-sass/src/index.ts, packages/taro-plugin-sass/yarn.lock, packages/taro-transformer-wx/yarn.lock, packages/taroize/yarn.lock, yarn.lock
把2.x的node-sass换成sass（dart-sass），并且清除了taro-plugin-sass和taro-cli中的node-sass依赖。
=> chore: 2.x的node-sass换成sass

packages/taro/types/api/media/live.d.ts
=> feat(weapp): live-player 增加投屏接口

packages/taro-service/src/platform-plugin-base/mini.ts
=> fix: merge environment variables

packages/taro-components/types/Button.d.ts
增加 Vue3 button 组件获取电话号码的示例，#11445
=> docs(types): 增加 Vue3 button 组件获取电话号码的示例，#11445

packages/taro-helper/src/esbuild/utils.ts
=> fix: omit result importer

packages/taro-h5/src/api/ui/interaction/modal.ts, packages/taro-router/src/router/page.ts, packages/taro-router/src/router/spa.ts
1. 修复浏览器回退时路由current未更新的问题
2. 修复showModal显示的弹窗滚动透传问题
=> 修复Taro.showModal浏览器退回到上一页面不消失和遮罩层滚动透传问题

packages/taro-webpack5-runner/src/plugins/MiniSplitChunksPlugin.ts
输出分包 sub-common 下 source map 文件
```js
"use strict";
(tt["webpackJsonp"] = tt["webpackJsonp"] || []).push([["sub-common/84949777d80e3c1f5a53429654fb9fd7"],{
/***/ "./src/pages/common/index.ts":
/*!***********************************!*\
!*** ./src/pages/common/index.ts ***!
\***********************************/
/***/ (function(__unused_webpack_module, __webpack_exports__, __webpack_require__) {
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "makeError": function() { return /* binding */ makeError; }
/* harmony export */ });
/* harmony import */ var lodash__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! lodash */ "./node_modules/lodash/lodash.js");
/* harmony import */ var lodash__WEBPACK_IMPORTED_MODULE_0___default …
```
=> fix(webpack5): 修复抽取 sub-common 模块时输出 source map

packages/taro-components-library-react/scripts/fix.js, packages/taro-components-library-vue2/scripts/fix.js, packages/taro-components-library-vue3/scripts/fix.js
=> fix(h5): custom-wrapper 对齐小程序

packages/taro-api/package.json, packages/taro-api/rollup.config.js, packages/taro-webpack-runner/src/__tests__/__snapshots__/babel.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/compiler-macros.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/config.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/nerv.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/react.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/sass.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/ts.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/vue.spec.ts.snap, packages/taro-webpack-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap, pnpm-lock.yaml
修改 @tarojs/api 引用的依赖，将 deps 设置为 external
=> fix(api): 将生产依赖设置为 external

packages/taro-plugin-http/src/runtime/XMLHttpRequest.ts, packages/taro-plugin-http/src/runtime/index.ts
修复 https://github.com/NervJS/taro/issues/13941
=> fix(taro-plugin-http): 发送请求时未正确携带包含httpOnly的cookie #13941

packages/taro-cli/package.json, packages/taro-cli/src/__tests__/doctor-config.spec.ts, packages/taro-cli/src/__tests__/doctor.spec.ts, packages/taro-cli/src/doctor/index.ts, packages/taro-cli/src/presets/commands/build.ts, pnpm-lock.yaml
=> chore: 更新依赖的 @tarojs/plugin-doctor 版本

packages/taro-runtime-rn/src/page.ts
=> fix(rn): 类组件的函数式组件hooks不触发(#14051)

packages/taro-runtime-rn/src/page.ts
=> feat: add nestedScrollEnabled true for android

packages/taro-h5/src/api/alipay/index.ts, packages/taro/types/api/alipay/index.d.ts
支付宝小程序新增tradePay api的类型
关联的issue：https://github.com/NervJS/taro/issues/14072
=> feat(types): 支付宝小程序新增tradePay api的类型

packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap, packages/taro-swan/src/components.ts
=> feat(types): 完善swan button属性 #12665

packages/taro-webpack5-runner/src/plugins/MiniPlugin.ts
修复使用 sentry-webpack-plugin 时报错，fix #13988
=> fix(webpack5-runner): 修复使用 sentry-webpack-plugin 时报错，fix #13988

packages/taro-components-library-vue2/src/component-lib/index.ts
修改在app.js中修改 ignoredElements 配置不生效的问题
=> fix: 修改在app.js中配置了ignoredElements ，配置未生效问题

packages/taro/types/api/open-api/address.d.ts
=> fix(types): update address api

packages/taro-components-rn/src/components/Navigator/index.tsx, packages/taro-rn-supporter/src/Support.ts, packages/taro-rn-supporter/src/utils.ts, packages/taro-rn-transformer/__tests__/__snapshots__/app.spec.ts.snap, packages/taro-rn-transformer/src/app.ts, packages/taro-router-rn/src/provider.ts, packages/taro-runtime-rn/src/EventChannel.ts, packages/taro-runtime-rn/src/app.tsx, packages/taro-runtime-rn/src/current.ts, packages/taro-runtime-rn/src/index.ts, packages/taro-runtime-rn/src/page.ts, packages/taro-runtime-rn/src/router.ts
=> fix(rn): 单页面引入react-navigation导致体积过大问题(#14079)

packages/taro-runtime/src/hydrate.ts
** 问题复现 **
** 微信小程序sourcemap定位 **
=> fix: fix taro runtime error of hydrate file

packages/shared/src/template.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap, packages/taro-webpack5-runner/src/__tests__/__snapshots__/mini-platform.spec.ts.snap
=> fix(template): 修复递归模版 child 生成错误的问题

packages/taro-cli/templates/default/package.json.tmpl
…ndency requirement
更新@babel/runtime版本，满足@tarojs/test-utils-react运行的最低要求
=> @babel/runtime版本号要满足@tarojs/test-utils-react运行的最低要求

packages/shared/src/runtime-hooks.ts, packages/taro-runtime/src/dsl/common.ts
修复 useTabItemTap 不触发的问题，fix #14170
=> fix(runtime): 修复 useTabItemTap 不触发的问题，fix #14170

packages/taro-cli/src/presets/platforms/plugin.ts
- 修复 config 新增默认 clean 配置项导致的微信小程序插件编译失败的问题
=> fix(config): 修复 config 新增默认 clean 配置项导致的微信小程序插件编译失败的问题

.github/workflows/publish.yml
修复 publish actions 给 PR 提交评论时报错的问题
=> chore(ci): 修复 publish actions 给 PR 提交评论时报错的问题

packages/taro-webpack5-prebundle/src/index.ts
=> fix(prebundle): 修复虚拟模块冗余调用 fix #14257

packages/taro-platform-h5/src/program.ts
=> fix(h5): component path when useDeprecatedAdapterComponent

packages/taro-webpack5-prebundle/package.json, pnpm-lock.yaml
修复 pnpm worksapce 使用了不同 Taro 版本时报错的问题，fix #14224
=> fix(prebundle): 修复 pnpm worksapce 使用了不同 Taro 版本时报错的问题，fix #14224

packages/taro-h5/__tests__/network/websocket.test.ts, packages/taro-h5/src/api/network/websocket/index.ts
=> feat(h5): 对齐小程序 connectSocket API 限制 fix #14292

packages/taro-h5/__tests__/network/request.test.ts, packages/taro-h5/src/api/network/request/index.ts, packages/taro/types/api/network/request.d.ts
- 优化 request 方法参数传递给 fetch
- 补充 request 方法类型限制说明
=> fix(h5): 优化 fetch 参数传递 fix #14222

packages/taro-components-rn/src/components/Block/index.tsx, packages/taro-components-rn/src/components/SwiperItem/index.tsx, packages/taro-components-rn/src/components/Text/index.tsx, packages/taro-components-rn/src/components/Textarea/index.tsx, packages/taro-components-rn/src/components/WebView/index.tsx
1. 类型推断：由于 props 已经声明为 TextareaProps 类型，可以省略在函数参数中显式指定 props 的类型。TypeScript 可以根据上下文自动推断类型。
2. 省略的写法更加清爽优雅，望采纳
=> fix(type): remove duplicate declarations

packages/taro-components-rn/src/components/ClickableSimplified/index.tsx, packages/taro-components-rn/src/components/PageContainer/container.tsx, packages/taro-components-rn/src/components/ScrollView/index.tsx, packages/taro-rn/src/lib/file.ts
1. any 不具备ts类型的优势， returnType更加严格
2. 也同时保证了和项目中其他对于定时器的描述类型保持一致
=> fix(type): use returnType replace timer any type

packages/taro-components/src/components/scroll-view/readme.md, packages/taro-components/src/components/swiper/swiper-item.tsx, packages/taro-components/src/components/swiper/swiper.tsx
- 修复 swiper 调用 cloneNode 错误
- 兼容 Swiper 中使用到即将兼容的事件
=> fix(h5): 修复 swiper 调用 cloneNode 错误 fix #14160

packages/taro-webpack5-runner/src/plugins/TaroNormalModulesPlugin.ts
=> fix(vue): 修复 vue 框架使用 h() 导致的报错问题

packages/taro-cli/src/__tests__/doctor-config.spec.ts, packages/taro-components/types/Button.d.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap, packages/taro-tt/src/components.ts, packages/taro-webpack5-runner/src/__tests__/__snapshots__/mini-platform.spec.ts.snap
为[button 组件跳转抖音号个人页](https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/component/open-capacity/button-open-aweme-user-profile)功能提供支持
=> feat(taro-tt): button组件支持跳转抖音个人号主页

packages/taro-components/src/components/video/video.tsx
fix:增加exitFullScreen的实现，适配不同的webkit
fix
Web 平台（H5）
=> fix:增加exitFullScreen的实现，适配不同的webkit

packages/taro-rn-supporter/src/terminal-reporter.ts
修复 taro-rn-supporter 模块本地编译时，ts类型推断编译报错
=> chore(rn-supporter): ts类型推断导致编译报错处理

README.md, README_EN.md
=> docs: update Readme

packages/taro-h5/src/api/canvas/CanvasContext.ts, packages/taro/types/api/canvas/index.d.ts
- 修复 canvas 字体设置问题，并更新类型
- 修复 canvas save、restore 方法设置错误
- H5 canvas 上下文支持 reset 方法
=> fix(h5): 修复 canvas 字体设置问题，并更新类型

packages/taro-components-react/src/components/scroll-view/index.tsx, packages/taro-components/src/components/scroll-view/scroll-view.tsx
react 适配组件库 scroll-view 支持 scrollIntoView 相关参数
- 支持动画判断
- 支持 scrollIntoViewAlignment 参数
web-components 组件库 scroll-view 组件
- 修复 touchmove 事件冒泡导致的下拉刷新问题
- 修复 scroll 事件捕获导致嵌套的问题
=> fix(components): react 适配组件库 scroll-view 支持 scrollIntoView 相关参数  #14032

packages/taro-components/src/components/swiper/swiper.tsx
=> fix(h5): swiper loop handle immediately #14487

packages/shared/src/native-apis.ts
修复小程序createIntersectionObserver方法失效的问题，fix #14563
=> fix(shared): 修复小程序createIntersectionObserver方法失效的问题，fix #14563

packages/taro/types/taro.config.d.ts
fix(type): update type of app.json
修复skyline框架类型提示错误
参考
https://developers.weixin.qq.com/miniprogram/dev/framework/runtime/skyline/migration/release.html#%E5%8F%91%E5%B8%83%E4%B8%8A%E7%BA%BF
=> fix(type): update type of app.json

packages/taro-runtime/src/hydrate.ts
文本节点补充传递sid属性，避免文本节点列表更新时提示没有key的问题
=> fix(runtime): 文本节点补充传递sid属性，避免文本节点列表更新时提示没有key的问题

packages/taro-alipay/src/components.ts, packages/taro-components/types/Video.d.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap, packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap, packages/taro-webpack5-runner/src/__tests__/__snapshots__/mini-platform.spec.ts.snap, packages/taro-webpack5-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
=> fix(alipay): video attribute replenishment

README.md
掘金小册不再维护，下架后跳转回提示 404，故而从首页移除
掘金小册下架后无法购买，当前跳转提示 404 错误，仅已购买用户可以正常查阅
=> feat: udpate readme

packages/taro-plugin-mini-ci/src/WeappCI.ts
fix(taro-plugin-mini-ci): 修复主包大小计算错误问题
=> fix(taro-plugin-mini-ci): 修复主包大小计算错误问题

packages/taro-components/src/components/snapshot/readme.md, packages/taro-components/src/components/swiper/swiper.tsx
=> fix(h5): onChange 事件添加 source

packages/postcss-pxtransform/package.json
=> chore: fix homepage

packages/taro/types/api/media/camera.d.ts
https://developers.weixin.qq.com/miniprogram/dev/api/media/camera/CameraContext.takePhoto.html
=> feat(types): 添加原图成像质量type

packages/postcss-pxtransform/index.js, packages/taro-runtime-rn/src/compute.ts, packages/taro-webpack5-runner/src/webpack/H5WebpackPlugin.ts
rem 适配时基于 vmin 计算 font-size
https://github.com/NervJS/taro/discussions/13913
=> feat: rem calc by vmin

packages/taro-router-rn/package.json, pnpm-lock.yaml
新版本的 react native screen 编译不过，进行降级
=> fix(rn): react native screens build error

packages/taro-with-weapp/src/index.ts
This reverts commit eeb66463ffb1abc42b3a7ac4a622b8a46ce81126.
Revert(taro-with-weapp):  "把properties转换为React的state，支持可读可写，同时再通过props传入修改后的值"
=> Revert(taro-with-weapp):  "把properties转换为React的state，支持可读可写，同时再通过props传入修改后的值"

packages/taro-jd/src/components.ts, packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap, packages/taro-webpack5-runner/src/__tests__/__snapshots__/mini-platform.spec.ts.snap
fix(jd): 补全京东小程序 Input、TextArea 组件的属性
=> fix(jd): 补全京东小程序 Input、TextArea 组件的属性

packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap, packages/taro-tt/src/program.ts, packages/taro-tt/src/template.ts, packages/taro-webpack5-runner/src/__tests__/__snapshots__/mini-platform.spec.ts.snap
=> feat(tt): 字节小程序支持 sjs，fix #14635

packages/taro-components-react/package.json, packages/taro-components-react/rollup.config.js
=> fix(style): react components style shake

packages/taro-components-advanced/src/components/virtual-list/react/list.ts, packages/taro-components-advanced/src/components/virtual-list/react/wrapper.ts, packages/taro-components-advanced/src/components/virtual-list/vue/list.ts, packages/taro-components-advanced/src/components/virtual-waterfall/react/waterfall.ts, packages/taro-components-advanced/src/components/virtual-waterfall/react/wrapper.ts, packages/taro-components-advanced/src/components/virtual-waterfall/vue/waterfall.ts, packages/taro-components/src/components/scroll-view/scroll-view.tsx
- 修复 scroll-view 冗余事件抛出问题
- 修复虚拟组件头尾节点未注入 key 问题
- 增加虚拟组件事件限制判断，避免受到子组件干扰
=> fix(advanced): 修复虚拟组件相关事件问题 fix #14792

packages/taro/types/api/navigate/index.d.ts
添加 打开的半屏小程序是否支持全屏参数 allowFullScreen
=> feat: 打开的半屏小程序是否支持全屏

packages/taro-swan/src/template.ts
#14844
https://smartprogram.baidu.com/docs/develop/component/formlist_slider/
修复百度小程序 Slider 设置 value 未生效问题
=> fix(swan): remove slider value in swanSpecialAttrs

packages/taro/html.css
=> fix: h1~h6 没有设置行高

.github/workflows/auto-review.yml, .github/workflows/nodejs.yml, .github/workflows/publish.yml, .github/workflows/sync-components-types.yml
=> chore: ci 中 next 重命名为 main

packages/taro-runtime-rn/package.json, packages/taro-runtime-rn/src/compute.ts, packages/taro-runtime-rn/src/scale2dp.tsx, pnpm-lock.yaml
1. 修复 pxTransform 计算不一致的问题
2. 安卓平板与 iPad 行为调整成一致
=> fix(rn): adjusting tablet phone styles

packages/taro-cli-convertor/__tests__/__snapshots__/script.test.ts.snap, packages/taro-cli-convertor/__tests__/script.test.ts
=> fix: 修复3.7分支因快照问题导致的CI报错

.github/workflows/nodejs.yml, .github/workflows/publish.yml
修复 CI 相关错误
- 移除 14 版本 CI 校验
- 提前 publish 取消规则校验
=> fix(ci): action cancel & node 14 error

.github/workflows/build-rust-binding.yml
=> fix(ci): rm rust node@14 supported

packages/taro-helper/src/esbuild/index.ts, packages/taro-helper/tsconfig.json
=> fix(helper): 排除 esbuild 不支持的别名配置

.github/workflows/nodejs.yml, codecov.yml, packages/taro-runtime/jest.config.js, packages/taro-runtime/package.json
=> chore: test ci codecov

Cargo.lock, Cargo.toml
=> fix: 修复 napi 版本依赖

packages/taro-router/src/router/multi-page.ts, packages/taro-router/src/router/page.ts, packages/taro-router/src/router/spa.ts, packages/taro-router/src/style.ts
- 增加navigationStyle配置项的处理逻辑trigger `__taroSetNavigationStyle`事件
- spa应用的页面加载时，生命周期触发顺序改为 page.onShow >> page.onReady
=> feat: 增加navigationStyle配置处理逻辑

crates/taro_init/src/constants.rs
=> fix: init media add keystore

packages/taro-platform-harmony-hybrid/package.json, packages/taro-platform-harmony-hybrid/src/api/apis/media/image/previewImage.ts, pnpm-lock.yaml
降低taro-platform-harmony-hybrid的rollup版本号
fix
鸿蒙（harmony
=> fix: 降低taro-platform-harmony-hybrid的rollup版本号

packages/taro-components/src/components/swiper/swiper.tsx
=> fix: 给 swiper 在复制节点后的一些报错问题添加兜底

packages/taro-components-react/package.json, packages/taro-components-react/rollup.config.ts, packages/taro-h5/rollup.config.ts, packages/taro-plugin-react/src/runtime/connect.ts, packages/taro-router/src/style.ts
- 导出 h5 组件 & API 默认样式供 node 环境使用
- 动画启用时禁用 body 滚动，避免 iOS 触底页面弹动遮挡
- 补充 preact 配置提示
=> feat(h5): 导出 h5 组件 & API 默认样式

.github/workflows/sync-components-types.yml, packages/taro-components/scripts/json-schema-to-types.ts, packages/taro-components/types/Input.d.ts, packages/taro-components/types/PickerView.d.ts, packages/taro-components/types/ShareElement.d.ts, packages/taro-components/types/Slider.d.ts, packages/taro-components/types/Switch.d.ts, packages/taro-components/types/Textarea.d.ts, packages/taro-rn/tsconfig.json, packages/taro-rn/types/runtime.d.ts, packages/taro/types/index.d.ts, packages/taro/types/taro.runtime.d.ts
- 修复 ci 脚本 ，仅编译同步类型所需依赖
- 修复缺失 runtime 类型
=> fix(ci): only build components deps

packages/taro-cli/src/presets/platforms/rn.ts, packages/taro-components-rn/package.json, packages/taro-rn-runner/package.json, packages/taro-rn/package.json, pnpm-lock.yaml
=> feat: expo 50 release

packages/taro-cli-convertor/src/index.ts
fix: 修复convertor生成配置文件时路径报错的问题
=> fix: 修复convertor生成配置文件时路径报错的问题

packages/taro-components/types/Input.d.ts, packages/taro-components/types/Picker.d.ts, packages/taro-components/types/Slider.d.ts, packages/taro-components/types/Switch.d.ts, packages/taro-components/types/Textarea.d.ts, packages/taro-platform-harmony-hybrid/package.json, packages/taro-platform-harmony-hybrid/src/api/apis/base/system.ts, packages/taro-platform-harmony-hybrid/src/api/apis/media/image/chooseImage.ts, packages/taro-platform-harmony-hybrid/src/api/apis/media/image/previewImage.ts, packages/taro-platform-harmony-hybrid/src/api/apis/media/video/chooseMedia.ts, packages/taro-platform-harmony-hybrid/src/api/apis/media/video/getVideoInfo.ts, packages/taro-platform-harmony-hybrid/src/api/apis/network/download.ts, packages/taro-platform-harmony-hybrid/src/api/apis/network/utils.ts, packages/taro-platform-harmony-hybrid/src/api/apis/taro.ts, packages/taro-platform-harmony-hybrid/src/program.ts, packages/taro/types/api/taro.extend.d.ts, pnpm-lock.yaml
=> fix: 修复harmony-hybrid编译报错，完善harmony接口

packages/taro-cli-convertor/src/index.ts, packages/taro-cli-convertor/src/util/index.ts, packages/taroize/src/utils.ts
=> feat: 注释convertor相关代码中未调用的函数

packages/taro-components/types/Picker.d.ts
Picker组件的类型里缺少headerText属性，补上了
https://developers.weixin.qq.com/miniprogram/dev/component/picker.html
=> feat(type): 补充Picker组件的headerText属性的类型

packages/taro-router/src/history.ts
=> fix(route): 优化路由 hash 拼接

README.md, README_EN.md
=> fix(docs): taro-ui official version has been released

packages/taro-platform-h5/src/program.ts, packages/taro-platform-harmony-hybrid/src/program.ts
修复 html 组件库引用
> 避免 pnpm 没有将适配组件库提升到根目录可能导致的问题
=> fix(h5): 修复 html 组件库引用

packages/taro-components/package.json, packages/taro-components/tsconfig.json, packages/taro-platform-h5/package.json, packages/taro-platform-h5/tsconfig.json, packages/taro-platform-harmony-hybrid/package.json, packages/taro-platform-harmony-hybrid/tsconfig.json, pnpm-lock.yaml
=> fix(ci): ts-node support node18+

packages/taro-webpack5-runner/src/index.h5.ts
升级后使用 0.0.0.0 不再能跳转唯本地 IP，直接使用 local-ip 会导致 web-socket 错误
=> fix(h5): use local-ip host

packages/taro-router/src/router/mpa.ts, packages/taro-router/src/router/spa.ts
- 修正App.onShow和onHide时的页面路径信息
- 应用显示/隐藏时触发页面onShow/onHide生命周期
=> fix: 修正app的onShow/onHide页面路径信息

packages/taro/types/api/base/performance.d.ts
修复微信小程序-资源预加载API`preloadAssets`参数类型错误。
=> Fix preloadAssets option type

packages/taro-plugin-react/src/index.ts, packages/taro-plugin-react/src/webpack.h5.ts
=> fix: 修复harmony-hybrid平台useLoad等API找不到的问题

packages/taro-platform-harmony/src/apis/route/index.ts
=> feat(harmony): support relative router-path

packages/taro-helper/scripts/backup.js
=> fix(helper): 修复 CI 会用旧的 wasm 覆盖新的文件的问题

packages/taro-router/src/api.ts, packages/taro-router/src/history.ts, packages/taro-router/src/router/index.ts
fix(#15296): 修复路由有 basename 的情况下navigate 报错
=> fix(#15296): 修复路由有 basename 的情况下navigate 报错

packages/taro-webpack5-runner/src/webpack/BaseConfig.ts
=> fix: app.config 缓存路径错误

packages/taro-platform-harmony-hybrid/build/config/harmony-definition.json, packages/taro-platform-harmony-hybrid/src/api/apis/network/request/index.ts
=> fix: 修改request接口参数的支持情况

packages/taro-platform-harmony-hybrid/build/config/harmony-definition.json, packages/taro-platform-harmony-hybrid/src/api/apis/NativeApi.ts, packages/taro-platform-harmony-hybrid/src/api/apis/taro.ts
=> fix(harmony-hybrid): 修复NavigationStyle配置无效的问题

crates/taro_init/src/constants.rs
=> fix: template replace ignore tgz

packages/taro-cli/templates/default/template_creator.js
PR #15328 只重命名了模板，实际文件名映射部分还未修改，导致修复其实不生效的
**TODO: 映射这部分写死了很不好，后续应该改成动态修改**
https://github.com/NervJS/taro/blob/93e47bcb8a73ea0e7cb7da8a033e415aab5c1ee0/packages/taro-cli/templates/default/template_creator.js#L5-L41
=> fix(cli): 修复环境变量 TARO_APP_ID 不生效的问题

examples/mini-program-example/src/util/nativeApi.ts, packages/taro-platform-harmony-hybrid/src/api/apis/NativeApi.ts
修复harmony-hybrid平台dev调试环境下装饰器导致的页面崩溃问题
=> fix: 修复harmony-hybrid平台dev调试环境下装饰器导致的页面崩溃问题

packages/taro-cli/src/util/defineConfig.ts
问题源自：[taro-docs #256](https://github.com/NervJS/taro-docs/issues/256)
修正了 `@tarojs/cli` 的 `defineConfig` 方法的参数名称，将 `mergin` 改为 `merge`。
另外，对应文档调整已提交 PR [taro-docs #257](https://github.com/NervJS/taro-docs/pull/257)
=> fix(cli): 修正 defineConfig 参数

packages/taro-rn-style-transformer/src/transforms/index.ts
解决 css 中包含 `\/` 字符，被序列化后会造成样式不生效
```css
.text-red-500\/50 {}
```
=> fix(taro-rn-style-transformer): 修复样式转换中的转义问题

packages/taro-react/package.json, packages/taro-react/tsconfig.json
`import { createPortal } from '@tarojs/react'` 缺少类型提示：
```typescript
TS7016: Could not find a declaration file for module @tarojs/react.
```
=> fix(types): 导出 `@tarojs/react` 包 `types`

packages/taro-vite-runner/src/utils/compiler/base.ts
生成sourceRoot路径时，改为使用path.resolve生成，兼容外部传入绝对路径
=> feat(harmony):  generate sourceRoot using path.resove

packages/taro-platform-harmony-hybrid/build/config/harmony-definition.json, packages/taro-platform-harmony-hybrid/src/api/apis/network/request/index.ts, packages/taro-platform-harmony-hybrid/src/api/apis/network/request/nativeRequest.ts
=> 【harmony-hybrid】支持addInterceptor和clearInterceptor

examples/mini-program-example/src/pages/api/media/video/index.tsx, packages/taro-platform-harmony-hybrid/build/config/harmony-definition.json, packages/taro-platform-harmony-hybrid/src/api/apis/NativeApi.ts, packages/taro-platform-harmony-hybrid/src/api/apis/media/video/chooseMedium.ts, packages/taro-platform-harmony-hybrid/src/api/apis/media/video/index.ts
=> 【harmony-hybrid】增加原生api chooseMedium

packages/taro-platform-harmony-hybrid/src/api/apis/taro.ts, packages/taro-platform-harmony-hybrid/src/api/apis/utils/colorConvert.ts
harmony hybrid导航栏适配深色模式，页面初始化导航栏样式时反转颜色适配
=> harmony hybrid导航栏适配深色模式，页面初始化导航栏样式时反转颜色适配

packages/taro-plugin-react/src/runtime/connect.ts
修复 `waitAppWrapper` 可能出现的同步和异步任务执行顺序导致生命周期执行顺序异常的问题
https://github.com/NervJS/taro/blob/9e5c328530aeecebc9d9b1c2bc87bfb93dc47a60/packages/taro-plugin-react/src/runtime/connect.ts#L191-L193
=> fix(react): 修复容器事件重复触发时导致的生命周期执行顺序异常的问题

packages/taro/types/api/network/request.d.ts
修改taro api request的complete配置中res的参数类型，这个类型与successCallback是一致的：  
=> types: 修改request请求api的complete res参数类型，与success一致

packages/taro-platform-harmony/src/components/components-harmony-ets/movableView.ets
=> feat: 添加xy的初始化

packages/taro-platform-harmony-hybrid/src/api/apis/utils/colorConvert.ts
harmony hybrid导航栏适配深色模式反转颜色适配时支持缩写的颜色值
=> harmony hybrid导航栏适配深色模式反转颜色适配时支持缩写的颜色值

packages/taro-router/src/router/page.ts, packages/taro-router/src/router/spa.ts
修复路由变化的 onhide 事件的调用时机，以及 switchTab 的时候不需要有动画
=> fix: 修复路由变化的 onhide 事件的调用时机，以及 switchTab 的时候不需要有动画

packages/taro-platform-harmony/src/runtime-framework/react/native-page.ts, packages/taro-vite-runner/src/harmony/page.ts, packages/taro-vite-runner/src/harmony/template/page.ts, packages/taro/types/compile/viteCompilerContext.d.ts
=> Feat: 完成混合开发组件解析逻辑

examples/mini-program-example/src/pages/api/canvas/index.tsx, packages/taro-platform-harmony-hybrid/build/config/harmony-definition.json, packages/taro-platform-harmony-hybrid/src/api/apis/NativeApi.ts, packages/taro-platform-harmony-hybrid/src/api/apis/canvas/canvasToTempFilePath.ts, packages/taro-platform-harmony-hybrid/src/api/apis/comments.ts, packages/taro-platform-harmony-hybrid/src/api/apis/interface/NativeAContextApi.ts, packages/taro-platform-harmony-hybrid/src/api/apis/network/request/nativeRequest.ts
修复request请求无法返回ArrayBuffer数据，音频无法暂停等问题
=> fix: [harmony-hybrid] 修复request请求无法返回ArrayBuffer数据，音频无法暂停等问题

packages/taro-platform-harmony-hybrid/src/api/apis/NativeApi.ts
=> removeStorage 删除js侧缓存

packages/taro-router/src/style.ts
=> fix(router): 修复 CSS 单行注释语法问题

packages/taro-platform-harmony-hybrid/src/api/apis/NativeApi.ts, packages/taro-platform-harmony-hybrid/src/api/apis/storage/index.ts, packages/taro-platform-harmony-hybrid/src/api/apis/storage/util.ts
=> 解决storage的sync逻辑bug，同步和异步都会同步更新js侧的缓存，同时只有第一次的sync方法，需要wait

packages/taro-platform-harmony-hybrid/src/api/apis/comments.ts, packages/taro-platform-harmony-hybrid/src/api/apis/navigate/index.ts
=>  fix：[Harmony Hybrid] navigateTo快速多次点击时重复打开页面

packages/taro-router/src/api.ts, packages/taro-router/src/router/spa.ts
修复弱网情况下，频繁切换页面造成页面实例错乱和挂载多个相同页面的bug
=> fix: 修复弱网情况下，频繁切换页面造成页面实例错乱和挂载多个相同页面的bug

packages/taro-components/__tests__/map.spec.tsx, packages/taro-components/package.json, packages/taro-components/src/components/map/map.tsx, packages/taro-components/src/components/map/style/map.scss, pnpm-lock.yaml
=> 添加h5版map实现

packages/taro-platform-harmony/src/runtime-framework/react/app.ts
=> fix: 修复 taroGlobalData 不生效的问题

packages/taro-platform-harmony/src/runtime-ets/dom/element/element.ts, packages/taro-platform-harmony/src/runtime-ets/dom/node.ts, packages/taro-vite-runner/src/harmony/template/render.ts, packages/taro-vite-runner/src/utils/compiler/harmony.ts
=> Fix:修复组件混合写法的一些类型报错和无法更新 

packages/taro-cli/src/presets/platforms/rn.ts, packages/taro-rn-runner/__tests__/components.spec.ts, packages/taro-rn-runner/src/config/build-component.ts, packages/taro/types/compile/config/index.d.ts, packages/taro/types/compile/config/rn.d.ts
修复 Taro 组件编译成 React Native 组件的异常
https://github.com/NervJS/taro/discussions/11860
=> feat(rn): 修复 ReactNative 组件打包

examples/mini-program-example/src/pages/component/map/map.js, packages/taro-platform-harmony-hybrid/src/components/components-react/Map/Map.tsx
=> feat: [harmony-hybrid]同层渲染Map组件新增Marker属性支持

packages/taro-cli-convertor/__tests__/__mocks__/fs-extra.js, packages/taro-cli-convertor/src/index.ts
=> fix: 修复taro-convertor-cli包测试不通过

packages/babel-preset-taro/index.js, packages/taro-framework-react/src/index.ts, packages/taro-framework-solid/src/index.ts
=> fix: 修复合并4.x solid的问题

examples/mini-program-example/src/pages/api/media/video/index.tsx, packages/taro-platform-harmony-hybrid/src/api/apis/media/video/chooseMedia/chooseMedia.ts, packages/taro-platform-harmony-hybrid/src/api/apis/media/video/chooseMedia/chooseMedium.ts, packages/taro-platform-harmony-hybrid/src/api/apis/media/video/chooseMedia/index.ts, packages/taro-platform-harmony-hybrid/src/api/apis/media/video/index.ts
=> 【harmony-hybrid】chooseMedia适配两种实现方式

packages/taro-platform-harmony-hybrid/src/api/apis/interface/NativeRequest.ts
=> 为request兼容ArrayBuffer数据

packages/taro-platform-harmony-hybrid/src/api/apis/comments.ts, packages/taro-platform-harmony-hybrid/src/api/apis/wxml/IntersectionObserver.ts, packages/taro-platform-harmony-hybrid/src/api/apis/wxml/index.ts
createIntersectionObserver修改为独立实现，回调参数支持id和dataset
=> feat: [Harmony-Hybrid] createIntersectionObserver修改为独立实现，回调参数支持id和dataset

examples/mini-program-example/src/pages/api/redirection/index.tsx, packages/taro-platform-harmony-hybrid/src/api/apis/NativeApi.ts, packages/taro-platform-harmony-hybrid/src/api/apis/navigate/index.ts
=> feat: 删除navigateToMiniProgram相关实现

packages/taro-platform-harmony-hybrid/src/api/apis/device/memory/offMemoryWarning.ts, packages/taro-platform-harmony-hybrid/src/api/apis/device/memory/onMemoryWarning.ts, packages/taro-platform-harmony-hybrid/src/api/apis/open-api/soter/checkIsSoterEnrolledInDevice.ts
=> fix: [harmony-hybrid]open-api相关接口实现修改

examples/mini-program-example/src/pages/api/wxml/index.tsx, packages/taro-platform-harmony-hybrid/src/api/apis/wxml/IntersectionObserver.ts
解决IntersectionObserver相关接口无效问题
=> 【harmony-hybrid】解决IntersectionObserver相关接口无效问题

packages/taro-platform-harmony-hybrid/src/api/apis/harmony-native/StorageCacheAndSyncProxy.ts
=> fix: [harmony-hybrid]修复clearStorageSync报错的问题

packages/taro-platform-harmony-hybrid/src/api/apis/harmony-native/ApiCache.ts
=> fix: [harmony-hybrid]修复dev模式下桥接到原生侧的同步API崩溃问题

packages/taro-runtime/src/bom/URLSearchParams.ts
修复 URL SearchParams 参数不规范导致的渲染白屏
https://github.com/NervJS/taro/issues/15717
=> feat(runtime): url search params 容错处理 (#15717)

packages/taro-platform-harmony-hybrid/src/api/apis/NativeApi.ts, packages/taro-platform-harmony-hybrid/src/api/apis/taro.ts
解决容器共用时，需通过jsbridge，通过Taro的navigate进行路由，通过webcontroller.loadUrl()会有一些问题
=> fix(harmony-hybrid): 解决容器共用时，需通过jsbridge，通过Taro的navigate进行路由，通过webcontroller.loadUrl()会有一些问题

packages/taro-cli/src/__tests__/doctor-config.spec.ts
=> fix(cli): test error

.github/dependabot.yml
fix: format dependabot
修改 ci 文件
=> ci: format dependabot

.github/workflows/nodejs.yml, .github/workflows/publish.yml
=> ci: 3.x分支允许发版

packages/taro-components/src/components/video/video.tsx
=> fix: [H5] video组件mute={true}时，静音按钮状态显示为非静音

packages/taro-cli/src/create/fetchTemplate.ts
增加私有化模板不在 CLI 展示的逻辑，同时也可以用于暂时下架模板的功能
=> feat(cli): 增加私有化模板不展示的逻辑

packages/taro-jd/package.json, packages/taro-jd/rollup.config.js, packages/taro-jd/src/components-react.ts, packages/taro-jd/src/program.ts, pnpm-lock.yaml
=> feat: 为京东小程序添加editor组件

packages/taro-platform-alipay/package.json, packages/taro-platform-jd/package.json, packages/taro-platform-jd/rollup.config.mjs, packages/taro-platform-jd/src/components-react.ts, packages/taro-platform-jd/src/program.ts, packages/taro-platform-swan/package.json, packages/taro-platform-tt/package.json, packages/taro-platform-weapp/package.json, pnpm-lock.yaml
=> feat: 为jd小程序平台补充 editor 组件

packages/taro-components/types/Picker.d.ts
fix(types): update picker region data
=> fix(types): update picker region data

packages/taro-cli/templates/default/_gitignore
https://docs.taro.zone/docs/env-mode-config#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E5%BC%8F
模版应该默认忽略 .local 文件，参考 [vite](https://github.com/vitejs/vite/blob/main/packages/create-vite/template-react/_gitignore#L13)
=> fix: 模板 git 忽略 .env.local 文件

packages/taro-platform-harmony-hybrid/src/api/apis/media/image/chooseImage.ts, packages/taro-platform-harmony-hybrid/src/api/apis/media/video/chooseVideo.ts
=> 【harmony-hybrid】替换chooseImage和chooseVideo的实现

packages/taro-cli/templates/default/config/dev.js, packages/taro-cli/templates/default/config/index.js, packages/taro-cli/templates/default/config/prod.js
修复默认项目模板中存在的一些问题：
使TS条件下生成的模板中的dev和prod的配置文件，import与export间保持一行空隙，以避免ESLint报错
修正tsconfig-paths-webpack-plugin插件的导入条件，在配置中为TS且非vite，但导入为TS，统一一下配置
=> fix(taro-cli): 修复默认项目模板中存在的一些问题

packages/postcss-pxtransform/index.js
修复鸿蒙端对于单位处理时，没经过designWidth函数判断
=> fix: 修复鸿蒙端对于单位的处理异常

.github/workflows/build-rust-binding.yml, .github/workflows/nodejs.yml
=> chore: update ci

README.md
=> doc: 新增 duxui

packages/taro-components/__tests__/__snapshots__/picker-view.spec.tsx.snap
更新picker-view组件的snapshopt
- [ ✅ ] 其他，请描述(Other, please describe):
- [✅ ] Web 平台（H5）
=> test(components): update snapshot

packages/taro-rn-style-transformer/src/transforms/postcss.ts
=> fix(rn-style-transformer): error print

packages/taro-framework-solid/src/index.ts, packages/taro-framework-solid/src/reconciler/index.ts, packages/taro-framework-solid/src/webpack.h5.ts, packages/taro-framework-solid/src/webpack.harmony.ts, packages/taro-framework-solid/src/webpack.mini.ts
- 🐛bugfix: 修复Portal组件使用报错问题
- 🚀feat: 引入第三方库，若该库引入了solid相关包（solid-js、@tarojs/plugin-framework-solid/dist/reconciler...）统一幻影依赖到业务侧，兼容第三方库使用external solid场景，减少包体积。
=> fix(solid): 引入第三方库，若该库引入了solid相关包（solid-js、@tarojs/plugin-framework-solid/dist/reconciler...）统一幻影依赖到业务侧

packages/taro/types/api/canvas/index.d.ts, packages/taro/types/api/device/keyboard.d.ts, packages/taro/types/api/device/memory.d.ts, packages/taro/types/api/files/index.d.ts, packages/taro/types/api/location/index.d.ts, packages/taro/types/api/media/video.d.ts, packages/taro/types/api/network/download.d.ts, packages/taro/types/api/network/upload.d.ts, packages/taro/types/api/route/index.d.ts, packages/taro/types/api/storage/index.d.ts, packages/taro/types/api/taro.hooks.d.ts, packages/taro/types/api/ui/tab-bar.d.ts
=> chore(types): 更新 api 支持端类型

packages/taro-platform-harmony/src/program/arkTS.ts
=> fix: 修改判断.d.ts的正则，修复正常d结尾文件被识别成类型文件的问题

packages/taro/types/taro.config.d.ts
修复了 supportedMaterials 类型申明错误的问题，可见以下文档 https://developers.weixin.qq.com/miniprogram/dev/framework/material/support_material.html
=> fix: `supportedMaterials` type

packages/taro-loader/src/h5.ts
fix(h5-native-component): 修复某些定制platform下组件预览场景挂载loader冲突问题(ihub)
- [ ✅ ] 错误修复(Bugfix) issue: fix #
- [ ✅ ] Web 平台（H5）
=> fix(h5-native-component): 修复某些定制platform下组件预览场景挂载loader冲突问题(ihub)

packages/taro-framework-react/src/loader-meta.ts
修复 preact >= 10.24.0 的兼容性问题
fix #16690
=> fix(preact): 修复 preact >= 10.24.0 的兼容性问题

.github/workflows/publish.yml
=> chore(ci): ci脚本增加tag校验

.github/workflows/publish.yml
=> fix(ci): publish

packages/taro-components-react/src/components/button/index.tsx, packages/taro-components-react/src/components/button/style/index.scss
- 支持 size 属性，提供多种尺寸选项
- 支持 type 属性，提供不同按钮类型
- 支持 plain 属性，实现朴素按钮样式
- 支持 disabled 属性，控制按钮禁用状态
- 支持 onClick 事件处理
**这个 PR 做了什么？** (简要描述所做更改)
**这个 PR 是什么类型？** (至少选择一个)
- [✓] 新功能 (Feature)
**这个 PR 涉及以下平台：**
- [✓] Web 端（H5）
- [✓] 移动端（React-Native）
=> [Feature request]新增 Button 组件对 TD 端的支持
